package com.drew.metadata.wav;

import androidx.emoji2.text.flatbuffer.aI.aJzfoQ;
import com.drew.metadata.Directory;
import com.drew.metadata.avi.AviDirectory;
import com.drew.metadata.exif.makernotes.CanonMakernoteDirectory;
import com.drew.metadata.exif.makernotes.FujifilmMakernoteDirectory;
import com.drew.metadata.exif.makernotes.NikonType2MakernoteDirectory;
import com.drew.metadata.exif.makernotes.OlympusCameraSettingsMakernoteDirectory;
import com.drew.metadata.exif.makernotes.OlympusFocusInfoMakernoteDirectory;
import com.drew.metadata.exif.makernotes.OlympusImageProcessingMakernoteDirectory;
import com.drew.metadata.exif.makernotes.OlympusMakernoteDirectory;
import com.drew.metadata.exif.makernotes.OlympusRawInfoMakernoteDirectory;
import com.drew.metadata.exif.makernotes.PanasonicMakernoteDirectory;
import com.drew.metadata.exif.makernotes.SonyType1MakernoteDirectory;
import com.drew.metadata.iptc.IptcDirectory;
import com.drew.metadata.photoshop.PhotoshopDirectory;
import com.google.android.gms.internal.fido.Hg.kSWQKWZ;
import com.google.android.material.internal.It.KLTXZbnQvj;
import defpackage.lv8;
import java.util.HashMap;

/* JADX INFO: compiled from: r8-map-id-b2309a5993a3f14549aeb617bc4a78ecbec51e99a3efca387f8965087335ae2d */
/* JADX INFO: loaded from: classes2.dex */
public class WavDirectory extends Directory {
    public static final String CHUNK_DATA = "data";
    public static final String CHUNK_FORMAT = "fmt ";
    public static final String FORMAT = "WAVE";
    public static final String LIST_INFO = "INFO";
    public static final int TAG_ARTIST = 7;
    public static final int TAG_BITS_PER_SAMPLE = 6;
    public static final int TAG_BLOCK_ALIGNMENT = 5;
    public static final int TAG_BYTES_PER_SEC = 4;
    public static final int TAG_CHANNELS = 2;
    public static final int TAG_COMMENTS = 13;
    public static final int TAG_COPYRIGHT = 14;
    public static final int TAG_DATE_CREATED = 11;
    public static final int TAG_DURATION = 16;
    public static final int TAG_FORMAT = 1;
    public static final int TAG_GENRE = 12;
    public static final int TAG_PRODUCT = 9;
    public static final int TAG_SAMPLES_PER_SEC = 3;
    public static final int TAG_SOFTWARE = 15;
    public static final int TAG_TITLE = 8;
    public static final int TAG_TRACK_NUMBER = 10;
    static final transient HashMap<Integer, String> _audioEncodingMap;
    static final transient HashMap<String, Integer> _tagIntegerMap;
    private static final HashMap<Integer, String> _tagNameMap;

    public WavDirectory() {
        setDescriptor(new WavDescriptor(this));
    }

    @Override // com.drew.metadata.Directory
    public final String getName() {
        return "WAV";
    }

    @Override // com.drew.metadata.Directory
    public final HashMap<Integer, String> getTagNameMap() {
        return _tagNameMap;
    }

    static {
        HashMap<Integer, String> map = new HashMap<>();
        _tagNameMap = map;
        HashMap<String, Integer> map2 = new HashMap<>();
        _tagIntegerMap = map2;
        HashMap<Integer, String> map3 = new HashMap<>();
        _audioEncodingMap = map3;
        map2.put("IART", 7);
        map2.put("INAM", 8);
        map2.put("IPRD", 9);
        map2.put("ITRK", 10);
        map2.put("ICRD", 11);
        map2.put("IGNR", 12);
        map2.put("ICMT", 13);
        map2.put("ICOP", 14);
        map2.put("ISFT", 15);
        map.put(1, "Format");
        map.put(2, "Channels");
        map.put(3, "Samples Per Second");
        map.put(4, "Bytes Per Second");
        map.put(5, "Block Alignment");
        map.put(6, "Bits Per Sample");
        map.put(7, "Artist");
        map.put(8, "Title");
        map.put(9, "Product");
        map.put(10, "Track Number");
        map.put(11, "Date Created");
        map.put(12, "Genre");
        map.put(13, "Comments");
        map.put(14, "Copyright");
        map.put(15, "Software");
        map.put(16, "Duration");
        map3.put(1, "Microsoft PCM");
        map3.put(2, "Microsoft ADPCM");
        map3.put(3, "Microsoft IEEE float");
        map3.put(4, "Compaq VSELP");
        map3.put(5, "IBM CVSD");
        map3.put(6, "Microsoft a-Law");
        map3.put(7, "Microsoft u-Law");
        map3.put(8, "Microsoft DTS");
        map3.put(9, "DRM");
        map3.put(10, "WMA 9 Speech");
        map3.put(11, "Microsoft Windows Media RT Voice");
        map3.put(16, "OKI-ADPCM");
        lv8.x(17, map3, "Intel IMA/DVI-ADPCM", 18, "Videologic Mediaspace ADPCM");
        lv8.x(19, map3, "Sierra ADPCM", 20, "Antex G.723 ADPCM");
        lv8.x(21, map3, "DSP Solutions DIGISTD", 22, "DSP Solutions DIGIFIX");
        lv8.x(23, map3, "Dialoic OKI ADPCM", 24, "Media Vision ADPCM");
        lv8.x(25, map3, "HP CU", 26, "HP Dynamic Voice");
        lv8.x(32, map3, "Yamaha ADPCM", 33, "SONARC Speech Compression");
        lv8.x(34, map3, "DSP Group True Speech", 35, "Echo Speech Corp.");
        lv8.x(36, map3, "Virtual Music Audiofile AF36", 37, "Audio Processing Tech.");
        lv8.x(38, map3, "Virtual Music Audiofile AF10", 39, "Aculab Prosody 1612");
        lv8.x(40, map3, "Merging Tech. LRC", 48, "Dolby AC2");
        lv8.x(49, map3, "Microsoft GSM610", 50, "MSN Audio");
        lv8.x(51, map3, "Antex ADPCME", 52, "Control Resources VQLPC");
        lv8.x(53, map3, "DSP Solutions DIGIREAL", 54, "DSP Solutions DIGIADPCM");
        lv8.x(55, map3, "Control Resources CR10", 56, "Natural MicroSystems VBX ADPCM");
        lv8.x(57, map3, "Crystal Semiconductor IMA ADPCM", 58, "Echo Speech ECHOSC3");
        lv8.x(59, map3, "Rockwell ADPCM", 60, "Rockwell DIGITALK");
        lv8.x(61, map3, "Xebec Multimedia", 64, "Antex G.721 ADPCM");
        lv8.x(65, map3, "Antex G.728 CELP", 66, "Microsoft MSG723");
        lv8.x(67, map3, "IBM AVC ADPCM", 69, "ITU-T G.726");
        lv8.x(80, map3, "Microsoft MPEG", 81, kSWQKWZ.iBC);
        lv8.x(82, map3, "InSoft RT24", 83, "InSoft PAC");
        lv8.x(85, map3, "MP3", 89, "Cirrus");
        lv8.x(96, map3, "Cirrus Logic", 97, "ESS Tech. PCM");
        lv8.x(98, map3, "Voxware Inc.", 99, "Canopus ATRAC");
        lv8.x(100, map3, "APICOM G.726 ADPCM", 101, "APICOM G.722 ADPCM");
        lv8.x(102, map3, "Microsoft DSAT", 103, "Micorsoft DSAT DISPLAY");
        lv8.x(PanasonicMakernoteDirectory.TAG_COUNTRY, map3, "Voxware Byte Aligned", PanasonicMakernoteDirectory.TAG_INTELLIGENT_RESOLUTION, "Voxware AC8");
        lv8.x(113, map3, "Voxware AC10", 114, "Voxware AC16");
        lv8.x(115, map3, "Voxware AC20", 116, "Voxware MetaVoice");
        lv8.x(117, map3, "Voxware MetaSound", 118, "Voxware RT29HW");
        lv8.x(PanasonicMakernoteDirectory.TAG_BURST_SPEED, map3, "Voxware VR12", 120, "Voxware VR18");
        lv8.x(PanasonicMakernoteDirectory.TAG_INTELLIGENT_D_RANGE, map3, "Voxware TQ40", 122, "Voxware SC3");
        lv8.x(123, map3, "Voxware SC3", 128, "Soundsoft");
        lv8.x(129, map3, "Voxware TQ60", NikonType2MakernoteDirectory.TAG_ADAPTER, "Microsoft MSRT24");
        lv8.x(131, map3, "AT&T G.729A", NikonType2MakernoteDirectory.TAG_LENS, "Motion Pixels MVI MV12");
        lv8.x(NikonType2MakernoteDirectory.TAG_MANUAL_FOCUS_DISTANCE, map3, "DataFusion G.726", NikonType2MakernoteDirectory.TAG_DIGITAL_ZOOM, "DataFusion GSM610");
        lv8.x(136, map3, "Iterated Systems Audio", 137, "Onlive");
        lv8.x(138, map3, "Multitude, Inc. FT SX20", NikonType2MakernoteDirectory.TAG_LENS_STOPS, "Infocom ITS A/S G.721 ADPCM");
        lv8.x(140, map3, "Convedia G729", 141, "Not specified congruency, Inc.");
        lv8.x(145, map3, "Siemens SBC24", 146, "Sonic Foundry Dolby AC3 APDIF");
        lv8.x(147, map3, "MediaSonic G.723", 148, "Aculab Prosody 8kbps");
        lv8.x(151, map3, "ZyXEL ADPCM", 152, "Philips LPCBB");
        lv8.x(153, map3, "Studer Professional Audio Packed", 160, "Malden PhonyTalk");
        lv8.x(CanonMakernoteDirectory.TAG_TONE_CURVE_TABLE, map3, "Racal Recorder GSM", 162, "Racal Recorder G720.a");
        lv8.x(163, map3, "Racal G723.1", 164, "Racal Tetra ACELP");
        lv8.x(176, map3, "NEC AAC NEC Corporation", 255, "AAC");
        lv8.x(256, map3, "Rhetorex ADPCM", 257, "IBM u-Law");
        lv8.x(258, map3, "IBM a-Law", 259, "IBM ADPCM");
        lv8.x(273, map3, "Vivo G.723", 274, "Vivo Siren");
        lv8.x(288, map3, "Philips Speech Processing CELP", 289, "Philips Speech Processing GRUNDIG");
        lv8.x(291, map3, "Digital G.723", 293, "Sanyo LD ADPCM");
        lv8.x(304, map3, "Sipro Lab ACEPLNET", 305, "Sipro Lab ACELP4800");
        lv8.x(306, map3, "Sipro Lab ACELP8V3", OlympusRawInfoMakernoteDirectory.TagWbRbLevelsWhiteFluorescent, "Sipro Lab G.729");
        lv8.x(308, map3, "Sipro Lab G.729A", 309, "Sipro Lab Kelvin");
        lv8.x(310, map3, "VoiceAge AMR", AviDirectory.TAG_DATETIME_ORIGINAL, "Dictaphone G.726 ADPCM");
        lv8.x(IptcDirectory.TAG_TIME_SENT, map3, "Qualcomm PureVoice", 337, "Qualcomm HalfRate");
        lv8.x(341, map3, KLTXZbnQvj.chnf, 352, "Microsoft Audio1");
        lv8.x(353, map3, "Windows Media Audio V2 V7 V8 V9 / DivX audio (WMA) / Alex AC3 Audio", 354, "Windows Media Audio Professional V9");
        lv8.x(355, map3, "Windows Media Audio Lossless V9", IptcDirectory.TAG_UNIQUE_OBJECT_NAME, "WMA Pro over S/PDIF");
        lv8.x(368, map3, "UNISYS NAP ADPCM", 369, "UNISYS NAP ULAW");
        lv8.x(370, map3, "UNISYS NAP ALAW", 371, "UNISYS NAP 16K");
        lv8.x(372, map3, "MM SYCOM ACM SYC008 SyCom Technologies", 373, "MM SYCOM ACM SYC701 G726L SyCom Technologies");
        lv8.x(374, map3, "MM SYCOM ACM SYC701 CELP54 SyCom Technologies", 375, "MM SYCOM ACM SYC701 CELP68 SyCom Technologies");
        lv8.x(IptcDirectory.TAG_ARM_IDENTIFIER, map3, "Knowledge Adventure ADPCM", 384, "Fraunhofer IIS MPEG2AAC");
        lv8.x(400, map3, "Digital Theater Systems DTS DS", 512, "Creative Labs ADPCM");
        lv8.x(514, map3, "Creative Labs FASTSPEECH8", 515, "Creative Labs FASTSPEECH10");
        lv8.x(528, map3, "UHER ADPCM", 533, "Ulead DV ACM");
        lv8.x(534, map3, "Ulead DV ACM", 544, "Quarterdeck Corp.");
        lv8.x(560, map3, "I-Link VC", 576, "Aureal Semiconductor Raw Sport");
        lv8.x(IptcDirectory.TAG_ORIGINATING_PROGRAM, map3, "ESST AC3", IptcDirectory.TAG_BY_LINE, "Interactive Products HSX");
        lv8.x(593, map3, "Interactive Products RPELP", 608, "Consistent CS2");
        lv8.x(624, map3, "Sony SCX", 625, "Sony SCY");
        lv8.x(626, map3, "Sony ATRAC3", IptcDirectory.TAG_SOURCE, "Sony SPC");
        lv8.x(OlympusMakernoteDirectory.TAG_PREVIEW_IMAGE, map3, "TELUM Telum Inc.", 641, "TELUMIA Telum Inc.");
        lv8.x(645, map3, "Norcom Voice Systems ADPCM", 768, "Fujitsu FM TOWNS SND");
        lv8.x(769, map3, "Fujitsu (not specified)", 770, "Fujitsu (not specified)");
        lv8.x(771, map3, "Fujitsu (not specified)", 772, "Fujitsu (not specified)");
        lv8.x(773, map3, "Fujitsu (not specified)", 774, "Fujitsu (not specified)");
        lv8.x(OlympusCameraSettingsMakernoteDirectory.TagAfFineTuneAdj, map3, "Fujitsu (not specified)", OlympusFocusInfoMakernoteDirectory.TagAfPoint, "Fujitsu (not specified)");
        lv8.x(848, map3, "Micronas Semiconductors, Inc. Development", 849, "Micronas Semiconductors, Inc. CELP833");
        lv8.x(1024, map3, "Brooktree Digital", OlympusCameraSettingsMakernoteDirectory.TagFlashExposureComp, "Intel Music Coder (IMC)");
        lv8.x(PhotoshopDirectory.TAG_LAYERS_GROUP_INFORMATION, map3, "Ligos Indeo Audio", 1104, "QDesign Music");
        lv8.x(1280, map3, "On2 VP7 On2 Technologies", 1281, "On2 VP6 On2 Technologies");
        lv8.x(1664, map3, "AT&T VME VMPCM", 1665, "AT&T TCP");
        lv8.x(1792, map3, "YMPEG Alpha (dummy for MPEG-2 compressor)", 2222, "ClearJump LiteWave (lossless)");
        lv8.x(4096, map3, "Olivetti GSM", 4097, "Olivetti ADPCM");
        lv8.x(4098, map3, "Olivetti CELP", 4099, "Olivetti SBC");
        lv8.x(4100, map3, "Olivetti OPR", FujifilmMakernoteDirectory.TAG_AUTO_BRACKETING, "Lernout & Hauspie");
        lv8.x(FujifilmMakernoteDirectory.TAG_SEQUENCE_NUMBER, map3, "Lernout & Hauspie CELP codec", 4354, "Lernout & Hauspie SBC codec");
        lv8.x(OlympusImageProcessingMakernoteDirectory.TagUnknownBlock3, map3, "Lernout & Hauspie SBC codec", OlympusImageProcessingMakernoteDirectory.TagUnknownBlock4, "Lernout & Hauspie SBC codec");
        lv8.x(FujifilmMakernoteDirectory.TAG_DYNAMIC_RANGE, map3, "Norris Comm. Inc.", FujifilmMakernoteDirectory.TAG_FILM_MODE, "ISIAudio");
        lv8.x(OlympusFocusInfoMakernoteDirectory.TagSensorTemperature, map3, "AT&T Soundspace Music Compression", 6172, "VoxWare RT24 speech codec");
        lv8.x(6174, map3, "Lucent elemedia AX24000P Music codec", 6513, "Sonic Foundry LOSSLESS");
        lv8.x(6521, map3, "Innings Telecom Inc. ADPCM", 7175, "Lucent SX8300P speech codec");
        lv8.x(7180, map3, "Lucent SX5363S G.723 compliant codec", 7939, "CUseeMe DigiTalk (ex-Rocwell)");
        lv8.x(8132, map3, "NCT Soft ALF2CD ACM", 8192, "FAST Multimedia DVM");
        lv8.x(8193, map3, "Dolby DTS (Digital Theater System)", 8194, "RealAudio 1 / 2 14.4");
        lv8.x(8195, map3, "RealAudio 1 / 2 28.8", SonyType1MakernoteDirectory.TAG_CONTRAST, "RealAudio G2 / 8 Cook (low bitrate)");
        lv8.x(SonyType1MakernoteDirectory.TAG_SATURATION, map3, "RealAudio 3 / 4 / 5 Music (DNET)", SonyType1MakernoteDirectory.TAG_SHARPNESS, "RealAudio 10 AAC (RAAC)");
        lv8.x(SonyType1MakernoteDirectory.TAG_BRIGHTNESS, map3, "RealAudio 10 AAC+ (RACP)", 9472, "Reserved range to 0x2600 Microsoft");
        lv8.x(13075, map3, "makeAVIS (ffvfw fake AVI sound from AviSynth scripts)", 16707, "Divio MPEG-4 AAC audio");
        lv8.x(16897, map3, "Nokia adaptive multirate", 16963, "Divio G726 Divio, Inc.");
        lv8.x(17228, map3, "LEAD Speech", 22092, "LEAD Vorbis");
        lv8.x(22358, map3, "WavPack Audio", 26447, "Ogg Vorbis (mode 1)");
        lv8.x(26448, map3, "Ogg Vorbis (mode 2)", 26449, "Ogg Vorbis (mode 3)");
        lv8.x(26479, map3, "Ogg Vorbis (mode 1+)", 26480, "Ogg Vorbis (mode 2+)");
        lv8.x(26481, map3, "Ogg Vorbis (mode 3+)", 28672, "3COM NBX 3Com Corporation");
        lv8.x(28781, map3, "FAAD AAC", 31265, "GSM-AMR (CBR, no SID)");
        lv8.x(31266, map3, "GSM-AMR (VBR, including SID)", 41216, "Comverse Infosys Ltd. G723 1");
        lv8.x(41217, map3, "Comverse Infosys Ltd. AVQSBC", 41218, "Comverse Infosys Ltd. OLDSBC");
        lv8.x(41219, map3, "Symbol Technologies G729A", 41220, "VoiceAge AMR WB VoiceAge Corporation");
        lv8.x(41221, map3, "Ingenient Technologies Inc. G726", 41222, "ISO/MPEG-4 advanced audio Coding");
        lv8.x(41223, map3, "Encore Software Ltd G726", 41225, "Speex ACM Codec xiph.org");
        lv8.x(57260, map3, "DebugMode SonicFoundry Vegas FrameServer ACM Codec", 59144, "Unknown -");
        lv8.x(61868, map3, aJzfoQ.yjB, 65534, "Extensible");
        map3.put(65535, "Development");
    }
}
