[versions]
morphe-patcher = "1.10.0"
morphe-patches-library = "1.6.2"
smali = "d92701d947"
gson = "2.14.0"
hiddenapi = "6.1"
annotation = "1.9.1"
okhttp = "5.5.0"

[libraries]
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
morphe-patches-library = { module = "app.morphe:morphe-patches-library", version.ref = "morphe-patches-library" }
morphe-extensions-library = { module = "app.morphe:morphe-extensions-library", version.ref = "morphe-patches-library" }
lsposed-hiddenApiBypass = { module = "org.lsposed.hiddenapibypass:hiddenapibypass", version.ref = "hiddenapi" }
annotation = { module = "androidx.annotation:annotation", version.ref = "annotation" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }

[plugins]
android-library = { id = "com.android.library" }
