/*
 * Copyright 2026 Hushfeed contributors
 * https://github.com/SysAdminDoc/hushfeed
 *
 * Built on icysymmetra/tiktok-patches-for-morphe (GPL-3.0).
 */
package app.morphe.extension.tiktok.settings.preference;

/** Published CHANGELOG entries carried inside the patched app. Run tools/gen-release-notes.py after release edits. */
public final class ReleaseNotesData {
    private ReleaseNotesData() {}
    public static final String TEXT =
            "## 0.67.0 (2026-10-02)\n" +
            "\n" +
            "* **TikTok:** New patch, Block suggested video notifications, stops TikTok's \"Videos you might like\" pushes, the ones about popular videos it picked for you, like \"25M+ people viewed\". Its switch under Inbox starts on once the patch is in, so they're blocked from the first launch, and turning it off lets them through again. Messages, comments, likes, follows and videos from accounts you follow aren't touched.\n" +
            "\n" +
            "* **TikTok:** Hide search rewards (App) now keeps the floating coin off search as well as the points banner (#21). The switch only reached the banner's service before, so the coin stayed and the banner could come back. Now every search rewards piece takes the path TikTok already takes for accounts without rewards. TikTok decides this once per launch, so the switch now asks for a restart after you change it.\n" +
            "\n" +
            "* **TikTok:** Hushfeed's settings come in Azerbaijani (#77). Like the other languages they follow the language TikTok runs in, and it's a first pass, so corrections are welcome.\n" +
            "\n" +
            "* **TikTok:** The four resource optimizers accept a universal APK split down to one ABI, such as an arm64-v8a only copy (#43). They used to stop because the other ABI's libraries were missing. Every file the split kept still has to match its reviewed checksum, and a set missing only part of an ABI is still refused.\n" +
            "\n" +
            "* **TikTok:** Show author region puts the country on the video you're watching again after you swipe down (#75). TikTok keeps the videos above and below attached while you scroll, and the country was going on the one above, so it only showed after swiping back up.\n" +
            "\n" +
            "* **TikTok:** New patch, Stop saving search history, keeps new searches out of the search history TikTok saves on the phone. Its switch, Privacy > Don't save new searches, starts on once the patch is picked. Typed and suggested searches still work, searches you'd already saved stay until you delete them, and turning the switch off or pausing Hushfeed lets TikTok record again. It doesn't touch anything TikTok keeps on its servers.\n" +
            "\n" +
            "* **TikTok:** Streaks take several usernames separated by commas or new lines (#73). Each chat has its own attempts, so a recipient that couldn't be found can retry without repeating another chat's message. Duplicate names and names for the same chat are counted once. The sending account is checked again before each message. TikTok's reply receiver doesn't confirm delivery, so the status says delivery is unconfirmed and avoids retrying a chat that may already have received its message, even after the process stops.\n" +
            "\n" +
            "* **TikTok:** New patch, Feed text sizes, gives the video description and the creator's name their own sizes on Feed screen, from 8 to 48 (#66). Both start at 0, which keeps TikTok's size, and Android's font scaling still applies. Spoken captions keep their separate size.\n" +
            "\n" +
            "* **TikTok:** Build details under About copies or saves build identity and verified patch-time resource choices, even without Diagnostic tools or events. Automatic reports include the same facts. Older APKs show unknown, and runtime settings can't rewrite them. Patching an APK that Hushfeed already patched now stops with an error, so start from TikTok's original APK.\n" +
            "\n" +
            "* **TikTok:** A bundle saved under a filename or folder with a plus sign, a space, a percent sign or non-English letters now applies. The patcher used to read `+` as a space and stop with \"no such file\".\n" +
            "\n" +
            "* **TikTok:** Recovery records for unfinished saves survive Android cache clearing. Existing records move only after a verified commit, and unreadable records stay intact.\n" +
            "\n" +
            "* **TikTok:** Finishing a download releases its temporary-file ownership even if deletion fails, so later cleanup can reclaim the abandoned file. Mirror retries keep their active ownership.\n" +
            "\n" +
            "* **TikTok:** Share sheet actions you exclude by name are matched on the titles TikTok exposes to accessibility. The panel's attachment, layout and draw events recheck late labels and recycled rows, including a reopened dialog (#74).\n" +
            "\n" +
            "* **TikTok:** CAPTCHA challenges that can't be classified or read stay visible, including on signed-in accounts. Hide CAPTCHA popups is unavailable until a browsing scene is validated, and shown decisions still appear in diagnostics.\n" +
            "\n" +
            "* **TikTok:** Hide the music line now hides the track name and its \"Contains:\" song credit on feed and opened videos (#68). The music disc still has its own switch.\n" +
            "\n" +
            "* **TikTok:** The README's install steps and TikTok badge list all three supported builds, and it explains which patch-time removals need a new APK to undo. The settings tour uses the current Share page, without the removed friend-send confirmation.\n" +
            "* **TikTok:** Video quality and Remove sound no longer intercept photo posts that also carry a video model (#71). Download original photos keeps control of still-image saves, and selected live-photo motion clips keep TikTok's native route.\n" +
            "* **TikTok:** Download video on a photo post now queues original stills before TikTok starts video conversion. Missing originals produce an error, and even one or two images show a file count and Cancel. Live Photo video choices retain their native route (#71).\n" +
            "\n" +
            "* **TikTok:** The LIVE feed you open with the LIVE button can be filtered now (#57). Feed filter has a LIVE feed section that hides gaming, Shop and sponsored LIVEs, verified creators, categories you name, and rooms outside a viewer or follower range. Blocked creators, Creators hidden on this phone and Blocked caption words carry over (words are matched against each LIVE's title), and Creator exceptions lets chosen creators past the gaming, verified, category and count rules, though never past a block, a blocked word, Shop or sponsored. The first room comes with the LIVE button itself, so the rules start with the one after it. When they hide every room on five pages in a row, one room gets through, because a page with nothing on it makes TikTok ask for the next one about once a second. TikTok's LIVE feed doesn't say when a stream started or when an account was made, so there's no rule for either. The diagnostic report's LIVE FEED section counts pages, rooms and what each rule hid.\n" +
            "* **TikTok:** A double tap, long press or left swipe set to open comments opens the comments of the video on screen (#63). Right after a swipe it could open the comments of the video before or after it, show that video's \"restricted comments\" message, or say comments weren't available. It went by the video the player was naming, and the player names a new video only once it starts playing. When what's on screen has no comment button of its own, you get the \"not available\" message rather than another video's comments.\n" +
            "* **TikTok:** The other long press choices go by the video on screen too (#63). Copy the video link, Copy the sound link, Save the original sound and Find the sound on YouTube Music took the video before right after a swipe, so a link copied then was that video's. When what's on screen has no comment button of its own, like a LIVE, they say there's nothing there for them instead. Seek from the edges no longer moves the video before either, and if the new one hasn't started playing yet it says nothing is playing. In a video opened from a profile, a comments gesture never reaches the feed behind it.\n" +
            "* **TikTok:** Hide the status bar now also keeps it away on videos you open from a profile, a hashtag, a sound or search (#50). It used to stop at the main feed, so the clock and status icons stayed over those videos.\n" +
            "* **TikTok:** A new switch on the Feed screen page, Hide the comment bar on opened videos, takes the Add comment bar off videos you open from a profile, a hashtag, a sound or search, and the video grows into the room it held (#50). TikTok's Clear display hides that bar but leaves a black strip where it was. The comment button on the right still opens comments. It's off by default.\n" +
            "* **TikTok:** A new switch on the Privacy page, Stop TikTok's benchmark runs, keeps TikTok's phone benchmark from starting (#64). TikTok's servers sometimes ask it to time the phone, and it does that in a background process of its own that held about 194 MB on one phone. The switch turns that process's service off, so it can't start. A run that's already going ends when TikTok restarts, and turning the switch off or pausing Hushfeed hands the service back. Turn it off before you patch TikTok again without that patch, or the benchmark stays off until TikTok is reinstalled. It comes with the Resource and battery governor patch and is off by default.\n" +
            "* **TikTok:** New patch, Hide profile shortcuts, takes the shortcuts you pick off the row under a profile's bio, like TikTok Studio or Your orders (#49). TikTok's server decides what goes in that row, so Hushfeed settings > App > Hide profile shortcuts lists the ones TikTok has sent to your phone once you've opened your profile, and the row beside it takes names you type. A change shows once TikTok restarts. Hide all of them and the row goes away with no gap left behind. Nothing is hidden until you pick something.\n" +
            "* **TikTok:** Hushfeed works in a second copy of TikTok made with Morphe's Clone app patch (#59). That patch gives the copy a new package name and renames TikTok's own resources to match, so the share sheet tools couldn't find their views, and neither could hiding video overlays, the captions settings, the comment tools or the author line. They now look views up under whatever name the app runs as. Logging in to a cloned TikTok was refused on the first try in testing, so the copy may only be usable logged out.\n" +
            "* **TikTok:** Remove unused language packs keeps every language now unless you list the ones you want in Languages to keep (#67). It used to keep only English out of the box, so picking every patch in Manager left TikTok in English for everyone else. To keep removing them, set Languages to keep to your codes, such as en or en, tr. If your TikTok lost its language this way, patch it again with this patch off (or with your language listed) and install it over the one you have. You stay signed in.\n" +
            "* **TikTok:** In Feed tabs, the Explore option is called Explore or Community now (#62). Some accounts see that tab as Community, and unticking Explore hid it with nothing in the list saying so.\n" +
            "\n" +
            "* **TikTok:** Hushfeed now needs Morphe Manager 1.33.0 or newer, because it's built against Morphe patcher 1.15.0. Older Managers say the bundle needs a Manager update. In a test with memory held near what Manager gets on a phone (768 MB), patcher 1.14.1 ran out of memory while saving patched TikTok 47.1.4, and 1.15.0 finished.\n" +
            "\n" +
            "## 0.66.0 (2026-10-01)\n" +
            "\n" +
            "* **TikTok:** Hushfeed's settings now come in Italian (#61) and Russian (#60). Both are first passes, and corrections from Italian and Russian speakers are very welcome. Russian counts use all three of the language's forms, so 2, 5 and 21 results each read the way Russian says them.\n" +
            "* **TikTok:** New patch, Change app name, puts a name you choose under the app's icon and in Android's app list, so a patched TikTok is easy to tell from another one (#59). Type the name in the patch's options in Morphe Manager. It's off by default, inside the app everything still says TikTok, and like Hide Play Store update offer it has the manager decode TikTok's resources, which takes more memory.\n" +
            "* **TikTok:** Fit the video to the screen fits a video again when the space around it changes size (#29). A Pixel 9 showed a video fitted to about two thirds of the screen's height with bars on every side: the fit had been worked out against a space TikTok then laid out bigger, and nothing fitted the video again. The diagnostic report also has a VIDEO FIT section with the last few fits and the sizes each was worked out from, so a report taken when it happens shows where a wrong size came from.\n" +
            "* **TikTok:** A phone set to English first and another language second shows Hushfeed's settings in English, as TikTok does, instead of in the second language. Counts also follow the rules of the language the settings are shown in. A phone whose language has no table yet showed \"1 results\", and one set to Japanese and then Russian showed \"1 результатов\".\n" +
            "* **TikTok:** In Brazilian Portuguese a count of zero read as one, \"1 resultado\" for no results at all, because Portuguese counts 0 together with 1 and that form is written for exactly one. A count other than 1 now always shows its own number. A language whose one form covers more counts, like Russian's 21 and 31, gets a row of its own for them.\n" +
            "* **TikTok:** The diagnostic report has a FEED MUTE section, so a report of a feed with no sound can tell Hushfeed's mute apart from everything else (#58). It shows whether Mute feed videos and its button on the feed are on, how many feed players it has muted since TikTok started, and how many audio focus requests it has turned down. When Hushfeed is paused it says so, since the feed then plays with its sound.\n" +
            "* **TikTok:** The share sheet no longer shows \"Tap again to send\" on a friend you never touched (#58). That message came from the Confirm before sending to a friend switch, which was hooked to the code TikTok runs when a friend's picture scrolls into view, not to a tap, so it could ring a friend as the sheet opened and it never held back a real tap. On every TikTok version Hushfeed supports, tapping a friend only picks them and nothing goes out until you press Send, so the switch is gone rather than moved.\n" +
            "* **TikTok:** You can add apps of your own to the share sheet's Share via row. Pick them under Hushfeed settings > Share sheet > Add apps to Share via, from every installed app that takes a shared link. Each one shows up just before More with its own icon and gets the same link the other apps get, so Sanitize sharing links cleans it too. An app TikTok already shows is left alone, and one you've since uninstalled drops out of the row until it's back.\n" +
            "* **TikTok:** New patch, Look like the store app, for a follow or a like that undoes itself on a refresh on a patched build (#55). A patched TikTok is re-signed with the patcher's key and installed by Morphe Manager, and TikTok reports both about itself: its signature hash and its installer. This answers those reports the way the Play Store app would, so TikTok's signature hash carries TikTok's own certificate and its installer reads as the Play Store. TikTok can also read the APK on disk from native code, which no patch reaches, so this may not be enough on its own. It's off by default, under Hushfeed settings > Privacy, and needs a restart to take effect.\n" +
            "* **TikTok:** New patch, Keep a streak going, sends one message a day to someone you pick, at a time you pick, so your message streak with them doesn't lapse on a day you don't open TikTok. Set it up under Hushfeed settings > Inbox > Streak: their username, the time and the message, which is a 🔥 unless you change it. It goes out through TikTok's own notification reply, and TikTok doesn't have to be open. When it can't send, it tries again every 15 minutes, up to three more times, and a message that still didn't go out that day is sent if you open TikTok later the same day. Send it now sends today's right away, and the line under the switch says when the last one went and when the next one goes. Turning it on, or picking someone new, after today's time has passed starts it tomorrow, and nobody gets two messages in one day, even if you switch away from them and back. It only sends from the account you set it up on. The diagnostic report gets a section on how the last try went, without naming who it's for. The patch is off by default, and it adds the exact alarm and start at boot permissions the daily alarm needs.\n" +
            "* **TikTok:** New switch on the Screen time page, Let the last video finish. When the budget runs out, the video on screen plays to its end before the hold covers the feed, and the feed won't swipe to another video until then. A budget of five videos used to put the hold over the fifth, so you got four. Only the feed's swipe stops. It waits three minutes at most and it's off by default.\n" +
            "* **TikTok:** Hushfeed supports TikTok 47.1.4 as well as 47.0.3 and 47.1.3 (#56), and 47.0.3 stays supported. Every patch applies to each of the three. The trimming patches know 47.1.4's rebuilt libraries and language packs, and Block P2P video relay has nothing to remove from 47.1.4's split bundle, which leaves those libraries out, so it says so instead of refusing the bundle.\n" +
            "* **TikTok:** A new switch on the Feed screen page, Hide effect and template tags, takes the \"Try effect\", template, CapCut and AI style tags off the strip above a video's description (#51). Place, film and drama tags stay, and Diagnostics counts the tags it took away. The \"Contains:\" song credit belongs to the music line, which Hide the music line already hides.\n" +
            "* **TikTok:** Patching takes less time (#54). The privacy patches, Ghost mode and Allow screenshots each read every call in TikTok to find the few they change, and a dozen patches searched the whole app for code they could have looked up by class. Now they look only where it can be. On a desktop the patch step for all 98 patches dropped from about 240 seconds to 140, and at a phone-like 768 MB memory limit from about 280 to 180. The patched app comes out byte for byte the same. On a Galaxy S22 in Morphe Manager at 640 MB, the recommended patches plus AMOLED dark theme went from about 8 3/4 minutes to 6 1/2.\n" +
            "* **TikTok:** New patch, Keep playing in the background, keeps TikTok's own background play on whatever its server says (#52). The video you're watching keeps going after you leave TikTok or turn the screen off, and TikTok's media notification pauses and resumes it. It also covers photo posts and the videos on your own profile, private ones included, which TikTok leaves out. A feed video stops at its end, since TikTok doesn't loop or move on in the feed while it's in the background, and another app's sound still pauses it. TikTok's own background play switch in the long-press menu stays on while this is on. It's off by default. The switch is under Hushfeed settings > Playback, and TikTok needs a restart after you change it. Feature Gate Lab shows the switch deciding TikTok's background play value. Mute feed videos now stays muted when the notification resumes a video in the background.\n" +
            "* **TikTok:** Stop on-device AI profiling does something again. Both of the places it looked for had gone from all three supported TikTok builds, so it applied without changing anything, and it searched all of TikTok for them on every patch. It now keeps TikTok's Pitaya plugin from starting. Pitaya's native engine doesn't load, and TikTok no longer hands it a copy of every analytics event it logs. TikTok carries on the way it does when the plugin isn't installed, and patching fails if a TikTok update moves any of this.\n" +
            "\n" +
            "## 0.65.0 (2026-09-29)\n" +
            "\n" +
            "* **TikTok:** The Screen time page shows Start today over's result straight away, and a page left open while the day starts over shows what the new day changed. Both used to keep the old numbers and switches until you left the page and opened it again.\n" +
            "* **TikTok:** Resource and battery governor's description, and the Block motion sensors switch it adds to Hushfeed's settings, no longer claim a battery saving that was never measured. They say which sensors it stops TikTok listening to.\n" +
            "* **TikTok:** The README and the patch descriptions in Morphe Manager now give measured numbers for the optional trimming patches instead of adjectives: the storage each one saves, and what they did to memory use on a Galaxy S22 (alone or all together, nothing beyond the run-to-run spread, apart from about 13 MB less loaded code with all of them on).\n" +
            "* **TikTok:** AMOLED dark theme's description and the README no longer say it needs a 768 MB memory limit to patch. Measured on two phones, it still finishes at 640 MB, just slower, so 768 MB or more is now advice rather than a requirement.\n" +
            "* **TikTok:** The keyboard no longer rewrites an app's package name in Send links to another app, or a host in Share links through another host. A keyboard like SwiftKey used to capitalize it and add a space after every dot, so com.dv.adm came out as \"Com. Dv. Adm\" and the field refused it. The fields for handles, country and language codes, sound ids, filename templates and speeds get the same plain keyboard.\n" +
            "* **TikTok:** A list or text setting saved right as you left the settings screen could keep its old value until TikTok restarted, even though the row and the saved file both already showed the new one. Closing a dialog is its own step after the tap on OK, and leaving the screen a beat too soon used to skip past it.\n" +
            "* **TikTok:** When TikTok closes in the middle of a save, the next time you open it a banner says which saves didn't finish, or might not have, and how many of their files are missing. Files that already reached your gallery count as saved, and nothing restarts on its own, so save it again if you still want it. If another message covers the banner before its time is up, it comes back the next time you open TikTok. The start-up cleanup of half-written files from a day or more ago also runs now. It was meant to run every time TikTok started but never did.\n" +
            "* **TikTok:** A save's progress row sitting on one of TikTok's pop-up sheets could close TikTok when the save ended or a second row came up. It stays where the sheet puts it now.\n" +
            "* **TikTok:** With `{creator}/` at the start of the file name, the sound saved beside a video or a story now goes into that creator's folder with it. It went to the download folder one level up, so the two split apart. On Android 10 and newer it goes to the matching creator folder under Music.\n" +
            "* **TikTok:** Every save says it's been taken the moment you ask, sounds, profile pictures, stickers and a live photo's clip included. Hushfeed runs three saves at once and lines up the rest, and a save in line used to show nothing until it started. Now a save with a progress row shows it straight away as waiting, with Cancel to take it out of line, and one without a row says how many saves are ahead of it. Past three rows, a single line counts the rest, with a Cancel that takes the last save in line out of it. Asking again for something already in line says whether it's still waiting or already saving, where it used to do nothing.\n" +
            "* **TikTok:** On Android 10 and older, tapping the block button over a video, Unblock on its banner or Save media on a sticker no longer closes TikTok. Each of them marked itself busy in a way those Android versions refuse.\n" +
            "* **TikTok:** Diagnostics can record a screen's layout for a \"please hide this\" report. Tap Record a screen's layout, go to the screen, and twenty seconds later the next exported report carries how that screen and any sheet over it are built, without any of its text.\n" +
            "* **TikTok:** The block control, the mute button and Hushfeed's other buttons over the video now show on a video opened from a creator's profile, a hashtag or a sound, and come back to the feed with you. They stayed on the feed behind that screen, where nobody could see them. Mute feed videos mutes those videos too, so the button means what it says there.\n" +
            "* **TikTok:** The budget label and the fade before the hold go as soon as you switch to Profile, Inbox or another tab. Only the playing video moved them, so they could stay over those tabs, the fade nearly black. The fade also stops above the tab row now.\n" +
            "* **TikTok:** When the time budget runs out partway through a long video, the notice and the hold come right then. They waited for the next video, so a long or looping one could play well past the budget. Lowering the budget below what you've already watched today brings them on the same video too.\n" +
            "* **TikTok:** New row under Downloads, Forget saved videos. It empties the record behind the already-saved check, keeps the files and your settings, and offers Undo while its notice is up. A save that was already running when you forgot doesn't add itself back.\n" +
            "* **TikTok:** Mute feed videos leaves another app's music playing in two more cases. Turning mute on from the settings page now gives the sound back when you return to the feed, and turning the sound back on while a video is paused makes the feed ask for it when it plays again, rather than playing over the other app. The mute button also stays off stories and LIVE replays, which keep their sound.\n" +
            "* **TikTok:** Blocking a commenter from the comments is remembered for the account that did it. After switching accounts, someone the first account blocked showed as blocked for the second, and the first tap there sent an unblock. A tap on the row while the banner's Undo is still working no longer sends a second unblock.\n" +
            "* **TikTok:** Hushfeed now needs Morphe Manager 1.32.0 or newer, because it's built against Morphe patcher 1.14.1. Older Managers say the bundle needs a Manager update. The new patcher writes Hushfeed's changes into TikTok's own resource table instead of rebuilding it, so everything the patches don't touch stays exactly as TikTok shipped it. The old one dropped the quote marks around about 70 translated phrases in TikTok's effect tools and widened the type of five attributes. Patched code is the same with either patcher on both supported TikTok builds.\n" +
            "* **TikTok:** Press and hold the Home tab to open Hushfeed's settings (#45), rather than going through Profile, the menu and TikTok's own settings. A tap on Home works as before. It comes with Feed tab navigation and has its own switch under Feed tabs.\n" +
            "* **TikTok:** Settings say more exactly what's going on. A Reset or Undo that fails names itself instead of reporting a failed restore, and Reset no longer leaves Calm feed offering to bring back the setup from before it. The YTDLnis rows say to put its package name in Send links to another app, which is a text field, not a switch. The store region row names Override SIM details when that's the switch that's off. Start the day at takes 06:00 or 0600, which it used to read as 23:00. A long restore result now stays on screen long enough to read. Two playback rows moved out from under Auto-advance, where they didn't belong, and the Feature Gate Lab says when Undo stops covering a preset.\n" +
            "* **TikTok:** Saves now connect only to the server address Hushfeed checked. It used to check that a download's host was a public address and then let the phone look the name up again as it connected, so a name that switched to a local address in between could still have been reached. Each download now goes straight to a checked address over HTTPS, and the certificate is still checked against the original name. Checked on a phone with a video, a photo, subtitles and an animated sticker.\n" +
            "* **TikTok:** Mute feed videos works on TikTok 47.1.3 now, and on 47.0.3 it silences photo posts with a sound too. TikTok gets the next videos ready before you reach them and starts most of them by a route the mute never heard, so it never knew which videos were the feed's. It follows the feed's own list now, and a video is already silent when you swipe to it. It stays silent when you come back after watching the same video from a DM, and after scrolling a long profile grid or search results. On 47.0.3 ordinary videos went quiet before, but only because TikTok's request for the sound was turned down.\n" +
            "* **TikTok:** The README has a troubleshooting entry for unfollowing many accounts at once. TikTok's own Manage view on the Following list does it with checkboxes, and the 10,000 follow limit is TikTok's server rule, which no patch can change.\n" +
            "* **TikTok:** The feed filter table in a diagnostic report now has a line for each route that hands the feed one cached video at a time: the cache chain, the video TikTok slips in when playback lags, and the one it delivers when the feed reaches its end. They never had a line, so a report couldn't tell whether they ran.\n" +
            "* **TikTok:** In the SIM country preset list, the chosen preset's operator line now sits level with every other row's, at any font size. The mark beside the chosen country made its title taller and pushed that line down, and with large text a long country name wrapped only once it was chosen. Every row now keeps a column for the mark, like Android's own choice lists.\n" +
            "* **TikTok:** The README says why a one-photo post saved with TikTok's Download video keeps TikTok's watermark. The server holds no video for such a post, only the photo and its sound, so TikTok renders one on the phone with its logo, the creator's handle and an end card. Download image gives the clean photo.\n" +
            "* **TikTok:** Exported diagnostics keep room for the events that matter. Playback quality wrote a line for nearly every video, since gear names and bitrates change each time, and a busy export was almost nothing else. It now writes one line per mode and size ladder.\n" +
            "\n" +
            "## 0.64.0 (2026-09-28)\n" +
            "\n" +
            "* **TikTok:** Hiding buttons in the right column now works on videos opened from a creator's profile, a hashtag or a sound too (#47). Those play in a screen of their own, which the hides never reached, so only the feed lost its Like, Save or Share button.\n" +
            "* **TikTok:** Hide TikTok Shop also hides a LIVE that is selling while it streams (#46). Only Hide LIVE videos took those away before, and that hides every LIVE.\n" +
            "* **TikTok:** Tapping Pause Hushfeed in the settings search no longer closes TikTok. It opens the main settings page with that row picked out.\n" +
            "* **TikTok:** The settings search finds rows that stay greyed out until another switch is on, such as Auto-advance session limit. Their page says which switch that is, where the search used to say nothing matched.\n" +
            "* **TikTok:** Default playback speed, Subtitle language, the delay before controls hide and the edge press step grey out while the switch that uses them is off, and say which switch that is. A greyed choice puts that note on its own line under its value.\n" +
            "* **TikTok:** Undo last restore or reset keeps whatever it replaces, so pressing it a second time brings back the changes you made after the restore. A restore that also wrote Feature Gate Lab rules retires the Lab's own Undo, which would have taken those rules back.\n" +
            "* **TikTok:** A restore that kept one of your download folders is no longer undone at the next start when TikTok closed before it finished tidying up.\n" +
            "* **TikTok:** The daily budget's countdown keeps running after you come back from messages, a creator's video or Hushfeed's settings, and Wait for a tap after a return only stops the feed when you actually left TikTok. A hold that ended while TikTok was in the background takes its panel down when you come back.\n" +
            "* **TikTok:** With the feed muted, opening the comments or coming back to TikTok no longer pauses the music another app is playing.\n" +
            "* **TikTok:** Clear all on the Inbox's suggested accounts works on TikTok 47.1.3. It found nothing to press there.\n" +
            "* **TikTok:** A story saved with its sound is no longer reported as failed when only the sound ran out of space or time, so a retry doesn't make a second copy.\n" +
            "* **TikTok:** The already-saved choice opens on the screen you're looking at, a video opened from a profile or search included. It used to open behind it, where nobody could see it, and hold the save until you went back to the feed.\n" +
            "* **TikTok:** With Remove watermark off, Automatic saves keep TikTok's watermark even when Hushfeed makes the save for its details, progress row or saved-video check.\n" +
            "* **TikTok:** With only Show download progress on, a video Hushfeed can't fetch as one file goes to TikTok's own save instead of being refused. A save that fails no longer announces \"Stopping after this file\".\n" +
            "* **TikTok:** Only these caption languages reads three-letter codes such as eng or spa as their two-letter forms. Before, eng matched nothing and hid every English video it was meant to keep.\n" +
            "* **TikTok:** A clip shorter than a second can now count as seen. It never played to the one-second mark, so it kept coming back.\n" +
            "* **TikTok:** The like and follow confirmations let a tap through when TikTok hasn't said which video is playing, as on some photo posts. The button did nothing at all there.\n" +
            "* **TikTok:** The Feature Gate Lab says why a change was refused, for example that none of the chosen gates had an override to reset, and shows its rule limit, instead of asking you to try again. A reviewed preset waits until the whole gate list has loaded rather than refusing as not matching.\n" +
            "* **TikTok:** In the Feature Gate Lab the list ends above the selection bar at any text size, and the bar drops its hint line at large text. Switch Access, Voice Access and TalkBack's actions menu can open and select gates.\n" +
            "* **TikTok:** Diagnostic reports leave out network addresses, your phone's own IPv6 address among them, TikTok's US and EU server names, and the video ids in saved file names. With SIM spoofing on, debug logging no longer records your real carrier and country.\n" +
            "\n" +
            "## 0.63.0 (2026-09-27)\n" +
            "\n" +
            "Includes the changes developed in 0.62.0, which wasn't published as a separate bundle.\n" +
            "\n" +
            "* **TikTok:** Diagnostic messages remove quoted credentials, headers and account identifiers before reaching system logs, the in-memory buffer or crash files. Long inputs and exception chains are bounded, and a long dotted hostname no longer overflows the redactor's stack.\n" +
            "* **TikTok:** Opening links in an external browser preserves ordinary sites' `target` parameters. Only TikTok's known link-safety routes unwrap that parameter. Lookalike characters in a hostname no longer pass that check.\n" +
            "* **TikTok:** Ghost mode shows whether this process has seen a reporting call and warns when a story-reporting check fails. Clearing diagnostics or toggling the switch doesn't erase that warning. A diagnostics row sits beside the switch. Blocking a local call still doesn't verify TikTok's viewer list (#39).\n" +
            "* **TikTok:** Delayed budget changes survive a failed save and can be retried. Tightening a limit saves the new value and cancels its scheduled change together. A restore saves the delayed changes with the rest of its settings, and recovery restores both. A failed edit keeps its dialog open instead of claiming it was scheduled.\n" +
            "* **TikTok:** A settings transaction that throws puts every live value back. A queued screen-time reminder also checks that its original screen is still active and the feature is still on before leaving TikTok.\n" +
            "* **TikTok:** Failed settings and Lab exports remove the file created by the picker. If the provider refuses cleanup, the message points to the folder you chose. Backup actions stay disabled while a write is running, including after the settings page is recreated.\n" +
            "* **TikTok:** Structured Lab edits keep their draft after a failed save. Discard returns to the last successful save, newer edits survive an older save finishing, and untouched null fields keep their original values. Reset refreshes the fields to the value it restored.\n" +
            "* **TikTok:** Multi-file saves stop on a storage refusal or deadline instead of trying another mirror or counting the last file as an ordinary skip. Counted audio saves preserve the same reason.\n" +
            "* **TikTok:** Sticker saves check free space in their destination before writing and again while PNG, GIF and video output grows. Running out of space removes the unfinished output and keeps an older saved file intact.\n" +
            "* **TikTok:** Share-action and button checklists keep your choices open when a save fails. Apply saves the whole selection together, and you can retry without choosing everything again.\n" +
            "* **TikTok:** Clear seen videos waits for storage before announcing success. Failed clears keep the record and earlier Undo, and completion from a previous account can't offer recovery on the current account.\n" +
            "* **TikTok:** Undo and Unblock controls respect Android's requested time to act. The Calm feed preset keeps its heading and action visible at larger text sizes in both themes.\n" +
            "* **TikTok:** New release receipts check the source commit and clean source snapshots embedded during the build. A dirty build stays ineligible after its files are restored, even with a matching timestamp. Ignored source files also make it ineligible. Equivalent checkout line endings keep the same metadata. Builds whose before-and-after source bytes differ stay ineligible. Previously published receipts are accepted only when their exact recorded bytes and bundle identity match the verified archive.\n" +
            "\n" +
            "## 0.62.0 (2026-09-27)\n" +
            "\n" +
            "Source changes included in the v0.63.0 release.\n" +
            "\n" +
            "* **TikTok:** Installation instructions name the current published bundle and distinguish it from the 98-patch source build. Removed the inherited donation button and corrected the Android verification advice.\n" +
            "\n" +
            "* **TikTok:** Show download progress adds a bar for a single video save, including Automatic quality (#27). Known-size video transfers show a percentage; preparation and unknown-size transfers keep a busy indicator. It starts off and announces the start once to a screen reader.\n" +
            "\n" +
            "* **TikTok:** Downloads can save a TXT file with the video's caption and source details. An optional saved-video check offers Open or Save again before making another copy, even when the post no longer supplies a download link. Start a video filename template with `{creator}/` for a folder per creator. The switches start off and existing templates keep their current folders.\n" +
            "\n" +
            "* **TikTok:** The Feature Gate Lab leaves more room for gates on small screens (#42). Its title fits in the toolbar, the warning opens from the icon beside Apply overrides, and tabs can scroll sideways at larger text sizes. Search and the override switch stay on screen.\n" +
            "\n" +
            "* **TikTok:** The Feature Gate Lab now has Reviewed presets in its menu. The first restores See translation on 47.1.3 by setting both required gates together. You can review the values before applying and undo the whole change. A preset for another TikTok version won't apply.\n" +
            "\n" +
            "* **TikTok:** New patch, Mute feed videos. It adds a movable button beside the block control, and a switch under Playback, that play the feed without sound while the phone's volume stays where it is. Music from another app keeps playing while the feed is muted, since TikTok no longer takes the audio over for it. DMs, stories and LIVE keep their sound, and the button says Muted or Sound on to a screen reader.\n" +
            "* **TikTok:** With a playback quality set, a video's quality list is read once instead of on every switch. TikTok asks for it through two getters and reads the next video's list in between, and Hushfeed kept only the last one, so each switch parsed the whole list again. It keeps the last four now.\n" +
            "* **TikTok:** New switch under Feed screen, Hide the status bar in LIVE rooms (#38). A LIVE then fills the screen up to the top edge, camera cutout included, and TikTok's buttons at the top move up into the space the bar left. The status bar comes back as soon as you leave the LIVE or switch apps. Hide the status bar never reached LIVE rooms, since TikTok opens them as a separate screen. It's part of Hide video overlays.\n" +
            "* **TikTok:** New row in Feed filter, Only these caption languages. List the languages you understand, like en, es, and a video whose original caption is in another language is hidden. It goes by the caption TikTok marks as the original, so a video with no caption, only translated captions, or a tag that isn't a language always stays. It takes effect without a restart, leaves profile pages alone and counts what it hides in the diagnostic report. The section it sits in is now called Words, countries and languages.\n" +
            "* **TikTok:** Restoring a settings backup no longer takes a download folder that can't hold what it's for. A backup from before the three download folders were split names one folder for everything, and a Pictures folder there used to become the video and sticker folder too, while those saves quietly went to DCIM/TikTok. Now that folder keeps what you had, and the restore says so in its banner. Undo still puts every folder back as it was.\n" +
            "* **TikTok:** A number setting greyed out by another switch shows \"Turn on ... first.\" on a line of its own. It used to run straight on from the current value, as in \"Current: Off Turn on Auto-advance videos first.\"\n" +
            "* **TikTok:** Plainer words in the Feature Gate Lab and the number editors. A gate's source line says whether TikTok declares it and whether it has a current value, where it used to say \"generated registry\" and \"current cache\". Player config is now Video player settings and Save JSON is Save report. An empty number field shows the range it takes, and an empty maximum in a range reads No limit.\n" +
            "* **TikTok:** The block symbol Block from comment puts beside a comment's heart is easier to hit. It was about 40 by 24 dp, and a tap now counts anywhere in a 48 dp square around it where the row has blank space. A tap meant for the heart, the comment text or the next comment still goes there, and Easier comment likes keeps working beside it. How far it reaches depends on the row: on a Galaxy S22 it's about 45 by 35 dp, because the comment text sits right above it.\n" +
            "* **TikTok:** Ghost mode also holds back the play report TikTok sends when a story plays (#39). Every story view went out twice: once as a story view, which Ghost mode already blocked, and once as an ordinary play count carrying the story's id, which it didn't, and a second account could still see you in its viewer list. Feed videos still send their play reports as before. This hasn't been checked with two accounts yet, so the diagnostic report now has a \"story play stats\" line saying whether the report was held back.\n" +
            "* **TikTok:** Hide videos you have already seen has a new row, Count a video as seen after. Set a percent and a video only counts once you've watched that much of it, so five seconds of a ten-minute video no longer hides it at 50%. Zero, the default, keeps the old rule of a few seconds. A video TikTok gives no length for still counts after two seconds, and a short clip never needs its last second.\n" +
            "* **TikTok:** The settings search and the Feature Gate Lab search match text the same way now: case, accents and punctuation don't matter in either, so \"pre roll\" finds \"Pre-roll\".\n" +
            "* **TikTok:** Saving, restoring, resetting and undoing settings, and the Calm feed preset, tell you how it went in a banner at the bottom of the settings window instead of toasts that vanish. A restore that left some settings alone says so in the same banner, and a change that needs a restart has a Restart now button.\n" +
            "* **TikTok:** On a phone whose blocked creators, hidden creators, creator exceptions or blocked caption words list grew past the limits added on 2026-09-14, restoring a backup, resetting settings and undoing now work again. Before, all three failed with the generic try-again message. Saving a backup names the list that's too long instead of writing a file no restore would accept.\n" +
            "* **TikTok:** The Feature Gate Lab works from the TikTok build you have installed. It shows that build's own gate list and names it in exports and backups. When TikTok updates, it keeps the overrides whose gates didn't change, turns the rest off and tells you how many. Before, it treated 47.1.3 as 47.0.3 and carried every override across unchecked.\n" +
            "* **TikTok:** The Lab's \"first caller\" and its SettingsManager observations name the right code again. Reads without a default had stopped being recorded after the first read with one.\n" +
            "* **TikTok:** The diagnostic report has a LIVE BUTTON section that says what decided the LIVE button in the feed's corner each time: the Hide the LIVE button switch, TikTok hiding it because LIVE has a bottom or top tab, or Hushfeed keeping it because that tab was taken off (#28).\n" +
            "* **TikTok:** New patch, Stay on the video in full screen. When a video ends in TikTok's full-screen viewer, you stay on that video instead of being moved to the next one, and the next-video countdown doesn't show. Turn it on in Hushfeed settings > Playback. Swiping still moves on. The viewer has an auto-next of its own, which Auto-advance and Stop video looping never reached.\n" +
            "* **TikTok:** People and apps hidden from the share sheet one per line are hidden from its contact row too. That row only split the list on commas, while the rest of the sheet also split it on line breaks.\n" +
            "* **TikTok:** Share sheet tools looks through TikTok's screens once per layout pass instead of four times. It runs on every layout of the main screen, share sheet open or not.\n" +
            "* **TikTok:** The block symbol that stands in for the thumbs down on comments is drawn in the same grey as the comment's name and time, so it shows on TikTok's dark comment sheet. It used to take its colour from the phone's theme, which TikTok's own dark mode doesn't follow, and came out almost black on black.\n" +
            "* **TikTok:** Hide videos you have already seen keeps a separate record for each TikTok account on the phone. Before, a second account inherited everything the first one had watched, and could have seen that list. Clear seen videos now names the account it forgets for. The record from before this update doesn't say whose it was, so it hides nothing until you add it to an account with the new Add older seen videos to this account row, which shows up while there's anything to add.\n" +
            "* **TikTok:** Saves refuse a download address in any block the internet's registry sets aside for testing, documentation, benchmarking or network equipment, not just private and local ones. TikTok's servers never use those, so a link that points there is not a TikTok file. On a mobile network that only has IPv6, saves from IPv4-only servers keep working.\n" +
            "* **TikTok:** Your own profile shows your newest posts again (#35). TikTok loads a profile's posts in the same kind of list as the feed, so the feed rules reached profile grids too. With Filter location-tagged videos on, recent posts with a place tag were taken off your own grid and only older ones were left. Your own posts now stay wherever TikTok shows them.\n" +
            "* **TikTok:** A profile you open keeps all of its videos. Minimum views, likes and the other count limits, Hide seen videos and the rest of the feed rules used to hide posts there as well, so a small creator's page could look nearly empty. Profiles, their favorites and their reposts now lose only ads, the same as the rest of the profile page.\n" +
            "* **TikTok:** The camera and microphone indicator stays up for as long as TikTok records. Before, the orange diamond only flashed at the start of a story recording, because TikTok records a story's sound in its own native code, which the patch never saw. On Android 11 and newer the mark now also reads what Android itself reports for TikTok's camera and microphone, the same thing the status bar's privacy dots show. On older Android it works as before.\n" +
            "* **TikTok:** On a TikTok version where a patch's hook can't be written the way the patch asks, that patch now stops with a message naming the method, instead of applying and then doing nothing. Morphe's patcher could leave a hook call out without a word when a method has more than 16 registers. It never happened on 47.0.3 or 47.1.3, and now it can't happen silently on a later version either.\n" +
            "* **TikTok:** Save story works again when you press and hold a story. It looked up TikTok's story player by names from TikTok 46.2.3, and neither 47.0.3 nor 47.1.3 has them, so holding a story showed \"Open the story again and try once more\" and saved nothing. It finds the story by TikTok's own class names now, which don't change between versions.\n" +
            "\n" +
            "## 0.61.0 (2026-09-26)\n" +
            "\n" +
            "A large release. Hushfeed supports TikTok 47.1.3 as well as 47.0.3 now, and it carries every fix made since 0.60.0. Copy comments without username works from the comment menu again, folding a foldable no longer jumps to another video, and sticker saves read TikTok's own sticker data. The settings screens also had a long polish pass.\n" +
            "\n" +
            "* **TikTok:** Save media on a sticker's sheet lightens while you hold it, like TikTok's own Share and Save next to it. It used to be the one button there that showed no press.\n" +
            "* **TikTok:** Save media on a comment sticker reads the sticker from TikTok's own sticker data now, which keeps its names from one version to the next. It used to look first for a field and a class that neither 47.0.3 nor 47.1.3 has, and only reached the sticker through its last fallback. It saves the picture the sheet shows, and if a later TikTok renames that data, Hook status says so.\n" +
            "* **TikTok:** Hushfeed supports TikTok 47.1.3 as well as 47.0.3 (#33). Every patch applies to both, and Morphe Manager lists both versions. 47.1.3 renamed 42 of the screen parts Hushfeed finds by name, so each one is looked up by the name the running build gives it. The feed filter reads 47.1.3's rearranged cold-start cache, AMOLED dark theme knows its gray palette, the corner LIVE button check reads its LIVE mode where 47.1.3 moved it, and the four resource optimizers and the language purger accept its reviewed files, from the universal APK and from APKMirror's split bundle. On the S22 running 47.1.3, the feed, comments, inbox, share sheet, captions and the dark theme were checked.\n" +
            "* **TikTok:** The Feature Gate Lab names its export file in UTC like every other Hushfeed export, so they sort together.\n" +
            "* **TikTok:** A like, comment or share count range restored with spaces around its numbers is read as that range instead of being reset to any.\n" +
            "* **TikTok:** A CAPTCHA check whose type TikTok sends as a number is named by its scene now, not by the word scene.\n" +
            "* **TikTok:** Region spoof no longer works out the country, locale and timezone again on every call, and TikTok asks for them constantly. Share sheet tools, the comment tools, search card filtering, Fit the video to the screen and the Feature Gate Lab look up what they need once instead of on every screen update, and the block button's overlay no longer keeps a closed screen in memory.\n" +
            "* **TikTok:** A blocked-creator pattern that could stall the feed is refused when you type it and skipped, with one note, when it comes in with a backup or from an older list. That covers back-references, a repeat inside a repeated group, and patterns stacked with open-ended repeats. The time limit that was meant to catch these never actually ran on a phone.\n" +
            "* **TikTok:** Rarely, the block, Not interested and sound buttons stayed off for a whole video when it started playing at the moment the feed loaded it. That no longer happens.\n" +
            "* **TikTok:** A restored backup that had a number out of range, like an edge seek of 90 seconds where 60 is the most, is no longer undone at the next start as if the restore had been interrupted.\n" +
            "* **TikTok:** A day locked by the daily budget stays locked when TikTok restarts after the phone's timezone moved forward. Before, swiping TikTok away after the change handed the rest of the day back.\n" +
            "* **TikTok:** A settings search that finds nothing now says that switches from patches you didn't tick in Morphe Manager aren't listed. Fill the screen with the video is one of them, since it comes with Fit the video to the screen, which is off by default.\n" +
            "* **TikTok:** Camera and microphone indicator draws a green square for the camera and an orange diamond for the microphone, so telling them apart doesn't depend on seeing green and orange. The text on Hushfeed's banners over a video is easier to read against a bright frame or TikTok's light comment sheet.\n" +
            "* **TikTok:** In settings, the back arrow is announced as a button, and the search box's clear button, the Lab's switch rows and its Technical details heading show when they're pressed or focused. A chosen SIM preset no longer looks like the row that has focus. When a budget change or Pause is refused, the reason stays on screen, under the number you typed or in the settings banner, instead of a toast that was gone before the time in it could be read.\n" +
            "* **TikTok:** Settings text reads more naturally, with contractions throughout, one way of asking you to restart TikTok and one of saying to try again in a moment. Number rows show their range the way they show the value, as in \"0 to 86,400 seconds\". The Feature Gate Lab says On or off where its filter said Boolean, tells you what to fix in a bad value or bad JSON, uses a real ellipsis while it loads, and its menu has a title and a Cancel.\n" +
            "* **TikTok:** The settings home's status mark is a rounded square now, on the same corner scale as the cards and icon tiles, and the three quick routes no longer sit on the search card's edge. The Feature Gate Lab's icon buttons show where keyboard or d-pad focus is, which the round ripple they had never did.\n" +
            "* **TikTok:** The page that opens when settings can't load now has a proper title, and Retry is drawn as the way forward instead of a second plain row next to Back. Choice dialogs line their marks up under the title and show Cancel in the dialog's own language. What's new offers Got it and Later and has an icon of its own. When Undo or Restart now fails, the message says which one failed, where it used to talk about undoing a clear either way.\n" +
            "* **TikTok:** A What's new row sits at the top of Hushfeed's settings after an update. It opens the changelog for the version you're on, and for any releases you skipped since you last dismissed it. Later keeps the row for another look, and Got it takes it away until the next release.\n" +
            "* **TikTok:** Hide Play Store update offer is a new optional patch. On the S22, Play changed from Update to Open while Morphe Manager kept showing TikTok 47.0.3. Android won't install a lower-code APK over this one, so leave the patch off if you expect to switch back without removing the app.\n" +
            "* **TikTok:** The settings home has pink section icons, quieter group labels and a warmer active card in dark mode. Search now has its own framed field and a separate results card. Section pages keep pink headings and larger row titles.\n" +
            "* **TikTok:** Repost diagnostics writes the request, TikTok's response status and the next repost-list result into a diagnostic report when logging is on. It keeps the video's ID and any repost note out of the report.\n" +
            "* **TikTok:** Taking LIVE off the top feed tabs now keeps the corner LIVE button available, just as taking LIVE off the bottom bar does. Hide the LIVE button still works on its own.\n" +
            "* **TikTok:** On a foldable with the split comment view, folding or unfolding no longer moves you to another video when Hide seen videos is on. The rebuild for the new width let the filter drop the video you were watching before TikTok could put it back.\n" +
            "* **TikTok:** Camera and microphone indicator shows its mark on TikTok's camera screen. Before, the first time the camera opened the mark was drawn on the main screen hidden behind it, so on a phone it rarely showed at all.\n" +
            "* **TikTok:** Copy comments without username works from the comment sheet's own menu again. Since TikTok 46.9.3 that menu builds the clipboard text a different way, and the option was only reaching Copy in Favorites. Stickers and emoji in the copied text come through as before.\n" +
            "\n" +
            "## 0.60.0 (2026-09-25)\n" +
            "\n" +
            "A small release with three fixes. Comments that TikTok dropped without a word now go out, the caption no longer shows over the video when Caption above comments is on, and Allow Duet and Stitch covers creators who limit duets on their whole account.\n" +
            "\n" +
            "* **TikTok:** Comment send fix, a new patch that's on by default, covers a way TikTok drops a comment without a word. TikTok checks a send against the page opened most recently, and when that page has already lost its screen, the check stops the comment and shows nothing, so the text just stays in the box. The check now gets the comment panel's own screen in that case. The diagnostic export names the page that had none, so a report from a phone where comments still don't post says whether this was the reason.\n" +
            "* **TikTok:** With Caption above comments on, the caption over the video goes away, since the whole caption now sits at the top of the comments. It used to show in both places. Hide the caption still hides it on its own.\n" +
            "* **TikTok:** Allow Duet and Stitch now answers the creator's account-wide choice as well as the video's own. TikTok checks both, and on the S22 a video that allowed anyone still had no Duet entry because its creator's account allowed only people they follow back. With the switch on, Duet and Stitch both show on those videos now. Whether TikTok's servers accept the upload is still up to them.\n";
}
