{
  "formatVersion": "1.1",
  "component": {
    "group": "app.morphe",
    "module": "morphe-patches-gradle-plugin",
    "version": "1.3.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "morphe-patches-gradle-plugin-1.3.4.jar",
          "url": "morphe-patches-gradle-plugin-1.3.4.jar",
          "size": 59094,
          "sha512": "358ac35e6b490e3aa7dfc36364988a07430c5f163083970e01f0e53eba26ad87f68b703035af54a1ee5d84014a8fd04260751b0d60f122b167bd5fb3d6298833",
          "sha256": "4238e080c7a91b8d7078f34cce8dd9ed6ee2578ba536cc9488f708583926f2c6",
          "sha1": "378d5efc8cb90f2804911a42e4b0bf5ae087f9c0",
          "md5": "7ab479ddf6356ec781d01ece1f40f95a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.application",
          "module": "com.android.application.gradle.plugin",
          "version": {
            "requires": "9.1.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.5.0-jre"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "2.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "morphe-patches-gradle-plugin-1.3.4.jar",
          "url": "morphe-patches-gradle-plugin-1.3.4.jar",
          "size": 59094,
          "sha512": "358ac35e6b490e3aa7dfc36364988a07430c5f163083970e01f0e53eba26ad87f68b703035af54a1ee5d84014a8fd04260751b0d60f122b167bd5fb3d6298833",
          "sha256": "4238e080c7a91b8d7078f34cce8dd9ed6ee2578ba536cc9488f708583926f2c6",
          "sha1": "378d5efc8cb90f2804911a42e4b0bf5ae087f9c0",
          "md5": "7ab479ddf6356ec781d01ece1f40f95a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "morphe-patches-gradle-plugin-1.3.4-sources.jar",
          "url": "morphe-patches-gradle-plugin-1.3.4-sources.jar",
          "size": 9097,
          "sha512": "d2ad171e4cef32e64a82965fa7494b717fa76d452dba87385751c7d471e37e2061f189a3dd25c93c482f05f1bb390e3182a31c5da1bb4c23731557f855a604c6",
          "sha256": "a0bed40bf973c8c7f3e7e1bbb1440412ebdf6fd71e381eccf48f6e52321ebf43",
          "sha1": "9064ef9e0d6373be70db73210a3fe8081680c6e3",
          "md5": "45436d193f38861c623813bd4de432bd"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "morphe-patches-gradle-plugin-1.3.4-javadoc.jar",
          "url": "morphe-patches-gradle-plugin-1.3.4-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
