[versions]
morphe-patcher = "1.8.0"
#noinspection GradleDependency
smali = "d92701d947"
gson = "2.14.0"
ftpserver = "1.2.1"
apache-mina = "2.2.9"

[libraries]
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
apache-ftpserver-core = { group = "org.apache.ftpserver", name = "ftpserver-core", version.ref = "ftpserver" }
apache-mina-core = { group = "org.apache.mina", name = "mina-core", version.ref = "apache-mina" }
