#!/usr/bin/env python3
"""Exercise production bounded SAF streams with an fd-backed provider stand-in."""
import os,pathlib,subprocess,tempfile
ROOT=pathlib.Path(__file__).resolve().parents[2];J=pathlib.Path(os.environ.get('JAVA_HOME','/workspace/scratch/48be16aedc6f/tools/jdk-21.0.12.1+1'))/'bin'
with tempfile.TemporaryDirectory() as d:
 p=pathlib.Path(d);sources={
 'android/net/Uri.java':'package android.net;public class Uri{}',
 'android/os/ParcelFileDescriptor.java':'''package android.os;import java.io.*;public class ParcelFileDescriptor implements Closeable{FileInputStream in;public ParcelFileDescriptor(File f)throws FileNotFoundException{in=new FileInputStream(f);}public FileDescriptor getFileDescriptor(){try{return in.getFD();}catch(IOException e){throw new RuntimeException(e);}}public void close()throws IOException{in.close();}}''',
 'e/e/a/CacheFile.java':'package e.e.a;class CacheFile extends java.io.File{CacheFile(String s){super(s);}}',
 'e/e/a/CacheFolders.java':'''package e.e.a;import java.io.*;import android.os.*;import android.net.*;class CacheFolders{static File folder;static boolean virtual(File f){return true;}static File real(File f){return new File(folder,f.getName());}static Uri document(File f,boolean create)throws IOException{return real(f).exists()?new Uri():null;}static ParcelFileDescriptor open(File f,boolean w,boolean a)throws FileNotFoundException{return new ParcelFileDescriptor(real(f));}}''',
 'e/e/a/CachePack.java':'''package e.e.a;import java.io.*;class CachePack{static File archive(File f){return new File(f.getParent(),"sm1.ncache");}static CachePackIndex.Entry entry(File f)throws IOException{try(FileInputStream in=new FileInputStream(CacheFolders.real(archive(f)))){return CachePackIndex.read(in.getChannel()).get(f.getName());}}}''',
 'e/e/a/PackStreamTest.java':'''package e.e.a;import java.io.*;import java.util.*;public class PackStreamTest{static void check(boolean b,String s){if(!b)throw new AssertionError(s);}public static void main(String[] args)throws Exception{CacheFolders.folder=new File(args[0]);File pack=new File(CacheFolders.folder,"sm1.ncache");try(OutputStream out=new FileOutputStream(pack)){out.write("ABCD0123456789secret".getBytes("UTF-8"));CachePackIndex.finish(out,Arrays.asList(new CachePackIndex.Entry("sm1.m3u8",0,4,0),new CachePackIndex.Entry("sm1_asset_0.bin",4,10,0),new CachePackIndex.Entry("sm1_asset_1.bin",14,6,0)));}try(InputStream in=new CacheInputStream("/virtual/sm1_asset_0.bin")){check(in.available()==10,"bounded available");check(in.skip(2)==2,"entry seek");byte[] bytes=new byte[100];check(in.read(bytes)==8,"entry read bounded");check(new String(bytes,0,8,"UTF-8").equals("23456789"),"correct bytes");check(in.read()==-1&&in.read(bytes)==-1,"no next entry/index leakage");}try(InputStream in=new CacheInputStream("/virtual/sm1.m3u8")){check(in.skip(100)==4&&in.read()==-1,"skip cannot cross entry");}File ordinary=new File(CacheFolders.folder,"ordinary");try(FileOutputStream out=new FileOutputStream(ordinary)){out.write("plain".getBytes("UTF-8"));}try(InputStream in=new CacheInputStream("/virtual/ordinary")){check(new String(in.readAllBytes(),"UTF-8").equals("plain"),"loose cache retained");}System.out.println("Packed stream: 7 boundary/seek/compatibility checks passed");}}'''
 }
 for name,text in sources.items():f=p/name;f.parent.mkdir(parents=True,exist_ok=True);f.write_text(text)
 actual=ROOT/'extensions/extension/src/main/java/e/e/a';subprocess.run([str(J/'javac'),'-d',str(p),*map(str,p.rglob('*.java')),str(actual/'CacheInputStream.java'),str(actual/'CachePackIndex.java')],check=True);disk=p/'files';disk.mkdir();subprocess.run([str(J/'java'),'-cp',str(p),'e.e.a.PackStreamTest',str(disk)],check=True)
