package hoodles.morphe.patches.xrecorder.misc.signature

import hoodles.morphe.patches.shared.misc.signature.spoofSignaturePatch
import hoodles.morphe.patches.xrecorder.shared.Constants

const val SIGNATURE = """
MIICzTCCAbWgAwIBAgIECSihPDANBgkqhkiG9w0BAQsFADAWMRQwEgYDVQQKEwtW
aWRlb1N0dWRpbzAgFw0xODA4MjMwNzU2NDlaGA8yMTE4MDczMDA3NTY0OVowFjEU
MBIGA1UEChMLVmlkZW9TdHVkaW8wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEK
AoIBAQCrMFYpXPXQXHkJxSFijquA2i0L+0rcN/Hnz676dqRODS3Ag6WMcBSe5lpL
bE2CHLoD65y6sC1iVMJpzKUyIbsmHxJM8rkRllpCxzfOcQralyywIZaETj8OtkZ8
kNfUlsoOCcdhhcaLm3/3djtreQFdU3c0mpvHf68R61LnCFWaCEnFNwWAyzsnfrwF
wRUcS8ETamFhvOMafmj8YGlGk0/NIYS7LMCZaKI4wMRaqqc/NV7v1smMJcQ+Xszb
UuIWDA4FUzGqu+JkcdOz8E1Q3qAxepHILrj9qk1CAWg2hVl1UA2uK+onDG3zoBjS
SfV/j2HNyg/AMwLktqQI7pVZODj5AgMBAAGjITAfMB0GA1UdDgQWBBRa8r7K53LE
oufJRn81MQugMBbAlDANBgkqhkiG9w0BAQsFAAOCAQEAjGIWjeRMdXoP31m98X3S
mEmSKuONtYJtR+F0NqiFrDI9ruElBTNRlJO59BgTM+3clrW+6FIwqu8KWM1SKL42
h8LdwEc8G8FNF829YyiyGFwTiwHbXFOklOjzPFjkKVTgGE9KXQirrG55Dgt6mf+6
VdayUXuWw5DwmF+di5ZNowMMSVaOw3gGZuASzVzaXzhUBVIftw+hC18OJuiKTPpE
Qc94pOrFjSKRVGp26eBKjitRlUj/UI6vHg9+6L2tOb/Y9g14lsaxeL35Y8iLynUz
DD+gFAoNT4ZFIX7/Jjjo9gBKYqIOtp7ZP5qZpUK7yVAienCOyHwKgGYvegU6tlal
Ig==
    """

val spoofSignaturePatch = spoofSignaturePatch(Constants.PACKAGE_NAME, SIGNATURE)