#!/usr/bin/env python3
"""Generate the VocaColle values-ko overlay from the reviewed translation catalog."""

from __future__ import annotations

import csv
import re
import xml.etree.ElementTree as ET
from collections import defaultdict
from pathlib import Path
from xml.sax.saxutils import escape as xml_escape

ROOT = Path(__file__).resolve().parents[1]
CATALOG = ROOT / "translations/ui/ko.csv"
OUTPUT_DIRECTORY = ROOT / "patches/src/main/resources/vocacolle/values-ko"
FORMAT_RE = re.compile(r"%(?:\d+\$)?[-#+ 0,(<]*\d*(?:\.\d+)?(?:[tT][a-zA-Z]|[a-zA-Z%])")
INCLUDED_STATUSES = {"approved", "machine_verified"}


def catalog_text(value: str) -> str:
    return value.replace("\\n", "\n").replace("\\t", "\t")


def android_escape(value: str) -> str:
    value = value.replace("\\", "\\\\")
    value = value.replace("\n", "\\n").replace("\t", "\\t")
    value = value.replace("'", "\\'").replace('"', '\\"')
    if value.startswith(("@", "?")):
        value = "\\" + value
    return xml_escape(value)


def attributes(row: dict[str, str]) -> str:
    tokens = FORMAT_RE.findall(row["ko"])
    formatted = ' formatted="false"' if len(tokens) > 1 else ""
    return formatted


def render_value(row: dict[str, str]) -> str:
    fragment = row["ko_markup"]
    if not fragment:
        return android_escape(catalog_text(row["ko"]))

    root = ET.fromstring(f"<root>{fragment}</root>")
    if "".join(root.itertext()) != catalog_text(row["ko"]):
        raise RuntimeError(f"ko_markup text differs from ko: {row['key']}")

    def render(node: ET.Element) -> str:
        value = android_escape(node.text or "")
        for child in node:
            if child.tag != "b" or child.attrib:
                raise RuntimeError(f"unsupported ko_markup element: {row['key']}")
            value += f"<b>{render(child)}</b>"
            value += android_escape(child.tail or "")
        return value

    return render(root)


def main() -> None:
    with CATALOG.open(encoding="utf-8", newline="") as handle:
        rows = [row for row in csv.DictReader(handle) if row["ko_status"] in INCLUDED_STATUSES]
    if not rows:
        raise RuntimeError("translation catalog is empty")

    strings = sorted((row for row in rows if row["resource_type"] == "string"), key=lambda row: row["key"])
    structured: dict[tuple[str, str], list[dict[str, str]]] = defaultdict(list)
    for row in rows:
        if row["resource_type"] != "string":
            structured[(row["resource_type"], row["key"])].append(row)

    header = [
        '<?xml version="1.0" encoding="utf-8"?>',
        "<!-- Generated by scripts/generate-korean-static-ui.py. Edit translations/ui/ko.csv instead. -->",
        "<resources>",
    ]
    string_lines = header.copy()
    for row in strings:
        string_lines.append(
            f'    <string name="{row["key"]}"{attributes(row)}>{render_value(row)}</string>'
        )

    plural_lines = header.copy()
    array_lines = header.copy()
    for (resource_type, key), items in sorted(structured.items()):
        if resource_type == "plurals":
            plural_lines.append(f'    <plurals name="{key}">')
            order = {"zero": 0, "one": 1, "two": 2, "few": 3, "many": 4, "other": 5}
            for row in sorted(items, key=lambda item: order[item["item_qualifier"]]):
                plural_lines.append(
                    f'        <item quantity="{row["item_qualifier"]}">{android_escape(catalog_text(row["ko"]))}</item>'
                )
            plural_lines.append("    </plurals>")
        elif resource_type == "string-array":
            array_lines.append(f'    <string-array name="{key}">')
            for row in sorted(items, key=lambda item: int(item["item_qualifier"])):
                array_lines.append(f'        <item>{android_escape(catalog_text(row["ko"]))}</item>')
            array_lines.append("    </string-array>")
        else:
            raise RuntimeError(f"unsupported resource type: {resource_type}")

    OUTPUT_DIRECTORY.mkdir(parents=True, exist_ok=True)
    for filename, lines in (
        ("strings.xml", string_lines),
        ("plurals.xml", plural_lines),
        ("arrays.xml", array_lines),
    ):
        lines.append("</resources>")
        (OUTPUT_DIRECTORY / filename).write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"generated {len(strings)} strings and {len(structured)} structured resources")


if __name__ == "__main__":
    main()
