package app.swampattack2.patches.iap

import app.morphe.patcher.patch.rawResourcePatch
import app.swampattack2.patches.shared.Constants.COMPATIBILITY_SWAMP_ATTACK_2

/**
 * Embeds the compiled unlimited-currency engine into the APK as a native
 * library (`lib/arm64-v8a/libSwampUnlimited.so`).
 *
 * The engine (source: analysis/com.hyperdotstudios.swampattack2/ndk/ —
 * built with NDK r27, bytes generated by ndk/lib/gen_so_bytes.py) is an
 * ~13 KB ARM64 companion library that waits for libil2cpp.so to be mapped
 * and then patches 17 verified method entries in the live text segment:
 *
 *   ALWAYS-TRUE — never lose currency, all gates open:
 *     PlayerData.PlayerProfile.CanAfford   x3  (RVA 0x1CDB2DC/2F4/30C)
 *     PlayerData.PlayerProfile.HasResource x2  (0x1CDB33C / 0x1CDB6CC)
 *     PlayerData.PlayerProfile.TryTakeResource(s) x3 (0x1CDBA14/D00/D24)
 *     ResourcePack.CanAfford      x3  (0x1D181C8 / 0x1D18E74 / 0x1D18FA4)
 *     ResourcePack.TryTakeResource(s) x2 (0x1D17EC8 / 0x1D18040)
 *     -> spends report success without deducting; prices (coins, gems,
 *        cards, boosters, premium ammo — every GenericResourceType) are
 *        effectively free.
 *
 *   GENEROUS — every earned/granted amount x10 (capped at 1e8):
 *     PlayerData.PlayerProfile.HandleAddingResource (0x1CDBF60) — the
 *     disassembly-verified grant funnel (AddResources → AddResource →
 *     HandleAddingResource; the prologue confirms w3 = amountToAdd). The
 *     hook scales w3 and runs the ORIGINAL body through a trampoline, so
 *     inventory bookkeeping and the "+N" reward display both see the same
 *     multiplied number — the UI stays honest.
 *
 *   BALANCE PIN — the visible wallet reads 99,999,999:
 *     PlayerData.PlayerProfile.GetResourceAmount (0x1CDB324) — THE balance
 *     read the UI uses. The original body runs through a relocated-prologue
 *     trampoline (the prologue ends in a PC-relative tail-branch, so
 *     install_ret_max re-targets it through an absolute-jump stub), then
 *     the result is raised to max(orig, 99,999,999) — but ONLY for
 *     GenericResourceType.Currency (coins + gems). Progression resources
 *     (cards, boosters, premium ammo, battle-pass ooze, skins, helpers,
 *     boosts, wheel tickets) keep their real counts, so game logic that
 *     compares them is never masked. ResourceType is read at object+0x20
 *     (dump.cs field offset, confirmed by the callee's own `ldr w8,
 *     [x19, #0x20]`). SetResourceAmount and HandleAddingResource never
 *     route through this wrapper (disassembly-verified), so grants, spends
 *     and cloud-save reconciliation keep computing against the REAL wallet.
 *
 * The pinned number appears wherever the UI pulls a balance (resource
 * tracker registration, level complete, shop open) — no event is fired
 * from the hook; push-style OnResourceAmountChanged handlers keep showing
 * real amounts until the view next reads.
 *
 * Every entry is gated against the first 16 bytes of the v1.3.9 shipping
 * binary (extracted straight from libil2cpp.so) — an unexpected build
 * skips the hook instead of writing blind. The balance-pin entry adds a
 * second shape gate (slot1 CBZ must land on entry+16, slots 0/2 must be
 * PC-independent, slot3 must be the tail `B`) so a mismatched prologue is
 * skipped rather than relocated incorrectly. The engine needs no il2cpp
 * exports, no domain attach and no MethodInfo layout: pure, minimal,
 * version-pinned code patching (RVA provenance: dump.cs + script.json +
 * live disassembly — notes/premium-bypass.md §3, targets C1–C8).
 *
 *   ADS GATED IN-ENGINE (two extra always-true hooks, notes/ads.md N1/N2):
 *     PlayerData.AreInterstitialsDisabled (0x1CD0CFC) — the sole gate of
 *     InterstitialAdManager.TryShowInterstitial; forcing it true makes every
 *     interstitial funnel return before load/show (and before any Java ad
 *     bridge is reached).
 *     PlayerData.AreVideoAdsDisabled (0x1CD0D2C) — the app's own "ads
 *     disabled" mode: VideoAdManager.TryWatchVideo → ShowVideoClip takes the
 *     RewardedVideoCompleted(completed=true, skipped=true) branch in-process,
 *     so every "watch ad for X" offer credits its reward INSTANTLY — no ad,
 *     no mediation, no SDK callback to wait on (cannot hang). Availability
 *     keeps reporting Available (CanShow pacing/caps still honored) so the
 *     offer buttons stay alive. Display-side banner/MREC removal is the
 *     separate (also default-on) ../ads/AdRemovalPatch.
 */
@Suppress("unused")
val unlimitedCurrencyPatch = rawResourcePatch(
    name = "Swamp Attack 2: Unlimited Currency Engine",
    description = "Unlimited coins and gems. Buying things never lowers your balance, you earn 10x more, and your wallet always shows 99,999,999. Also removes ads and gives ad rewards instantly. Note: the number shown in the game doesn't matter — whatever it displays, your currency is unlimited. If it ever changes or looks wrong, simply restart the game and the currency will be unlimited again.",
    default = true
) {
    compatibleWith(COMPATIBILITY_SWAMP_ATTACK_2)

    execute {
        val soFile = get("lib/arm64-v8a/libSwampUnlimited.so", true)
        soFile.writeBytes(SwampUnlimitedSoBytes.bytes())
    }
}
