package anxyis.morphe.patches.pure.content

import app.morphe.patcher.patch.PatchException
import app.morphe.patcher.patch.ResourcePatchContext
import app.morphe.patcher.patch.resourcePatch
import anxyis.morphe.patches.pure.shared.ALIGHT_5270
import java.nio.file.Files
import java.nio.file.StandardCopyOption

/**
 * Manifest patch (Morphe keeps the STOCK package — no re-homing).
 *
 * Stock 5.0.270 manifest FACTS (from the decoded binary manifest):
 *  - application android:name = com.pairip.application.Application
 *  - uses-permission com.android.vending.CHECK_LICENSE present
 *  - FileProvider authority = com.alightcreative.app.motion.fileprovider
 *    (code passes the SAME literal — no rename needed since the package
 *    does not change; the Tanryu underscore-join rename existed only
 *    because THEY renamed the package)
 *  - Play-bundle meta-data (splits.required/stamp/source...) present
 *    (Morphe merges/handles splits itself; left untouched)
 *
 * So the manifest delta is exactly 3 ops:
 *  1. application android:name -> com.alightcreative.app.motion.AlightMotionApplication
 *  2. delete uses-permission CHECK_LICENSE
 *  3. android:versionCode -> 999999999 (ForceUpdater kill: stock 1002578 is
 *     below the server minimum, so BendingSpoons' ForceUpdater shows a
 *     non-dismissable "Update Available!" sheet on home. Tanryu precedent:
 *     versionCode 999999999. versionName stays stock; the check reads the
 *     code via PackageManager, not the name.)
 */
@Suppress("unused")
val manifestPatch = resourcePatch(
    name = "No forced updates",
    description = "Stops the app from forcing you to update.",
) {
    compatibleWith(ALIGHT_5270)
    execute {
        document("AndroidManifest.xml").use { doc ->
            val manifest = doc.documentElement
            manifest.setAttribute("android:versionCode", "999999999")
            val apps = doc.getElementsByTagName("application")
            if (apps.length != 1) {
                throw PatchException(
                    "Pure: application nodes = ${apps.length}, expected 1",
                )
            }
            val app = apps.item(0) as org.w3c.dom.Element
            val cur = app.getAttribute("android:name")
            if (cur != "com.pairip.application.Application") {
                throw PatchException(
                    "Pure: application android:name = $cur (wrong base?)",
                )
            }
            app.setAttribute(
                "android:name",
                "com.alightcreative.app.motion.AlightMotionApplication",
            )
            val perms = doc.getElementsByTagName("uses-permission")
            var dropped = 0
            for (i in perms.length - 1 downTo 0) {
                val el = perms.item(i) as? org.w3c.dom.Element ?: continue
                if (el.getAttribute("android:name") == "com.android.vending.CHECK_LICENSE") {
                    el.parentNode.removeChild(el)
                    dropped++
                }
            }
            if (dropped != 1) {
                throw PatchException(
                    "Pure: CHECK_LICENSE removals = $dropped, expected 1",
                )
            }
        }
    }
}

/**
 * Effects content bundle (353 new XMLs + 292 TANRYU thumbs + banner).
 *
 * Staged by tools/stage_bundle.py into resources/pure-bundle/files/ as
 *   assets/effects/<name>.xml (353+4 re-authored, 1 removal listed)
 *   assets/effects/thumb/TANRYU star png (292)
 *   assets/banner.png
 * and copied with the standard copyResources(sourceDir, groups) helper
 * (same API the reference sources use). The group list is generated by
 * the stager into resources/pure-bundle/groups.txt (one line per
 * `dir|file`); the patch reads it so no 600-line literal lives in code.
 */
@Suppress("unused")
val effectsBundlePatch = resourcePatch(
    name = "New effects pack",
    description = "Adds 350+ extra effects with previews.",
    default = false,
) {
    compatibleWith(ALIGHT_5270)
    execute {
        // File-by-file copy via the ResourcePatchContext file API.
        // groups.txt lines: <target-rel-path> (source mirrors same rel path
        // under pure-bundle/files/).
        val listing = object {}.javaClass.classLoader
            .getResourceAsStream("pure-bundle/groups.txt")
            ?.bufferedReader()?.readText()
            ?: throw PatchException("Pure: groups.txt missing")
        var n = 0
        for (rel in listing.lineSequence()) {
            if (rel.isBlank()) continue
            copyBundledFile("pure-bundle/files/$rel", rel)
            n++
        }
        if (n != 646) {
            throw PatchException("Pure: bundle files copied = $n, expected 646")
        }
    }
}

/** Copy one bundled file into the target tree (mirrors ResourceUtils.copyResources). */
private fun ResourcePatchContext.copyBundledFile(source: String, targetRel: String) {
    // this["", false]: target root dir; nested rel paths create parents.
    val targetDir = this["", false]
    val stream = object {}.javaClass.classLoader.getResourceAsStream(source)
        ?: throw PatchException("Pure: bundled file missing: $source")
    val out = targetDir.resolve(targetRel).toPath()
    Files.createDirectories(out.parent)
    Files.copy(stream, out, StandardCopyOption.REPLACE_EXISTING)
}
