package com.medium.android.graphql.type;

import defpackage.d46;
import defpackage.g04;
import defpackage.g76;
import defpackage.gy2;
import defpackage.i04;
import defpackage.n04;
import defpackage.z73;
import java.util.Iterator;
import java.util.List;
import kotlin.Metadata;
import pushnotifications.SY.eoLmc;

/* JADX WARN: Failed to restore enum class, 'enum' modifier and super class removed */
/* JADX WARN: Unknown enum class pattern. Please report as an issue! */
/* JADX INFO: compiled from: r8-map-id-b2309a5993a3f14549aeb617bc4a78ecbec51e99a3efca387f8965087335ae2d */
/* JADX INFO: loaded from: classes4.dex */
@Metadata(d1 = {"\u0000\u0012\n\u0002\u0018\u0002\n\u0002\u0010\u0010\n\u0000\n\u0002\u0010\u000e\n\u0002\b>\b\u0086\u0081\u0002\u0018\u0000 @2\b\u0012\u0004\u0012\u00020\u00000\u0001:\u0001@B\u0011\b\u0002\u0012\u0006\u0010\u0002\u001a\u00020\u0003¢\u0006\u0004\b\u0004\u0010\u0005R\u0011\u0010\u0002\u001a\u00020\u0003¢\u0006\b\n\u0000\u001a\u0004\b\u0006\u0010\u0007j\u0002\b\bj\u0002\b\tj\u0002\b\nj\u0002\b\u000bj\u0002\b\fj\u0002\b\rj\u0002\b\u000ej\u0002\b\u000fj\u0002\b\u0010j\u0002\b\u0011j\u0002\b\u0012j\u0002\b\u0013j\u0002\b\u0014j\u0002\b\u0015j\u0002\b\u0016j\u0002\b\u0017j\u0002\b\u0018j\u0002\b\u0019j\u0002\b\u001aj\u0002\b\u001bj\u0002\b\u001cj\u0002\b\u001dj\u0002\b\u001ej\u0002\b\u001fj\u0002\b j\u0002\b!j\u0002\b\"j\u0002\b#j\u0002\b$j\u0002\b%j\u0002\b&j\u0002\b'j\u0002\b(j\u0002\b)j\u0002\b*j\u0002\b+j\u0002\b,j\u0002\b-j\u0002\b.j\u0002\b/j\u0002\b0j\u0002\b1j\u0002\b2j\u0002\b3j\u0002\b4j\u0002\b5j\u0002\b6j\u0002\b7j\u0002\b8j\u0002\b9j\u0002\b:j\u0002\b;j\u0002\b<j\u0002\b=j\u0002\b>j\u0002\b?¨\u0006A"}, d2 = {"Lcom/medium/android/graphql/type/UserDismissableFlags;", "", "rawValue", "", "<init>", "(Ljava/lang/String;ILjava/lang/String;)V", "getRawValue", "()Ljava/lang/String;", "AURORA_NAV_AVAILABLE", "AUTHOR_PAYWALL_OPEN_EDITOR_MODAL", "BETA_CUSTOM_HEADER_LOGO_TOOLTIP", "BETA_LEGACY_PUB_HEADER_PERSONAL_TOOLTIP", "BETA_LEGACY_PUB_HEADER_TOOLTIP", "BETA_PUB_CUSTOM_HEADER_LOGO_PERSONAL_TOOLTIP", "BETA_PUB_CUSTOM_HEADER_LOGO_TOOLTIP", "BLACK_FRIDAY_2025_DISCOUNT_HOME_BANNER", "BLACK_FRIDAY_2025_DISCOUNT_MEMBERSHIP_PAGE_BANNER", "BLACK_FRIDAY_2025_DISCOUNT_POST_PAGE_BANNER", "BLOGROLL_ENABLE", "BLOGROLL_UPDATE", "CREATE_CATALOGS_CTA", "CUSTOMIZE_MEMBERSHIP_PROMOTIONS_BANNER", "DIGEST_TAB_NEW_LABEL", "EXPLICIT_SIGNAL_TOOLTIP", "EXTERNAL_PLATFORM_TIPPING_AWARENESS", "FIRST_USE_ABOUT_BOOKS_AUTHOR_TOOLTIP", "FIRST_USE_BOOKS_HIGHLIGHTS_PRIVACY_TOOLTIP", "FIRST_USE_GET_MORE_FROM_BOOKS_MODAL", "FIRST_USE_GLOBAL_NAV_TOOLTIP", "FIRST_USE_YOUR_BOOKS_MODALS", "FOLLOWERS_TOOLTIP", "HIDE_HIGHLIGHTS_TOOLTIP", "HOMEFEED_FEATURED_TAB_NEW_LABEL", "HOMEFEED_FREE_READ_CTA", "HOMEFEED_REPOST_TOOLTIP", "HOMEPAGE_MEMBERSHIP_BANNER_CTA", "HOMEPAGE_TOPIC_FILTERING_TOOLTIP", "HOMEPAGE_TWITTER_CTA", "MOBILE_OFFLINE_MODE_EDUCATIONAL_DIALOG", "MOBILE_PREMIUM_TIER_EDUCATIONAL_DIALOG", "PAYMENT_METHOD_EXPIRED_MEMBERSHIP_LAST_WEEK_BANNER", "PAYMENT_METHOD_WILL_EXPIRE_MEMBERSHIP_LAST_WEEK_BANNER", "POST_PAGE_FIRST_REPOST_TOAST", "POST_PAGE_REPOST_TOOLTIP", "PP_AWARENESS_BANNER", "PP_TERMS_ACKNOWLEDGEMENT", "PUB_STATS_UPDATE_TOAST", "PUBLICATION_UPDATED_TO_V3_DIALOG", "READING_LIST_EMPTY_CTA", "RECEIPT_EDITABLE_TOOLTIP", "SAVE_TO_LIST_FROM_MOBILE_BOTTOM_BAR_TOOLTIP", "SAVE_TO_LIST_FROM_MORE_MENU_TOOLTIP", "SIDEBAR_MENU_FOLLOWING_EXPERIENCE_SURVEY", "SIDEBAR_MENU_SURVEY", "TOOLTIP_ABOUT_EDITOR", "USER_PROFILE_ACTIVITY_FEED_TOOLTIP", "USER_SIGNAL_MENU", "VERIFIED_BOOK_AUTHORS_CTA", "WRITER_EMAIL_NOTIFICATION_TOOLTIP", "WRITER_ONBOARDING", "WRITER_STARTER_KIT_CTA", "WRITER_SUBSCRIPTIONS_TOOLTIP", "YOUR_STORIES_TK_WRITING_APP_BANNER", "UNKNOWN__", "Companion", "graphql"}, k = 1, mv = {2, 2, 0}, xi = 48)
public final class UserDismissableFlags {
    private static final /* synthetic */ g04 $ENTRIES;
    private static final /* synthetic */ UserDismissableFlags[] $VALUES;

    /* JADX INFO: renamed from: Companion, reason: from kotlin metadata */
    public static final Companion INSTANCE;
    private static final n04 type;
    private final String rawValue;
    public static final UserDismissableFlags AURORA_NAV_AVAILABLE = new UserDismissableFlags("AURORA_NAV_AVAILABLE", 0, "AURORA_NAV_AVAILABLE");
    public static final UserDismissableFlags AUTHOR_PAYWALL_OPEN_EDITOR_MODAL = new UserDismissableFlags("AUTHOR_PAYWALL_OPEN_EDITOR_MODAL", 1, "AUTHOR_PAYWALL_OPEN_EDITOR_MODAL");
    public static final UserDismissableFlags BETA_CUSTOM_HEADER_LOGO_TOOLTIP = new UserDismissableFlags("BETA_CUSTOM_HEADER_LOGO_TOOLTIP", 2, "BETA_CUSTOM_HEADER_LOGO_TOOLTIP");
    public static final UserDismissableFlags BETA_LEGACY_PUB_HEADER_PERSONAL_TOOLTIP = new UserDismissableFlags("BETA_LEGACY_PUB_HEADER_PERSONAL_TOOLTIP", 3, "BETA_LEGACY_PUB_HEADER_PERSONAL_TOOLTIP");
    public static final UserDismissableFlags BETA_LEGACY_PUB_HEADER_TOOLTIP = new UserDismissableFlags("BETA_LEGACY_PUB_HEADER_TOOLTIP", 4, "BETA_LEGACY_PUB_HEADER_TOOLTIP");
    public static final UserDismissableFlags BETA_PUB_CUSTOM_HEADER_LOGO_PERSONAL_TOOLTIP = new UserDismissableFlags("BETA_PUB_CUSTOM_HEADER_LOGO_PERSONAL_TOOLTIP", 5, "BETA_PUB_CUSTOM_HEADER_LOGO_PERSONAL_TOOLTIP");
    public static final UserDismissableFlags BETA_PUB_CUSTOM_HEADER_LOGO_TOOLTIP = new UserDismissableFlags("BETA_PUB_CUSTOM_HEADER_LOGO_TOOLTIP", 6, "BETA_PUB_CUSTOM_HEADER_LOGO_TOOLTIP");
    public static final UserDismissableFlags BLACK_FRIDAY_2025_DISCOUNT_HOME_BANNER = new UserDismissableFlags("BLACK_FRIDAY_2025_DISCOUNT_HOME_BANNER", 7, "BLACK_FRIDAY_2025_DISCOUNT_HOME_BANNER");
    public static final UserDismissableFlags BLACK_FRIDAY_2025_DISCOUNT_MEMBERSHIP_PAGE_BANNER = new UserDismissableFlags("BLACK_FRIDAY_2025_DISCOUNT_MEMBERSHIP_PAGE_BANNER", 8, "BLACK_FRIDAY_2025_DISCOUNT_MEMBERSHIP_PAGE_BANNER");
    public static final UserDismissableFlags BLACK_FRIDAY_2025_DISCOUNT_POST_PAGE_BANNER = new UserDismissableFlags("BLACK_FRIDAY_2025_DISCOUNT_POST_PAGE_BANNER", 9, "BLACK_FRIDAY_2025_DISCOUNT_POST_PAGE_BANNER");
    public static final UserDismissableFlags BLOGROLL_ENABLE = new UserDismissableFlags("BLOGROLL_ENABLE", 10, "BLOGROLL_ENABLE");
    public static final UserDismissableFlags BLOGROLL_UPDATE = new UserDismissableFlags("BLOGROLL_UPDATE", 11, "BLOGROLL_UPDATE");
    public static final UserDismissableFlags CREATE_CATALOGS_CTA = new UserDismissableFlags("CREATE_CATALOGS_CTA", 12, "CREATE_CATALOGS_CTA");
    public static final UserDismissableFlags CUSTOMIZE_MEMBERSHIP_PROMOTIONS_BANNER = new UserDismissableFlags("CUSTOMIZE_MEMBERSHIP_PROMOTIONS_BANNER", 13, "CUSTOMIZE_MEMBERSHIP_PROMOTIONS_BANNER");
    public static final UserDismissableFlags DIGEST_TAB_NEW_LABEL = new UserDismissableFlags("DIGEST_TAB_NEW_LABEL", 14, "DIGEST_TAB_NEW_LABEL");
    public static final UserDismissableFlags EXPLICIT_SIGNAL_TOOLTIP = new UserDismissableFlags("EXPLICIT_SIGNAL_TOOLTIP", 15, "EXPLICIT_SIGNAL_TOOLTIP");
    public static final UserDismissableFlags EXTERNAL_PLATFORM_TIPPING_AWARENESS = new UserDismissableFlags("EXTERNAL_PLATFORM_TIPPING_AWARENESS", 16, "EXTERNAL_PLATFORM_TIPPING_AWARENESS");
    public static final UserDismissableFlags FIRST_USE_ABOUT_BOOKS_AUTHOR_TOOLTIP = new UserDismissableFlags("FIRST_USE_ABOUT_BOOKS_AUTHOR_TOOLTIP", 17, "FIRST_USE_ABOUT_BOOKS_AUTHOR_TOOLTIP");
    public static final UserDismissableFlags FIRST_USE_BOOKS_HIGHLIGHTS_PRIVACY_TOOLTIP = new UserDismissableFlags("FIRST_USE_BOOKS_HIGHLIGHTS_PRIVACY_TOOLTIP", 18, "FIRST_USE_BOOKS_HIGHLIGHTS_PRIVACY_TOOLTIP");
    public static final UserDismissableFlags FIRST_USE_GET_MORE_FROM_BOOKS_MODAL = new UserDismissableFlags("FIRST_USE_GET_MORE_FROM_BOOKS_MODAL", 19, "FIRST_USE_GET_MORE_FROM_BOOKS_MODAL");
    public static final UserDismissableFlags FIRST_USE_GLOBAL_NAV_TOOLTIP = new UserDismissableFlags("FIRST_USE_GLOBAL_NAV_TOOLTIP", 20, "FIRST_USE_GLOBAL_NAV_TOOLTIP");
    public static final UserDismissableFlags FIRST_USE_YOUR_BOOKS_MODALS = new UserDismissableFlags("FIRST_USE_YOUR_BOOKS_MODALS", 21, "FIRST_USE_YOUR_BOOKS_MODALS");
    public static final UserDismissableFlags FOLLOWERS_TOOLTIP = new UserDismissableFlags("FOLLOWERS_TOOLTIP", 22, "FOLLOWERS_TOOLTIP");
    public static final UserDismissableFlags HIDE_HIGHLIGHTS_TOOLTIP = new UserDismissableFlags("HIDE_HIGHLIGHTS_TOOLTIP", 23, "HIDE_HIGHLIGHTS_TOOLTIP");
    public static final UserDismissableFlags HOMEFEED_FEATURED_TAB_NEW_LABEL = new UserDismissableFlags("HOMEFEED_FEATURED_TAB_NEW_LABEL", 24, "HOMEFEED_FEATURED_TAB_NEW_LABEL");
    public static final UserDismissableFlags HOMEFEED_FREE_READ_CTA = new UserDismissableFlags("HOMEFEED_FREE_READ_CTA", 25, "HOMEFEED_FREE_READ_CTA");
    public static final UserDismissableFlags HOMEFEED_REPOST_TOOLTIP = new UserDismissableFlags("HOMEFEED_REPOST_TOOLTIP", 26, "HOMEFEED_REPOST_TOOLTIP");
    public static final UserDismissableFlags HOMEPAGE_MEMBERSHIP_BANNER_CTA = new UserDismissableFlags("HOMEPAGE_MEMBERSHIP_BANNER_CTA", 27, "HOMEPAGE_MEMBERSHIP_BANNER_CTA");
    public static final UserDismissableFlags HOMEPAGE_TOPIC_FILTERING_TOOLTIP = new UserDismissableFlags("HOMEPAGE_TOPIC_FILTERING_TOOLTIP", 28, "HOMEPAGE_TOPIC_FILTERING_TOOLTIP");
    public static final UserDismissableFlags HOMEPAGE_TWITTER_CTA = new UserDismissableFlags("HOMEPAGE_TWITTER_CTA", 29, "HOMEPAGE_TWITTER_CTA");
    public static final UserDismissableFlags MOBILE_OFFLINE_MODE_EDUCATIONAL_DIALOG = new UserDismissableFlags("MOBILE_OFFLINE_MODE_EDUCATIONAL_DIALOG", 30, "MOBILE_OFFLINE_MODE_EDUCATIONAL_DIALOG");
    public static final UserDismissableFlags MOBILE_PREMIUM_TIER_EDUCATIONAL_DIALOG = new UserDismissableFlags("MOBILE_PREMIUM_TIER_EDUCATIONAL_DIALOG", 31, "MOBILE_PREMIUM_TIER_EDUCATIONAL_DIALOG");
    public static final UserDismissableFlags PAYMENT_METHOD_EXPIRED_MEMBERSHIP_LAST_WEEK_BANNER = new UserDismissableFlags("PAYMENT_METHOD_EXPIRED_MEMBERSHIP_LAST_WEEK_BANNER", 32, "PAYMENT_METHOD_EXPIRED_MEMBERSHIP_LAST_WEEK_BANNER");
    public static final UserDismissableFlags PAYMENT_METHOD_WILL_EXPIRE_MEMBERSHIP_LAST_WEEK_BANNER = new UserDismissableFlags("PAYMENT_METHOD_WILL_EXPIRE_MEMBERSHIP_LAST_WEEK_BANNER", 33, "PAYMENT_METHOD_WILL_EXPIRE_MEMBERSHIP_LAST_WEEK_BANNER");
    public static final UserDismissableFlags POST_PAGE_FIRST_REPOST_TOAST = new UserDismissableFlags("POST_PAGE_FIRST_REPOST_TOAST", 34, "POST_PAGE_FIRST_REPOST_TOAST");
    public static final UserDismissableFlags POST_PAGE_REPOST_TOOLTIP = new UserDismissableFlags("POST_PAGE_REPOST_TOOLTIP", 35, "POST_PAGE_REPOST_TOOLTIP");
    public static final UserDismissableFlags PP_AWARENESS_BANNER = new UserDismissableFlags("PP_AWARENESS_BANNER", 36, "PP_AWARENESS_BANNER");
    public static final UserDismissableFlags PP_TERMS_ACKNOWLEDGEMENT = new UserDismissableFlags("PP_TERMS_ACKNOWLEDGEMENT", 37, "PP_TERMS_ACKNOWLEDGEMENT");
    public static final UserDismissableFlags PUB_STATS_UPDATE_TOAST = new UserDismissableFlags("PUB_STATS_UPDATE_TOAST", 38, "PUB_STATS_UPDATE_TOAST");
    public static final UserDismissableFlags PUBLICATION_UPDATED_TO_V3_DIALOG = new UserDismissableFlags("PUBLICATION_UPDATED_TO_V3_DIALOG", 39, "PUBLICATION_UPDATED_TO_V3_DIALOG");
    public static final UserDismissableFlags READING_LIST_EMPTY_CTA = new UserDismissableFlags("READING_LIST_EMPTY_CTA", 40, "READING_LIST_EMPTY_CTA");
    public static final UserDismissableFlags RECEIPT_EDITABLE_TOOLTIP = new UserDismissableFlags("RECEIPT_EDITABLE_TOOLTIP", 41, "RECEIPT_EDITABLE_TOOLTIP");
    public static final UserDismissableFlags SAVE_TO_LIST_FROM_MOBILE_BOTTOM_BAR_TOOLTIP = new UserDismissableFlags("SAVE_TO_LIST_FROM_MOBILE_BOTTOM_BAR_TOOLTIP", 42, "SAVE_TO_LIST_FROM_MOBILE_BOTTOM_BAR_TOOLTIP");
    public static final UserDismissableFlags SAVE_TO_LIST_FROM_MORE_MENU_TOOLTIP = new UserDismissableFlags("SAVE_TO_LIST_FROM_MORE_MENU_TOOLTIP", 43, "SAVE_TO_LIST_FROM_MORE_MENU_TOOLTIP");
    public static final UserDismissableFlags SIDEBAR_MENU_FOLLOWING_EXPERIENCE_SURVEY = new UserDismissableFlags("SIDEBAR_MENU_FOLLOWING_EXPERIENCE_SURVEY", 44, "SIDEBAR_MENU_FOLLOWING_EXPERIENCE_SURVEY");
    public static final UserDismissableFlags SIDEBAR_MENU_SURVEY = new UserDismissableFlags("SIDEBAR_MENU_SURVEY", 45, "SIDEBAR_MENU_SURVEY");
    public static final UserDismissableFlags TOOLTIP_ABOUT_EDITOR = new UserDismissableFlags("TOOLTIP_ABOUT_EDITOR", 46, "TOOLTIP_ABOUT_EDITOR");
    public static final UserDismissableFlags USER_PROFILE_ACTIVITY_FEED_TOOLTIP = new UserDismissableFlags("USER_PROFILE_ACTIVITY_FEED_TOOLTIP", 47, "USER_PROFILE_ACTIVITY_FEED_TOOLTIP");
    public static final UserDismissableFlags USER_SIGNAL_MENU = new UserDismissableFlags("USER_SIGNAL_MENU", 48, "USER_SIGNAL_MENU");
    public static final UserDismissableFlags VERIFIED_BOOK_AUTHORS_CTA = new UserDismissableFlags("VERIFIED_BOOK_AUTHORS_CTA", 49, "VERIFIED_BOOK_AUTHORS_CTA");
    public static final UserDismissableFlags WRITER_EMAIL_NOTIFICATION_TOOLTIP = new UserDismissableFlags("WRITER_EMAIL_NOTIFICATION_TOOLTIP", 50, "WRITER_EMAIL_NOTIFICATION_TOOLTIP");
    public static final UserDismissableFlags WRITER_ONBOARDING = new UserDismissableFlags("WRITER_ONBOARDING", 51, "WRITER_ONBOARDING");
    public static final UserDismissableFlags WRITER_STARTER_KIT_CTA = new UserDismissableFlags("WRITER_STARTER_KIT_CTA", 52, "WRITER_STARTER_KIT_CTA");
    public static final UserDismissableFlags WRITER_SUBSCRIPTIONS_TOOLTIP = new UserDismissableFlags("WRITER_SUBSCRIPTIONS_TOOLTIP", 53, "WRITER_SUBSCRIPTIONS_TOOLTIP");
    public static final UserDismissableFlags YOUR_STORIES_TK_WRITING_APP_BANNER = new UserDismissableFlags("YOUR_STORIES_TK_WRITING_APP_BANNER", 54, "YOUR_STORIES_TK_WRITING_APP_BANNER");
    public static final UserDismissableFlags UNKNOWN__ = new UserDismissableFlags("UNKNOWN__", 55, "UNKNOWN__");

    private static final /* synthetic */ UserDismissableFlags[] $values() {
        return new UserDismissableFlags[]{AURORA_NAV_AVAILABLE, AUTHOR_PAYWALL_OPEN_EDITOR_MODAL, BETA_CUSTOM_HEADER_LOGO_TOOLTIP, BETA_LEGACY_PUB_HEADER_PERSONAL_TOOLTIP, BETA_LEGACY_PUB_HEADER_TOOLTIP, BETA_PUB_CUSTOM_HEADER_LOGO_PERSONAL_TOOLTIP, BETA_PUB_CUSTOM_HEADER_LOGO_TOOLTIP, BLACK_FRIDAY_2025_DISCOUNT_HOME_BANNER, BLACK_FRIDAY_2025_DISCOUNT_MEMBERSHIP_PAGE_BANNER, BLACK_FRIDAY_2025_DISCOUNT_POST_PAGE_BANNER, BLOGROLL_ENABLE, BLOGROLL_UPDATE, CREATE_CATALOGS_CTA, CUSTOMIZE_MEMBERSHIP_PROMOTIONS_BANNER, DIGEST_TAB_NEW_LABEL, EXPLICIT_SIGNAL_TOOLTIP, EXTERNAL_PLATFORM_TIPPING_AWARENESS, FIRST_USE_ABOUT_BOOKS_AUTHOR_TOOLTIP, FIRST_USE_BOOKS_HIGHLIGHTS_PRIVACY_TOOLTIP, FIRST_USE_GET_MORE_FROM_BOOKS_MODAL, FIRST_USE_GLOBAL_NAV_TOOLTIP, FIRST_USE_YOUR_BOOKS_MODALS, FOLLOWERS_TOOLTIP, HIDE_HIGHLIGHTS_TOOLTIP, HOMEFEED_FEATURED_TAB_NEW_LABEL, HOMEFEED_FREE_READ_CTA, HOMEFEED_REPOST_TOOLTIP, HOMEPAGE_MEMBERSHIP_BANNER_CTA, HOMEPAGE_TOPIC_FILTERING_TOOLTIP, HOMEPAGE_TWITTER_CTA, MOBILE_OFFLINE_MODE_EDUCATIONAL_DIALOG, MOBILE_PREMIUM_TIER_EDUCATIONAL_DIALOG, PAYMENT_METHOD_EXPIRED_MEMBERSHIP_LAST_WEEK_BANNER, PAYMENT_METHOD_WILL_EXPIRE_MEMBERSHIP_LAST_WEEK_BANNER, POST_PAGE_FIRST_REPOST_TOAST, POST_PAGE_REPOST_TOOLTIP, PP_AWARENESS_BANNER, PP_TERMS_ACKNOWLEDGEMENT, PUB_STATS_UPDATE_TOAST, PUBLICATION_UPDATED_TO_V3_DIALOG, READING_LIST_EMPTY_CTA, RECEIPT_EDITABLE_TOOLTIP, SAVE_TO_LIST_FROM_MOBILE_BOTTOM_BAR_TOOLTIP, SAVE_TO_LIST_FROM_MORE_MENU_TOOLTIP, SIDEBAR_MENU_FOLLOWING_EXPERIENCE_SURVEY, SIDEBAR_MENU_SURVEY, TOOLTIP_ABOUT_EDITOR, USER_PROFILE_ACTIVITY_FEED_TOOLTIP, USER_SIGNAL_MENU, VERIFIED_BOOK_AUTHORS_CTA, WRITER_EMAIL_NOTIFICATION_TOOLTIP, WRITER_ONBOARDING, WRITER_STARTER_KIT_CTA, WRITER_SUBSCRIPTIONS_TOOLTIP, YOUR_STORIES_TK_WRITING_APP_BANNER, UNKNOWN__};
    }

    private UserDismissableFlags(String str, int i, String str2) {
        this.rawValue = str2;
    }

    public static g04 getEntries() {
        return $ENTRIES;
    }

    public static UserDismissableFlags valueOf(String str) {
        return (UserDismissableFlags) Enum.valueOf(UserDismissableFlags.class, str);
    }

    public static UserDismissableFlags[] values() {
        return (UserDismissableFlags[]) $VALUES.clone();
    }

    public final String getRawValue() {
        return this.rawValue;
    }

    static {
        UserDismissableFlags[] userDismissableFlagsArr$values = $values();
        $VALUES = userDismissableFlagsArr$values;
        $ENTRIES = new i04(userDismissableFlagsArr$values);
        INSTANCE = new Companion();
        d46.R("AURORA_NAV_AVAILABLE", "AUTHOR_PAYWALL_OPEN_EDITOR_MODAL", "BETA_CUSTOM_HEADER_LOGO_TOOLTIP", "BETA_LEGACY_PUB_HEADER_PERSONAL_TOOLTIP", "BETA_LEGACY_PUB_HEADER_TOOLTIP", "BETA_PUB_CUSTOM_HEADER_LOGO_PERSONAL_TOOLTIP", "BETA_PUB_CUSTOM_HEADER_LOGO_TOOLTIP", "BLACK_FRIDAY_2025_DISCOUNT_HOME_BANNER", "BLACK_FRIDAY_2025_DISCOUNT_MEMBERSHIP_PAGE_BANNER", "BLACK_FRIDAY_2025_DISCOUNT_POST_PAGE_BANNER", "BLOGROLL_ENABLE", "BLOGROLL_UPDATE", "CREATE_CATALOGS_CTA", "CUSTOMIZE_MEMBERSHIP_PROMOTIONS_BANNER", "DIGEST_TAB_NEW_LABEL", "EXPLICIT_SIGNAL_TOOLTIP", "EXTERNAL_PLATFORM_TIPPING_AWARENESS", "FIRST_USE_ABOUT_BOOKS_AUTHOR_TOOLTIP", "FIRST_USE_BOOKS_HIGHLIGHTS_PRIVACY_TOOLTIP", "FIRST_USE_GET_MORE_FROM_BOOKS_MODAL", "FIRST_USE_GLOBAL_NAV_TOOLTIP", "FIRST_USE_YOUR_BOOKS_MODALS", "FOLLOWERS_TOOLTIP", "HIDE_HIGHLIGHTS_TOOLTIP", "HOMEFEED_FEATURED_TAB_NEW_LABEL", "HOMEFEED_FREE_READ_CTA", "HOMEFEED_REPOST_TOOLTIP", "HOMEPAGE_MEMBERSHIP_BANNER_CTA", "HOMEPAGE_TOPIC_FILTERING_TOOLTIP", "HOMEPAGE_TWITTER_CTA", "MOBILE_OFFLINE_MODE_EDUCATIONAL_DIALOG", "MOBILE_PREMIUM_TIER_EDUCATIONAL_DIALOG", "PAYMENT_METHOD_EXPIRED_MEMBERSHIP_LAST_WEEK_BANNER", "PAYMENT_METHOD_WILL_EXPIRE_MEMBERSHIP_LAST_WEEK_BANNER", "POST_PAGE_FIRST_REPOST_TOAST", "POST_PAGE_REPOST_TOOLTIP", "PP_AWARENESS_BANNER", "PP_TERMS_ACKNOWLEDGEMENT", "PUB_STATS_UPDATE_TOAST", "PUBLICATION_UPDATED_TO_V3_DIALOG", "READING_LIST_EMPTY_CTA", "RECEIPT_EDITABLE_TOOLTIP", "SAVE_TO_LIST_FROM_MOBILE_BOTTOM_BAR_TOOLTIP", "SAVE_TO_LIST_FROM_MORE_MENU_TOOLTIP", "SIDEBAR_MENU_FOLLOWING_EXPERIENCE_SURVEY", "SIDEBAR_MENU_SURVEY", "TOOLTIP_ABOUT_EDITOR", "USER_PROFILE_ACTIVITY_FEED_TOOLTIP", eoLmc.EDkKhHEgbI, "VERIFIED_BOOK_AUTHORS_CTA", "WRITER_EMAIL_NOTIFICATION_TOOLTIP", "WRITER_ONBOARDING", "WRITER_STARTER_KIT_CTA", "WRITER_SUBSCRIPTIONS_TOOLTIP", "YOUR_STORIES_TK_WRITING_APP_BANNER");
        type = new n04("UserDismissableFlags");
    }

    /* JADX INFO: compiled from: r8-map-id-b2309a5993a3f14549aeb617bc4a78ecbec51e99a3efca387f8965087335ae2d */
    @Metadata(d1 = {"\u00000\n\u0002\u0018\u0002\n\u0002\u0010\u0000\n\u0002\b\u0002\n\u0002\u0010\u0011\n\u0002\u0018\u0002\n\u0002\b\u0002\n\u0002\u0010\u000e\n\u0002\b\u0003\n\u0002\u0018\u0002\n\u0002\b\u0004\n\u0002\u0010 \n\u0002\b\u0004\b\u0086\u0003\u0018\u00002\u00020\u0001B\t\b\u0002¢\u0006\u0004\b\u0002\u0010\u0003J\u0015\u0010\u0006\u001a\b\u0012\u0004\u0012\u00020\u00050\u0004H\u0007¢\u0006\u0004\b\u0006\u0010\u0007J\u0015\u0010\n\u001a\u00020\u00052\u0006\u0010\t\u001a\u00020\b¢\u0006\u0004\b\n\u0010\u000bR\u0017\u0010\r\u001a\u00020\f8\u0006¢\u0006\f\n\u0004\b\r\u0010\u000e\u001a\u0004\b\u000f\u0010\u0010R\u0017\u0010\u0014\u001a\b\u0012\u0004\u0012\u00020\u00050\u00118F¢\u0006\u0006\u001a\u0004\b\u0012\u0010\u0013¨\u0006\u0015"}, d2 = {"Lcom/medium/android/graphql/type/UserDismissableFlags$Companion;", "", "<init>", "()V", "", "Lcom/medium/android/graphql/type/UserDismissableFlags;", "knownValues", "()[Lcom/medium/android/graphql/type/UserDismissableFlags;", "", "rawValue", "safeValueOf", "(Ljava/lang/String;)Lcom/medium/android/graphql/type/UserDismissableFlags;", "Ln04;", "type", "Ln04;", "getType", "()Ln04;", "", "getKnownEntries", "()Ljava/util/List;", "knownEntries", "graphql"}, k = 1, mv = {2, 2, 0}, xi = 48)
    public static final class Companion {
        private Companion() {
        }

        public final List<UserDismissableFlags> getKnownEntries() {
            return d46.R(UserDismissableFlags.AURORA_NAV_AVAILABLE, UserDismissableFlags.AUTHOR_PAYWALL_OPEN_EDITOR_MODAL, UserDismissableFlags.BETA_CUSTOM_HEADER_LOGO_TOOLTIP, UserDismissableFlags.BETA_LEGACY_PUB_HEADER_PERSONAL_TOOLTIP, UserDismissableFlags.BETA_LEGACY_PUB_HEADER_TOOLTIP, UserDismissableFlags.BETA_PUB_CUSTOM_HEADER_LOGO_PERSONAL_TOOLTIP, UserDismissableFlags.BETA_PUB_CUSTOM_HEADER_LOGO_TOOLTIP, UserDismissableFlags.BLACK_FRIDAY_2025_DISCOUNT_HOME_BANNER, UserDismissableFlags.BLACK_FRIDAY_2025_DISCOUNT_MEMBERSHIP_PAGE_BANNER, UserDismissableFlags.BLACK_FRIDAY_2025_DISCOUNT_POST_PAGE_BANNER, UserDismissableFlags.BLOGROLL_ENABLE, UserDismissableFlags.BLOGROLL_UPDATE, UserDismissableFlags.CREATE_CATALOGS_CTA, UserDismissableFlags.CUSTOMIZE_MEMBERSHIP_PROMOTIONS_BANNER, UserDismissableFlags.DIGEST_TAB_NEW_LABEL, UserDismissableFlags.EXPLICIT_SIGNAL_TOOLTIP, UserDismissableFlags.EXTERNAL_PLATFORM_TIPPING_AWARENESS, UserDismissableFlags.FIRST_USE_ABOUT_BOOKS_AUTHOR_TOOLTIP, UserDismissableFlags.FIRST_USE_BOOKS_HIGHLIGHTS_PRIVACY_TOOLTIP, UserDismissableFlags.FIRST_USE_GET_MORE_FROM_BOOKS_MODAL, UserDismissableFlags.FIRST_USE_GLOBAL_NAV_TOOLTIP, UserDismissableFlags.FIRST_USE_YOUR_BOOKS_MODALS, UserDismissableFlags.FOLLOWERS_TOOLTIP, UserDismissableFlags.HIDE_HIGHLIGHTS_TOOLTIP, UserDismissableFlags.HOMEFEED_FEATURED_TAB_NEW_LABEL, UserDismissableFlags.HOMEFEED_FREE_READ_CTA, UserDismissableFlags.HOMEFEED_REPOST_TOOLTIP, UserDismissableFlags.HOMEPAGE_MEMBERSHIP_BANNER_CTA, UserDismissableFlags.HOMEPAGE_TOPIC_FILTERING_TOOLTIP, UserDismissableFlags.HOMEPAGE_TWITTER_CTA, UserDismissableFlags.MOBILE_OFFLINE_MODE_EDUCATIONAL_DIALOG, UserDismissableFlags.MOBILE_PREMIUM_TIER_EDUCATIONAL_DIALOG, UserDismissableFlags.PAYMENT_METHOD_EXPIRED_MEMBERSHIP_LAST_WEEK_BANNER, UserDismissableFlags.PAYMENT_METHOD_WILL_EXPIRE_MEMBERSHIP_LAST_WEEK_BANNER, UserDismissableFlags.POST_PAGE_FIRST_REPOST_TOAST, UserDismissableFlags.POST_PAGE_REPOST_TOOLTIP, UserDismissableFlags.PP_AWARENESS_BANNER, UserDismissableFlags.PP_TERMS_ACKNOWLEDGEMENT, UserDismissableFlags.PUB_STATS_UPDATE_TOAST, UserDismissableFlags.PUBLICATION_UPDATED_TO_V3_DIALOG, UserDismissableFlags.READING_LIST_EMPTY_CTA, UserDismissableFlags.RECEIPT_EDITABLE_TOOLTIP, UserDismissableFlags.SAVE_TO_LIST_FROM_MOBILE_BOTTOM_BAR_TOOLTIP, UserDismissableFlags.SAVE_TO_LIST_FROM_MORE_MENU_TOOLTIP, UserDismissableFlags.SIDEBAR_MENU_FOLLOWING_EXPERIENCE_SURVEY, UserDismissableFlags.SIDEBAR_MENU_SURVEY, UserDismissableFlags.TOOLTIP_ABOUT_EDITOR, UserDismissableFlags.USER_PROFILE_ACTIVITY_FEED_TOOLTIP, UserDismissableFlags.USER_SIGNAL_MENU, UserDismissableFlags.VERIFIED_BOOK_AUTHORS_CTA, UserDismissableFlags.WRITER_EMAIL_NOTIFICATION_TOOLTIP, UserDismissableFlags.WRITER_ONBOARDING, UserDismissableFlags.WRITER_STARTER_KIT_CTA, UserDismissableFlags.WRITER_SUBSCRIPTIONS_TOOLTIP, UserDismissableFlags.YOUR_STORIES_TK_WRITING_APP_BANNER);
        }

        public final n04 getType() {
            return UserDismissableFlags.type;
        }

        @z73
        public final UserDismissableFlags[] knownValues() {
            return (UserDismissableFlags[]) getKnownEntries().toArray(new UserDismissableFlags[0]);
        }

        public final UserDismissableFlags safeValueOf(String rawValue) {
            Object next;
            rawValue.getClass();
            Iterator<E> it2 = UserDismissableFlags.getEntries().iterator();
            while (true) {
                if (!it2.hasNext()) {
                    next = null;
                    break;
                }
                next = it2.next();
                if (g76.L(((UserDismissableFlags) next).getRawValue(), rawValue)) {
                    break;
                }
            }
            UserDismissableFlags userDismissableFlags = (UserDismissableFlags) next;
            return userDismissableFlags == null ? UserDismissableFlags.UNKNOWN__ : userDismissableFlags;
        }

        public Companion(gy2 gy2Var) {
        }
    }
}
