/*
 * Copyright 2026 Hushfacebook contributors
 * https://github.com/SysAdminDoc/Hushfacebook
 */
package app.morphe.extension.facebook.settings;

import app.morphe.extension.shared.L10n;
import app.morphe.extension.shared.settings.BooleanSetting;

/** Individual switch names, shared by the feature pages and imports regardless of patch selection. */
final class SwitchLabels {
    private SwitchLabels() {
    }

    static String title(BooleanSetting setting) {
        if (setting == Settings.MARKETPLACE_ONLY) return L10n.t("Marketplace only");
        if (setting == Settings.MARKETPLACE_QUIET_NOTIFICATIONS) return L10n.t("Quiet social notifications");
        if (setting == Settings.MARKETPLACE_SKIP_FEED_PREFETCH) return L10n.t("Skip feed preloading");
        if (setting == Settings.OPEN_ON_CHOSEN_TAB) return L10n.t("Open on a chosen tab");
        if (setting == Settings.FOLLOWING_FEED_HOME) return L10n.t("Following feed on Home");
        if (setting == Settings.HIDE_SPONSORED_POSTS) return L10n.t("Hide sponsored posts");
        if (setting == Settings.HIDE_PROMOTED_POSTS) return L10n.t("Hide promoted posts");
        if (setting == Settings.HIDE_SPONSORED_PROFILE_POSTS) return L10n.t("Hide sponsored profile posts");
        if (setting == Settings.HIDE_AFFILIATE_LINKS) return L10n.t("Hide affiliate product links");
        if (setting == Settings.HIDE_SUGGESTED_POSTS) return L10n.t("Hide page suggestions and Facebook's own promos");
        if (setting == Settings.HIDE_SUGGESTED_FOR_YOU) return L10n.t("Hide \"Suggested for you\" posts");
        if (setting == Settings.HIDE_PEOPLE_YOU_MAY_KNOW) return L10n.t("Hide \"People you may know\"");
        if (setting == Settings.HIDE_SUGGESTED_GROUPS) return L10n.t("Hide suggested groups");
        if (setting == Settings.HIDE_STORIES_YOU_MIGHT_LIKE) return L10n.t("Hide \"Stories you might like\"");
        if (setting == Settings.HIDE_FEED_MEMORIES) return L10n.t("Hide Memories in the feed");
        if (setting == Settings.HIDE_FEED_FRIEND_REQUESTS) return L10n.t("Hide friend requests in the feed");
        if (setting == Settings.HIDE_FRIENDS_LOCATIONS) return L10n.t("Hide friends' locations");
        if (setting == Settings.HIDE_TOP_STORIES_TRAY) return L10n.t("Hide the Stories tray");
        if (setting == Settings.HIDE_STORIES_BETWEEN_POSTS) return L10n.t("Hide Stories between posts");
        if (setting == Settings.HIDE_HOME_COMPOSER) return L10n.t("Hide the composer row");
        if (setting == Settings.HIDE_FEED_REELS) return L10n.t("Hide Reels in the feed");
        if (setting == Settings.HIDE_POST_PROMPTS) return L10n.t("Hide post prompts");
        if (setting == Settings.HIDE_SEEN_POSTS) return L10n.t("Hide posts you've already seen");
        if (setting == Settings.HIDE_META_AI_QUESTIONS) return L10n.t("Hide Meta AI questions under posts");
        if (setting == Settings.KEEP_POST_DATES) return L10n.t("Keep post dates");
        if (setting == Settings.TURN_OFF_AUTO_TRANSLATION) return L10n.t("Turn off auto-translation");
        if (setting == Settings.HIDE_FEEDS_HEADER) return L10n.t("Hide the Feeds header");
        if (setting == Settings.BLOCK_RETURN_REFRESH) return L10n.t("Keep feed position on return");
        if (setting == Settings.RETURN_REFRESH_NO_LIMIT) return L10n.t("No time limit");
        if (setting == Settings.HIDE_AI_DETECTED_POSTS) return L10n.t("Hide AI-detected posts");
        if (setting == Settings.HIDE_AI_LABELLED_POSTS) return L10n.t("Also hide posts labelled as AI");
        if (setting == Settings.HIDE_META_AI_FEED_UNITS) return L10n.t("Hide Meta AI in the feed");
        if (setting == Settings.HIDE_AI_CHARACTER_POSTS) return L10n.t("Hide AI character posts");
        if (setting == Settings.HIDE_POSTS_WITH_WORDS) return L10n.t("Hide posts with words you choose");
        if (setting == Settings.HIDE_POSTS_FROM_SOURCES) return L10n.t("Hide posts from people, Pages and sites");
        if (setting == Settings.POST_WORDS_WHOLE_WORDS) return L10n.t("Match whole words");
        if (setting == Settings.HIDE_PHOTO_POSTS) return L10n.t("Hide photo posts");
        if (setting == Settings.HIDE_VIDEO_POSTS) return L10n.t("Hide video posts");
        if (setting == Settings.HIDE_LINK_POSTS) return L10n.t("Hide link posts");
        if (setting == Settings.HIDE_BACKGROUND_POSTS) return L10n.t("Hide posts on a colored background");
        if (setting == Settings.HIDE_SPONSORED_STORIES) return L10n.t("Hide sponsored stories");
        if (setting == Settings.HIDE_SUGGESTED_STORIES) return L10n.t("Hide suggested stories");
        if (setting == Settings.HIDE_CONTACT_IMPORT_CARD) return L10n.t("Hide \"Find friends from contacts\"");
        if (setting == Settings.HIDE_STORY_PROMPTS) return L10n.t("Hide story prompts");
        if (setting == Settings.BLOCK_STORY_AUTO_ADVANCE) return L10n.t("Stop Story auto-advance");
        if (setting == Settings.LOOP_STORIES) return L10n.t("Loop stories");
        if (setting == Settings.VIEW_STORIES_ANONYMOUSLY) return L10n.t("View stories anonymously");
        if (setting == Settings.MARK_STORIES_SEEN) return L10n.t("Mark as seen button");
        if (setting == Settings.DOWNLOAD_STORIES) return L10n.t("Save any story");
        if (setting == Settings.DEFAULT_COMMENT_ORDER) return L10n.t("Default comment order");
        if (setting == Settings.HIDE_META_AI_SUMMARIES) return L10n.t("Hide Meta AI comment summaries");
        if (setting == Settings.LIKE_ONLY) return L10n.t("Like only");
        if (setting == Settings.HIDE_COMMENT_GIF_STICKER_BUTTONS) return L10n.t("Hide GIF and sticker buttons");
        if (setting == Settings.OPEN_REPLY_THREADS) return L10n.t("Open every reply thread");
        if (setting == Settings.TAG_SUGGESTIONS_ONLY_AFTER_AT) return L10n.t("Tag suggestions only after @");
        if (setting == Settings.HIDE_REELS_TAB) return L10n.t("Hide the Reels tab");
        if (setting == Settings.HIDE_REELS_TAB_DOT) return L10n.t("Hide the Reels tab dot");
        if (setting == Settings.HIDE_HOME_TAB_BADGE) return L10n.t("Hide the Home tab badge");
        if (setting == Settings.HIDE_FRIENDS_TAB_BADGE) return L10n.t("Hide the Friends tab badge");
        if (setting == Settings.HIDE_MARKETPLACE_TAB_BADGE) return L10n.t("Hide the Marketplace tab badge");
        if (setting == Settings.HIDE_NOTIFICATIONS_TAB_BADGE) return L10n.t("Hide the Notifications tab badge");
        if (setting == Settings.HIDE_MENU_TAB_BADGE) return L10n.t("Hide the Menu tab badge");
        if (setting == Settings.HIDE_GROUPS_TAB_BADGE) return L10n.t("Hide the Groups tab badge");
        if (setting == Settings.HIDE_OTHER_TAB_BADGES) return L10n.t("Hide other tabs' badges");
        if (setting == Settings.HIDE_APP_ICON_COUNT) return L10n.t("Hide the app icon count");
        if (setting == Settings.HIDE_FEEDS_TAB) return L10n.t("Hide the Feeds tab");
        if (setting == Settings.HIDE_FRIENDS_TAB) return L10n.t("Hide the Friends tab");
        if (setting == Settings.HIDE_MARKETPLACE_TAB) return L10n.t("Hide the Marketplace tab");
        if (setting == Settings.HIDE_GROUPS_TAB) return L10n.t("Hide the Groups tab");
        if (setting == Settings.HIDE_GAMING_TAB) return L10n.t("Hide the Gaming tab");
        if (setting == Settings.HIDE_EVENTS_TAB) return L10n.t("Hide the Events tab");
        if (setting == Settings.HIDE_DATING_TAB) return L10n.t("Hide the Dating tab");
        if (setting == Settings.HIDE_PROFESSIONAL_DASHBOARD_TAB) return L10n.t("Hide the Professional dashboard tab");
        if (setting == Settings.HIDE_SAVED_TAB) return L10n.t("Hide the Saved tab");
        if (setting == Settings.HIDE_AD_CENTER_TAB) return L10n.t("Hide the Ad Center tab");
        if (setting == Settings.HIDE_CREATE_TAB) return L10n.t("Hide the Create tab");
        if (setting == Settings.HIDE_EXPLORE_TAB) return L10n.t("Hide the Explore tab");
        if (setting == Settings.HIDE_JOBS_TAB) return L10n.t("Hide the Jobs tab");
        if (setting == Settings.HIDE_REEL_PROMPTS) return L10n.t("Hide reel interest prompts");
        if (setting == Settings.HIDE_SPONSORED_REELS) return L10n.t("Hide sponsored reels");
        if (setting == Settings.HIDE_AI_DETECTED_REELS) return L10n.t("Hide AI-detected reels and videos");
        if (setting == Settings.HIDE_REEL_CHIPS) return L10n.t("Hide prompts and promos under reels");
        if (setting == Settings.HIDE_REEL_FOLLOW_BUTTON) return L10n.t("Hide the Follow button on reels");
        if (setting == Settings.HIDE_REEL_SOCIAL_FOOTER) return L10n.t("Hide comment and reaction previews");
        if (setting == Settings.HIDE_REEL_THREADS_CARDS) return L10n.t("Hide Threads cards between reels");
        if (setting == Settings.REEL_CLEAN_MODE) return L10n.t("Always use Clean mode");
        if (setting == Settings.DONT_SEND_REEL_WATCH_HISTORY) return L10n.t("Don't send reel watch history");
        if (setting == Settings.HOLD_ANALYTICS_UPLOADS) return L10n.t("Hold back analytics uploads");
        if (setting == Settings.ALLOW_SCREENSHOTS) return L10n.t("Allow screenshots");
        if (setting == Settings.TURN_OFF_HAPTICS) return L10n.t("Turn off haptics");
        if (setting == Settings.TURN_OFF_SCREEN_TRANSITIONS) return L10n.t("Turn off screen transitions");
        if (setting == Settings.BLOCK_SCREENSHOT_DETECTION) return L10n.t("Block screenshot detection");
        if (setting == Settings.HIDE_CHAT_TYPING) return L10n.t("Hide typing in chats");
        if (setting == Settings.HIDE_COMMENT_TYPING) return L10n.t("Hide typing in comments");
        if (setting == Settings.HIDE_READ_RECEIPTS) return L10n.t("Hide read receipts");
        if (setting == Settings.ORIGINAL_CHAT_MEDIA) return L10n.t("Send photos and videos at original quality");
        if (setting == Settings.TURN_OFF_DOUBLE_TAP_LIKE) return L10n.t("Turn off double tap to like");
        if (setting == Settings.KEEP_REEL_SPEED) return L10n.t("Keep the reel speed");
        if (setting == Settings.KEEP_VIDEO_SPEED) return L10n.t("Keep the video speed");
        if (setting == Settings.SLOWER_REEL_SPEEDS) return L10n.t("Slower speeds");
        if (setting == Settings.HOLD_REEL_FOR_2X) return L10n.t("Hold a reel for 2x");
        if (setting == Settings.HOLD_REEL_RIGHT_EDGE) return L10n.t("Only on the right edge");
        if (setting == Settings.DOWNLOAD_REELS) return L10n.t("Download button on reels");
        if (setting == Settings.TAP_TO_PLAY) return L10n.t("Tap to play");
        if (setting == Settings.TAP_TO_PLAY_REELS_AFTER_FIRST) return L10n.t("Only the first reel waits");
        if (setting == Settings.RESUME_LONG_VIDEOS) return L10n.t("Resume long videos");
        if (setting == Settings.DEFAULT_PLAYBACK_QUALITY) return L10n.t("Default playback quality");
        if (setting == Settings.PICTURE_IN_PICTURE) return L10n.t("Picture-in-picture");
        if (setting == Settings.TURN_OFF_HDR_BRIGHTNESS) return L10n.t("Turn off HDR brightness");
        if (setting == Settings.KEEP_PROGRESS_BAR) return L10n.t("Keep the progress bar");
        if (setting == Settings.DOWNLOAD_VIDEOS) return L10n.t("Download feed and Watch videos");
        if (setting == Settings.CLIPBOARD_DOWNLOAD) return L10n.t("Offer to download copied links");
        if (setting == Settings.DOWNLOAD_PHOTOS) return L10n.t("Save any photo");
        if (setting == Settings.POST_MENU_PHOTO_SAVE) return L10n.t("Save photo in post menus");
        if (setting == Settings.DOWNLOAD_COMPATIBLE) return L10n.t("Save videos other apps can open");
        if (setting == Settings.HIDE_GET_MESSENGER_CARD) return L10n.t("Hide the Get Messenger card");
        if (setting == Settings.HIDE_CHAT_NOTES_TRAY) return L10n.t("Hide the notes and active now row");
        if (setting == Settings.HIDE_CHAT_PROMOTIONS) return L10n.t("Hide chat list promotions");
        if (setting == Settings.OPEN_MESSENGER_APP) return L10n.t("Open the Messenger app");
        if (setting == Settings.SAVED_SHORTCUT) return L10n.t("Saved shortcut");
        if (setting == Settings.APP_LOCK) return L10n.t("Lock Facebook");
        if (setting == Settings.HIDE_MENU_UPGRADES) return L10n.t("Hide Upgrades");
        if (setting == Settings.HIDE_MENU_ALSO_FROM_META) return L10n.t("Hide Also from Meta");
        if (setting == Settings.HIDE_EDITS_UPSELLS) return L10n.t("Hide Edits promotions");
        if (setting == Settings.HIDE_THREADS_CROSS_POSTING) return L10n.t("Hide Threads cross-posting prompts");
        if (setting == Settings.HIDE_THREADS_SHARE_BUTTON) return L10n.t("Hide Threads in the share sheet");
        if (setting == Settings.HIDE_META_VERIFIED_UPSELLS) return L10n.t("Hide Meta Verified offers");
        if (setting == Settings.HIDE_AVATAR_UPSELLS) return L10n.t("Hide avatar sticker promotions");
        if (setting == Settings.HIDE_META_AI_IMAGINE) return L10n.t("Hide Meta AI's Imagine");
        if (setting == Settings.HIDE_META_AI_POST_BUTTONS) return L10n.t("Hide other Meta AI buttons under posts");
        if (setting == Settings.HIDE_META_AI_IN_SEARCH) return L10n.t("Hide Meta AI in search");
        if (setting == Settings.HIDE_SPONSORED_SEARCH_RESULTS) return L10n.t("Hide sponsored search results");
        if (setting == Settings.HIDE_SPONSORED_MARKETPLACE_LISTINGS) return L10n.t("Hide sponsored Marketplace listings");
        if (setting == Settings.SHOW_SELLER_VIEW_PROFILE) return L10n.t("Show View profile on Marketplace sellers");
        if (setting == Settings.BLOCK_GAME_ADS) return L10n.t("Block Instant Games ads");
        if (setting == Settings.ANSWER_REWARDED_GAME_ADS) return L10n.t("Answer rewarded game ads as watched");
        if (setting == Settings.BLOCK_TRENDING_VIDEO_NOTIFICATIONS) return L10n.t("Block trending video notifications");
        if (setting == Settings.BLOCK_MEMORY_NOTIFICATIONS) return L10n.t("Block memory notifications");
        if (setting == Settings.BLOCK_BIRTHDAY_NOTIFICATIONS) return L10n.t("Block birthday notifications");
        if (setting == Settings.BLOCK_HIGHLIGHT_NOTIFICATIONS) return L10n.t("Block group and Page highlights");
        if (setting == Settings.BLOCK_PEOPLE_YOU_MAY_KNOW_NOTIFICATIONS) return L10n.t("Block \"People you may know\"");
        if (setting == Settings.BLOCK_NEARBY_NOTIFICATIONS) return L10n.t("Block nearby and weather notifications");
        if (setting == Settings.BLOCK_ACCOUNT_SETUP_NOTIFICATIONS) return L10n.t("Block account setup reminders");
        if (setting == Settings.BLOCK_GROUP_ACTIVITY_NOTIFICATIONS) return L10n.t("Block group activity notifications");
        if (setting == Settings.BLOCK_EVENT_NOTIFICATIONS) return L10n.t("Block event invites");
        if (setting == Settings.BLOCK_LIVE_VIDEO_NOTIFICATIONS) return L10n.t("Block live video notifications");
        if (setting == Settings.BLOCK_REACTION_NOTIFICATIONS) return L10n.t("Block reaction notifications");
        if (setting == Settings.NOTIFICATION_QUIET_HOURS) return L10n.t("Quiet hours");
        if (setting == Settings.OPEN_LINKS_EXTERNALLY) return L10n.t("Open links in your browser");
        if (setting == Settings.SANITIZE_SHARING_LINKS) return L10n.t("Remove tracking from shared links");
        if (setting == Settings.STOP_UPDATE_PROMPTS) return L10n.t("Stop update prompts");
        if (setting == Settings.CHECK_FOR_RELEASES) return L10n.t("Check for new Hushfacebook releases");
        if (setting == Settings.USE_SYSTEM_FONT) return L10n.t("Use the system font");
        if (setting == Settings.USE_SYSTEM_EMOJI) return L10n.t("Use the phone's emoji");
        if (setting == Settings.BOTTOM_TAB_BAR) return L10n.t("Tab bar at the bottom");
        if (setting == Settings.TAB_BAR_SCROLL_AWAY) return L10n.t("Hide the tab bar while scrolling");
        if (setting == Settings.FORCE_DARK_MODE) return L10n.t("Force dark mode");
        throw new IllegalArgumentException("No individual switch label: " + setting.key);
    }
}
