// Generated by tools/gen/build-ioscore.mjs from blockblast-re/app/src/core -- do not edit.
var IOSCore = (function (__setTimeout, __setInterval) {
// The Android game's setTimeout never fires when the delay is left out (browsers and Node use 0), and the
// core's asset stubs answer with setTimeout(cb): give every timer here an explicit delay.
var setTimeout = function (f, ms) { return __setTimeout.apply(null, [f, +ms || 0].concat(Array.prototype.slice.call(arguments, 2))); };
var setInterval = function (f, ms) { return __setInterval.apply(null, [f, +ms || 0].concat(Array.prototype.slice.call(arguments, 2))); };
var __runtime = (function () {
// Environment-agnostic runtime for the iOS Block Blast game code (decrypted Cocos Creator 2.x bundles).
// The original plugin scripts and bundles run in an isolated global (Node vm context or a hidden iframe)
// with the rendering engine stubbed; the game's own logic -- strategy pipeline, traits, placement, clears,
// combo, score, persistence -- runs as shipped. An `env` adapter supplies script evaluation and assets:
//   env.global            the isolated global object (window of the game)
//   env.evaluate(src, n)  run a script in that global
//   env.script(n)         source text of a plugin/bundle script (n: "plugin:<path>" | "bundle:<name>")
//   env.hasBundle(n)      whether a Cocos bundle exists offline (remote bundles do not)
//   env.asset(b, p, t)    { json } | { text } for a JsonAsset/TextAsset at bundle path, else null
//   env.storage           a Storage-like object (window.localStorage in the browser)

// ---------------------------------------------------------------- stubs
function stubPrototype(name) {
  return new Proxy({}, {
    get(t, k) { if (k in t || typeof k === "symbol" || k === "then") return t[k]; return stub(name + "#" + String(k)); },
    set(t, k, v, recv) { Object.defineProperty(recv, k, { value: v, writable: true, configurable: true, enumerable: true }); return true; },
  });
}
const stubs = new WeakSet();
const isStub = (x) => stubs.has(x);
// Hook for node.getComponent(RealGameClass): installAutoMount points this at its mounter.
const componentResolver = { resolve: null };
const COMPONENT_GETTERS = new Set(["getComponent", "addComponent", "getComponentInChildren"]);
// Every property read, call or `new` yields another stub; assignments stick. As a base class
// (`cc.Component` ...) the compiled `Base.apply(this, args) || this` gets `this` back and instances inherit
// stub members from a stub-backed prototype.
function stub(name = "stub") {
  const fn = function () {};
  fn.prototype = stubPrototype(name);
  const p = new Proxy(fn, {
    get(t, k) {
      if (k === Symbol.toPrimitive) return () => 0;
      if (COMPONENT_GETTERS.has(k) && !(k in t)) {
        t[k] = (C) => (typeof C === "function" && !stubs.has(C) && componentResolver.resolve ? componentResolver.resolve(C) : stub(`${name}.${k}()`));
      }
      if (k === Symbol.iterator || k === "then") return undefined;
      if (k === "prototype") return t.prototype;
      if (k === "toString" || k === "valueOf") return () => name;
      if (!(k in t)) t[k] = stub(name + "." + String(k));
      return t[k];
    },
    set(t, k, v) { Object.defineProperty(t, k, { value: v, writable: true, configurable: true, enumerable: true }); return true; },
    apply(t, thisArg) { return thisArg && typeof thisArg === "object" ? thisArg : stub(name + "()"); },
    construct() { return stub("new " + name); },
  });
  stubs.add(p);
  return p;
}

// ---------------------------------------------------------------- timing
// cc.tween: game flow waits on tween completion (`.call(fn)` after `.delay/.to`), so actions run on real
// timers: `.to/.by` apply their end values when their duration elapses, `.call` fires at its point in the
// sequence, `.delay` waits. Visual easing is irrelevant here.
function makeTween(target) {
  const steps = [];
  let timers = [];
  const tw = {
    // opts.progress (cc.tween's per-frame interpolator) is called every frame of the step, as the engine does --
    // the result screens' count-up plays its tick sound from it
    to(d, props, opts) {
      const step = { d: +d || 0, apply: () => props && target && Object.assign(target, props) };
      if (opts && typeof opts.progress === "function" && props && target) {
        step.begin = () => {
          const from = {};
          for (const k in props) if (typeof props[k] === "number") from[k] = +target[k] || 0;
          const t0 = Date.now(), ms = step.d * 1000;
          const tick = () => {
            const r = ms ? Math.min(1, (Date.now() - t0) / ms) : 1;
            for (const k in from) { try { target[k] = opts.progress(from[k], props[k], target[k], r); } catch { /* visual */ } }
            if (r < 1) timers.push(setTimeout(tick, 16));
          };
          tick();
        };
      }
      steps.push(step);
      return tw;
    },
    by(d, props) {
      steps.push({ d: +d || 0, apply: () => { if (props && target) for (const k in props) if (typeof props[k] === "number") target[k] = (+target[k] || 0) + props[k]; } });
      return tw;
    },
    set(props) { steps.push({ d: 0, apply: () => props && target && Object.assign(target, props) }); return tw; },
    delay(d) { steps.push({ d: +d || 0 }); return tw; },
    call(fn) { steps.push({ d: 0, apply: fn }); return tw; },
    hide() { return tw; }, show() { return tw; }, removeSelf() { return tw; }, easing() { return tw; }, union() { return tw; },
    target() { return tw; }, tag() { return tw; },
    then(other) { if (other && other.__steps) steps.push(...other.__steps); return tw; },
    sequence(...list) { for (const o of list) if (o && o.__steps) steps.push(...o.__steps); return tw; },
    parallel(...list) { // run as one step lasting the longest branch
      const d = Math.max(0, ...list.map((o) => (o && o.__steps ? o.__steps.reduce((s, x) => s + x.d, 0) : 0)));
      steps.push({ d, apply: () => list.forEach((o) => o && o.__steps && o.__steps.forEach((x) => x.apply && x.apply())) });
      return tw;
    },
    repeat(n, inner) { const src = inner && inner.__steps ? inner.__steps : steps.slice(); for (let i = 1; i < (n || 1); i++) steps.push(...src); return tw; },
    repeatForever() { steps.length = 0; return tw; }, // endless visual loops never complete a flow
    start() {
      let t = 0;
      for (const s of steps) {
        if (s.begin) timers.push(setTimeout(s.begin, t));
        t += s.d * 1000;
        if (s.apply) timers.push(setTimeout(() => { try { s.apply(); } catch { /* visual step */ } }, t));
      }
      return tw;
    },
    stop() { timers.forEach(clearTimeout); timers = []; return tw; },
    clone() { return tw; },
    get __steps() { return steps; },
  };
  // any other action (blink, bezierTo, rotateTo ...) is a visual step lasting its first numeric argument
  const proxy = new Proxy(tw, {
    get(t, k) {
      if (k in t) return t[k];
      if (typeof k === "symbol" || k === "then") return undefined;
      return (...args) => { const d = args.find((a) => typeof a === "number"); steps.push({ d: d || 0 }); return proxy; };
    },
  });
  for (const k of Object.keys(tw)) if (typeof tw[k] === "function") { const f = tw[k]; tw[k] = (...a) => { const r = f(...a); return r === tw ? proxy : r; }; }
  return proxy;
}

// cc.director: frame events (once/on AFTER_UPDATE ...) on a 60 fps loop, a real scheduler, and the global
// effect speed factor _kSpeed the game reads for its timings.
function makeDirector() {
  const d = stub("cc.director");
  const handlers = new Map(); // event -> [{fn, target, once}]
  let loop = null;
  const frame = () => {
    for (const [ev, list] of handlers) {
      handlers.set(ev, list.filter((h) => !h.once));
      for (const h of list) { try { h.fn.call(h.target); } catch { /* keep ticking */ } }
    }
  };
  const ensure = () => { if (!loop) loop = setInterval(frame, 16); };
  const scheduled = new Map();
  Object.assign(d, {
    _kSpeed: 1,
    once(ev, fn, target) { ensure(); (handlers.get(ev) || handlers.set(ev, []).get(ev)).push({ fn, target, once: true }); },
    on(ev, fn, target) { ensure(); (handlers.get(ev) || handlers.set(ev, []).get(ev)).push({ fn, target, once: false }); },
    off(ev, fn, target) { const l = handlers.get(ev); if (l) handlers.set(ev, l.filter((h) => h.fn !== fn || (target && h.target !== target))); },
    emit() {}, getDeltaTime: () => 1 / 60, calculateDeltaTime() {}, getTotalFrames: () => 0,
    getScheduler: () => ({
      schedule(fn, target, interval = 0, repeat = Infinity, delay = 0) {
        let n = 0; const tick = () => { fn.call(target, interval); if (++n <= repeat) scheduled.set(fn, setTimeout(tick, Math.max(16, interval * 1000))); };
        scheduled.set(fn, setTimeout(tick, delay * 1000));
      },
      scheduleOnce(fn, target, delay = 0) { scheduled.set(fn, setTimeout(() => fn.call(target), delay * 1000)); },
      scheduleUpdate() {}, unscheduleUpdate() {},
      unschedule(fn) { clearTimeout(scheduled.get(fn)); scheduled.delete(fn); },
      unscheduleAllForTarget() {}, isScheduled: (fn) => scheduled.has(fn), pauseTarget() {}, resumeTarget() {}, enableForTarget() {},
    }),
  });
  return d;
}

// cc.Vec2 / cc.Vec3: real value types (the game keeps data in them -- BlocksProducerTouch records each placed
// cell as new cc.Vec2(row, col) and traits compare them), with the Cocos 2.4 math API; members this does not
// implement still resolve to stubs through the prototype chain.
function makeVec(name, keys) {
  const V = class {
    constructor(...a) {
      const src = a[0] !== null && typeof a[0] === "object" ? a[0] : null;
      keys.forEach((k, i) => { this[k] = src ? +src[k] || 0 : a[i] === undefined ? 0 : a[i]; });
    }
  };
  Object.setPrototypeOf(V.prototype, stubPrototype(name));
  const map = (f) => function (v, out) { out = out || new V(); keys.forEach((k) => { out[k] = f(this[k], typeof v === "number" ? v : v ? v[k] : 0); }); return out; };
  const self = (f) => function (v) { keys.forEach((k) => { this[k] = f(this[k], typeof v === "number" ? v : v ? v[k] : 0); }); return this; };
  const add = (a, b) => a + b, sub = (a, b) => a - b, mul = (a, b) => a * b, div = (a, b) => a / b;
  Object.assign(V.prototype, {
    clone() { return new V(this); },
    set(v) { keys.forEach((k) => { this[k] = v[k]; }); return this; },
    equals(v) { return !!v && keys.every((k) => this[k] === v[k]); },
    strictEquals(v) { return v instanceof V && this.equals(v); },
    fuzzyEquals(v, e) { return !!v && keys.every((k) => Math.abs(this[k] - v[k]) <= e); },
    add: map(add), sub: map(sub), mul: map(mul), div: map(div), scale: map(mul),
    addSelf: self(add), subSelf: self(sub), mulSelf: self(mul), divSelf: self(div), scaleSelf: self(mul),
    neg(out) { out = out || new V(); keys.forEach((k) => { out[k] = -this[k]; }); return out; },
    negSelf() { keys.forEach((k) => { this[k] = -this[k]; }); return this; },
    dot(v) { return keys.reduce((t, k) => t + this[k] * v[k], 0); },
    cross(v) { return this.x * v.y - this.y * v.x; },
    magSqr() { return this.dot(this); }, lengthSqr() { return this.dot(this); },
    mag() { return Math.sqrt(this.dot(this)); }, len() { return Math.sqrt(this.dot(this)); },
    normalize(out) { out = out || new V(); const l = this.mag() || 1; keys.forEach((k) => { out[k] = this[k] / l; }); return out; },
    normalizeSelf() { return this.normalize(this); },
    lerp(to, r, out) { out = out || new V(); keys.forEach((k) => { out[k] = this[k] + (to[k] - this[k]) * r; }); return out; },
    angle(v) { const d = Math.sqrt(this.magSqr() * v.magSqr()); return d ? Math.acos(Math.max(-1, Math.min(1, this.dot(v) / d))) : 0; },
    signAngle(v) { return Math.atan2(this.cross(v), this.dot(v)); },
    rotate(r, out) { out = out || new V(); const c = Math.cos(r), s = Math.sin(r), x = this.x; out.x = c * x - s * this.y; out.y = s * x + c * this.y; return out; },
    rotateSelf(r) { return this.rotate(r, this); },
    toString() { return `(${keys.map((k) => this[k].toFixed(2)).join(", ")})`; },
  });
  const frozen = (...a) => Object.freeze(new V(...a));
  Object.assign(V, { ZERO: frozen(), ONE: frozen(...keys.map(() => 1)), distance: (a, b) => a.sub(b).mag() });
  if (keys.length === 2) Object.assign(V, { UP: frozen(0, 1), RIGHT: frozen(1, 0), NEG_ONE: frozen(-1, -1) });
  return V;
}

// Component base class: scheduling runs on real timers; everything else is stubbed. unschedule(fn) cancels a
// pending scheduleOnce(fn) as the engine's does (repeating schedules are not tracked). The pending timers are kept
// outside the instance: a field the instance does not own reads as a stub from its stub-backed prototype.
const pendingOnce = new WeakMap(); // component -> Map(fn -> timer)
function componentBase(name) {
  const C = stub(name);
  Object.assign(C.prototype, {
    scheduleOnce(fn, delay = 0) {
      if (!pendingOnce.has(this)) pendingOnce.set(this, new Map());
      const pending = pendingOnce.get(this);
      const id = setTimeout(() => { if (pending.get(fn) === id) pending.delete(fn); fn.call(this, delay); }, delay * 1000);
      (this.__timers ||= []).push(id);
      pending.set(fn, id);
    },
    schedule(fn, interval = 0, repeat = Infinity, delay = 0) {
      let n = 0;
      const tick = () => { fn.call(this, interval); if (++n <= repeat) (this.__timers ||= []).push(setTimeout(tick, Math.max(16, interval * 1000))); };
      (this.__timers ||= []).push(setTimeout(tick, delay * 1000));
    },
    unschedule(fn) {
      const pending = pendingOnce.get(this);
      if (!pending || !pending.has(fn)) return;
      clearTimeout(pending.get(fn));
      pending.delete(fn);
    },
    unscheduleAllCallbacks() {
      const timers = this.__timers || [], pending = pendingOnce.get(this);
      timers.forEach(clearTimeout);
      if (pending && Array.isArray(timers)) for (const [fn, id] of pending) if (timers.includes(id)) pending.delete(fn);
      this.__timers = [];
    },
  });
  return C;
}

// Whether `component.scheduleOnce(fn)` is still waiting to run.
function isScheduledOnce(component, fn) { const pending = pendingOnce.get(component); return !!pending && pending.has(fn); }

// ---------------------------------------------------------------- globals
const APP_VERSION = "7.4.3"; // CFBundleShortVersionString of the analysed IPA

function installGlobals(env, { installTime, country = "IL" }) {
  const g = env.global;
  const cc = stub("cc");
  cc._RF = { push() {}, pop() {} };
  const classDeco = (a) => (typeof a === "function" ? a : (c) => c);
  const propDeco = (...a) => (a.length >= 2 && typeof a[1] === "string" ? undefined : () => undefined);
  cc._decorator = { ccclass: classDeco, property: propDeco, executeInEditMode: classDeco, requireComponent: () => (c) => c, menu: () => (c) => c,
    disallowMultiple: classDeco, playOnFocus: classDeco, inspector: () => (c) => c, executionOrder: () => (c) => c, help: () => (c) => c, mixins: () => (c) => c };
  cc.tween = (target) => makeTween(target);
  cc.Vec2 = makeVec("cc.Vec2", ["x", "y"]);
  cc.v2 = (x, y) => new cc.Vec2(x, y);
  cc.Vec3 = makeVec("cc.Vec3", ["x", "y", "z"]);
  cc.v3 = (x, y, z) => new cc.Vec3(x, y, z);
  cc.isValid = (o) => o !== null && o !== undefined && !(typeof o === "object" && o._destroyed === true);
  // cc.audioEngine: every clip the game plays is reported to env.onSound({bundle, path, loop, volume, music})
  // -- clips are asset stubs named "asset:<bundle>:<path>" by installAssets.
  let audioId = 0;
  const clipOf = (clip) => { const m = (clip && typeof clip.toString === "function" ? clip.toString() : "").match(/^asset:([^:]+):(.+)$/); return m ? { bundle: m[1], path: m[2] } : null; };
  const report = (clip, extra) => { const c = clipOf(clip); if (c && env.onSound) env.onSound({ ...c, ...extra }); return ++audioId; };
  cc.audioEngine = Object.assign(stub("cc.audioEngine"), {
    play: (clip, loop = false, volume = 1) => report(clip, { loop, volume, music: false }),
    playEffect: (clip, loop = false) => report(clip, { loop, volume: 1, music: false }),
    playMusic: (clip, loop = true) => report(clip, { loop, volume: 1, music: true }),
    stopMusic: () => env.onSound && env.onSound({ stopMusic: true }),
    stopAllEffects() {}, stopAll() {}, stop() {}, pauseMusic() {}, resumeMusic() {}, pauseAll() {}, resumeAll() {},
    isMusicPlaying: () => false, setEffectsVolume() {}, setMusicVolume() {}, getEffectsVolume: () => 1, getMusicVolume: () => 1,
    getState: () => 0, setFinishCallback() {}, getDuration: () => 1, uncache() {}, uncacheAll() {},
  });
  cc.Tween = Object.assign(stub("cc.Tween"), { stopAllByTarget() {}, stopAllByTag() {} });
  cc.Component = componentBase("cc.Component");
  const compScheduler = { _onEnabled() {} };
  cc.director = makeDirector();
  cc.director._compScheduler = compScheduler;
  cc.Director = Object.assign(stub("cc.Director"), { EVENT_AFTER_UPDATE: "director_after_update", EVENT_BEFORE_UPDATE: "director_before_update",
    EVENT_AFTER_DRAW: "director_after_draw", EVENT_AFTER_SCENE_LAUNCH: "director_after_scene_launch", EVENT_BEFORE_SCENE_LOADING: "director_before_scene_loading" });
  cc.Component.EventHandler = stub("cc.Component.EventHandler");
  // cc.sys as on the iPhone build (cocos2d-jsb): native, iOS
  cc.sys = Object.assign(stub("cc.sys"), {
    isNative: true, isBrowser: false, isMobile: true, os: "iOS", OS_IOS: "iOS", OS_ANDROID: "Android", OS_OSX: "OS X", OS_WINDOWS: "Windows",
    platform: 1, IPHONE: 1, IPAD: 2, ANDROID: 3, WECHAT_GAME: 104, EDITOR_PAGE: 100, EDITOR_CORE: 101, MOBILE_BROWSER: 101, DESKTOP_BROWSER: 102,
    language: "en", languageCode: "en", LANGUAGE_ENGLISH: "en", LANGUAGE_CHINESE: "zh", osVersion: "17.0", osMainVersion: 17,
    now: () => Date.now(), getNetworkType: () => 0, NetworkType: { NONE: 0, LAN: 1, WWAN: 2 }, localStorage: env.storage,
  });
  const quiet = () => {};
  Object.assign(g, {
    cc, dragonBones: stub("dragonBones"), sp: stub("sp"), jsb: stub("jsb"),
    console: { log: quiet, warn: quiet, error: quiet, info: quiet, debug: quiet, trace: quiet, time: quiet, timeEnd: quiet, group: quiet, groupEnd: quiet },
  });
  if (!g.localStorage) g.localStorage = env.storage;
  if (!g.document) g.document = stub("document");
  if (!g.navigator) g.navigator = { userAgent: "iPhone", language: "en-US", platform: "iPhone" };
  // The game runs offline: no request of any kind leaves the realm (analytics, ads, trait server ...).
  g.XMLHttpRequest = stub("XMLHttpRequest");
  g.WebSocket = stub("WebSocket");
  g.EventSource = stub("EventSource");
  g.Image = stub("Image");
  g.fetch = () => Promise.reject(new Error("offline"));
  try { Object.defineProperty(g.navigator, "sendBeacon", { value: () => false, configurable: true }); } catch { /* not a browser */ }
  try { Object.defineProperty(g.navigator, "onLine", { value: false, configurable: true }); } catch { /* not a browser */ }
  // jsb.reflection.callStaticMethod(cls, method, ...) answers, as the iOS native side would give them
  const native = {
    getAppVersion: APP_VERSION,
    getClientInfo: () => JSON.stringify({ distinct_id: "local", install_time: installTime, device_model: "iPad", manufacturer: "Apple",
      country, os_version: "17.0", local_language: "en", network: "wifi", all_memory: 4096 }),
    // NativeAd.callNativeAd: there is no ad SDK, so the native side reports at once that no ad was shown
    // (window.adCallback({result: 0}) -> Advertisement_Native_Proxy: failed), as iOS does when no ad fills.
    // Without an answer the game-over interstitial (ClassAdvertisement_FullScreenProxy) never hands over to
    // the result screen and the board sits under "No Space Left" forever. Only full-screen ads (interstitial
    // 4xx, rewarded 5xx, 7xx; AdvertisementConfig.AD_TYPE) finish through adCallback -- a banner (type "3")
    // never does, and answering it would replay a stale callback.
    "callNativeAd:info": (_, info) => {
      let type = 0;
      try { type = Number(JSON.parse(info).type); } catch { /* malformed */ }
      if (type >= 100) setTimeout(() => { try { if (g.adCallback) g.adCallback({ result: "0" }); } catch { /* not registered */ } }, 0);
    },
  };
  g.jsb.reflection = { callStaticMethod(cls, method, ...args) { const v = native[String(method).replace(/:$/, "")]; return typeof v === "function" ? v(...args) : v; } };
  return cc;
}

// ---------------------------------------------------------------- assets
// cc.assetManager / cc.resources: JSON and text assets come from env.asset; everything else (sprites,
// prefabs, audio, skeletons) is an inert stub -- game logic never inspects their contents.
function installAssets(env, cc, onBundle) {
  const isType = (t, name) => t && t === cc[name];
  const makeBundle = (name) => {
    const cache = new Map();
    const one = (p, type) => {
      const key = `${p}|${isType(type, "JsonAsset") ? "json" : isType(type, "TextAsset") ? "text" : "other"}`;
      if (cache.has(key)) return cache.get(key);
      const a = env.asset(name, p);
      let asset;
      if (a && "json" in a) asset = { _name: p, name: p, json: a.json, addRef() { return this; }, decRef() {} };
      else if (a && "text" in a) asset = { _name: p, name: p, text: a.text, addRef() { return this; }, decRef() {} };
      else asset = stub(`asset:${name}:${p}`);
      cache.set(key, asset);
      return asset;
    };
    const lastFn = (args) => [...args].reverse().find((x) => typeof x === "function");
    return {
      name,
      load(paths, type, ...rest) { const cb = lastFn(rest); const res = Array.isArray(paths) ? paths.map((p) => one(p, type)) : one(paths, type); setTimeout(() => cb && cb(null, res)); },
      loadDir(dir, type, ...rest) { const cb = lastFn(rest); setTimeout(() => cb && cb(null, [])); },
      preload(...a) { const cb = lastFn(a); setTimeout(() => cb && cb(null, [])); },
      preloadDir(...a) { const cb = lastFn(a); setTimeout(() => cb && cb(null, [])); },
      get(p, type) { return cache.get(`${p}|${isType(type, "JsonAsset") ? "json" : isType(type, "TextAsset") ? "text" : "other"}`) || null; },
      getInfoWithPath() { return null; }, getDirWithPath() { return []; },
      release() {}, releaseAll() {}, releaseUnusedAssets() {}, loadScene(n, cb) { setTimeout(() => cb && cb(null, stub("scene"))); },
    };
  };
  const bundles = new Map();
  const getBundle = (n) => {
    if (!bundles.has(n) && env.hasBundle(n)) bundles.set(n, makeBundle(n));
    return bundles.get(n) || null;
  };
  cc.resources = getBundle("resources");
  cc.assetManager = Object.assign(stub("cc.assetManager"), {
    bundles: { get: (n) => getBundle(n) }, getBundle,
    loadBundle(n, opts, cb) {
      if (typeof opts === "function") cb = opts;
      // a remote bundle is asked for by URL (ResLoader.loadBundle: <remoteResServerUrl>/remote/[ios/prod/]<name>);
      // the ones tools/fetch_remote.py downloaded are staged like the IPA's own
      const name = /\/remote\//.test(String(n)) ? String(n).split("/").pop() : n;
      const b = getBundle(name);
      if (b) onBundle(name); // run the bundle's scripts, which register its classes
      setTimeout(() => cb && cb(b ? null : new Error(`bundle not available offline: ${n}`), b));
    },
    loadRemote(url, opts, cb) { if (typeof opts === "function") cb = opts; setTimeout(() => cb && cb(new Error("offline"), null)); },
    downloader: { bundleVers: {}, maxConcurrency: 4, maxRequestsPerFrame: 4 },
    releaseAsset() {}, releaseUnusedAssets() {}, utils: { getUrlWithUuid: () => "" },
  });
}

// ---------------------------------------------------------------- boot
// settings.js jsList order (the plugins with game logic), then the core bundles.
const PLUGINS = ["assets/libs/algorithmStrategy.379d1.js", "assets/libs/gameBase.2dec5.js", "assets/libs/rulesEngine.e0e00.js",
  "assets/scripts/G_Cfg.57769.js", "assets/scripts/modules/atomengine4/lib/atomengine.30aa9.js"];
const CORE_BUNDLES = ["main", "class", "mainTraits"];

const wait = (ms) => new Promise((r) => setTimeout(r, ms));

async function bootGame(env, { installTime = Date.now(), country } = {}) {
  const cc = installGlobals(env, { installTime, country });
  const loaded = new Set();
  const run = async (n) => env.evaluate(await env.script(n), n);
  const failures = [];
  installAssets(env, cc, (n) => {
    if (loaded.has(n)) return;
    loaded.add(n);
    // trait bundles register synchronously during loadBundle in the engine; env.scriptSync mirrors that
    try { env.evaluate(env.scriptSync(`bundle:${n}`), `bundle:${n}`); } catch (e) { failures.push(`${n}: ${e}`); }
  });
  for (const p of PLUGINS) await run(`plugin:${p}`);
  for (const b of CORE_BUNDLES) { loaded.add(b); await run(`bundle:${b}`); }
  const g = env.global, req = g.__require;
  req("Scene").scene._persist = stub("persistNode");
  // Offline the hot update fails and TraitServer_Response_Proxy.onUpdateFinish waits 2 s before reading the
  // (absent) server response and falling back to the bundled trait plan. Same path, without the idle wait.
  const TSR = req("TraitServer_Response_Proxy").TraitServer_Response_Proxy.prototype, onUpdateFinish = TSR.onUpdateFinish;
  TSR.onUpdateFinish = function (...a) {
    const st = g.setTimeout;
    g.setTimeout = (f, ms, ...r) => st(f, ms === 2000 ? 0 : ms, ...r);
    try { return onUpdateFinish.apply(this, a); } finally { g.setTimeout = st; }
  };
  const main = new (req("Main").default)();
  await main.onLoad();
  await main.launchStart();
  // the trait-server module resolves the offline case itself (bundled fallback plan)
  const tci = req("TraitConfigInfo").traitConfigInfo;
  for (let i = 0; i < 600 && !tci.ready; i++) await wait(50);
  if (!tci.ready) throw new Error("trait config never became ready");
  return { g, req, cc, loaded, failures };
}

// Component mounting: the game reaches its live components through Cinst(Class). On a cache miss the real
// component class is constructed, its null @property UI references get stub nodes, it is registered in
// CacheComponents like cc.director._compScheduler._onEnabled would, and onLoad/onEnable/start run.
function installAutoMount(g, req, log = () => {}) {
  const { cacheComponents } = req("CacheComponents");
  const Cache = cacheComponents.constructor;
  const { ModuleManager } = req("ModuleManager");
  const mounted = new Map();
  const mount = (C) => {
    if (mounted.has(C)) return mounted.get(C);
    const inst = new C();
    mounted.set(C, inst);
    for (const k of Object.keys(inst)) if (inst[k] === null && !k.startsWith("_")) inst[k] = stub(`${C.name}.${k}`);
    if (!Object.prototype.hasOwnProperty.call(inst, "node")) inst.node = stub(`${C.name}.node`);
    let per = Cache._cacheAllComponents.get(C);
    if (!per) Cache._cacheAllComponents.set(C, (per = {}));
    per[ModuleManager.moduleType] = inst;
    for (const hook of ["onLoad", "onEnable", "start"]) {
      if (typeof inst[hook] !== "function") continue;
      try { const r = inst[hook](); if (r && typeof r.catch === "function") r.catch((e) => log(`${C.name}.${hook}: ${e}`)); }
      catch (e) { log(`${C.name}.${hook}: ${String(e).slice(0, 160)}`); }
    }
    return inst;
  };
  const Cinst = (C) => {
    const hit = Cache._cacheAllComponents.get(C);
    if (hit && (hit[ModuleManager.moduleType] || hit.common)) return hit[ModuleManager.moduleType] || hit.common;
    return typeof C === "function" && !isStub(C) ? mount(C) : undefined;
  };
  cacheComponents.Cinst = Cinst;
  cacheComponents.CinstAsync = (C) => Promise.resolve(Cinst(C));
  componentResolver.resolve = (C) => (isStub(C) ? undefined : Cinst(C));
  g.Cinst = Cinst;
  g.CinstAsync = cacheComponents.CinstAsync;
  return mounted;
}

return { bootGame, installAutoMount, isScheduledOnce };
})();
var bootGame = __runtime.bootGame, installAutoMount = __runtime.installAutoMount, isScheduledOnce = __runtime.isScheduledOnce;
// ClassicCore: Classic mode of the iOS game, driven through its own code (see runtime.js). The caller only
// decides where a piece is dropped -- exactly the part a finger does -- and observes the game's events.


const wait = (ms) => new Promise((r) => setTimeout(r, ms));
const EMPTY = () => Array.from({ length: 8 }, () => new Array(8).fill(-1));

// module names from the bundles' cc._RF.push markers -> readable event names
function eventNameMap(req, sources) {
  const map = new Map();
  for (const src of sources) for (const m of src.matchAll(/cc\._RF\.push\([^,]+, "[^"]*", "(E_[^"]+)"\)/g)) {
    try { for (const v of Object.values(req(m[1]))) if (typeof v === "function") map.set(v, m[1]); } catch { /* not standalone */ }
  }
  return map;
}

class ClassicCore {
  static async create(env, { installTime, country, onEvent, loginDays } = {}) {
    const c = new ClassicCore();
    const { g, req, failures } = await bootGame(env, { installTime, country });
    Object.assign(c, { g, req, failures, listeners: new Set(), issues: [], loginDays: loginDays == null ? null : Math.max(1, Math.floor(Number(loginDays) || 1)) });
    if (onEvent) c.listeners.add(onEvent);
    c.storage = req("Storage").storage;
    // a returning player: the three-step tutorial is done (classGuideStep > 2)
    if (c.storage.getItem("classGuideStep", 0) < 3) c.storage.setItem("classGuideStep", 3);
    c.storage.setItem("isFinishedGuide", true);
    c.names = eventNameMap(req, await Promise.all(["bundle:main", "bundle:class", "bundle:mainTraits"].map((n) => env.script(n))));
    c.mounted = installAutoMount(g, req, (m) => c.issues.push(m));
    const { EventManager } = req("EventManager");
    c.EventManager = EventManager;
    const dispatch = EventManager.dispatchModuleEvent.bind(EventManager);
    EventManager.dispatchModuleEvent = (e) => {
      const name = c.names.get(e && e.getClass && e.getClass()) || "?";
      if (name === "E_ClassWin_Show" || name === "E_ClassFail_Show") {
        const info = req("ClassGameOverGameInfo").classGameOverGameInfo;
        c.result = { screen: name === "E_ClassWin_Show" ? "ClassWin" : "ClassFail", score: info._score, best: info._highScore };
      }
      const r = dispatch(e);
      c.emit(name, e && (e.state !== undefined ? e.state : e.option !== undefined ? e.option : e));
      return r;
    };
    c.installHooks();
    await c.enterClassic();
    return c;
  }

  emit(name, state) { for (const l of this.listeners) { try { l(name, state); } catch { /* UI errors never reach the game */ } } }

  // UI decisions the game makes through its (unrendered) prefabs, surfaced as events:
  //   "UI.show" {name}                 prefab the game opens (ComboBase, NoSpace, ClassWin, ClassFail ...)
  //   "ComboBase.setState" {count}     the combo badge and its count
  installHooks() {
    const UI = this.req("UI").UI, show = UI.show, self = this;
    UI.show = function (cfg, ...a) { self.emit("UI.show", { name: cfg && (cfg.name || cfg.url) }); return show.call(this, cfg, ...a); };
    const CB = this.req("ComboBase").default.prototype, setState = CB.setState;
    CB.setState = function (st) { self.emit("ComboBase.setState", st); return setState.call(this, st); };
    // "Splash" {grid, time, type}: BoardSplashAnimation (game-start intro, all-clear wave). grid[r][c] is the
    // colour each cell flashes, as setDefaultData picks it: own colour if occupied, else `color` or the pattern.
    const BSA = this.req("BoardSplashAnimation").default.prototype, bsaSet = BSA.setState;
    const pattern = this.req("BoardSplashAnimationConfig").boardSplashAnimationColorConfig;
    BSA.setState = function (st) {
      if (st && st.type != null) {
        const cfg = st.animationColorConfigs || pattern, b = self.board;
        const grid = b.map((row, r) => row.map((v, c) => (v === -1 || v === 10 ? (st.color > 0 ? st.color : cfg[r][c]) : v)));
        self.emit("Splash", { grid, time: st.time ?? 0.07, type: st.type });
      }
      return bsaSet.call(this, st);
    };
    // "Shake" {duration, step}: base/shake/Shake.start moves the camera through its 9-point path
    const shake = this.req("Shake").shake, shakeStart = shake.start;
    shake.start = function (duration, step = 0.03) { self.emit("Shake", { duration, step }); return shakeStart.call(this, duration, step); };
    // "Haptic" {style}: NativeVibrator.shakeOnceIOS (ContinueShakeTrait: one per cleared line, 200 ms apart)
    const NV = this.req("NativeVibrator").NativeVibrator, haptic = NV.shakeOnceIOS;
    NV.shakeOnceIOS = function (style) { self.emit("Haptic", { style }); return haptic.call(this, style); };
    // "Perfect": RightPutTrait -- all three pieces put where the dealing algorithm planned them
    const RP = this.req("RightPutTrait").RightPutTrait.prototype, perfect = RP.playPerfectEffect;
    RP.playPerfectEffect = function () { self.emit("Perfect", {}); return perfect.call(this); };
    // "NewBestScore" {highScore}: New_best_scoreTrait's NewBestScoreEffect at the score label
    const NB = this.req("NewBestScoreEffect").default.prototype, nbRender = NB.render;
    NB.render = function () { self.emit("NewBestScore", { highScore: this.state && this.state.highScore }); try { return nbRender.call(this); } catch { /* stub label */ } };
    // Game over: GameOver_Splash_Proxy waits getGameOverEventDelayTime (1600 ms) after the board fill before
    // E_GameOver_GameEnd opens the result screen; the player asked for it straight after the fill.
    const GOS = this.req("GameOver_Splash_Proxy").GameOver_Splash_Proxy.prototype;
    GOS.getGameOverEventDelayTime = () => 0;
    // Revive (ClassRevive_Proxy): at game over the game may offer a second chance that is paid for with a
    // rewarded ad. There are no ads here, so it is never offered: onReviveProcessing takes its own no-revive
    // branch (reviveFailPostProcessing + E_GameOver_GameEndPre) through the doNotReviveByTrait gate. Opening the
    // offer and closing it instead races Revive_Proxy's async UI.show: the view then opens anyway and its
    // countdown closes it a second time ~6 s later, which ran game over again on the cleared data (a second
    // result screen showing 0).
    this.req("ClassRevive_Proxy").ClassRevive_Proxy.prototype.doNotReviveByTrait = () => false;
    // ClassTopInfo, the score bar: the game rolls its own labels (updateScoreCurrentScoreWithAnimation: a
    // setInterval that walks the label to the new score in at most 0.2 s) and pops the score (playScoreAnim).
    //   "TopInfo.score" {value}  the current-score label now reads `value`
    //   "TopInfo.high" {value}   the best-score label now reads `value`
    //   "TopInfo.pulse"          playScoreAnim: scale 1.2 over 0.1 s and back over 0.1 s
    const TI = this.req("ClassTopInfo").default.prototype, setScore = TI.setScoreLabel, setHigh = TI.setHighScoreLabel, pulse = TI.playScoreAnim;
    TI.setScoreLabel = function (v) { self.emit("TopInfo.score", { value: Number(v) }); return setScore.call(this, v); };
    TI.setHighScoreLabel = function (v) { self.emit("TopInfo.high", { value: Number(v) }); return setHigh.call(this, v); };
    TI.playScoreAnim = function () { self.emit("TopInfo.pulse", {}); try { return pulse.call(this); } catch { /* stub nodes */ } };
    // "ComboTips" {comboLevel, comboAnimState}: the streak glow behind the score. Combo_tips_lv_blockTrait replaces
    // ClassTopInfo's heart with ComboTipsNew, whose render picks the animation (<blue|cyan|yellow>_in/_init/_out).
    const CT = this.req("ComboTipsNew").default.prototype, ctRender = CT.render;
    CT.render = function () { self.emit("ComboTips", { comboLevel: this.state && this.state.comboLevel, comboAnimState: this.state && this.state.comboAnimState }); try { return ctRender.call(this); } catch { /* stub armature */ } };
    // "Encourage" {anim}: the praise word starts. Encourage_Proxy.onEncourageEffectsPlay(play, true, delay) shows
    // the Encourage prefab after featureEffectsPlayDelayHook(delay || 16) ms, placed from node geometry (which the
    // headless engine does not have), and ClassEncourage_Proxy.onPlayLevelColor plays
    // EncouragePromptType[PROMPT<min(5, max(0, lines-2))>] + "_" + EncourageColorType[COLOR<color-1>].
    const EP = this.req("Encourage_Proxy").Encourage_Proxy.prototype, epPlay = EP.onEncourageEffectsPlay;
    const { EncourageType, EncouragePromptType, EncourageColorType } = this.req("EncourageType");
    EP.onEncourageEffectsPlay = function (e, show, delay) {
      const st = e && e.state;
      if (show && st && st.type === EncourageType.LEVEL_COLOR) {
        const n = Math.min(5, Math.max(0, st.eliminateCount - 2)), anim = `${EncouragePromptType[`PROMPT${n}`]}_${EncourageColorType[`COLOR${st.color - 1}`]}`;
        const ms = this.featureEffectsPlayDelayHook(delay || 16);
        setTimeout(() => self.emit("Encourage", { anim }), ms);
      }
      return epPlay.call(this, e, show, delay);
    };
    // "ScoreTip" {score, eliminateCount, combo, isClearScreen}: a ComboScoreTip "+N" is shown (ClassScoreTip_Proxy
    // sets its state 0.53 s after the drop, 1.5 s in a streak; the all-clear bonus is one at the board's centre)
    const CST = this.req("ComboScoreTip").default.prototype, cstRender = CST.render;
    CST.render = function () {
      const s = this.state || {};
      if (s.type !== "reset" && !Number.isNaN(Number(s.score))) self.emit("ScoreTip", { score: s.score, eliminateCount: s.eliminateCount, combo: s.combo, isClearScreen: !!s.isClearScreen });
      return cstRender.call(this);
    };
    // "TouchEffect" {pos}: TouchEffect_Proxy.play (throttled 50 ms) -> the gameclick ripple
    const TE = this.req("TouchEffect").TouchEffect.prototype, teSet = TE.setState;
    TE.setState = function (st) { self.emit("TouchEffect", st); return teSet.call(this, st); };
    // "BlockBonus" {color, score}: PlacementBlocksEliminateEffectTrait -- a placed piece cleared completely scores
    // `score` more per cell (added by the trait to classScore); each placed cell plays its light (Remote bundle
    // gameplay_block_light, animation by colour) and shows a ComboScoreIosTip with `score`, 0.16 s after the drop.
    const PB = this.req("PlacementBlocksEliminateEffectTrait").PlacementBlocksEliminateEffectTrait.prototype, pbAdd = PB.addBlocksEliminateEffect;
    PB.addBlocksEliminateEffect = function (cells, color, score, ...a) { self.emit("BlockBonus", { color, score }); return pbAdd.call(this, cells, color, score, ...a); };
    // Param230012Trait, the active score multiplier, scales every clear by a function of `days`: the distinct days
    // ScoreParam230012Info.recordLogin has counted (Param230012TraitData). The player sets that number in Settings
    // instead (setLoginDays): logins no longer add days, and the stored count always reads the chosen value.
    const P230012 = this.req("ScoreParam230012Info").param230012Info, recordLogin = P230012.recordLogin;
    P230012.recordLogin = function (...a) { const r = recordLogin.apply(this, a); self.applyLoginDays(); return r; };
    this.applyLoginDays();
  }

  // ClassGame's touch listener: every touch on the game screen dispatches E_TouchEffect_Point
  touchEffect(x, y) {
    this.EventManager.dispatchModuleEvent(new (this.req("E_TouchEffect_Point").E_TouchEffect_Point)({ _startPoint: { x, y } }));
  }

  on(fn) { this.listeners.add(fn); return () => this.listeners.delete(fn); }

  // The login-day count the score multiplier reads (see installHooks); null leaves the game's own counting.
  setLoginDays(days) {
    this.loginDays = Math.max(1, Math.floor(Number(days) || 1));
    this.applyLoginDays();
  }

  applyLoginDays() {
    if (this.loginDays == null) return;
    const info = this.req("ScoreParam230012Info").param230012Info, d = info.paramData;
    if (d.days !== this.loginDays || d.curDay !== this.loginDays) info.updateParamData({ ...d, days: this.loginDays, curDay: this.loginDays });
  }

  // What that multiplier makes of the day count: Param230012Trait's own strategy for its type, applied to a single
  // line at combo 1000 (base 10000, so the game's Math.ceil keeps four decimals). 1 when the trait is not active.
  get dayMultiplier() {
    const t = this.g.TRAIT("Param230012Trait"), fn = t && t.active && t.paramStrategies && t.paramStrategies[t.props.type];
    return fn ? fn(1000, 1, this.req("ScoreParam230012Info").param230012Info.paramData) / 10000 : 1;
  }

  // HomePage_Game_Proxy.onEnterClass + the ClassMain component, then the board intro finishing
  async enterClassic() {
    const { req, EventManager } = this;
    const { ModuleManager, ModuleType } = req("ModuleManager");
    ModuleManager.setCurrentModuleType(ModuleType.Class);
    EventManager.dispatchModuleEvent(new (req("E_Scene_Change").E_Scene_Change)(req("GameType").GameMode.Class));
    // an unfinished game is resumed as on iOS; only a new game gets the empty-board rule
    this.resumed = this.round > 0 && this.tray.some((id) => id >= 0);
    if (!this.resumed) { this.forceEmptyBoard(); this.restoreOriginalSkin(); }
    const cm = new (req("ClassMain").default)();
    cm.onLoad(); cm.onEnable();
    await wait(200);
    await this.boardIntroDone();
  }

  // A new game opens in the original look, as the live iOS game does (its remote-config skin-reset traits
  // are not in the offline build), through the game's own restore (IsOpenClassReviveRestoreDefaultSkinTrait).
  restoreOriginalSkin() {
    const si = this.req("SkinInfo").skinInfo;
    if (si.currentSkinId !== si.originSkinId) this.EventManager.dispatchModuleEvent(new (this.req("E_Skin_Update").E_Skin_Update)(si.originSkinId));
  }

  // User requirement: every game starts on an empty board (overrides any board seeding).
  forceEmptyBoard() {
    const b = this.storage.getItem("classFaceBlocks", null);
    if (b && b.some && b.some((row) => row.some((v) => v !== -1))) this.storage.setItem("classFaceBlocks", EMPTY());
  }

  // ClassBlocksProducer_BlocksProducerValidate_Proxy deals the first tray when the board splash ends. The splash that
  // opens a game (ClassBoardSplashAnimation_Proxy.onDefaultBoardReadyComplete: ClassGame's BoardSplashAnimation,
  // UP_DOWN) ends by its own completion 1.9 s after it starts; that completion runs now instead, and only once -- a
  // second splash end finds the tray full and recolours it at random (setRecordOperationColor, the resume path).
  async boardIntroDone() {
    const game = this.g.Cinst(this.req("ClassGame").default);
    const splash = game && game.boardSplashAnimation && game.boardSplashAnimation.getComponent(this.req("BoardSplashAnimation").default);
    const pending = () => (splash && isScheduledOnce(splash, splash._splashCompleteCb) ? splash._splashCompleteCb : null);
    let complete = pending();
    for (let t = 0; !complete && t < 2500; t += 20) { await wait(20); complete = pending(); }
    if (complete) {
      splash.unschedule(complete);
      complete.call(splash);
    } else {
      this.EventManager.dispatchModuleEvent(new (this.req("E_BoardSplashAnimation_End").E_BoardSplashAnimation_End)());
    }
    for (let t = 0; t < 900 && !this.tray.some((id) => id >= 0); t += 20) await wait(20); // the deal lands
    await wait(20);
  }

  // wait for the game's timers (touch-end delay, next-tray request) to run out
  async idle(ms = 900) { await wait(ms); }

  // The skin the game has on (SkinInfo): 1000 is the original art; all-clears can move it along a sequence.
  get skin() {
    const si = this.req("SkinInfo").skinInfo;
    return { id: String(si.currentSkinId), original: !!si.isOriginalSkin, info: si.currentSkinInfo };
  }

  get touch() { return this.g.Cinst(this.req("BlocksProducerTouch").default); }
  get tray() { return this.storage.getItem("classProducerBlocks", [-1, -1, -1]); }
  get colors() { return this.storage.getItem("classColorLists", []); }
  get board() { return this.storage.getItem("classFaceBlocks", null) || EMPTY(); }
  get score() { return this.storage.getItem("classScore", 0); }
  get best() { return this.storage.getItem("classHighScore", 0); }
  get round() { return this.storage.getItem("classRoundNum", 0); }

  shape(id) {
    const s = this.req("BinaryConfig").BlockShapeMap[id], cells = [];
    s.shape.forEach((row, r) => { for (let c = 0; c < s.width; c++) if (row & (1 << (s.width - 1 - c))) cells.push([r, c]); });
    return cells;
  }

  canPlace(idx, row, col) {
    const id = this.tray[idx], b = this.board;
    if (id == null || id < 0) return false;
    return this.shape(id).every(([dr, dc]) => { const r = row + dr, c = col + dc; return r >= 0 && r < 8 && c >= 0 && c < 8 && b[r][c] === -1; });
  }

  // Drop tray slot `idx` with its top-left cell at (row, col). Sets the snap state that onTouchMove
  // derives from the finger position, then the game's computeEliminate + onAfterTouchEnd take over.
  place(idx, row, col) {
    if (!this.canPlace(idx, row, col)) throw new Error(`cannot place slot ${idx} at ${row},${col}`);
    const t = this.touch, id = this.tray[idx], color = this.colors[idx];
    t._producerBlocks = this.tray.slice();
    t._faceBlocks = this.board;
    t._selectIndex = idx;
    t._selectItem = t._selectItem || new this.g.cc.Node();
    t._color = color;
    t._showShaders = {};
    for (const [dr, dc] of this.shape(id)) (t._showShaders[row + dr] ||= {})[col + dc] = color;
    t._canSnap = true;
    const se = t.computeEliminate();
    t._rowsEffect = se.rowsEffect; t._colsEffect = se.colsEffect; t._eliminateCols = se.cols; t._eliminateRows = se.rows;
    t._canEliminateShaders = t.mergeEliminateShaders(t.computeCanEliminateShaders("ROW", se.rows), t.computeCanEliminateShaders("COL", se.cols));
    t.onAfterTouchEnd({}, t._selectItem);
  }

  get gameOver() { return !this.tray.some((id, i) => id >= 0 && this.anyFit(i)); }
  anyFit(i) { for (let r = 0; r < 8; r++) for (let c = 0; c < 8; c++) if (this.canPlace(i, r, c)) return true; return false; }

  // After the last move the game runs its game-over sequence (splash, data clear, result screen).
  async waitResult(timeoutMs = 15000) {
    const t0 = Date.now();
    while (!this.result && Date.now() - t0 < timeoutMs) await wait(50);
    return this.result;
  }

  // The in-game settings panel's Replay button (Setup_Proxy.onClick_replay -> E_Game_Replay)
  async replay() {
    this.result = null;
    this.EventManager.dispatchModuleEvent(new (this.req("E_Game_Replay").E_Game_Replay)());
    await wait(100);
    this.forceEmptyBoard();
    this.restoreOriginalSkin();
    await this.boardIntroDone();
  }

  // The result screen's Play button (ClassWin or ClassFail .onClickPlay -> E_Game_Ready), then the board intro
  async restart() {
    const screen = (this.result && this.result.screen) || "ClassFail";
    this.result = null;
    this.g.Cinst(this.req(screen).default).onClickPlay();
    await wait(100);
    this.forceEmptyBoard();
    this.restoreOriginalSkin();
    await this.boardIntroDone();
  }
}

return { ClassicCore: ClassicCore };
})(setTimeout, setInterval);
