.class public final Lcom/p1/mobile/longlink/msg/liveroom/LongLinkLiveMessage;
.super Ljava/lang/Object;
.source "SourceFile"


# annotations
.annotation system Ldalvik/annotation/MemberClasses;
    value = {
        Lcom/p1/mobile/longlink/msg/liveroom/LongLinkLiveMessage$GiftWallRefresh;,
        Lcom/p1/mobile/longlink/msg/liveroom/LongLinkLiveMessage$GiftWallRefreshOrBuilder;,
        Lcom/p1/mobile/longlink/msg/liveroom/LongLinkLiveMessage$RefreshVoiceRoomLeaderboard;,
        Lcom/p1/mobile/longlink/msg/liveroom/LongLinkLiveMessage$RefreshVoiceRoomLeaderboardOrBuilder;,
        Lcom/p1/mobile/longlink/msg/liveroom/LongLinkLiveMessage$VoiceSettleGuideMessage;,
        Lcom/p1/mobile/longlink/msg/liveroom/LongLinkLiveMessage$VoiceSettleGuideMessageOrBuilder;,
        Lcom/p1/mobile/longlink/msg/liveroom/LongLinkLiveMessage$VoiceVirtualAvatarInitNoticeMessage;,
        Lcom/p1/mobile/longlink/msg/liveroom/LongLinkLiveMessage$VoiceVirtualAvatarInitNoticeMessageOrBuilder;,
        Lcom/p1/mobile/longlink/msg/liveroom/LongLinkLiveMessage$VoiceLiveEnterRoomEffectMessage;,
        Lcom/p1/mobile/longlink/msg/liveroom/LongLinkLiveMessage$VoiceLiveEnterRoomEffectMessageOrBuilder;,
        Lcom/p1/mobile/longlink/msg/liveroom/LongLinkLiveMessage$VoiceLiveHighQualityTagMessage;,
        Lcom/p1/mobile/longlink/msg/liveroom/LongLinkLiveMessage$VoiceLiveHighQualityTagMessageOrBuilder;,
        Lcom/p1/mobile/longlink/msg/liveroom/LongLinkLiveMessage$VoiceLiveTopEffectMessage;,
        Lcom/p1/mobile/longlink/msg/liveroom/LongLinkLiveMessage$VoiceLiveTopEffectMessageOrBuilder;,
        Lcom/p1/mobile/longlink/msg/liveroom/LongLinkLiveMessage$VoiceChatGroupApply;,
        Lcom/p1/mobile/longlink/msg/liveroom/LongLinkLiveMessage$VoiceChatGroupApplyOrBuilder;,
        Lcom/p1/mobile/longlink/msg/liveroom/LongLinkLiveMessage$VoiceChatGroupInviteCreate;,
        Lcom/p1/mobile/longlink/msg/liveroom/LongLinkLiveMessage$VoiceChatGroupInviteCreateOrBuilder;,
        Lcom/p1/mobile/longlink/msg/liveroom/LongLinkLiveMessage$VoiceRoomAnnouncementUpdate;,
        Lcom/p1/mobile/longlink/msg/liveroom/LongLinkLiveMessage$VoiceRoomAnnouncementUpdateOrBuilder;,
        Lcom/p1/mobile/longlink/msg/liveroom/LongLinkLiveMessage$AnnouncementAudit;,
        Lcom/p1/mobile/longlink/msg/liveroom/LongLinkLiveMessage$AnnouncementAuditOrBuilder;,
        Lcom/p1/mobile/longlink/msg/liveroom/LongLinkLiveMessage$VoiceMemberUpdate;,
        Lcom/p1/mobile/longlink/msg/liveroom/LongLinkLiveMessage$VoiceMemberUpdateOrBuilder;,
        Lcom/p1/mobile/longlink/msg/liveroom/LongLinkLiveMessage$SchemaJumpMessage;,
        Lcom/p1/mobile/longlink/msg/liveroom/LongLinkLiveMessage$SchemaJumpMessageOrBuilder;,
        Lcom/p1/mobile/longlink/msg/liveroom/LongLinkLiveMessage$PkExecuteInfo;,
        Lcom/p1/mobile/longlink/msg/liveroom/LongLinkLiveMessage$PkExecuteInfoOrBuilder;,
        Lcom/p1/mobile/longlink/msg/liveroom/LongLinkLiveMessage$PkExecuteConfig;,
        Lcom/p1/mobile/longlink/msg/liveroom/LongLinkLiveMessage$PkExecuteConfigOrBuilder;,
        Lcom/p1/mobile/longlink/msg/liveroom/LongLinkLiveMessage$VoiceAnswerOption;,
        Lcom/p1/mobile/longlink/msg/liveroom/LongLinkLiveMessage$VoiceAnswerOptionOrBuilder;,
        Lcom/p1/mobile/longlink/msg/liveroom/LongLinkLiveMessage$VoiceSongGameUserNotice;,
        Lcom/p1/mobile/longlink/msg/liveroom/LongLinkLiveMessage$VoiceSongGameUserNoticeOrBuilder;,
        Lcom/p1/mobile/longlink/msg/liveroom/LongLinkLiveMessage$VoiceSongGameStatusNotice;,
        Lcom/p1/mobile/longlink/msg/liveroom/LongLinkLiveMessage$VoiceSongGameStatusNoticeOrBuilder;,
        Lcom/p1/mobile/longlink/msg/liveroom/LongLinkLiveMessage$VoiceLiveGame;,
        Lcom/p1/mobile/longlink/msg/liveroom/LongLinkLiveMessage$VoiceLiveGameOrBuilder;,
        Lcom/p1/mobile/longlink/msg/liveroom/LongLinkLiveMessage$UserDailyTaskMessage;,
        Lcom/p1/mobile/longlink/msg/liveroom/LongLinkLiveMessage$UserDailyTaskMessageOrBuilder;,
        Lcom/p1/mobile/longlink/msg/liveroom/LongLinkLiveMessage$AnchorDailyTaskMessage;,
        Lcom/p1/mobile/longlink/msg/liveroom/LongLinkLiveMessage$AnchorDailyTaskMessageOrBuilder;,
        Lcom/p1/mobile/longlink/msg/liveroom/LongLinkLiveMessage$SchemePopup;,
        Lcom/p1/mobile/longlink/msg/liveroom/LongLinkLiveMessage$SchemePopupOrBuilder;,
        Lcom/p1/mobile/longlink/msg/liveroom/LongLinkLiveMessage$VoiceLiveMaskModeFollowApplyInfo;,
        Lcom/p1/mobile/longlink/msg/liveroom/LongLinkLiveMessage$VoiceLiveMaskModeFollowApplyInfoOrBuilder;,
        Lcom/p1/mobile/longlink/msg/liveroom/LongLinkLiveMessage$VoiceLiveFollowShipApplyMessage;,
        Lcom/p1/mobile/longlink/msg/liveroom/LongLinkLiveMessage$VoiceLiveFollowShipApplyMessageOrBuilder;,
        Lcom/p1/mobile/longlink/msg/liveroom/LongLinkLiveMessage$Topic;,
        Lcom/p1/mobile/longlink/msg/liveroom/LongLinkLiveMessage$TopicOrBuilder;,
        Lcom/p1/mobile/longlink/msg/liveroom/LongLinkLiveMessage$VoiceRoomTopicUpdate;,
        Lcom/p1/mobile/longlink/msg/liveroom/LongLinkLiveMessage$VoiceRoomTopicUpdateOrBuilder;,
        Lcom/p1/mobile/longlink/msg/liveroom/LongLinkLiveMessage$LiveSchemaChatMessage;,
        Lcom/p1/mobile/longlink/msg/liveroom/LongLinkLiveMessage$LiveSchemaChatMessageOrBuilder;,
        Lcom/p1/mobile/longlink/msg/liveroom/LongLinkLiveMessage$LiveRewardPointInfo;,
        Lcom/p1/mobile/longlink/msg/liveroom/LongLinkLiveMessage$LiveRewardPointInfoOrBuilder;,
        Lcom/p1/mobile/longlink/msg/liveroom/LongLinkLiveMessage$RoomInfo;,
        Lcom/p1/mobile/longlink/msg/liveroom/LongLinkLiveMessage$RoomInfoOrBuilder;,
        Lcom/p1/mobile/longlink/msg/liveroom/LongLinkLiveMessage$Mask;,
        Lcom/p1/mobile/longlink/msg/liveroom/LongLinkLiveMessage$MaskOrBuilder;,
        Lcom/p1/mobile/longlink/msg/liveroom/LongLinkLiveMessage$VoiceCallMessage;,
        Lcom/p1/mobile/longlink/msg/liveroom/LongLinkLiveMessage$VoiceCallMessageOrBuilder;,
        Lcom/p1/mobile/longlink/msg/liveroom/LongLinkLiveMessage$CallEffectConfig;,
        Lcom/p1/mobile/longlink/msg/liveroom/LongLinkLiveMessage$CallEffectConfigOrBuilder;,
        Lcom/p1/mobile/longlink/msg/liveroom/LongLinkLiveMessage$VoiceCall;,
        Lcom/p1/mobile/longlink/msg/liveroom/LongLinkLiveMessage$VoiceCallOrBuilder;,
        Lcom/p1/mobile/longlink/msg/liveroom/LongLinkLiveMessage$BossModeInfo;,
        Lcom/p1/mobile/longlink/msg/liveroom/LongLinkLiveMessage$BossModeInfoOrBuilder;,
        Lcom/p1/mobile/longlink/msg/liveroom/LongLinkLiveMessage$LiveUpdatePullVideoQuality;,
        Lcom/p1/mobile/longlink/msg/liveroom/LongLinkLiveMessage$LiveUpdatePullVideoQualityOrBuilder;,
        Lcom/p1/mobile/longlink/msg/liveroom/LongLinkLiveMessage$LiveUpdateVideoQuality;,
        Lcom/p1/mobile/longlink/msg/liveroom/LongLinkLiveMessage$LiveUpdateVideoQualityOrBuilder;,
        Lcom/p1/mobile/longlink/msg/liveroom/LongLinkLiveMessage$CallMessage;,
        Lcom/p1/mobile/longlink/msg/liveroom/LongLinkLiveMessage$CallMessageOrBuilder;,
        Lcom/p1/mobile/longlink/msg/liveroom/LongLinkLiveMessage$Call;,
        Lcom/p1/mobile/longlink/msg/liveroom/LongLinkLiveMessage$CallOrBuilder;,
        Lcom/p1/mobile/longlink/msg/liveroom/LongLinkLiveMessage$UserProfile;,
        Lcom/p1/mobile/longlink/msg/liveroom/LongLinkLiveMessage$UserProfileOrBuilder;,
        Lcom/p1/mobile/longlink/msg/liveroom/LongLinkLiveMessage$PkMute;,
        Lcom/p1/mobile/longlink/msg/liveroom/LongLinkLiveMessage$PkMuteOrBuilder;,
        Lcom/p1/mobile/longlink/msg/liveroom/LongLinkLiveMessage$PkMvp;,
        Lcom/p1/mobile/longlink/msg/liveroom/LongLinkLiveMessage$PkMvpOrBuilder;,
        Lcom/p1/mobile/longlink/msg/liveroom/LongLinkLiveMessage$PkPunishmentSelected;,
        Lcom/p1/mobile/longlink/msg/liveroom/LongLinkLiveMessage$PkPunishmentSelectedOrBuilder;,
        Lcom/p1/mobile/longlink/msg/liveroom/LongLinkLiveMessage$PkPunishmentSelect;,
        Lcom/p1/mobile/longlink/msg/liveroom/LongLinkLiveMessage$PkPunishmentSelectOrBuilder;,
        Lcom/p1/mobile/longlink/msg/liveroom/LongLinkLiveMessage$PkInviteRejected;,
        Lcom/p1/mobile/longlink/msg/liveroom/LongLinkLiveMessage$PkInviteRejectedOrBuilder;,
        Lcom/p1/mobile/longlink/msg/liveroom/LongLinkLiveMessage$PkInviteCanceled;,
        Lcom/p1/mobile/longlink/msg/liveroom/LongLinkLiveMessage$PkInviteCanceledOrBuilder;,
        Lcom/p1/mobile/longlink/msg/liveroom/LongLinkLiveMessage$PkInviteNotify;,
        Lcom/p1/mobile/longlink/msg/liveroom/LongLinkLiveMessage$PkInviteNotifyOrBuilder;,
        Lcom/p1/mobile/longlink/msg/liveroom/LongLinkLiveMessage$PkPushCdnFail;,
        Lcom/p1/mobile/longlink/msg/liveroom/LongLinkLiveMessage$PkPushCdnFailOrBuilder;,
        Lcom/p1/mobile/longlink/msg/liveroom/LongLinkLiveMessage$PkPunishmentMotion;,
        Lcom/p1/mobile/longlink/msg/liveroom/LongLinkLiveMessage$PkPunishmentMotionOrBuilder;,
        Lcom/p1/mobile/longlink/msg/liveroom/LongLinkLiveMessage$PkEnd;,
        Lcom/p1/mobile/longlink/msg/liveroom/LongLinkLiveMessage$PkEndOrBuilder;,
        Lcom/p1/mobile/longlink/msg/liveroom/LongLinkLiveMessage$PkResult;,
        Lcom/p1/mobile/longlink/msg/liveroom/LongLinkLiveMessage$PkResultOrBuilder;,
        Lcom/p1/mobile/longlink/msg/liveroom/LongLinkLiveMessage$PkPoints;,
        Lcom/p1/mobile/longlink/msg/liveroom/LongLinkLiveMessage$PkPointsOrBuilder;,
        Lcom/p1/mobile/longlink/msg/liveroom/LongLinkLiveMessage$PkUserPoints;,
        Lcom/p1/mobile/longlink/msg/liveroom/LongLinkLiveMessage$PkUserPointsOrBuilder;,
        Lcom/p1/mobile/longlink/msg/liveroom/LongLinkLiveMessage$PkContributor;,
        Lcom/p1/mobile/longlink/msg/liveroom/LongLinkLiveMessage$PkContributorOrBuilder;,
        Lcom/p1/mobile/longlink/msg/liveroom/LongLinkLiveMessage$PkStart;,
        Lcom/p1/mobile/longlink/msg/liveroom/LongLinkLiveMessage$PkStartOrBuilder;,
        Lcom/p1/mobile/longlink/msg/liveroom/LongLinkLiveMessage$PkCreated;,
        Lcom/p1/mobile/longlink/msg/liveroom/LongLinkLiveMessage$PkCreatedOrBuilder;,
        Lcom/p1/mobile/longlink/msg/liveroom/LongLinkLiveMessage$PkPlayingBuffInfo;,
        Lcom/p1/mobile/longlink/msg/liveroom/LongLinkLiveMessage$PkPlayingBuffInfoOrBuilder;,
        Lcom/p1/mobile/longlink/msg/liveroom/LongLinkLiveMessage$PkInfo;,
        Lcom/p1/mobile/longlink/msg/liveroom/LongLinkLiveMessage$PkInfoOrBuilder;,
        Lcom/p1/mobile/longlink/msg/liveroom/LongLinkLiveMessage$PlayerInfo;,
        Lcom/p1/mobile/longlink/msg/liveroom/LongLinkLiveMessage$PlayerInfoOrBuilder;,
        Lcom/p1/mobile/longlink/msg/liveroom/LongLinkLiveMessage$PkSeekTimeout;,
        Lcom/p1/mobile/longlink/msg/liveroom/LongLinkLiveMessage$PkSeekTimeoutOrBuilder;,
        Lcom/p1/mobile/longlink/msg/liveroom/LongLinkLiveMessage$LiveStickerAuditMsg;,
        Lcom/p1/mobile/longlink/msg/liveroom/LongLinkLiveMessage$LiveStickerAuditMsgOrBuilder;,
        Lcom/p1/mobile/longlink/msg/liveroom/LongLinkLiveMessage$Position;,
        Lcom/p1/mobile/longlink/msg/liveroom/LongLinkLiveMessage$PositionOrBuilder;,
        Lcom/p1/mobile/longlink/msg/liveroom/LongLinkLiveMessage$LiveSticker;,
        Lcom/p1/mobile/longlink/msg/liveroom/LongLinkLiveMessage$LiveStickerOrBuilder;,
        Lcom/p1/mobile/longlink/msg/liveroom/LongLinkLiveMessage$LiveRoomAnnouncementAuditMsg;,
        Lcom/p1/mobile/longlink/msg/liveroom/LongLinkLiveMessage$LiveRoomAnnouncementAuditMsgOrBuilder;,
        Lcom/p1/mobile/longlink/msg/liveroom/LongLinkLiveMessage$LiveStickerChangeMsg;,
        Lcom/p1/mobile/longlink/msg/liveroom/LongLinkLiveMessage$LiveStickerChangeMsgOrBuilder;,
        Lcom/p1/mobile/longlink/msg/liveroom/LongLinkLiveMessage$LiveTemplateMsg;,
        Lcom/p1/mobile/longlink/msg/liveroom/LongLinkLiveMessage$LiveTemplateMsgOrBuilder;,
        Lcom/p1/mobile/longlink/msg/liveroom/LongLinkLiveMessage$ChatTipsChange;,
        Lcom/p1/mobile/longlink/msg/liveroom/LongLinkLiveMessage$ChatTipsChangeOrBuilder;,
        Lcom/p1/mobile/longlink/msg/liveroom/LongLinkLiveMessage$DeleteManager;,
        Lcom/p1/mobile/longlink/msg/liveroom/LongLinkLiveMessage$DeleteManagerOrBuilder;,
        Lcom/p1/mobile/longlink/msg/liveroom/LongLinkLiveMessage$AddManager;,
        Lcom/p1/mobile/longlink/msg/liveroom/LongLinkLiveMessage$AddManagerOrBuilder;,
        Lcom/p1/mobile/longlink/msg/liveroom/LongLinkLiveMessage$Follow;,
        Lcom/p1/mobile/longlink/msg/liveroom/LongLinkLiveMessage$FollowOrBuilder;,
        Lcom/p1/mobile/longlink/msg/liveroom/LongLinkLiveMessage$CallRewardPoint;,
        Lcom/p1/mobile/longlink/msg/liveroom/LongLinkLiveMessage$CallRewardPointOrBuilder;,
        Lcom/p1/mobile/longlink/msg/liveroom/LongLinkLiveMessage$LiveInfo;,
        Lcom/p1/mobile/longlink/msg/liveroom/LongLinkLiveMessage$LiveInfoOrBuilder;,
        Lcom/p1/mobile/longlink/msg/liveroom/LongLinkLiveMessage$LiveForceStop;,
        Lcom/p1/mobile/longlink/msg/liveroom/LongLinkLiveMessage$LiveForceStopOrBuilder;,
        Lcom/p1/mobile/longlink/msg/liveroom/LongLinkLiveMessage$BootOutRoomByAdmin;,
        Lcom/p1/mobile/longlink/msg/liveroom/LongLinkLiveMessage$BootOutRoomByAdminOrBuilder;,
        Lcom/p1/mobile/longlink/msg/liveroom/LongLinkLiveMessage$BootOutRoom;,
        Lcom/p1/mobile/longlink/msg/liveroom/LongLinkLiveMessage$BootOutRoomOrBuilder;,
        Lcom/p1/mobile/longlink/msg/liveroom/LongLinkLiveMessage$Block;,
        Lcom/p1/mobile/longlink/msg/liveroom/LongLinkLiveMessage$BlockOrBuilder;,
        Lcom/p1/mobile/longlink/msg/liveroom/LongLinkLiveMessage$JailInRoom;,
        Lcom/p1/mobile/longlink/msg/liveroom/LongLinkLiveMessage$JailInRoomOrBuilder;,
        Lcom/p1/mobile/longlink/msg/liveroom/LongLinkLiveMessage$LeaveRoom;,
        Lcom/p1/mobile/longlink/msg/liveroom/LongLinkLiveMessage$LeaveRoomOrBuilder;,
        Lcom/p1/mobile/longlink/msg/liveroom/LongLinkLiveMessage$EnterRoom;,
        Lcom/p1/mobile/longlink/msg/liveroom/LongLinkLiveMessage$EnterRoomOrBuilder;,
        Lcom/p1/mobile/longlink/msg/liveroom/LongLinkLiveMessage$LiveRecover;,
        Lcom/p1/mobile/longlink/msg/liveroom/LongLinkLiveMessage$LiveRecoverOrBuilder;,
        Lcom/p1/mobile/longlink/msg/liveroom/LongLinkLiveMessage$LivePause;,
        Lcom/p1/mobile/longlink/msg/liveroom/LongLinkLiveMessage$LivePauseOrBuilder;,
        Lcom/p1/mobile/longlink/msg/liveroom/LongLinkLiveMessage$LiveStop;,
        Lcom/p1/mobile/longlink/msg/liveroom/LongLinkLiveMessage$LiveStopOrBuilder;,
        Lcom/p1/mobile/longlink/msg/liveroom/LongLinkLiveMessage$LiveStart;,
        Lcom/p1/mobile/longlink/msg/liveroom/LongLinkLiveMessage$LiveStartOrBuilder;,
        Lcom/p1/mobile/longlink/msg/liveroom/LongLinkLiveMessage$LiveSystemMessage;,
        Lcom/p1/mobile/longlink/msg/liveroom/LongLinkLiveMessage$LiveSystemMessageOrBuilder;,
        Lcom/p1/mobile/longlink/msg/liveroom/LongLinkLiveMessage$UserInfo;,
        Lcom/p1/mobile/longlink/msg/liveroom/LongLinkLiveMessage$UserInfoOrBuilder;,
        Lcom/p1/mobile/longlink/msg/liveroom/LongLinkLiveMessage$Operate;,
        Lcom/p1/mobile/longlink/msg/liveroom/LongLinkLiveMessage$PkEndType;,
        Lcom/p1/mobile/longlink/msg/liveroom/LongLinkLiveMessage$VoiceSongGameEndType;,
        Lcom/p1/mobile/longlink/msg/liveroom/LongLinkLiveMessage$VoiceSongGameStatus;,
        Lcom/p1/mobile/longlink/msg/liveroom/LongLinkLiveMessage$AwayReason;,
        Lcom/p1/mobile/longlink/msg/liveroom/LongLinkLiveMessage$CallMessageType;,
        Lcom/p1/mobile/longlink/msg/liveroom/LongLinkLiveMessage$UpdateField;
    }
.end annotation


# direct methods
.method static constructor <clinit>()V
    .locals 0

    return-void
.end method

.method private constructor <init>()V
    .locals 0

    .line 1
    invoke-direct {p0}, Ljava/lang/Object;-><init>()V

    .line 2
    .line 3
    .line 4
    return-void
.end method

.method public static registerAllExtensions(Lcom/google/protobuf/h;)V
    .locals 0

    return-void
.end method
