package unipatches.overlay.presets

internal val luckyPatcherPreset = OverlayPresetDefinition(
    "luckyPatcher",
    "LuckyPatcher-inspired",
    "Original black-and-yellow UI inspired by Lucky Patcher.",
    explicitOverlayPreset(
        buttonText = "LP",
        background = "#000000",
        backgroundTransparency = 100,
        outline = "#FFFF00",
        overlayTextColor = "#FFFFFF",
        outlineWidth = 4,
        appendDescription = "Inspired by Lucky Patcher",
        appendDescriptionColor = "#FFFF00",
        buttonTextColor = "#FFFFFF",
        gradientBackground = true,
        buttonBackground = "#F0E60A",
        iconBackground2 = "#C6B407",
        iconGradientAngle = 0,
        iconOutline = true,
        iconOutlineColor = "#000000",
        iconOutlineWidth = 4,
        iconStyle = "multi",
        iconShape = "smile",
        iconShapeColor1 = "#000000",
        iconShapeColor2 = "#000000",
        iconShapeGradient = false,
        iconShapeStrokeWidth = 3,
        iconShapeScale = 68,
        iconHighlight = true,
        iconShadow = true,
        controlTheme = "modern",
        controlBackground = "#D3D3D3",
        controlForeground = "#B0FFFF",
        bottomButtonStyle = "gradient",
        bottomButtonShape = "squircle",
        bottomButtonPadding = true,
        bottomButtonTextColor = "#FFFFFF",
        bottomButtonBackground1 = "#3A5A80",
        bottomButtonBackground2 = "#6E91B9",
        menuTextColor1 = "#FFFFFF",
        menuTextColor2 = "#00FF00",
        menuTextColor3 = "#B8B8B8",
        menuTextColor4 = "#D14DCA",
        menuTextColor5 = "#00FF00",
        menuTextColor6 = "#000000",
        separatorBackgroundColor = "#D0D0D0",
        separatorStyle = "background",
        titleIconPlacement = "left",
        titleAlignment = "left",
        titleSeparator = true,
        menuCorners = "square",
        menuOutlineAnimation = "static",
        openingAnimation = "appearRight",
        closingAnimation = "disappearUp",
        animationDuration = 300,
        animationEasing = "linear",
    ),
)
