package unipatches.overlay.presets

internal data class OverlayUiPreset(
    val title: String,
    val description: String,
    val appendDescription: String = "",
    val descriptionAlignment: String = "center",
    val repositoryText: String,
    val repositoryUrl: String,
    val background: String,
    val backgroundTransparency: Int,
    val outline: String,
    val overlayTextColor: String,
    val outlineWidth: Int,
    val buttonText: String,
    val iconBold: Boolean,
    val buttonTextColor: String,
    val gradientBackground: Boolean,
    val buttonBackground: String,
    val iconBackground2: String,
    val iconGradientAngle: Int,
    val iconOutline: Boolean,
    val iconOutlineWidth: Int,
    val iconOutlineColor: String,
    val customIconImageLocal: String,
    val customIconImageInput: String,
    val buttonShape: String,
    val buttonSize: Int,
    val buttonOpacity: Int,
    val dragVisibilityDuration: Int,
    val buttonPosition: String,
    val activityOverride: String,
    val iconTextSize: Int,
    val controlTheme: String = "modern",
    val controlBackground: String = "#300000",
    val controlForeground: String = "#FF5656",
    val bottomButtonStyle: String = "text",
    val bottomButtonShape: String = "square",
    val bottomButtonPadding: Boolean = false,
    val bottomButtonTextColor: String = "#FFFFFF",
    val bottomButtonBackground1: String = "#500000",
    val bottomButtonBackground2: String = "#AA0000",
    val menuTextColor1: String = "#FF5656",
    val menuTextColor2: String = "#FF5656",
    val menuTextColor3: String = "#FF5656",
    val menuTextColor4: String = "#FF5656",
    val menuTextColor5: String = "#FF5656",
    val menuTextColor6: String = menuTextColor2,
    val separatorBackgroundColor: String = background,
    val appendDescriptionColor: String = menuTextColor3,
    val separatorStyle: String = "ascii",
    val titleIconPlacement: String = "none",
    val titleAlignment: String = "left",
    val titleSeparator: Boolean = false,
    val menuCorners: String = "rounded",
    val menuOutlineAnimation: String = "static",
    val outlineAnimationSpeed: Int = 1,
    val openingAnimation: String = "fade",
    val closingAnimation: String = "fade",
    val animationDuration: Int = 180,
    val animationEasing: String = "linear",
    val iconStyle: String = "text",
    val iconShape: String = "triangle",
    val iconShapeColor1: String = "#FFFFFF",
    val iconShapeColor2: String = "#FFFFFF",
    val iconShapeGradient: Boolean = false,
    val iconShapeGradientAngle: Int = 0,
    val iconShapeStrokeWidth: Int = 3,
    val iconShapeScale: Int = 70,
    val iconHighlight: Boolean = false,
    val iconShadow: Boolean = false,
    val iconOutlineGradient: Boolean = false,
    val iconOutlineColor2: String = iconOutlineColor,
    val iconOutlineGradientAngle: Int = 0,
    val iconBackgroundStyle: String = "flat",
    val iconBackgroundColor3: String = iconBackground2,
    val iconBackgroundColor4: String = buttonBackground,
)

internal data class OverlayPresetDefinition(
    val id: String,
    val displayName: String,
    val description: String,
    val values: OverlayUiPreset,
)

internal fun explicitOverlayPreset(
    buttonText: String,
    background: String,
    backgroundTransparency: Int,
    outline: String,
    overlayTextColor: String,
    buttonTextColor: String,
    gradientBackground: Boolean,
    buttonBackground: String,
    iconBackground2: String,
    iconGradientAngle: Int,
    iconOutlineColor: String,
    controlTheme: String = "modern",
    controlBackground: String = "#300000",
    controlForeground: String = "#FF5656",
    bottomButtonStyle: String = "text",
    bottomButtonShape: String = "square",
    bottomButtonPadding: Boolean = false,
    bottomButtonTextColor: String = "#FFFFFF",
    bottomButtonBackground1: String = "#500000",
    bottomButtonBackground2: String = "#AA0000",
    menuTextColor1: String = overlayTextColor,
    menuTextColor2: String = overlayTextColor,
    menuTextColor3: String = overlayTextColor,
    menuTextColor4: String = overlayTextColor,
    menuTextColor5: String = overlayTextColor,
    menuTextColor6: String = menuTextColor2,
    separatorBackgroundColor: String = background,
    separatorStyle: String = "ascii",
    titleIconPlacement: String = "none",
    titleAlignment: String = "left",
    titleSeparator: Boolean = false,
    menuCorners: String = "rounded",
    menuOutlineAnimation: String = "static",
    outlineAnimationSpeed: Int = 1,
    openingAnimation: String = "fade",
    closingAnimation: String = "fade",
    animationDuration: Int = 180,
    animationEasing: String = "linear",
    appendDescription: String = "",
    descriptionAlignment: String = "center",
    appendDescriptionColor: String = menuTextColor3,
    outlineWidth: Int = 2,
    iconOutline: Boolean = false,
    iconOutlineWidth: Int = 3,
    buttonShape: String = "circle",
    iconStyle: String = "text",
    iconShape: String = "triangle",
    iconShapeColor1: String = "#FFFFFF",
    iconShapeColor2: String = iconShapeColor1,
    iconShapeGradient: Boolean = false,
    iconShapeGradientAngle: Int = 0,
    iconShapeStrokeWidth: Int = 3,
    iconShapeScale: Int = 70,
    iconHighlight: Boolean = false,
    iconShadow: Boolean = false,
    iconOutlineGradient: Boolean = false,
    iconOutlineColor2: String = iconOutlineColor,
    iconOutlineGradientAngle: Int = 0,
    iconBackgroundStyle: String = "flat",
    iconBackgroundColor3: String = iconBackground2,
    iconBackgroundColor4: String = background,
): OverlayUiPreset = OverlayUiPreset(
    title = "UniPatches Universal Overlay Patch",
    description = "Welcome! This is the UniPatches Universal Overlay Patch Menu.\n" +
        "The idea and initial works of Universal Overlay Patch are from Zanuaimi / Noobite.",
    appendDescription = appendDescription,
    descriptionAlignment = descriptionAlignment,
    appendDescriptionColor = appendDescriptionColor,
    repositoryText = "UniPatches repository",
    repositoryUrl = "https://github.com/Zanuaimi/UniPatches",
    background = background,
    backgroundTransparency = backgroundTransparency,
    outline = outline,
    overlayTextColor = overlayTextColor,
    outlineWidth = outlineWidth,
    buttonText = buttonText,
    iconBold = true,
    buttonTextColor = buttonTextColor,
    gradientBackground = gradientBackground,
    buttonBackground = buttonBackground,
    iconBackground2 = iconBackground2,
    iconGradientAngle = iconGradientAngle,
    iconOutline = iconOutline,
    iconOutlineWidth = iconOutlineWidth,
    iconOutlineColor = iconOutlineColor,
    customIconImageLocal = "",
    customIconImageInput = "",
    buttonShape = buttonShape,
    buttonSize = 56,
    buttonOpacity = 50,
    dragVisibilityDuration = 2,
    buttonPosition = "topRight",
    activityOverride = "",
    iconTextSize = 18,
    controlTheme = controlTheme,
    controlBackground = controlBackground,
    controlForeground = controlForeground,
    bottomButtonStyle = bottomButtonStyle,
    bottomButtonShape = bottomButtonShape,
    bottomButtonPadding = bottomButtonPadding,
    bottomButtonTextColor = bottomButtonTextColor,
    bottomButtonBackground1 = bottomButtonBackground1,
    bottomButtonBackground2 = bottomButtonBackground2,
    menuTextColor1 = menuTextColor1,
    menuTextColor2 = menuTextColor2,
    menuTextColor3 = menuTextColor3,
    menuTextColor4 = menuTextColor4,
    menuTextColor5 = menuTextColor5,
    menuTextColor6 = menuTextColor6,
    separatorBackgroundColor = separatorBackgroundColor,
    separatorStyle = separatorStyle,
    titleIconPlacement = titleIconPlacement,
    titleAlignment = titleAlignment,
    titleSeparator = titleSeparator,
    menuCorners = menuCorners,
    menuOutlineAnimation = menuOutlineAnimation,
    outlineAnimationSpeed = outlineAnimationSpeed,
    openingAnimation = openingAnimation,
    closingAnimation = closingAnimation,
    animationDuration = animationDuration,
    animationEasing = animationEasing,
    iconStyle = iconStyle,
    iconShape = iconShape,
    iconShapeColor1 = iconShapeColor1,
    iconShapeColor2 = iconShapeColor2,
    iconShapeGradient = iconShapeGradient,
    iconShapeGradientAngle = iconShapeGradientAngle,
    iconShapeStrokeWidth = iconShapeStrokeWidth,
    iconShapeScale = iconShapeScale,
    iconHighlight = iconHighlight,
    iconShadow = iconShadow,
    iconOutlineGradient = iconOutlineGradient,
    iconOutlineColor2 = iconOutlineColor2,
    iconOutlineGradientAngle = iconOutlineGradientAngle,
    iconBackgroundStyle = iconBackgroundStyle,
    iconBackgroundColor3 = iconBackgroundColor3,
    iconBackgroundColor4 = iconBackgroundColor4,
)
