package unipatches.overlay.presets

internal data class OverlayUiPreset(
    val title: String,
    val description: String,
    val repositoryText: String,
    val repositoryUrl: String,
    val background: String,
    val backgroundTransparency: Int,
    val outline: String,
    val overlayTextColor: String,
    val outlineWidth: Int,
    val buttonText: String,
    val iconBold: Boolean,
    val buttonTextColor: String,
    val gradientBackground: Boolean,
    val buttonBackground: String,
    val iconBackground2: String,
    val iconGradientAngle: Int,
    val iconOutline: Boolean,
    val iconOutlineWidth: Int,
    val iconOutlineColor: String,
    val customIconImageLocal: String,
    val customIconImageInput: String,
    val buttonShape: String,
    val buttonSize: Int,
    val buttonOpacity: Int,
    val dragVisibilityDuration: Int,
    val buttonPosition: String,
    val activityOverride: String,
    val iconTextSize: Int,
)

internal data class OverlayPresetDefinition(
    val id: String,
    val displayName: String,
    val description: String,
    val values: OverlayUiPreset,
)

internal fun explicitOverlayPreset(
    buttonText: String,
    background: String,
    backgroundTransparency: Int,
    outline: String,
    overlayTextColor: String,
    buttonTextColor: String,
    gradientBackground: Boolean,
    buttonBackground: String,
    iconBackground2: String,
    iconGradientAngle: Int,
    iconOutlineColor: String,
): OverlayUiPreset = OverlayUiPreset(
    title = "UniPatches Universal Overlay Patch",
    description = "Welcome! This is the UniPatches Universal Overlay Patch Menu.\n" +
        "You will find modules below the description if you enabled some modules\n" +
        "in this patch settings before patching this APK.\n" +
        "The idea and initial works of Universal Overlay Patch are from Zanuaimi / Noobite.",
    repositoryText = "UniPatches repository",
    repositoryUrl = "https://github.com/Zanuaimi/UniPatches",
    background = background,
    backgroundTransparency = backgroundTransparency,
    outline = outline,
    overlayTextColor = overlayTextColor,
    outlineWidth = 2,
    buttonText = buttonText,
    iconBold = true,
    buttonTextColor = buttonTextColor,
    gradientBackground = gradientBackground,
    buttonBackground = buttonBackground,
    iconBackground2 = iconBackground2,
    iconGradientAngle = iconGradientAngle,
    iconOutline = false,
    iconOutlineWidth = 3,
    iconOutlineColor = iconOutlineColor,
    customIconImageLocal = "",
    customIconImageInput = "",
    buttonShape = "circle",
    buttonSize = 56,
    buttonOpacity = 50,
    dragVisibilityDuration = 2,
    buttonPosition = "topRight",
    activityOverride = "",
    iconTextSize = 18,
)
