package unipatches.overlay.presets

internal val reVancedPreset = OverlayPresetDefinition(
    "reVanced",
    "ReVanced-inspired",
    "Original dark Material You-style UI inspired by ReVanced.",
    explicitOverlayPreset(
        buttonText = "RV",
        background = "#1B1B1D",
        backgroundTransparency = 90,
        outline = "#3D8BFF",
        overlayTextColor = "#B8D2FF",
        buttonTextColor = "#FFFFFF",
        outlineWidth = 4,
        appendDescription = "Inspired by ReVanced",
        appendDescriptionColor = "#D5B8FF",
        gradientBackground = false,
        buttonBackground = "#1B1B1B",
        iconBackground2 = "#1B1B1B",
        iconGradientAngle = 0,
        iconOutlineColor = "#EF4E99",
        iconOutlineGradient = true,
        iconOutlineColor2 = "#4E97F0",
        iconOutlineGradientAngle = 90,
        iconOutlineWidth = 6,
        iconStyle = "shape",
        iconShape = "triangle",
        iconShapeColor1 = "#E651A0",
        iconShapeColor2 = "#6564D3",
        iconShapeGradient = true,
        iconShapeGradientAngle = 0,
        iconShapeScale = 58,
        iconHighlight = false,
        iconShadow = false,
        controlTheme = "monet",
        controlBackground = "#91B6F2",
        controlForeground = "#C5D9FF",
        bottomButtonStyle = "solid",
        bottomButtonShape = "squircle",
        bottomButtonPadding = true,
        bottomButtonTextColor = "#D5B8FF",
        bottomButtonBackground1 = "#39304D",
        bottomButtonBackground2 = "#39304D",
        menuTextColor1 = "#B8D2FF",
        menuTextColor2 = "#D5B8FF",
        menuTextColor3 = "#D0D0D5",
        menuTextColor4 = "#8DB8F5",
        menuTextColor5 = "#8DB8F5",
        menuTextColor6 = "#A990D0",
        separatorStyle = "inline",
        menuOutlineAnimation = "gradient",
        openingAnimation = "scale",
        closingAnimation = "scale",
        animationDuration = 500,
        animationEasing = "logarithmic",
    ),
)
