"""Generate Android resources and a source-string migration map. No network translation at runtime."""
import json,html
from pathlib import Path
root=Path(__file__).resolve().parents[1]
data=json.loads((root/'localization/catalog.json').read_text(encoding='utf-8'))
out=root/'patches/src/main/resources/captionlocales';out.mkdir(parents=True,exist_ok=True)
paths=[]
for locale,values in data['languages'].items():
 folder='values' if locale=='en' else 'values-'+({'id':'in'}.get(locale,locale))
 path=out/folder/'caption_addon_strings.xml';path.parent.mkdir(parents=True,exist_ok=True)
 def escape(s):return html.escape(s,quote=False).replace('"','\\"').replace("'","\\'")
 path.write_text('<?xml version="1.0" encoding="utf-8"?>\n<resources>\n'+''.join(f'    <string name="cap_{key}" formatted="false">"{escape(value)}"</string>\n' for key,value in values.items())+'</resources>\n',encoding='utf-8');paths.append(folder)
(out/'index.txt').write_text('\n'.join(paths)+'\n',encoding='utf-8')
(out/'source-keys.tsv').write_text('\n'.join(source+'\tcap_'+key for source,key in data['source_keys'].items())+'\n',encoding='utf-8')
j=lambda s:json.dumps(s,ensure_ascii=False)
java='package app.yydarlinker.deepseekcaptions;\n/** Generated by tools/generate_localization.py. */\nfinal class CaptionTranslationCatalog {\n'
java+='static final String[][] SOURCES={\n'+',\n'.join('{'+j(s)+','+j(k)+'}' for s,k in sorted(data['source_keys'].items(),key=lambda x:-len(x[0])))+'\n};\n'
java+='static final String[][] ENGLISH=values_en();\n'
java+='private static final java.util.Map<String,java.util.Map<String,String>> VALUES=new java.util.HashMap<>();\nstatic {\n'
for locale in data['languages']:
 method='values_'+locale.replace('-','_')
 java+='java.util.Map<String,String> '+method+'=new java.util.HashMap<>();\n'
 java+='for(String[] entry:'+method+'())'+method+'.put(entry[0],entry[1]);\n'
 java+='VALUES.put('+j(locale)+','+method+');\n'
java+='}\nstatic String text(String locale,String key){java.util.Map<String,String> values=VALUES.get(locale);String value=values==null?null:values.get(key);return value!=null?value:VALUES.get("en").getOrDefault(key,"");}\n'
for locale,values in data['languages'].items():
 java+='private static String[][] values_'+locale.replace('-','_')+'(){return new String[][]{\n'+',\n'.join('{'+j(k)+','+j(v)+'}' for k,v in values.items())+'\n};}\n'
java+='}\n'
(root/'extensions/extension/src/main/java/app/yydarlinker/deepseekcaptions/CaptionTranslationCatalog.java').write_text(java,encoding='utf-8')
assert all(set(data['languages']['en'])==set(v) for v in data['languages'].values())
print(f"{len(data['languages'])} locales; {len(data['keys'])} core UI keys in every locale; {len(data['languages']['en'])} default keys")
