"""Turn the settings translation tables into a Java class the extension carries.

Reads every extensions/tiktok/src/main/l10n/<lang>.tsv (English TAB translation, one entry
per line, # comments) and writes:

  extensions/tiktok/src/main/java/app/morphe/extension/tiktok/settings/L10nTranslations.java

The English text in the code is the lookup key, so only the translations are stored. They
travel in the extension's own DEX rather than in TikTok's resources: merging a few hundred
strings into an app whose resource table already holds 74,765 of them costs more than 250 MB
of patching memory, which is more than Morphe Manager gives by default (measured 2026-09-06).

Each language becomes its own method returning a flat {key, value, key, value} array, split
across several methods so no single one approaches the 64 KB bytecode limit.

Run from the repository root: python scripts/gen-l10n.py
"""
import io
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
L10N = os.path.join(ROOT, "extensions", "tiktok", "src", "main", "l10n")
JAVA = os.path.join(ROOT, "extensions", "tiktok", "src", "main", "java", "app", "morphe",
                    "extension", "tiktok", "settings", "L10nTranslations.java")

# Entries per generated method. 60 pairs is roughly 2 KB of bytecode, well inside the limit
# and few enough methods to stay readable.
CHUNK = 60

# Three languages have two ISO codes, and the two runtimes disagree about which one to give
# back. Android's Locale.getLanguage() answers with the legacy code, a JVM since 17 answers
# with the new one, so the same table has to be reachable under both or the tests and the
# phone read different tables.
ALIASES = {"in": "id", "id": "in", "iw": "he", "he": "iw", "ji": "yi", "yi": "ji"}


def read(path):
    entries = {}
    with io.open(path, encoding="utf-8") as handle:
        for number, line in enumerate(handle, 1):
            line = line.rstrip("\r\n")
            if not line or line.startswith("#"):
                continue
            if "\t" not in line:
                sys.exit("%s:%d: no tab" % (path, number))
            english, translated = line.split("\t", 1)
            english = english.replace("\\n", "\n")
            translated = translated.replace("\\n", "\n")
            if english in entries:
                sys.exit("%s:%d: duplicate entry: %s" % (path, number, english))
            entries[english] = translated
    return entries


def literal(text):
    out = text.replace("\\", "\\\\").replace('"', '\\"')
    out = out.replace("\n", "\\n").replace("\r", "\\r").replace("\t", "\\t")
    return '"%s"' % out


def java_name(lang):
    return lang.replace("-", "_").replace("+", "_")


def main():
    tables = {}
    for name in sorted(os.listdir(L10N)):
        if name.endswith(".tsv"):
            tables[name[:-4]] = read(os.path.join(L10N, name))
    if not tables:
        sys.exit("no .tsv tables in " + L10N)

    lines = [
        "/*",
        " * Copyright 2026 Hushfeed contributors",
        " * https://github.com/SysAdminDoc/hushfeed",
        " *",
        " * Built on icysymmetra/tiktok-patches-for-morphe (GPL-3.0).",
        " */",
        "package app.morphe.extension.tiktok.settings;",
        "",
        "import java.util.HashMap;",
        "import java.util.Map;",
        "",
        "/**",
        " * The settings text in every language the bundle carries.",
        " *",
        " * Generated by scripts/gen-l10n.py from extensions/tiktok/src/main/l10n. Do not edit by",
        " * hand: edit the .tsv table and run the script.",
        " *",
        " * The translations live here rather than in TikTok's resources because merging them into",
        " * a resource table of 74,765 strings costs more patching memory than Morphe Manager gives",
        " * by default.",
        " */",
        "public final class L10nTranslations {",
        "    private L10nTranslations() {",
        "    }",
        "",
    ]

    languages = sorted(tables)
    lines.append("    /** The language tags with a table, lower case, in the order they are tried. */")
    lines.append("    static final String[] LANGUAGES = {%s};"
                 % ", ".join(literal(lang.lower()) for lang in languages))
    lines.append("")
    lines.append("    /**")
    lines.append("     * The table for one language tag, or null when nothing was translated into it.")
    lines.append("     * A language with two ISO codes answers to both, because Android reports the")
    lines.append("     * legacy one and a desktop JVM reports the new one.")
    lines.append("     */")
    lines.append("    static Map<String, String> of(String language) {")
    lines.append("        switch (language) {")
    known = [other.lower() for other in languages]
    for lang in languages:
        name = lang.lower()
        labels = [name]
        # The alias is on the language, so a regional table answers to both spellings too.
        head, dash, tail = name.partition("-")
        alias = ALIASES.get(head)
        if alias and alias + dash + tail not in known:
            labels.append(alias + dash + tail)
        for label in labels:
            lines.append("            case %s:" % literal(label))
        lines.append("                return build%s();" % java_name(lang).capitalize())
    lines.append("            default:")
    lines.append("                return null;")
    lines.append("        }")
    lines.append("    }")

    total = 0
    for lang in languages:
        entries = tables[lang]
        total += len(entries)
        pairs = [(english, entries[english]) for english in sorted(entries)]
        chunks = [pairs[at:at + CHUNK] for at in range(0, len(pairs), CHUNK)]
        name = java_name(lang).capitalize()

        lines.append("")
        lines.append("    private static Map<String, String> build%s() {" % name)
        lines.append("        Map<String, String> table = new HashMap<>(%d);" % (len(pairs) * 2))
        for index in range(len(chunks)):
            lines.append("        fill%s%d(table);" % (name, index))
        lines.append("        return table;")
        lines.append("    }")
        for index, chunk in enumerate(chunks):
            lines.append("")
            lines.append("    private static void fill%s%d(Map<String, String> table) {" % (name, index))
            for english, translated in chunk:
                lines.append("        table.put(%s," % literal(english))
                lines.append("                %s);" % literal(translated))
            lines.append("    }")

    lines.append("}")

    os.makedirs(os.path.dirname(JAVA), exist_ok=True)
    with io.open(JAVA, "w", encoding="utf-8", newline="\n") as handle:
        handle.write("\n".join(lines) + "\n")
    print("wrote %d translations for %s" % (total, ", ".join(languages)))


if __name__ == "__main__":
    main()
