package app.yydarlinker.deepseekcaptions;
import org.junit.*;import static org.junit.Assert.*;import java.util.*;import org.json.*;
public class Release110Test {
    private SourceAtomTimeline.Result track(int size,int known,boolean reference){List<SourceAtomTimeline.Atom>a=new ArrayList<>();for(int i=0;i<size;i++){long start=i*500L+(reference?300:0);a.add(new SourceAtomTimeline.Atom(start,start+400,(reference&&i>=known?"other":"word")+i,i,reference));}return new SourceAtomTimeline.Result(a,size,reference?size:0,reference?0:size,true,false);}
    @Test public void sparseAnchorsDoNotNeedSeventyPercentTrackCoverage(){SourceAtomTimeline.Result p=track(60,16,false),a=track(60,16,true),r=AsrLocalTiming.align(p,a);assertNotSame(p,r);assertEquals(300,r.atoms.get(0).startMs);assertEquals(16,r.nativeTimedAtoms);for(int i=1;i<r.atoms.size();i++)assertTrue(r.atoms.get(i).startMs>=r.atoms.get(i-1).endMs);}
    @Test public void punctuationDoesNotPreventPhraseMatching(){SourceAtomTimeline.Result p=track(16,16,false),a=track(16,16,true);List<SourceAtomTimeline.Atom>x=new ArrayList<>();for(SourceAtomTimeline.Atom v:p.atoms)x.add(new SourceAtomTimeline.Atom(v.startMs,v.endMs,"..."+v.text+",",v.cueIndex,false));SourceAtomTimeline.Result r=AsrLocalTiming.align(new SourceAtomTimeline.Result(x,16,0,16,true,false),a);assertEquals(16,r.nativeTimedAtoms);assertEquals("...word0,",r.atoms.get(0).text);assertEquals(300,r.atoms.get(0).startMs);}
    @Test public void repeatedOrUnrelatedTextCannotCreateAlignment(){SourceAtomTimeline.Result p=track(16,16,false),a=track(16,0,true);assertSame(p,AsrLocalTiming.align(p,a));}
    @Test public void estimatedReferenceRetainsOriginal(){SourceAtomTimeline.Result p=track(16,16,false);assertSame(p,AsrLocalTiming.align(p,track(16,16,false)));}
    @Test public void ellipsisDoesNotBecomeSentenceEnd(){assertFalse(SentenceBoundaryUtil.strong("three...",7));assertTrue(SentenceBoundaryUtil.strong("Done.",4));}
    @Test public void ellipsisStaysOneAtom()throws Exception{String body="{\"events\":[{\"tStartMs\":0,\"dDurationMs\":5000,\"segs\":[{\"utf8\":\"three... new phones\"}]}]}";byte[] b=body.getBytes(java.nio.charset.StandardCharsets.UTF_8);SourceAtomTimeline.Result a=SourceAtomTimeline.build(b,CaptionDocument.parse(b,"application/json"));assertEquals(3,a.atoms.size());assertEquals("three...",a.atoms.get(0).text);}
    private AnchoredCaptionPlan.Segment s(int i,long start,long end,String text){return new AnchoredCaptionPlan.Segment(i,i,start,end,text);}
    @Test public void semanticAttachmentNotDurationDictionaryJoinsThePhrase(){List<AnchoredCaptionPlan.Segment>a=Arrays.asList(s(0,0,1600,"我们从三星身上已经习惯的那种"),s(1,1600,4000,"缓慢而稳定的改进。"));List<AnchoredCaptionPlan.Segment>r=SemanticEventPacking.pack(a,new JSONArray().put(0));assertEquals(1,r.size());assertEquals(0,r.get(0).startMs);assertEquals(4000,r.get(0).endMs);assertEquals(2,SemanticEventPacking.pack(a,null).size());}
    @Test public void shortIndependentThoughtNotJoinedWithoutEvidence(){assertEquals(2,SemanticEventPacking.pack(Arrays.asList(s(0,0,500,"不。"),s(1,500,2500,"第二点是时间。")),null).size());}
    @Test public void speakerPauseAndOverloadRemainBoundaries(){for(AnchoredCaptionPlan.Segment next:Arrays.asList(s(1,1000,2500,">> Why?"),s(1,1500,3000,"为什么？"),s(1,1000,8000,"下一段"),s(1,1000,3000,String.join("",Collections.nCopies(50,"字")))))assertEquals(2,SemanticEventPacking.pack(Arrays.asList(s(0,0,1000,"到底"),next),new JSONArray().put(0)).size());}
    @Test public void otherLanguageAttachmentUsesSameDecision(){assertEquals(1,SemanticEventPacking.pack(Arrays.asList(s(0,0,1500,"the kind of"),s(1,1500,4000,"slow and steady improvement")),new JSONArray().put(0)).size());}
    @Test public void firstRequestUsesNormalTranslationContext(){assertEquals(4,StartupCaptionPolicy.targetLimit(false,4));assertEquals(4,StartupCaptionPolicy.targetLimit(true,4));assertEquals(3,AnchoredRetryPolicy.MAX_FAILURES);}
    @Test public void pausedAuthoritativeClockNeverAdvances(){for(long n=1100;n<20000;n+=100)assertEquals(500,PlaybackSignalPolicy.position(500,1000,500,550,1000,0,false,true,n));}
    @Test public void playingClockUsesExplicitSpeed(){assertEquals(2000,PlaybackSignalPolicy.position(1000,1500,500,0,1000,2,true,false,2000));}
    @Test public void absentStaleOldVideoAndSeekUseConfirmedClock(){assertEquals(800,PlaybackSignalPolicy.position(800,1000,500,0,400,1,true,false,1500));assertEquals(800,PlaybackSignalPolicy.position(800,1000,500,0,1000,1,true,false,9000));assertEquals(8000,PlaybackSignalPolicy.position(8000,1000,500,0,1000,1,true,false,1500));assertEquals(800,PlaybackSignalPolicy.position(800,1000,500,0,1000,Float.NaN,true,false,1500));}
    @Test public void bufferingDoesNotExtrapolate(){assertEquals(800,PlaybackSignalPolicy.position(800,1000,500,0,1000,1,false,false,1500));}
    @Test public void coverageFailureTriggersSimplerButBudgetedProtocol(){assertTrue(ProtocolRecovery.wholeText("incomplete token coverage;missing=14-15"));assertFalse(ProtocolRecovery.wholeText("translation_quality"));assertFalse(ProtocolRecovery.wholeText("presentation_warning"));}
    @Test public void cjkReadabilityAlsoCoversJapaneseAndKorean(){assertTrue(CaptionPresentationPolicy.cjk("これはテスト"));assertTrue(CaptionPresentationPolicy.cjk("안녕하세요"));assertFalse(CaptionPresentationPolicy.cjk("English test"));}
    @Test public void recoveryCannotFlattenSourceAlignmentToWholeText()throws Exception{
        SourceAtomTimeline.Result a=track(6,6,false);TranslationUnitTimeline.Unit u=AnchoredWindowPlanner.build(a).units.get(0);
        String json=new JSONObject().put("translations",new JSONArray().put(new JSONObject().put("id",u.id).put("text","这是包含完整语义的自然翻译。"))).toString();
        assertEquals(0,ContextualBatchApiClient.parseAnchored(json,Arrays.asList(u),a.atoms).validCount());
        assertEquals(0,ContextualBatchApiClient.parseAnchored(json,Arrays.asList(u),a.atoms,Collections.singletonMap(u.id,"incomplete token coverage")).validCount());
    }
    @Test public void partialSegmentsAreNeverRepairedByExtendingTheirLastId()throws Exception{SourceAtomTimeline.Result a=track(8,8,false);TranslationUnitTimeline.Unit u=AnchoredWindowPlanner.build(a).units.get(0);String json=new JSONObject().put("translations",new JSONArray().put(new JSONObject().put("id",u.id).put("segments",new JSONArray().put(new JSONArray().put(3).put("只译了一部分。"))))).toString();assertEquals(0,ContextualBatchApiClient.parseAnchored(json,Arrays.asList(u),a.atoms,Collections.singletonMap(u.id,"incomplete token coverage")).validCount());}
}
