package app.subwaysurfers.patches.il2cpp

import app.morphe.patcher.patch.rawResourcePatch
import app.subwaysurfers.patches.shared.Constants.COMPATIBILITY_SUBWAY_SURFERS

/**
 * Embeds the compiled IAP-grant engine into the APK as a native library.
 *
 * The engine (built from analysis/com.kiloo.subwaysurf/ndk/ via nix + NDK
 * r27, bytes generated by ndk/lib/gen_so_bytes.py) is a small ARM64
 * companion library that, once loaded by the trigger patch:
 *   1. waits for libil2cpp.so to be mapped + unpacked (probe, not blind
 *      sleep), resolves the true load bias via dladdr on il2cpp_domain_get,
 *   2. forces HOOK A (ShopManager.<PurchaseWithIAP>d__100 cbz @ file
 *      0x24AC10C) and HOOK B (<Validate>d__70 cbz @ file 0x23B79E8) to nop
 *      via expect-checked writes, so validation always takes the success
 *      fall-through regardless of the server verdict,
 *   3. polls AbstractIAPPurchasesImplementation._purchaseInProgress; a TCS
 *      stuck past the grant delay is unwrapped (Task → continuation →
 *      MoveNextRunner → boxed state machine → product) and driven through
 *      ShopManager.ProcessPurchasedProduct (origin=RealCurrencyPurchase,
 *      status=TransactionValidated), falling back to WalletModel.AddCurrency
 *      (Coins x10000) when the product cannot be recovered.
 *
 * Ships with the Java trigger patch (NativeIapGrantTriggerPatch): trigger
 * loads the .so, native forces the grant. Either layer alone cannot fully
 * grant free taps — see notes/iap-bypass-trace.md.
 */
@Suppress("unused")
val nativeIapGrantEnginePatch = rawResourcePatch(
    name = "IAP Grant Engine",
    description = "Approves every in-app purchase for free — items are added to your account instantly.",
    default = true
) {
    compatibleWith(COMPATIBILITY_SUBWAY_SURFERS)

    execute {
        val soFile = get("lib/arm64-v8a/libSsIapGrant.so", true)
        soFile.writeBytes(SsIapGrantSoBytes.bytes())
    }
}
