name: Verify
on:
  pull_request:
permissions:
  contents: read
  packages: read
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-java@v6
        with:
          distribution: temurin
          java-version: '21'
      - uses: android-actions/setup-android@v4
        with:
          packages: platform-tools

      - run: ./gradlew :patches:test :patches:buildAndroid --no-daemon
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
