package defpackage;

/* JADX INFO: compiled from: r8-map-id-b2309a5993a3f14549aeb617bc4a78ecbec51e99a3efca387f8965087335ae2d */
/* JADX INFO: loaded from: classes.dex */
public abstract class av1 {
    public static final long A;
    public static final long B;
    public static final long C;
    public static final long D;
    public static final long E;
    public static final long F;
    public static final long G;
    public static final long H;
    public static final long I;
    public static final long J;
    public static final long K;
    public static final long L;
    public static final long M;
    public static final long N;
    public static final long O;
    public static final long P;
    public static final long Q;
    public static final long R;
    public static final long S;
    public static final long T;
    public static final long U;
    public static final long a;
    public static final long b;
    public static final long c;
    public static final long d;
    public static final long e;
    public static final long f;
    public static final long g;
    public static final long h;
    public static final long i;
    public static final long j;
    public static final long k;
    public static final long l;
    public static final long m;
    public static final long n;
    public static final long o;
    public static final long p;
    public static final long q;
    public static final long r;
    public static final long s;
    public static final long t;
    public static final long u;
    public static final long v;
    public static final long w;
    public static final long x;
    public static final long y;
    public static final long z;

    static {
        long j2 = g09.v;
        a = j2;
        b = g09.d;
        c = g09.e;
        d = g09.t;
        long j3 = g09.F;
        e = j3;
        f = g09.k;
        long j4 = g09.g;
        g = j4;
        h = g09.b;
        i = g09.a;
        j = g09.C;
        long j5 = g09.B;
        k = j5;
        l = j5;
        m = g09.D;
        n = g09.I;
        long j6 = g09.H;
        o = j6;
        p = j6;
        q = g09.J;
        r = j4;
        s = g09.w;
        t = g09.O;
        long j7 = g09.N;
        u = j7;
        v = j7;
        w = g09.Q;
        x = g09.x;
        y = g09.z;
        z = g09.E;
        long j8 = g09.G;
        A = j8;
        B = j8;
        C = j3;
        D = g09.f;
        E = g09.K;
        long j9 = g09.M;
        F = j9;
        G = j9;
        H = g09.L;
        I = j2;
        J = j2;
        K = g09.s;
        L = g09.r;
        M = g09.q;
        N = g09.u;
        O = g09.h;
        P = g09.p;
        Q = g09.A;
        R = g09.R;
        long j10 = g09.T;
        S = j10;
        T = j10;
        U = g09.S;
    }
}
