package defpackage;

/* JADX INFO: compiled from: r8-map-id-b2309a5993a3f14549aeb617bc4a78ecbec51e99a3efca387f8965087335ae2d */
/* JADX INFO: loaded from: classes.dex */
public abstract class axd {
    public static final long A;
    public static final long A0;
    public static final y75 A1;
    public static final long B;
    public static final d05 B0;
    public static final long B1;
    public static final long C;
    public static final y75 C0;
    public static final long C1;
    public static final d05 D;
    public static final long D0;
    public static final long D1;
    public static final y75 E;
    public static final long E0;
    public static final d05 E1;
    public static final long F;
    public static final long F0;
    public static final y75 F1;
    public static final long G;
    public static final d05 G0;
    public static final long G1;
    public static final long H;
    public static final y75 H0;
    public static final long H1;
    public static final d05 I;
    public static final long I0;
    public static final long I1;
    public static final y75 J;
    public static final long J0;
    public static final d05 J1;
    public static final long K;
    public static final long K0;
    public static final y75 K1;
    public static final long L;
    public static final d05 L0;
    public static final long L1;
    public static final long M;
    public static final y75 M0;
    public static final long M1;
    public static final d05 N;
    public static final long N0;
    public static final long N1;
    public static final y75 O;
    public static final long O0;
    public static final d05 O1;
    public static final long P;
    public static final long P0;
    public static final y75 P1;
    public static final long Q;
    public static final d05 Q0;
    public static final long Q1;
    public static final long R;
    public static final y75 R0;
    public static final long R1;
    public static final d05 S;
    public static final long S0;
    public static final long S1;
    public static final y75 T;
    public static final long T0;
    public static final d05 T1;
    public static final long U;
    public static final long U0;
    public static final long V;
    public static final d05 V0;
    public static final long W;
    public static final y75 W0;
    public static final d05 X;
    public static final long X0;
    public static final y75 Y;
    public static final long Y0;
    public static final long Z;
    public static final long Z0;
    public static final y75 a;
    public static final long a0;
    public static final d05 a1;
    public static final long b;
    public static final long b0;
    public static final y75 b1;
    public static final long c;
    public static final d05 c0;
    public static final long c1;
    public static final long d;
    public static final y75 d0;
    public static final long d1;
    public static final d05 e;
    public static final long e0;
    public static final long e1;
    public static final y75 f;
    public static final long f0;
    public static final d05 f1;
    public static final long g;
    public static final long g0;
    public static final y75 g1;
    public static final long h;
    public static final d05 h0;
    public static final long h1;
    public static final long i;
    public static final y75 i0;
    public static final long i1;
    public static final d05 j;
    public static final long j0;
    public static final long j1;
    public static final y75 k;
    public static final long k0;
    public static final d05 k1;
    public static final long l;
    public static final long l0;
    public static final y75 l1;
    public static final long m;
    public static final d05 m0;
    public static final long m1;
    public static final long n;
    public static final y75 n0;
    public static final long n1;
    public static final d05 o;
    public static final long o0;
    public static final long o1;
    public static final y75 p;
    public static final long p0;
    public static final d05 p1;
    public static final long q;
    public static final long q0;
    public static final y75 q1;
    public static final long r;
    public static final d05 r0;
    public static final long r1;
    public static final long s;
    public static final y75 s0;
    public static final long s1;
    public static final d05 t;
    public static final long t0;
    public static final long t1;
    public static final y75 u;
    public static final long u0;
    public static final d05 u1;
    public static final long v;
    public static final long v0;
    public static final y75 v1;
    public static final long w;
    public static final d05 w0;
    public static final long w1;
    public static final long x;
    public static final y75 x0;
    public static final long x1;
    public static final d05 y;
    public static final long y0;
    public static final long y1;
    public static final y75 z;
    public static final long z0;
    public static final d05 z1;

    static {
        d05 d05Var = hyd.a;
        y75 y75Var = az4.b;
        a = y75Var;
        b = en7.A(24.0d);
        c = en7.B(16);
        d = en7.A(0.5d);
        d05 d05Var2 = hyd.c;
        e = d05Var2;
        f = y75Var;
        g = en7.A(20.0d);
        h = en7.B(14);
        i = en7.A(0.2d);
        j = d05Var2;
        k = y75Var;
        l = en7.A(16.0d);
        m = en7.B(12);
        n = en7.A(0.4d);
        o = d05Var2;
        p = y75Var;
        q = en7.A(64.0d);
        r = en7.B(57);
        long jA = en7.A(0.2d);
        en7.m(jA);
        s = en7.M(-qkd.c(jA), jA & 1095216660480L);
        t = d05Var2;
        u = y75Var;
        v = en7.A(52.0d);
        w = en7.B(45);
        x = en7.A(0.0d);
        y = d05Var2;
        z = y75Var;
        A = en7.A(44.0d);
        B = en7.B(36);
        C = en7.A(0.0d);
        D = d05Var2;
        E = y75Var;
        F = en7.A(40.0d);
        G = en7.B(32);
        H = en7.A(0.0d);
        I = d05Var2;
        J = y75Var;
        K = en7.A(36.0d);
        L = en7.B(28);
        M = en7.A(0.0d);
        N = d05Var2;
        O = y75Var;
        P = en7.A(32.0d);
        Q = en7.B(24);
        R = en7.A(0.0d);
        S = d05Var2;
        T = y75Var;
        U = en7.A(20.0d);
        V = en7.B(14);
        W = en7.A(0.1d);
        d05 d05Var3 = hyd.b;
        X = d05Var3;
        Y = y75Var;
        Z = en7.A(16.0d);
        a0 = en7.B(12);
        b0 = en7.A(0.5d);
        c0 = d05Var3;
        d0 = y75Var;
        e0 = en7.A(16.0d);
        f0 = en7.B(11);
        g0 = en7.A(0.5d);
        h0 = d05Var3;
        i0 = y75Var;
        j0 = en7.A(28.0d);
        k0 = en7.B(22);
        l0 = en7.A(0.0d);
        m0 = d05Var2;
        n0 = y75Var;
        o0 = en7.A(24.0d);
        p0 = en7.B(16);
        q0 = en7.A(0.2d);
        r0 = d05Var3;
        s0 = y75Var;
        t0 = en7.A(20.0d);
        u0 = en7.B(14);
        v0 = en7.A(0.1d);
        w0 = d05Var3;
        x0 = y75Var;
        y0 = en7.A(24.0d);
        z0 = en7.B(16);
        A0 = en7.A(0.15d);
        B0 = d05Var3;
        C0 = y75Var;
        D0 = en7.A(20.0d);
        E0 = en7.B(14);
        F0 = en7.A(0.25d);
        G0 = d05Var3;
        H0 = y75Var;
        I0 = en7.A(16.0d);
        J0 = en7.B(12);
        K0 = en7.A(0.4d);
        L0 = d05Var3;
        M0 = y75Var;
        N0 = en7.A(64.0d);
        O0 = en7.B(57);
        P0 = en7.B(0);
        Q0 = d05Var3;
        R0 = y75Var;
        S0 = en7.A(52.0d);
        T0 = en7.B(45);
        U0 = en7.B(0);
        V0 = d05Var3;
        W0 = y75Var;
        X0 = en7.A(44.0d);
        Y0 = en7.B(36);
        Z0 = en7.B(0);
        a1 = d05Var3;
        b1 = y75Var;
        c1 = en7.A(40.0d);
        d1 = en7.B(32);
        e1 = en7.B(0);
        f1 = d05Var3;
        g1 = y75Var;
        h1 = en7.A(36.0d);
        i1 = en7.B(28);
        j1 = en7.B(0);
        k1 = d05Var3;
        l1 = y75Var;
        m1 = en7.A(32.0d);
        n1 = en7.B(24);
        o1 = en7.B(0);
        p1 = d05Var3;
        q1 = y75Var;
        r1 = en7.A(20.0d);
        s1 = en7.B(14);
        t1 = en7.A(0.1d);
        d05 d05Var4 = hyd.a;
        u1 = d05Var4;
        v1 = y75Var;
        w1 = en7.A(16.0d);
        x1 = en7.B(12);
        y1 = en7.A(0.5d);
        z1 = d05Var4;
        A1 = y75Var;
        B1 = en7.A(16.0d);
        C1 = en7.B(11);
        D1 = en7.A(0.5d);
        E1 = d05Var4;
        F1 = y75Var;
        G1 = en7.A(28.0d);
        H1 = en7.B(22);
        I1 = en7.B(0);
        J1 = d05Var3;
        K1 = y75Var;
        L1 = en7.A(24.0d);
        M1 = en7.B(16);
        N1 = en7.A(0.15d);
        O1 = d05Var4;
        P1 = y75Var;
        Q1 = en7.A(20.0d);
        R1 = en7.B(14);
        S1 = en7.A(0.1d);
        T1 = d05Var4;
    }
}
