package defpackage;

import com.drew.imaging.eps.ld.PdtluglzAX;
import com.drew.imaging.raf.yvq.AXoTRPEGKEve;
import com.drew.imaging.riff.pvS.uuLAxLN;
import pushnotifications.SY.eoLmc;
import sprig.g.Hq.fiHTiFJ;

/* JADX INFO: compiled from: r8-map-id-b2309a5993a3f14549aeb617bc4a78ecbec51e99a3efca387f8965087335ae2d */
/* JADX INFO: loaded from: classes2.dex */
public abstract class f01 {
    public static final d01 a;
    public static final e01 b;
    public static final d01 c;

    static {
        d01 d01Var = new d01();
        d01Var.put("uxdesign.cc", "user-experience-design-1");
        d01Var.put("ehandbook.com", "entrepreneur-s-handbook");
        d01Var.put("betterhumans.pub", "better-humans");
        d01Var.put("uxplanet.org", "ux-planet");
        d01Var.put("levelup.gitconnected.com", "gitconnected");
        d01Var.put(fiHTiFJ.oBxFMcTFja, "writing-cooperative");
        d01Var.put("betterprogramming.pub", "better-programming");
        d01Var.put("medium.muz.li", "muzli-design-inspiration");
        d01Var.put(eoLmc.EbSoiY, "prototypr");
        d01Var.put("netflixtechblog.com", "netflix-techblog");
        d01Var.put("bettermarketing.pub", "better-marketing");
        d01Var.put("javascript.plainenglish.io", "javascript-in-plain-english");
        d01Var.put("pub.towardsai.net", "towards-artificial-intelligence");
        d01Var.put("baos.pub", "books-are-our-superpower");
        d01Var.put("medium.datadriveninvestor.com", "datadriveninvestor");
        d01Var.put("codeburst.io", "codeburst");
        d01Var.put("generativeai.pub", "generative-ai");
        d01Var.put("ai.gopubby.com", "ai-advances");
        d01Var.put("python.plainenglish.io", "python-in-plain-english");
        d01Var.put("proandroiddev.com", "proandroiddev");
        d01Var.put("infosecwriteups.com", "bugbountywriteup");
        d01Var.put("blog.stackademic.com", "stackademic");
        d01Var.put("itnext.io", "itnext");
        d01Var.put("curiosityneverkilledthewriter.com", "curiosity-never-killed-the-writer");
        d01Var.put("www.thebelladonnacomedy.com", "thebelladonnacomedy");
        d01Var.put("code.likeagirl.io", "code-like-a-girl");
        d01Var.put("blog.flutter.dev", "flutter");
        d01Var.put("aws.plainenglish.io", "aws-in-plain-english");
        d01Var.put("medium.productcoalition.com", "managing-digital-products");
        d01Var.put("blog.angular.dev", "angular-blog");
        d01Var.put("medium.reinvent.net", "reinvent");
        d01Var.put("blog.dataengineerthings.org", "data-engineer-things");
        d01Var.put("500ish.com", "five-hundred-words");
        d01Var.put("ai.plainenglish.io", "ai-in-plain-english");
        d01Var.put("deepdives.in", "deep-dives");
        d01Var.put("www.cantorsparadise.com", "cantors-paradise");
        d01Var.put("sciencespectrumu.com", "science-spectrum");
        d01Var.put("aninjusticemag.com", "an-injustice");
        d01Var.put("becominghuman.ai", "becoming-human");
        d01Var.put("thequantasticjournal.com", PdtluglzAX.yIfg);
        d01Var.put("brasil.uxdesign.cc", "ux-user-experience-design-em-portugues");
        d01Var.put("blog.faceit.com", "faceit-blog");
        d01Var.put("fanfare.pub", "fan-fare");
        d01Var.put("blog.devgenius.io", "dev-genius");
        d01Var.put("learnaitoprofit.com", "writing-for-profit-with-ai");
        d01Var.put("blog.chatbotslife.com", "a-chatbots-life");
        d01Var.put("gointothestory.blcklst.com", "go-into-the-story");
        d01Var.put("themakingofamillionaire.com", "makingofamillionaire");
        d01Var.put("blog.devops.dev", "devops-dev");
        d01Var.put("blog.meteor.com", "official-meteor-blog");
        d01Var.put("medium.design", "design");
        d01Var.put("news.legendfantasywar.com", "legend-of-fantasy-war");
        d01Var.put("medium.engineering", "medium-eng");
        d01Var.put("faun.pub", "faun");
        d01Var.put("osintteam.blog", "the-first-digit");
        d01Var.put("www.towardsdeeplearning.com", "towards-deep-learning");
        d01Var.put("blog.trezor.io", "trezor-security-blog");
        d01Var.put("wire.insiderfinance.io", "insiderfinance");
        d01Var.put("blog.startupstash.com", "startup-stash");
        d01Var.put("eng.lyft.com", "lyft-engineering");
        d01Var.put("blog.uxuy.com", "uxuy-protocol");
        d01Var.put("open.nytimes.com", "timesopen");
        d01Var.put("archive.sia.tech", "sia-tech");
        d01Var.put("muddyum.net", "muddyum");
        d01Var.put("blog.jupyter.org", "jupyter-blog");
        d01Var.put("long.sweet.pub", "long-sweet-valuable");
        d01Var.put("towardsaws.com", "towards-aws");
        d01Var.put("hinged.press", "the-weekly-knob");
        d01Var.put("humanizing.tech", "humanizing-tech");
        d01Var.put("heartbeat.comet.ml", "cometheartbeat");
        d01Var.put("blog.matter-labs.io", "matter-labs");
        d01Var.put("awstip.com", "aws-tip");
        d01Var.put("medium.flutterdevs.com", "flutterdevs");
        d01Var.put("blog.mlreview.com", "mlreview");
        d01Var.put("medium.dave-bailey.com", "davesuperman");
        d01Var.put("blog.expo.dev", "the-exponent-log");
        d01Var.put("blog.blockswap.network", "crypto-capital-markets");
        d01Var.put("systemweakness.com", "system-weakness");
        d01Var.put("eidolon.pub", "eidolon");
        d01Var.put("towardsdev.com", uuLAxLN.ZHUhl);
        d01Var.put("blog.palantir.com", "palantir");
        d01Var.put("doublepulsar.com", "doublepulsar");
        d01Var.put("news.dvinlabs.com", "clubdvin");
        d01Var.put("blog.flipkart.tech", "flipkart-engineering");
        d01Var.put("digitalcurrencytraders.com", "digitalcurrencytraders");
        d01Var.put("short.sweet.pub", "short-sweet-valuable");
        d01Var.put("blog.austinstartups.com", "austin-startups");
        d01Var.put("www.eruditeelders.com", "the-erudite-elders");
        d01Var.put("faziapoesia.com.br", "fazia-poesia");
        d01Var.put("medium.tastyble.com", "tastyble");
        d01Var.put("news.gigco.com", "gigco");
        d01Var.put("blog.kaporcenter.org", "kapor-the-bridge");
        d01Var.put("medium.learningbyshipping.com", "learning-by-shipping");
        d01Var.put(AXoTRPEGKEve.kCUtJSRb, "the-hub-pub");
        d01Var.put("tech.instacart.com", "tech-at-instacart");
        d01Var.put("blog.venturemagazine.net", "venturehq");
        d01Var.put("rocknheavy.net", "rock-nheavy");
        d01Var.put("pub.aimind.so", "ai-mind-labs");
        d01Var.put("blog.tars.pro", "tars-protocol");
        d01Var.put("stories.platformdesigntoolkit.com", "platform-design-toolkit");
        a = d01Var;
        e01 e01Var = new e01();
        e01Var.add("help");
        e01Var.add("images");
        e01Var.add("jss");
        e01Var.add("link");
        e01Var.add("links");
        e01Var.add("click");
        b = e01Var;
        d01 d01Var2 = new d01();
        d01Var2.put("www", "");
        d01Var2.put("blog", "blog");
        d01Var2.put("about", "about");
        d01Var2.put("jobs", "jobs");
        d01Var2.put("policy", "policy");
        d01Var2.put("onezero", "one-zero");
        d01Var2.put("elemental", "elemental-by-medium");
        d01Var2.put("humanparts", "human-parts");
        d01Var2.put("forge", "forge");
        d01Var2.put("gen", "gen");
        d01Var2.put("marker", "marker");
        d01Var2.put("zora", "zora");
        d01Var2.put("level", "level");
        d01Var2.put("heated", "heated");
        d01Var2.put("tenderly", "tenderlymag");
        d01Var2.put("coronavirus", "coronavirus-medium");
        d01Var2.put("modus", "modus");
        d01Var2.put("debugger", "debugger-by-medium");
        d01Var2.put("momentum", "the-movement-blog");
        d01Var2.put("gay", "gay-magazine");
        d01Var2.put("futurehuman", "future-human");
        d01Var2.put("obama", "obama");
        d01Var2.put("themobilist", "themobilist");
        d01Var2.put("noteworthy", "medium-noteworthy");
        d01Var2.put("index", "index");
        d01Var2.put("stopasianhate", "stopasianhate");
        c = d01Var2;
    }
}
