package defpackage;

/* JADX INFO: compiled from: r8-map-id-b2309a5993a3f14549aeb617bc4a78ecbec51e99a3efca387f8965087335ae2d */
/* JADX INFO: loaded from: classes.dex */
public final class fv1 {
    public final long A;
    public final long B;
    public final long C;
    public final long D;
    public final long E;
    public final long F;
    public final long G;
    public final long H;
    public final long I;
    public final long J;
    public final long K;
    public final long L;
    public final long M;
    public final long N;
    public final long O;
    public final long P;
    public final long Q;
    public final long R;
    public final long S;
    public final long T;
    public final long U;
    public final long V;
    public g11 W;
    public g11 X;
    public g11 Y;
    public r61 Z;
    public final long a;
    public nl1 a0;
    public final long b;
    public nl1 b0;
    public final long c;
    public qod c0;
    public final long d;
    public cl1 d0;
    public final long e;
    public nv5 e0;
    public final long f;
    public qx7 f0;
    public final long g;
    public xb8 g0;
    public final long h;
    public isa h0;
    public final long i;
    public qfc i0;
    public final long j;
    public thd j0;
    public final long k;
    public final long l;
    public final long m;
    public final long n;
    public final long o;
    public final long p;
    public final long q;
    public final long r;
    public final long s;
    public final long t;
    public final long u;
    public final long v;
    public final long w;
    public final long x;
    public final long y;
    public final long z;

    public fv1(long j, long j2, long j3, long j4, long j5, long j6, long j7, long j8, long j9, long j10, long j11, long j12, long j13, long j14, long j15, long j16, long j17, long j18, long j19, long j20, long j21, long j22, long j23, long j24, long j25, long j26, long j27, long j28, long j29, long j30, long j31, long j32, long j33, long j34, long j35, long j36, long j37, long j38, long j39, long j40, long j41, long j42, long j43, long j44, long j45, long j46, long j47, long j48) {
        this.a = j;
        this.b = j2;
        this.c = j3;
        this.d = j4;
        this.e = j5;
        this.f = j6;
        this.g = j7;
        this.h = j8;
        this.i = j9;
        this.j = j10;
        this.k = j11;
        this.l = j12;
        this.m = j13;
        this.n = j14;
        this.o = j15;
        this.p = j16;
        this.q = j17;
        this.r = j18;
        this.s = j19;
        this.t = j20;
        this.u = j21;
        this.v = j22;
        this.w = j23;
        this.x = j24;
        this.y = j25;
        this.z = j26;
        this.A = j27;
        this.B = j28;
        this.C = j29;
        this.D = j30;
        this.E = j31;
        this.F = j32;
        this.G = j33;
        this.H = j34;
        this.I = j35;
        this.J = j36;
        this.K = j37;
        this.L = j38;
        this.M = j39;
        this.N = j40;
        this.O = j41;
        this.P = j42;
        this.Q = j43;
        this.R = j44;
        this.S = j45;
        this.T = j46;
        this.U = j47;
        this.V = j48;
    }

    public final String toString() {
        StringBuilder sb = new StringBuilder("ColorScheme(primary=");
        ev6.F(this.a, "onPrimary=", sb);
        ev6.F(this.b, "primaryContainer=", sb);
        ev6.F(this.c, "onPrimaryContainer=", sb);
        long j = this.d;
        ev6.F(j, "inversePrimary=", sb);
        ev6.F(this.e, "secondary=", sb);
        ev6.F(this.f, "onSecondary=", sb);
        ev6.F(this.g, "secondaryContainer=", sb);
        ev6.F(this.h, "onSecondaryContainer=", sb);
        ev6.F(this.i, "tertiary=", sb);
        ev6.F(this.j, "onTertiary=", sb);
        ev6.F(this.k, "tertiaryContainer=", sb);
        ev6.F(this.l, "onTertiaryContainer=", sb);
        ev6.F(this.m, "background=", sb);
        ev6.F(this.n, "onBackground=", sb);
        ev6.F(this.o, "surface=", sb);
        ev6.F(this.p, "onSurface=", sb);
        ev6.F(this.q, "surfaceVariant=", sb);
        ev6.F(this.r, "onSurfaceVariant=", sb);
        ev6.F(this.s, "surfaceTint=", sb);
        ev6.F(this.t, "inverseSurface=", sb);
        ev6.F(this.u, "inverseOnSurface=", sb);
        ev6.F(this.v, "error=", sb);
        ev6.F(this.w, "onError=", sb);
        ev6.F(this.x, "errorContainer=", sb);
        ev6.F(this.y, "onErrorContainer=", sb);
        ev6.F(this.z, "outline=", sb);
        ev6.F(this.A, "outlineVariant=", sb);
        ev6.F(this.B, "scrim=", sb);
        ev6.F(this.C, "surfaceBright=", sb);
        ev6.F(this.D, "surfaceDim=", sb);
        ev6.F(this.E, "surfaceContainer=", sb);
        ev6.F(this.F, "surfaceContainerHigh=", sb);
        ev6.F(this.G, "surfaceContainerHighest=", sb);
        ev6.F(this.H, "surfaceContainerLow=", sb);
        ev6.F(this.I, "surfaceContainerLowest=", sb);
        ev6.F(this.J, "primaryFixed=", sb);
        ev6.F(this.K, "primaryFixedDim=", sb);
        ev6.F(this.L, "onPrimaryFixed=", sb);
        ev6.F(j, "onPrimaryFixedVariant=", sb);
        ev6.F(this.N, "secondaryFixed=", sb);
        ev6.F(this.O, "secondaryFixedDim=", sb);
        ev6.F(this.P, "onSecondaryFixed=", sb);
        ev6.F(this.Q, "onSecondaryFixedVariant=", sb);
        ev6.F(this.R, "tertiaryFixed=", sb);
        ev6.F(this.S, "tertiaryFixedDim=", sb);
        ev6.F(this.T, "onTertiaryFixed=", sb);
        ev6.F(this.U, "onTertiaryFixedVariant=", sb);
        sb.append((Object) uu1.h(this.V));
        sb.append(')');
        return sb.toString();
    }
}
