package defpackage;

import com.datadog.android.core.yjCm.PqkdNGCEoxOKZk;
import java.util.LinkedHashMap;
import java.util.LinkedHashSet;
import java.util.Set;

/* JADX INFO: compiled from: r8-map-id-b2309a5993a3f14549aeb617bc4a78ecbec51e99a3efca387f8965087335ae2d */
/* JADX INFO: loaded from: classes5.dex */
public final class gnc {
    public static final mn1 A;
    public static final y05 a;
    public static final y05 b;
    public static final y05 c;
    public static final y05 d;
    public static final y05 e;
    public static final y05 f;
    public static final y05 g;
    public static final y05 h;
    public static final mn1 i;
    public static final mn1 j;
    public static final mn1 k;
    public static final mn1 l;
    public static final mn1 m;
    public static final mn1 n;
    public static final mn1 o;
    public static final mn1 p;
    public static final mn1 q;
    public static final mn1 r;
    public static final mn1 s;
    public static final mn1 t;
    public static final mn1 u;
    public static final Set v;
    public static final Set w;
    public static final mn1 x;
    public static final mn1 y;
    public static final mn1 z;

    static {
        y05 y05Var = new y05("kotlin");
        a = y05Var;
        y05 y05VarA = y05Var.a(n98.e("reflect"));
        b = y05VarA;
        y05Var.a(n98.e("experimental"));
        y05 y05VarA2 = y05Var.a(n98.e("collections"));
        c = y05VarA2;
        y05Var.a(n98.e("sequences"));
        y05 y05VarA3 = y05Var.a(n98.e("ranges"));
        d = y05VarA3;
        y05 y05VarA4 = y05Var.a(n98.e("jvm"));
        y05Var.a(n98.e("js"));
        y05Var.a(n98.e("annotations")).a(n98.e("jvm"));
        y05VarA4.a(n98.e("internal"));
        y05VarA4.a(n98.e("functions"));
        y05 y05VarA5 = y05Var.a(n98.e("annotation"));
        e = y05VarA5;
        y05 y05VarA6 = y05Var.a(n98.e("internal"));
        y05VarA6.a(n98.e("ir"));
        y05 y05VarA7 = y05Var.a(n98.e("coroutines"));
        f = y05VarA7;
        y05VarA7.a(n98.e("intrinsics"));
        g = y05Var.a(n98.e("enums"));
        y05Var.a(n98.e("contracts"));
        y05 y05VarA8 = y05Var.a(n98.e("concurrent")).a(n98.e("atomics"));
        h = y05VarA8;
        y05Var.a(n98.e("test"));
        y05Var.a(n98.e("text"));
        k80.S0(new y05[]{y05Var, y05VarA2, y05VarA3, y05VarA5});
        k80.S0(new y05[]{y05Var, y05VarA2, y05VarA3, y05VarA5, y05VarA, y05VarA6, y05VarA7, y05VarA8});
        qq7.j("Nothing");
        i = qq7.j("Unit");
        j = qq7.j("Any");
        k = qq7.j("Enum");
        qq7.j("Annotation");
        l = qq7.j("Array");
        mn1 mn1VarJ = qq7.j("Boolean");
        m = mn1VarJ;
        mn1 mn1VarJ2 = qq7.j("Char");
        mn1 mn1VarJ3 = qq7.j("Byte");
        mn1 mn1VarJ4 = qq7.j("Short");
        mn1 mn1VarJ5 = qq7.j("Int");
        n = mn1VarJ5;
        mn1 mn1VarJ6 = qq7.j("Long");
        o = mn1VarJ6;
        mn1 mn1VarJ7 = qq7.j("Float");
        mn1 mn1VarJ8 = qq7.j("Double");
        p = qq7.G(mn1VarJ3);
        q = qq7.G(mn1VarJ4);
        r = qq7.G(mn1VarJ5);
        s = qq7.G(mn1VarJ6);
        qq7.j("CharSequence");
        t = qq7.j("String");
        qq7.j("Throwable");
        qq7.j("Cloneable");
        qq7.z("KProperty");
        qq7.z("KMutableProperty");
        qq7.z("KProperty0");
        qq7.z("KMutableProperty0");
        qq7.z("KProperty1");
        qq7.z("KMutableProperty1");
        qq7.z("KProperty2");
        qq7.z("KMutableProperty2");
        u = qq7.z("KFunction");
        qq7.z("KClass");
        qq7.z("KCallable");
        qq7.z("KType");
        qq7.j("Comparable");
        qq7.j("Number");
        qq7.j("Function");
        Set setS0 = k80.S0(new mn1[]{mn1VarJ, mn1VarJ2, mn1VarJ3, mn1VarJ4, mn1VarJ5, mn1VarJ6, mn1VarJ7, mn1VarJ8});
        v = setS0;
        k80.S0(new mn1[]{mn1VarJ3, mn1VarJ4, mn1VarJ5, mn1VarJ6});
        Set set = setS0;
        int iP = ei7.P(cu1.k0(set, 10));
        if (iP < 16) {
            iP = 16;
        }
        LinkedHashMap linkedHashMap = new LinkedHashMap(iP);
        for (Object obj : set) {
            linkedHashMap.put(obj, qq7.w(((mn1) obj).f()));
        }
        qq7.r(linkedHashMap);
        Set setS02 = k80.S0(new mn1[]{p, q, r, s});
        w = setS02;
        Set set2 = setS02;
        int iP2 = ei7.P(cu1.k0(set2, 10));
        LinkedHashMap linkedHashMap2 = new LinkedHashMap(iP2 >= 16 ? iP2 : 16);
        for (Object obj2 : set2) {
            linkedHashMap2.put(obj2, qq7.w(((mn1) obj2).f()));
        }
        qq7.r(linkedHashMap2);
        Set set3 = v;
        Set set4 = w;
        LinkedHashSet linkedHashSetV = qo7.v(set3, set4);
        mn1 mn1Var = t;
        qo7.w(linkedHashSetV, mn1Var);
        y05 y05Var2 = f;
        n98 n98VarE = n98.e("Continuation");
        y05Var2.getClass();
        y05 y05Var3 = y05.c;
        sgg.b0(n98VarE).a.c();
        qq7.l("Iterator");
        qq7.l("Iterable");
        qq7.l("Collection");
        qq7.l("List");
        qq7.l("ListIterator");
        qq7.l("Set");
        mn1 mn1VarL = qq7.l("Map");
        qq7.l("AbstractMap");
        qq7.l("MutableIterator");
        qq7.l("CharIterator");
        qq7.l("MutableIterable");
        qq7.l("MutableCollection");
        x = qq7.l("MutableList");
        qq7.l("MutableListIterator");
        y = qq7.l("MutableSet");
        mn1 mn1VarL2 = qq7.l("MutableMap");
        z = mn1VarL2;
        mn1VarL.d(n98.e("Entry"));
        mn1VarL2.d(n98.e("MutableEntry"));
        qq7.j("Result");
        y05 y05Var4 = d;
        n98 n98VarE2 = n98.e("IntRange");
        y05Var4.getClass();
        sgg.b0(n98VarE2).a.c();
        sgg.b0(n98.e("LongRange")).a.c();
        sgg.b0(n98.e("CharRange")).a.c();
        y05 y05Var5 = e;
        n98 n98VarE3 = n98.e("AnnotationRetention");
        y05Var5.getClass();
        sgg.b0(n98VarE3).a.c();
        sgg.b0(n98.e("AnnotationTarget")).a.c();
        qq7.j("DeprecationLevel");
        A = new mn1(g, n98.e("EnumEntries"));
        mn1 mn1VarI = qq7.i("AtomicBoolean");
        mn1 mn1VarI2 = qq7.i("AtomicInt");
        mn1 mn1VarI3 = qq7.i("AtomicLong");
        qq7.i(PqkdNGCEoxOKZk.sGgRshVAbhm);
        f09 f09Var = new f09(m, mn1VarI);
        mn1 mn1Var2 = n;
        f09 f09Var2 = new f09(mn1Var2, mn1VarI2);
        mn1 mn1Var3 = o;
        ei7.Q(f09Var, f09Var2, new f09(mn1Var3, mn1VarI3));
        qq7.i("AtomicArray");
        ei7.Q(new f09(mn1Var2, qq7.i("AtomicIntArray")), new f09(mn1Var3, qq7.i("AtomicLongArray")));
        qo7.w(qo7.w(qo7.w(qo7.w(qo7.v(set3, set4), mn1Var), i), j), k);
    }
}
