package defpackage;

import com.medium.proto.model.PostQualityLabel;
import com.medium.proto.model.PostViewContent;
import com.medium.proto.model.PreviewContent;
import com.squareup.wire.Message;
import gen.model.Collection;
import gen.model.ImageMetadata;
import gen.model.LockedPostSource;
import gen.model.MediaResource;
import gen.model.Post;
import gen.model.PostCardType;
import gen.model.PostContentType;
import gen.model.PostLicense;
import gen.model.PostMongerRequestType;
import gen.model.PostPremiumTier;
import gen.model.PostResponseType;
import gen.model.PostSuggestionReason;
import gen.model.PostVirtuals;
import gen.model.PostVisibility;
import gen.model.ProxyPostType;
import gen.model.ResponseDistribution;
import gen.model.Sequence;
import gen.model.ShortformType;
import gen.model.Topic;
import gen.model.Unused;
import gen.model.User;

/* JADX INFO: compiled from: r8-map-id-b2309a5993a3f14549aeb617bc4a78ecbec51e99a3efca387f8965087335ae2d */
/* JADX INFO: loaded from: classes5.dex */
public final class jd9 extends Message.Builder {
    public Boolean A;
    public PostQualityLabel A0;
    public String B;
    public String B0;
    public String C;
    public String C0;
    public String D;
    public String D0;
    public User E;
    public String E0;
    public Boolean F;
    public ImageMetadata F0;
    public String G;
    public Long G0;
    public Post H;
    public Topic H0;
    public Long I;
    public String I0;
    public PostResponseType J;
    public Boolean J0;
    public ResponseDistribution K;
    public String K0;
    public Boolean L;
    public String L0;
    public Boolean M;
    public ProxyPostType M0;
    public String N;
    public Boolean N0;
    public Long O;
    public Boolean O0;
    public PostVisibility P;
    public String P0;
    public String Q;
    public String Q0;
    public PreviewContent R;
    public PostCardType R0;
    public PreviewContent S;
    public Boolean S0;
    public PostLicense T;
    public Boolean T0;
    public String U;
    public ShortformType U0;
    public String V;
    public Boolean V0;
    public String W;
    public Boolean W0;
    public String X;
    public Boolean X0;
    public MediaResource Y;
    public Boolean Y0;
    public Boolean Z;
    public Boolean Z0;
    public String a;
    public String a0;
    public String a1;
    public String b;
    public Boolean b0;
    public String b1;
    public String c;
    public Boolean c0;
    public String c1;
    public User d;
    public String d0;
    public String d1;
    public String e;
    public PostSuggestionReason e0;
    public String e1;
    public Collection f;
    public Boolean f0;
    public Integer f1;
    public String g;
    public Boolean g0;
    public Float g1;
    public Collection h;
    public Boolean h0;
    public Float h1;
    public String i;
    public Long i0;
    public PostContentType i1;
    public String j;
    public Boolean j0;
    public Boolean j1;
    public String k;
    public Long k0;
    public Boolean k1;
    public String l;
    public Boolean l0;
    public String l1;
    public String m;
    public String m0;
    public MediaResource m1;
    public Boolean n;
    public Float n0;
    public Unused n1;
    public Integer o;
    public String o0;
    public String o1;
    public Long p;
    public Sequence p0;
    public String p1;
    public Long q;
    public LockedPostSource q0;
    public PostPremiumTier q1;
    public Long r;
    public Boolean r0;
    public Boolean r1;
    public Long s;
    public Boolean s0;
    public Boolean s1;
    public Long t;
    public Long t0;
    public Long u;
    public Long u0;
    public Boolean v;
    public Long v0;
    public String w;
    public Integer w0;
    public String x;
    public Integer x0;
    public PostViewContent y;
    public Long y0;
    public PostVirtuals z;
    public PostMongerRequestType z0;

    @Override // com.squareup.wire.Message.Builder
    public final Message build() {
        return new Post(this.a, this.b, this.c, this.d, this.e, this.f, this.g, this.h, this.i, this.j, this.k, this.l, this.m, this.n, this.o, this.p, this.q, this.r, this.s, this.t, this.u, this.v, this.w, this.x, this.y, this.z, this.A, this.B, this.C, this.D, this.E, this.F, this.G, this.H, this.I, this.J, this.K, this.L, this.M, this.N, this.O, this.P, this.Q, this.R, this.S, this.T, this.U, this.V, this.W, this.X, this.Y, this.Z, this.a0, this.b0, this.c0, this.d0, this.e0, this.f0, this.g0, this.h0, this.i0, this.j0, this.k0, this.l0, this.m0, this.n0, this.o0, this.p0, this.q0, this.r0, this.s0, this.t0, this.u0, this.v0, this.w0, this.x0, this.y0, this.z0, this.A0, this.B0, this.C0, this.D0, this.E0, this.F0, this.G0, this.H0, this.I0, this.J0, this.K0, this.L0, this.M0, this.N0, this.O0, this.P0, this.Q0, this.R0, this.S0, this.T0, this.U0, this.V0, this.W0, this.X0, this.Y0, this.Z0, this.a1, this.b1, this.c1, this.d1, this.e1, this.f1, this.g1, this.h1, this.i1, this.j1, this.k1, this.l1, this.m1, this.n1, this.o1, this.p1, this.q1, this.r1, this.s1, buildUnknownFields());
    }
}
