package defpackage;

import j$.util.DesugarCollections;
import java.security.GeneralSecurityException;
import java.util.HashMap;

/* JADX INFO: compiled from: r8-map-id-b2309a5993a3f14549aeb617bc4a78ecbec51e99a3efca387f8965087335ae2d */
/* JADX INFO: loaded from: classes.dex */
public abstract class mdg {
    static {
        int i = mtg.a;
        try {
            a();
        } catch (GeneralSecurityException e) {
            throw new ExceptionInInitializerError(e);
        }
    }

    public static void a() {
        hhg hhgVar = hhg.b;
        hhgVar.a(q0g.f);
        hhgVar.b(q0g.g);
        hhgVar.a(q0g.h);
        hhgVar.b(q0g.i);
        l0g.a();
        gbg.a();
        if (oag.a()) {
            return;
        }
        cig cigVar = acg.a;
        mag magVar = mag.zza;
        if (!magVar.zza()) {
            ygf.l("Registering ECIES Hybrid Encryption is not supported in FIPS mode");
            return;
        }
        uhg uhgVar = geg.a;
        fhg fhgVar = fhg.b;
        fhgVar.h(geg.a);
        fhgVar.g(geg.b);
        fhgVar.f(geg.c);
        fhgVar.e(geg.d);
        fhgVar.f(geg.e);
        fhgVar.e(geg.f);
        chg chgVar = chg.b;
        HashMap map = new HashMap();
        ing ingVarB = jcg.b();
        fcg fcgVar = fcg.b;
        ingVarB.a = fcgVar;
        ecg ecgVar = ecg.d;
        ingVarB.b = ecgVar;
        hcg hcgVar = hcg.c;
        ingVarB.c = hcgVar;
        gcg gcgVar = gcg.b;
        ingVarB.e = gcgVar;
        o2b o2bVarB = g2g.b();
        o2bVarB.R();
        o2bVarB.W(16);
        o2bVarB.Y();
        d2g d2gVar = d2g.e;
        o2bVarB.e = d2gVar;
        ingVarB.m(o2bVarB.P());
        map.put("ECIES_P256_HKDF_HMAC_SHA256_AES128_GCM", ingVarB.j());
        ing ingVarB2 = jcg.b();
        ingVarB2.a = fcgVar;
        ingVarB2.b = ecgVar;
        ingVarB2.c = hcgVar;
        gcg gcgVar2 = gcg.d;
        ingVarB2.e = gcgVar2;
        o2b o2bVarB2 = g2g.b();
        o2bVarB2.R();
        o2bVarB2.W(16);
        o2bVarB2.Y();
        o2bVarB2.e = d2gVar;
        ingVarB2.m(o2bVarB2.P());
        map.put("ECIES_P256_HKDF_HMAC_SHA256_AES128_GCM_RAW", ingVarB2.j());
        ing ingVarB3 = jcg.b();
        ingVarB3.a = fcgVar;
        ingVarB3.b = ecgVar;
        hcg hcgVar2 = hcg.b;
        ingVarB3.c = hcgVar2;
        ingVarB3.e = gcgVar;
        o2b o2bVarB3 = g2g.b();
        o2bVarB3.R();
        o2bVarB3.W(16);
        o2bVarB3.Y();
        o2bVarB3.e = d2gVar;
        ingVarB3.m(o2bVarB3.P());
        map.put("ECIES_P256_COMPRESSED_HKDF_HMAC_SHA256_AES128_GCM", ingVarB3.j());
        ing ingVarB4 = jcg.b();
        ingVarB4.a = fcgVar;
        ingVarB4.b = ecgVar;
        ingVarB4.c = hcgVar2;
        ingVarB4.e = gcgVar2;
        o2b o2bVarB4 = g2g.b();
        o2bVarB4.R();
        o2bVarB4.W(16);
        o2bVarB4.Y();
        o2bVarB4.e = d2gVar;
        ingVarB4.m(o2bVarB4.P());
        map.put("ECIES_P256_COMPRESSED_HKDF_HMAC_SHA256_AES128_GCM_RAW", ingVarB4.j());
        ing ingVarB5 = jcg.b();
        ingVarB5.a = fcgVar;
        ingVarB5.b = ecgVar;
        ingVarB5.c = hcgVar2;
        ingVarB5.e = gcgVar2;
        o2b o2bVarB5 = g2g.b();
        o2bVarB5.R();
        o2bVarB5.W(16);
        o2bVarB5.Y();
        o2bVarB5.e = d2gVar;
        ingVarB5.m(o2bVarB5.P());
        map.put("ECIES_P256_HKDF_HMAC_SHA256_AES128_GCM_COMPRESSED_WITHOUT_PREFIX", ingVarB5.j());
        ing ingVarB6 = jcg.b();
        ingVarB6.a = fcgVar;
        ingVarB6.b = ecgVar;
        ingVarB6.c = hcgVar;
        ingVarB6.e = gcgVar;
        ing ingVarB7 = f1g.b();
        ingVarB7.l(16);
        ingVarB7.n(32);
        ingVarB7.p(16);
        ingVarB7.o(16);
        e1g e1gVar = e1g.e;
        ingVarB7.d = e1gVar;
        d1g d1gVar = d1g.e;
        ingVarB7.e = d1gVar;
        ingVarB6.m(ingVarB7.i());
        map.put("ECIES_P256_HKDF_HMAC_SHA256_AES128_CTR_HMAC_SHA256", ingVarB6.j());
        ing ingVarB8 = jcg.b();
        ingVarB8.a = fcgVar;
        ingVarB8.b = ecgVar;
        ingVarB8.c = hcgVar;
        ingVarB8.e = gcgVar2;
        ing ingVarB9 = f1g.b();
        ingVarB9.l(16);
        ingVarB9.n(32);
        ingVarB9.p(16);
        ingVarB9.o(16);
        ingVarB9.d = e1gVar;
        ingVarB9.e = d1gVar;
        ingVarB8.m(ingVarB9.i());
        map.put("ECIES_P256_HKDF_HMAC_SHA256_AES128_CTR_HMAC_SHA256_RAW", ingVarB8.j());
        ing ingVarB10 = jcg.b();
        ingVarB10.a = fcgVar;
        ingVarB10.b = ecgVar;
        ingVarB10.c = hcgVar2;
        ingVarB10.e = gcgVar;
        ing ingVarB11 = f1g.b();
        ingVarB11.l(16);
        ingVarB11.n(32);
        ingVarB11.p(16);
        ingVarB11.o(16);
        ingVarB11.d = e1gVar;
        ingVarB11.e = d1gVar;
        ingVarB10.m(ingVarB11.i());
        map.put("ECIES_P256_COMPRESSED_HKDF_HMAC_SHA256_AES128_CTR_HMAC_SHA256", ingVarB10.j());
        ing ingVarB12 = jcg.b();
        ingVarB12.a = fcgVar;
        ingVarB12.b = ecgVar;
        ingVarB12.c = hcgVar2;
        ingVarB12.e = gcgVar2;
        ing ingVarB13 = f1g.b();
        ingVarB13.l(16);
        ingVarB13.n(32);
        ingVarB13.p(16);
        ingVarB13.o(16);
        ingVarB13.d = e1gVar;
        ingVarB13.e = d1gVar;
        ingVarB12.m(ingVarB13.i());
        map.put("ECIES_P256_COMPRESSED_HKDF_HMAC_SHA256_AES128_CTR_HMAC_SHA256_RAW", ingVarB12.j());
        chgVar.b(DesugarCollections.unmodifiableMap(map));
        hhgVar.b(acg.a);
        hhgVar.b(acg.b);
        zgg zggVar = zgg.b;
        zggVar.a(acg.e, jcg.class);
        ufg ufgVar = ufg.d;
        ufgVar.b(acg.c, true);
        ufgVar.b(acg.d, false);
        cig cigVar2 = ueg.a;
        if (!magVar.zza()) {
            ygf.l("Registering HPKE Hybrid Encryption is not supported in FIPS mode");
            return;
        }
        fhgVar.h(cdg.a);
        fhgVar.g(cdg.b);
        fhgVar.f(cdg.c);
        fhgVar.e(cdg.d);
        fhgVar.f(cdg.e);
        fhgVar.e(cdg.f);
        HashMap map2 = new HashMap();
        o2b o2bVarB6 = scg.b();
        qcg qcgVar = qcg.b;
        o2bVarB6.e = qcgVar;
        rcg rcgVar = rcg.g;
        o2bVarB6.b = rcgVar;
        pcg pcgVar = pcg.d;
        o2bVarB6.c = pcgVar;
        ocg ocgVar = ocg.d;
        o2bVarB6.d = ocgVar;
        map2.put("DHKEM_X25519_HKDF_SHA256_HKDF_SHA256_AES_128_GCM", o2bVarB6.Q());
        o2b o2bVarB7 = scg.b();
        qcg qcgVar2 = qcg.d;
        o2bVarB7.e = qcgVar2;
        o2bVarB7.b = rcgVar;
        o2bVarB7.c = pcgVar;
        o2bVarB7.d = ocgVar;
        map2.put("DHKEM_X25519_HKDF_SHA256_HKDF_SHA256_AES_128_GCM_RAW", o2bVarB7.Q());
        o2b o2bVarB8 = scg.b();
        o2bVarB8.e = qcgVar;
        o2bVarB8.b = rcgVar;
        o2bVarB8.c = pcgVar;
        ocg ocgVar2 = ocg.e;
        o2bVarB8.d = ocgVar2;
        map2.put("DHKEM_X25519_HKDF_SHA256_HKDF_SHA256_AES_256_GCM", o2bVarB8.Q());
        o2b o2bVarB9 = scg.b();
        o2bVarB9.e = qcgVar2;
        o2bVarB9.b = rcgVar;
        o2bVarB9.c = pcgVar;
        o2bVarB9.d = ocgVar2;
        map2.put("DHKEM_X25519_HKDF_SHA256_HKDF_SHA256_AES_256_GCM_RAW", o2bVarB9.Q());
        o2b o2bVarB10 = scg.b();
        o2bVarB10.e = qcgVar;
        o2bVarB10.b = rcgVar;
        o2bVarB10.c = pcgVar;
        ocg ocgVar3 = ocg.f;
        o2bVarB10.d = ocgVar3;
        map2.put("DHKEM_X25519_HKDF_SHA256_HKDF_SHA256_CHACHA20_POLY1305", o2bVarB10.Q());
        o2b o2bVarB11 = scg.b();
        o2bVarB11.e = qcgVar2;
        o2bVarB11.b = rcgVar;
        o2bVarB11.c = pcgVar;
        o2bVarB11.d = ocgVar3;
        map2.put("DHKEM_X25519_HKDF_SHA256_HKDF_SHA256_CHACHA20_POLY1305_RAW", o2bVarB11.Q());
        o2b o2bVarB12 = scg.b();
        o2bVarB12.e = qcgVar;
        rcg rcgVar2 = rcg.d;
        o2bVarB12.b = rcgVar2;
        o2bVarB12.c = pcgVar;
        o2bVarB12.d = ocgVar;
        map2.put("DHKEM_P256_HKDF_SHA256_HKDF_SHA256_AES_128_GCM", o2bVarB12.Q());
        o2b o2bVarB13 = scg.b();
        o2bVarB13.e = qcgVar2;
        o2bVarB13.b = rcgVar2;
        o2bVarB13.c = pcgVar;
        o2bVarB13.d = ocgVar;
        map2.put("DHKEM_P256_HKDF_SHA256_HKDF_SHA256_AES_128_GCM_RAW", o2bVarB13.Q());
        o2b o2bVarB14 = scg.b();
        o2bVarB14.e = qcgVar;
        o2bVarB14.b = rcgVar2;
        o2bVarB14.c = pcgVar;
        o2bVarB14.d = ocgVar2;
        map2.put("DHKEM_P256_HKDF_SHA256_HKDF_SHA256_AES_256_GCM", o2bVarB14.Q());
        o2b o2bVarB15 = scg.b();
        o2bVarB15.e = qcgVar2;
        o2bVarB15.b = rcgVar2;
        o2bVarB15.c = pcgVar;
        o2bVarB15.d = ocgVar2;
        map2.put("DHKEM_P256_HKDF_SHA256_HKDF_SHA256_AES_256_GCM_RAW", o2bVarB15.Q());
        o2b o2bVarB16 = scg.b();
        o2bVarB16.e = qcgVar;
        rcg rcgVar3 = rcg.e;
        o2bVarB16.b = rcgVar3;
        pcg pcgVar2 = pcg.e;
        o2bVarB16.c = pcgVar2;
        o2bVarB16.d = ocgVar;
        map2.put("DHKEM_P384_HKDF_SHA384_HKDF_SHA384_AES_128_GCM", o2bVarB16.Q());
        o2b o2bVarB17 = scg.b();
        o2bVarB17.e = qcgVar2;
        o2bVarB17.b = rcgVar3;
        o2bVarB17.c = pcgVar2;
        o2bVarB17.d = ocgVar;
        map2.put("DHKEM_P384_HKDF_SHA384_HKDF_SHA384_AES_128_GCM_RAW", o2bVarB17.Q());
        o2b o2bVarB18 = scg.b();
        o2bVarB18.e = qcgVar;
        o2bVarB18.b = rcgVar3;
        o2bVarB18.c = pcgVar2;
        o2bVarB18.d = ocgVar2;
        map2.put("DHKEM_P384_HKDF_SHA384_HKDF_SHA384_AES_256_GCM", o2bVarB18.Q());
        o2b o2bVarB19 = scg.b();
        o2bVarB19.e = qcgVar2;
        o2bVarB19.b = rcgVar3;
        o2bVarB19.c = pcgVar2;
        o2bVarB19.d = ocgVar2;
        map2.put("DHKEM_P384_HKDF_SHA384_HKDF_SHA384_AES_256_GCM_RAW", o2bVarB19.Q());
        o2b o2bVarB20 = scg.b();
        o2bVarB20.e = qcgVar;
        rcg rcgVar4 = rcg.f;
        o2bVarB20.b = rcgVar4;
        pcg pcgVar3 = pcg.f;
        o2bVarB20.c = pcgVar3;
        o2bVarB20.d = ocgVar;
        map2.put("DHKEM_P521_HKDF_SHA512_HKDF_SHA512_AES_128_GCM", o2bVarB20.Q());
        o2b o2bVarB21 = scg.b();
        o2bVarB21.e = qcgVar2;
        o2bVarB21.b = rcgVar4;
        o2bVarB21.c = pcgVar3;
        o2bVarB21.d = ocgVar;
        map2.put("DHKEM_P521_HKDF_SHA512_HKDF_SHA512_AES_128_GCM_RAW", o2bVarB21.Q());
        o2b o2bVarB22 = scg.b();
        o2bVarB22.e = qcgVar;
        o2bVarB22.b = rcgVar4;
        o2bVarB22.c = pcgVar3;
        o2bVarB22.d = ocgVar2;
        map2.put("DHKEM_P521_HKDF_SHA512_HKDF_SHA512_AES_256_GCM", o2bVarB22.Q());
        o2b o2bVarB23 = scg.b();
        o2bVarB23.e = qcgVar2;
        o2bVarB23.b = rcgVar4;
        o2bVarB23.c = pcgVar3;
        o2bVarB23.d = ocgVar2;
        map2.put("DHKEM_P521_HKDF_SHA512_HKDF_SHA512_AES_256_GCM_RAW", o2bVarB23.Q());
        chgVar.b(DesugarCollections.unmodifiableMap(map2));
        hhgVar.b(ueg.a);
        hhgVar.b(ueg.b);
        zggVar.a(ueg.e, scg.class);
        ufgVar.b(ueg.c, true);
        ufgVar.b(ueg.d, false);
    }
}
