package defpackage;

import android.R;

/* JADX INFO: loaded from: classes.dex */
public abstract class ura {
    public static final int[] a = {R.attr.maxWidth, R.attr.maxHeight, R.attr.elevation, com.medium.reader.R.attr.backgroundTint, com.medium.reader.R.attr.behavior_autoExpandOnRequestChildRectangleOffscreen, com.medium.reader.R.attr.behavior_draggable, com.medium.reader.R.attr.behavior_draggableOnNestedScroll, com.medium.reader.R.attr.behavior_expandedOffset, com.medium.reader.R.attr.behavior_fitToContents, com.medium.reader.R.attr.behavior_halfExpandedRatio, com.medium.reader.R.attr.behavior_hideable, com.medium.reader.R.attr.behavior_multipleScrollingChildrenSupported, com.medium.reader.R.attr.behavior_peekHeight, com.medium.reader.R.attr.behavior_saveFlags, com.medium.reader.R.attr.behavior_significantVelocityThreshold, com.medium.reader.R.attr.behavior_skipCollapsed, com.medium.reader.R.attr.gestureInsetBottomIgnored, com.medium.reader.R.attr.marginLeftSystemWindowInsets, com.medium.reader.R.attr.marginRightSystemWindowInsets, com.medium.reader.R.attr.marginTopSystemWindowInsets, com.medium.reader.R.attr.paddingBottomSystemWindowInsets, com.medium.reader.R.attr.paddingLeftSystemWindowInsets, com.medium.reader.R.attr.paddingRightSystemWindowInsets, com.medium.reader.R.attr.paddingTopSystemWindowInsets, com.medium.reader.R.attr.shapeAppearance, com.medium.reader.R.attr.shapeAppearanceOverlay, com.medium.reader.R.attr.shouldRemoveExpandedCorners};
    public static final int[] b = {com.medium.reader.R.attr.carousel_alignment, com.medium.reader.R.attr.carousel_backwardTransition, com.medium.reader.R.attr.carousel_emptyViewsBehavior, com.medium.reader.R.attr.carousel_firstView, com.medium.reader.R.attr.carousel_forwardTransition, com.medium.reader.R.attr.carousel_infinite, com.medium.reader.R.attr.carousel_nextState, com.medium.reader.R.attr.carousel_previousState, com.medium.reader.R.attr.carousel_touchUpMode, com.medium.reader.R.attr.carousel_touchUp_dampeningFactor, com.medium.reader.R.attr.carousel_touchUp_velocityThreshold};
    public static final int[] c = {com.medium.reader.R.attr.behavior_autoHide, com.medium.reader.R.attr.behavior_autoShrink};
    public static final int[] d = {com.medium.reader.R.attr.behavior_autoHide};
    public static final int[] e = {com.medium.reader.R.attr.focusRingsEnabled, com.medium.reader.R.attr.focusRingsInnerStrokeColor, com.medium.reader.R.attr.focusRingsInnerStrokeInset, com.medium.reader.R.attr.focusRingsInnerStrokeWidth, com.medium.reader.R.attr.focusRingsInset, com.medium.reader.R.attr.focusRingsOuterStrokeColor, com.medium.reader.R.attr.focusRingsOuterStrokeWidth, com.medium.reader.R.attr.focusRingsRadius, com.medium.reader.R.attr.focusRingsShapeAppearance};
    public static final int[] f = {R.attr.inputType, R.attr.popupElevation, com.medium.reader.R.attr.dropDownBackgroundTint, com.medium.reader.R.attr.simpleItemLayout, com.medium.reader.R.attr.simpleItemSelectedColor, com.medium.reader.R.attr.simpleItemSelectedRippleColor, com.medium.reader.R.attr.simpleItems};
    public static final int[] g = {R.attr.background, R.attr.checked, R.attr.insetLeft, R.attr.insetRight, R.attr.insetTop, R.attr.insetBottom, R.attr.checkable, com.medium.reader.R.attr.backgroundTint, com.medium.reader.R.attr.backgroundTintMode, com.medium.reader.R.attr.cornerRadius, com.medium.reader.R.attr.elevation, com.medium.reader.R.attr.icon, com.medium.reader.R.attr.iconGravity, com.medium.reader.R.attr.iconPadding, com.medium.reader.R.attr.iconSize, com.medium.reader.R.attr.iconTint, com.medium.reader.R.attr.iconTintMode, com.medium.reader.R.attr.opticalCenterEnabled, com.medium.reader.R.attr.rippleColor, com.medium.reader.R.attr.secondaryIcon, com.medium.reader.R.attr.secondaryIconGravity, com.medium.reader.R.attr.secondaryIconTint, com.medium.reader.R.attr.secondaryIconTintMode, com.medium.reader.R.attr.shapeAppearance, com.medium.reader.R.attr.shapeAppearanceOverlay, com.medium.reader.R.attr.strokeColor, com.medium.reader.R.attr.strokeWidth, com.medium.reader.R.attr.toggleCheckedStateOnClick};
    public static final int[] h = {R.attr.button, com.medium.reader.R.attr.buttonCompat, com.medium.reader.R.attr.buttonIcon, com.medium.reader.R.attr.buttonIconTint, com.medium.reader.R.attr.buttonIconTintMode, com.medium.reader.R.attr.buttonTint, com.medium.reader.R.attr.centerIfNoTextEnabled, com.medium.reader.R.attr.checkedState, com.medium.reader.R.attr.errorAccessibilityLabel, com.medium.reader.R.attr.errorShown, com.medium.reader.R.attr.rippleColor, com.medium.reader.R.attr.useMaterialThemeColors};
    public static final int[] i = {com.medium.reader.R.attr.buttonTint, com.medium.reader.R.attr.rippleColor, com.medium.reader.R.attr.useMaterialThemeColors};
    public static final int[] j = {com.medium.reader.R.attr.shapeAppearance, com.medium.reader.R.attr.shapeAppearanceOverlay};
    public static final int[] k = {com.medium.reader.R.attr.damping, com.medium.reader.R.attr.stiffness};
    public static final int[] l = {R.attr.letterSpacing, R.attr.fontVariationSettings, R.attr.lineHeight, com.medium.reader.R.attr.fontVariationSettings, com.medium.reader.R.attr.lineHeight};
    public static final int[] m = {R.attr.textAppearance, R.attr.lineHeight, com.medium.reader.R.attr.lineHeight};
    public static final int[] n = {com.medium.reader.R.attr.behavior_overlapTop};
    public static final int[] o = {com.medium.reader.R.attr.cornerFamily, com.medium.reader.R.attr.cornerFamilyBottomLeft, com.medium.reader.R.attr.cornerFamilyBottomRight, com.medium.reader.R.attr.cornerFamilyTopLeft, com.medium.reader.R.attr.cornerFamilyTopRight, com.medium.reader.R.attr.cornerSize, com.medium.reader.R.attr.cornerSizeBottomLeft, com.medium.reader.R.attr.cornerSizeBottomRight, com.medium.reader.R.attr.cornerSizeTopLeft, com.medium.reader.R.attr.cornerSizeTopRight};
    public static final int[] p = {R.attr.maxWidth, R.attr.maxHeight, R.attr.elevation, com.medium.reader.R.attr.backgroundTint, com.medium.reader.R.attr.behavior_draggable, com.medium.reader.R.attr.coplanarSiblingViewId, com.medium.reader.R.attr.shapeAppearance, com.medium.reader.R.attr.shapeAppearanceOverlay};
    public static final int[] q = {R.attr.maxWidth, com.medium.reader.R.attr.actionTextColorAlpha, com.medium.reader.R.attr.animationMode, com.medium.reader.R.attr.backgroundOverlayColorAlpha, com.medium.reader.R.attr.backgroundTint, com.medium.reader.R.attr.backgroundTintMode, com.medium.reader.R.attr.elevation, com.medium.reader.R.attr.maxActionInlineWidth, com.medium.reader.R.attr.shapeAppearance, com.medium.reader.R.attr.shapeAppearanceOverlay};
    public static final int[] r = {R.attr.textAppearance, com.medium.reader.R.attr.enforceMaterialTheme, com.medium.reader.R.attr.enforceTextAppearance};
}
