package defpackage;

/* JADX INFO: compiled from: r8-map-id-b2309a5993a3f14549aeb617bc4a78ecbec51e99a3efca387f8965087335ae2d */
/* JADX INFO: loaded from: classes.dex */
public abstract class xu1 {
    public static final long A;
    public static final long B;
    public static final long C;
    public static final long D;
    public static final long E;
    public static final long F;
    public static final long G;
    public static final long H;
    public static final long I;
    public static final long a;
    public static final long b;
    public static final long c;
    public static final long d;
    public static final long e;
    public static final long f;
    public static final long g;
    public static final long h;
    public static final long i;
    public static final long j;
    public static final long k;
    public static final long l;
    public static final long m;
    public static final long n;
    public static final long o;
    public static final long p;
    public static final long q;
    public static final long r;
    public static final long s;
    public static final long t;
    public static final long u;
    public static final long v;
    public static final long w;
    public static final long x;
    public static final long y;
    public static final long z;

    static {
        long j2 = g09.o;
        a = g09.c;
        b = g09.k;
        c = g09.q;
        d = g09.e;
        long j3 = g09.G;
        e = j3;
        f = g09.B;
        long j4 = g09.D;
        g = j4;
        long j5 = g09.M;
        h = j5;
        i = g09.H;
        long j6 = g09.J;
        j = j6;
        k = g09.z;
        l = g09.P;
        long j7 = g09.T;
        m = j7;
        n = g09.N;
        long j8 = g09.Q;
        o = j8;
        p = g09.y;
        long j9 = g09.w;
        q = j9;
        long j10 = g09.F;
        r = j4;
        s = j3;
        t = j10;
        u = g09.f;
        long j11 = g09.L;
        v = j6;
        w = j5;
        x = j11;
        y = g09.m;
        z = g09.i;
        A = g09.j;
        B = g09.l;
        C = g09.g;
        D = g09.n;
        E = j2;
        F = j9;
        long j12 = g09.S;
        G = j8;
        H = j7;
        I = j12;
    }
}
