package app.ubisoftpop.patches.il2cpp

import app.morphe.patcher.patch.rawResourcePatch
import app.ubisoftpop.patches.shared.Constants.COMPATIBILITY_POP

/**
 * Embeds the compiled unlock engine into the APK as a native library.
 *
 * The engine (built from analysis/com.ubisoft.princeofpersia.thelostcrown/ndk/
 * via nix + NDK r27, bytes generated by gen_so_bytes.py) is a ~12 KB ARM64
 * companion library that:
 *   1. sleeps 30 s (packed libil2cpp.so must not be touched before Unity's
 *      native init — earlier attempts crashed with SIGSEGV 0x132),
 *   2. resolves the il2cpp exports and polls for a valid domain,
 *   3. scans EVERY assembly for Alkawa.Engine.IAPManager (never filter by
 *      image name — the class is NOT in Alkawa.Gameplay.dll),
 *   4. invokes the game's own dev cheat CheatBuyFullGame(),
 *      falling back to get_Instance() + ConfirmFullGamePurchase() /
 *      ClaimFullGame(),
 *   5. verifies via get_HasFullGamePurchased.
 */
@Suppress("unused")
val fullGameUnlockPatch = rawResourcePatch(
    name = "Prince of Persia: Full Game Unlock Engine",
    description = "Adds a tiny hidden helper into the game. About 30 seconds after the game starts, it presses the game's own secret 'unlock full game' button — no purchases needed.",
    default = true
) {
    compatibleWith(COMPATIBILITY_POP)

    execute {
        val soFile = get("lib/arm64-v8a/libPopFullGame.so", true)
        soFile.writeBytes(PopFullGameSoBytes.bytes())
    }
}
