package com.android.billingclient.api;

import com.android.billingclient.api.BillingResult;
import defpackage.wgd;

/* JADX INFO: compiled from: r8-map-id-b2309a5993a3f14549aeb617bc4a78ecbec51e99a3efca387f8965087335ae2d */
/* JADX INFO: loaded from: classes.dex */
public abstract class n {
    public static final BillingResult A;
    public static final BillingResult B;
    public static final BillingResult C;
    public static final BillingResult D;
    public static final BillingResult E;
    public static final BillingResult F;
    public static final BillingResult G;
    public static final BillingResult H;
    public static final BillingResult I;
    public static final BillingResult a;
    public static final BillingResult b;
    public static final BillingResult c;
    public static final BillingResult d;
    public static final BillingResult e;
    public static final BillingResult f;
    public static final BillingResult g;
    public static final BillingResult h;
    public static final BillingResult i;
    public static final BillingResult j;
    public static final BillingResult k;
    public static final BillingResult l;
    public static final BillingResult m;
    public static final BillingResult n;
    public static final BillingResult o;
    public static final BillingResult p;
    public static final BillingResult q;
    public static final BillingResult r;
    public static final BillingResult s;
    public static final BillingResult t;
    public static final BillingResult u;
    public static final BillingResult v;
    public static final BillingResult w;
    public static final BillingResult x;
    public static final BillingResult y;
    public static final BillingResult z;

    static {
        BillingResult.Builder builderNewBuilder = BillingResult.newBuilder();
        builderNewBuilder.setResponseCode(3);
        builderNewBuilder.setDebugMessage("Google Play In-app Billing API version is less than 3");
        builderNewBuilder.build();
        BillingResult.Builder builderNewBuilder2 = BillingResult.newBuilder();
        builderNewBuilder2.setResponseCode(3);
        builderNewBuilder2.setDebugMessage("Google Play In-app Billing API version is less than 9");
        a = builderNewBuilder2.build();
        b = wgd.s(3, "Billing service unavailable on device.");
        c = wgd.s(2, "Billing service unavailable on device.");
        d = wgd.s(5, "Client is already in the process of connecting to billing service.");
        BillingResult.Builder builderNewBuilder3 = BillingResult.newBuilder();
        builderNewBuilder3.setResponseCode(5);
        builderNewBuilder3.setDebugMessage("The list of SKUs can't be empty.");
        builderNewBuilder3.build();
        BillingResult.Builder builderNewBuilder4 = BillingResult.newBuilder();
        builderNewBuilder4.setResponseCode(5);
        builderNewBuilder4.setDebugMessage("SKU type can't be empty.");
        builderNewBuilder4.build();
        BillingResult.Builder builderNewBuilder5 = BillingResult.newBuilder();
        builderNewBuilder5.setResponseCode(5);
        builderNewBuilder5.setDebugMessage("Product type can't be empty.");
        e = builderNewBuilder5.build();
        f = wgd.s(-2, "Client does not support extra params.");
        g = wgd.s(5, "Invalid purchase token.");
        h = wgd.s(6, "An internal error occurred.");
        BillingResult.Builder builderNewBuilder6 = BillingResult.newBuilder();
        builderNewBuilder6.setResponseCode(5);
        builderNewBuilder6.setDebugMessage("SKU can't be null.");
        builderNewBuilder6.build();
        BillingResult.Builder builderNewBuilder7 = BillingResult.newBuilder();
        builderNewBuilder7.setResponseCode(0);
        i = builderNewBuilder7.build();
        j = wgd.s(-1, "Service connection is disconnected.");
        k = wgd.s(2, "Timeout communicating with service.");
        l = wgd.s(-2, "Client does not support subscriptions.");
        m = wgd.s(-2, "Client does not support subscriptions update.");
        BillingResult.Builder builderNewBuilder8 = BillingResult.newBuilder();
        builderNewBuilder8.setResponseCode(-2);
        builderNewBuilder8.setDebugMessage("Client does not support get purchase history.");
        builderNewBuilder8.build();
        BillingResult.Builder builderNewBuilder9 = BillingResult.newBuilder();
        builderNewBuilder9.setResponseCode(-2);
        builderNewBuilder9.setDebugMessage("Client does not support price change confirmation.");
        n = builderNewBuilder9.build();
        o = wgd.s(-2, "Play Store version installed does not support cross selling products.");
        p = wgd.s(-2, "Client does not support multi-item purchases.");
        q = wgd.s(-2, "Client does not support offer_id_token.");
        r = wgd.s(-2, "Play Store version installed does not support gift code purchase.");
        s = wgd.s(-2, "Client does not support ProductDetails.");
        BillingResult.Builder builderNewBuilder10 = BillingResult.newBuilder();
        builderNewBuilder10.setResponseCode(-2);
        builderNewBuilder10.setDebugMessage("Client does not support launching subscription management action flow.");
        builderNewBuilder10.build();
        BillingResult.Builder builderNewBuilder11 = BillingResult.newBuilder();
        builderNewBuilder11.setResponseCode(-2);
        builderNewBuilder11.setDebugMessage("Client does not support in-app messages.");
        t = builderNewBuilder11.build();
        BillingResult.Builder builderNewBuilder12 = BillingResult.newBuilder();
        builderNewBuilder12.setResponseCode(-2);
        builderNewBuilder12.setDebugMessage("Client does not support user choice billing.");
        builderNewBuilder12.build();
        BillingResult.Builder builderNewBuilder13 = BillingResult.newBuilder();
        builderNewBuilder13.setResponseCode(-2);
        builderNewBuilder13.setDebugMessage("Play Store version installed does not support external offer.");
        u = builderNewBuilder13.build();
        v = wgd.s(-2, "Play Store version installed does not support multi-item purchases with season pass in one cart.");
        w = wgd.s(-2, "Play Store version installed does not support querying AutoPay plan purchase.");
        x = wgd.s(-2, "Play Store version installed does not support including suspended subscriptions.");
        y = wgd.s(5, "Unknown feature");
        z = wgd.s(-2, "Play Store version installed does not support get billing config.");
        A = wgd.s(-2, "Query product details with serialized docid is not supported.");
        BillingResult.Builder builderNewBuilder14 = BillingResult.newBuilder();
        builderNewBuilder14.setResponseCode(-2);
        builderNewBuilder14.setDebugMessage("Play Store version installed does not support launching external offer flow.");
        builderNewBuilder14.build();
        BillingResult.Builder builderNewBuilder15 = BillingResult.newBuilder();
        builderNewBuilder15.setResponseCode(4);
        builderNewBuilder15.setDebugMessage("Item is unavailable for purchase.");
        B = builderNewBuilder15.build();
        C = wgd.s(-2, "Query product details with developer specified account is not supported.");
        D = wgd.s(-2, "Play Store version installed does not support alternative billing only.");
        E = wgd.s(5, "To use this API you must specify a PurchasesUpdateListener when initializing a BillingClient.");
        F = wgd.s(6, "An error occurred while retrieving billing override.");
        G = wgd.s(-2, "Play Store version installed does not support the provided billing program.");
        H = wgd.s(-2, "Play Store version installed does not support launching external links.");
        I = wgd.s(5, "A DeveloperProvidedBillingListener must be provided when initializing the BillingClient in order to use multiple payment options for this billing program.");
        BillingResult.Builder builderNewBuilder16 = BillingResult.newBuilder();
        builderNewBuilder16.setResponseCode(5);
        builderNewBuilder16.setDebugMessage("A listener must be provided calling this method.");
        builderNewBuilder16.build();
        BillingResult.Builder builderNewBuilder17 = BillingResult.newBuilder();
        builderNewBuilder17.setResponseCode(-2);
        builderNewBuilder17.setDebugMessage("Play Store version installed does not support show billing program information dialog.");
        builderNewBuilder17.build();
        BillingResult.Builder builderNewBuilder18 = BillingResult.newBuilder();
        builderNewBuilder18.setResponseCode(-2);
        builderNewBuilder18.setDebugMessage("Play Store version installed does not support get billing choice info.");
        builderNewBuilder18.build();
    }

    public static BillingResult a(int i2, String str) {
        return wgd.s(i2, str);
    }
}
