/*
 * Copyright (C) 2026 piko <https://github.com/crimera/piko>
 *
 * See the included NOTICE file for GPLv3 §7(b) terms that apply to this code.
 */

package app.morphe.extension.instagram.utils;

import java.util.HashMap;
import java.util.Map;

/**
 * English text for the piko_* keys the extension looks up.
 *
 * piko ships these as string resources added to the app by its settings patch. This bundle does
 * not ship that patch, so without a fallback every label would render as its own key — a menu
 * reading "piko_download_current_media". IgStr consults this when the app has no such resource,
 * which also leaves room for a localised resource to win when one is present.
 */
final class IgStrDefaults {

    private IgStrDefaults() {}

    private static final String[] ENTRIES = {
            "piko_action_bar_chat", "Chat action bar icons",
            "piko_action_bar_chat_desc", "Action bar icons inside a DM",
            "piko_action_bar_inbox", "Inbox action bar icons",
            "piko_action_bar_main_feed", "Main feed action bar icons",
            "piko_action_bar_user_profile", "User profile action bar icons",
            "piko_all_deleted_messages", "All deleted messages",
            "piko_allow_user_network_certificate", "Allow user network certificate",
            "piko_allow_user_network_certificate_desc", "Allows user network certificate for whitehat testing",
            "piko_amoled_title", "AMOLED",
            "piko_app_version", "App version: %s",
            "piko_cancel", "Cancel",
            "piko_category_about", "About",
            "piko_category_action_bar", "Action bar customisation",
            "piko_category_ads", "Ads",
            "piko_category_dev_options", "Developer options",
            "piko_category_distraction_free", "Distraction free",
            "piko_category_dm", "DM",
            "piko_category_download_media", "Download media",
            "piko_category_filter_content", "Filter content",
            "piko_category_ghost", "Ghost",
            "piko_category_hide_navigation_buttons", "Hide navigation buttons",
            "piko_category_links", "Links",
            "piko_category_misc", "Misc",
            "piko_category_rec_flags", "Recommended flags",
            "piko_category_rec_flags_desc", "Developer flags suggested by the community",
            "piko_change_like_animation", "Change like animation",
            "piko_change_like_animation_desc", "Change the animation to one from existing Rings like animations",
            "piko_clear", "Clear",
            "piko_clear_all_confirm", "Clear ALL saved deleted messages?",
            "piko_clear_chat_confirm", "Clear deleted messages for this chat?",
            "piko_comment_copied_failed", "No text found to copy",
            "piko_comment_copied_success", "Comment copied",
            "piko_copied", "Copied",
            "piko_copied_media_link", "Copied media link",
            "piko_copy_bio", "Copy bio",
            "piko_copy_comment", "Copy comment",
            "piko_copy_comment_desc", "Adds a button to copy comments on posts and reels",
            "piko_copy_full_name", "Copy full name",
            "piko_copy_links_from_bio", "Copy links from bio",
            "piko_copy_media_link", "Copy media link",
            "piko_copy_post_description", "Copy post description",
            "piko_copy_post_owner_fullname", "Copy post owner fullname",
            "piko_copy_post_owner_username", "Copy post owner username",
            "piko_copy_profile_link", "Copy profile link",
            "piko_copy_user_id", "Copy user id",
            "piko_copy_username", "Copy username",
            "piko_custom_sharing_domain", "Custom sharing domain",
            "piko_custom_sharing_domain_desc", "Domain to use when sharing links",
            "piko_customise_story_ring_size", "Customise story ring size",
            "piko_customise_story_ring_size_desc", "Change the size of story ring by a percentage (Default: 100)",
            "piko_customise_story_timestamp", "Customise story timestamp",
            "piko_customise_story_timestamp_desc", "Customise the timestamp that shows when the story was posted",
            "piko_debug", "Piko debug",
            "piko_debug_desc", "Adds debug option on some of the components for testing",
            "piko_delete", "Delete",
            "piko_delete_analytics_cache", "Delete analytic cache",
            "piko_delete_saved_confirm", "Delete this saved message?",
            "piko_deleted", "Deleted",
            "piko_deleted_a_message", "%s deleted a message",
            "piko_deleted_in_chat", "Deleted in this chat",
            "piko_deleted_messages_channel", "Deleted messages",
            "piko_deleted_messages_channel_desc", "Notifies when a received message is unsent",
            "piko_directly_open_metaconfig", "Directly opens MetaConfig overrides",
            "piko_directly_open_metaconfig_desc", "Directly opens MetaConfig overrides on long pressing home icon (needs developer options enabled)",
            "piko_disable_ads", "Disable ads",
            "piko_disable_analytics", "Disable analytics",
            "piko_disable_analytics_desc", "Block analytics that are sent to Instagram/Facebook servers.",
            "piko_disable_comments", "Disable comments",
            "piko_disable_discover_people", "Disable discover people",
            "piko_disable_discover_people_desc", "Disables discover people section on user profile",
            "piko_disable_double_tap_like_comment", "Disable double tap like on comment",
            "piko_disable_double_tap_like_message", "Disable double tap like on message",
            "piko_disable_double_tap_like_post", "Disable double tap like on post",
            "piko_disable_double_tap_like_reel", "Disable double tap like on reel",
            "piko_disable_double_tap_to_like", "Disable double tap to like",
            "piko_disable_explore", "Disable explore",
            "piko_disable_highlights", "Disable highlights",
            "piko_disable_reels_scrolling", "Disable Reels scrolling",
            "piko_disable_reels_scrolling_desc", "Disables the endless scrolling behavior in Instagram Reels, preventing swiping to the next Reel. Note: On a clean install, the 'Tip' animation may appear but will stop on its own after a few seconds.",
            "piko_disable_screenshot_detection", "Disable screenshot detection",
            "piko_disable_stories", "Disable stories",
            "piko_disable_story_flipping", "Disable story flipping",
            "piko_disable_story_flipping_desc", "Disable automatic flipping/moving to next story",
            "piko_disable_swipe_to_create", "Disable swipe to create",
            "piko_disable_swipe_to_create_desc", "Prevents opening the creation screen by swiping right on the home tab.",
            "piko_disable_typing_status", "Disable typing status",
            "piko_disable_video_autoplay", "Disable video autoplay",
            "piko_download_all", "Download all",
            "piko_download_as_image", "Download as image",
            "piko_download_audio", "Download audio",
            "piko_download_choose_folder", "Choose a download folder to continue",
            "piko_download_choose_folder_failed", "Could not open folder picker",
            "piko_download_current_media", "Download current media",
            "piko_download_failed_media", "Download failed : ",
            "piko_download_id_mapping", "Download mapping file",
            "piko_download_options", "Download options",
            "piko_download_profile_picture", "Download profile picture",
            "piko_download_set_path", "Choose download folder",
            "piko_download_set_path_failed", "Failed to save download folder",
            "piko_download_set_path_success", "Download directory updated!",
            "piko_download_username_folder", "Split media by username",
            "piko_download_username_folder_desc", "Creates subfolders based on username",
            "piko_download_voice_media", "Download voice message",
            "piko_download_with_external_downloader", "Download with external downloader",
            "piko_downloaded_media", "Downloaded: ",
            "piko_downloading_media", "Downloading: ",
            "piko_enable_dev_options", "Enable developer options",
            "piko_enable_dev_options_desc", "Unlocks developer option by long pressing home icon",
            "piko_enable_direct_download", "Enable direct download",
            "piko_enable_direct_download_desc", "Downloads the current viewing media without asking for options",
            "piko_enable_download", "Enable download",
            "piko_enable_emp_options", "Enable employee options",
            "piko_enable_emp_options_desc", "Unlocks all employee options used for testing",
            "piko_enable_mark_chat_as_read", "Enable mark chat as read option",
            "piko_enable_mark_chat_as_read_desc", "Get an option, on long pressing the chat, to mark it as read",
            "piko_enable_more_options_on_post", "Enable more option on post",
            "piko_enable_more_options_on_post_desc", "Adds an overflow menu button to get more options on post/reels, like copy description, copy username etc",
            "piko_export_dev_overrides", "Export overrides",
            "piko_export_experiment_list", "Export experiment list",
            "piko_export_experiment_mappings", "Export experiment mappings",
            "piko_export_fail", "Exporting failed",
            "piko_export_pref", "Export Piko preferences",
            "piko_export_success", "Exported successfully",
            "piko_external_downloader_package_name", "External downloader package name",
            "piko_external_downloader_package_name_not_found", "External downloader package name not found",
            "piko_external_downloader_package_name_not_set", "Please set the external downloader package name",
            "piko_fail_no_file", "File not found",
            "piko_fail_no_path", "No destination path provided",
            "piko_fbi_color_indicator", "Enable colored friendship status indicator",
            "piko_fbi_color_indicator_desc", "Friendship status indicator needs to be enabled",
            "piko_fbi_doesnt_follows_you", "Does not follow you",
            "piko_fbi_following_each_other", "Following each other",
            "piko_fbi_follows_you", "Follows you",
            "piko_filter_story", "Filter Story",
            "piko_filter_story_maximum_item_count", "Maximum story items",
            "piko_filter_story_maximum_item_count_desc", "Stories having more than x items will be hidden (default 9999)",
            "piko_filter_story_minimum_item_count", "Minimum story items",
            "piko_filter_story_minimum_item_count_desc", "Stories having less than x items will be hidden (default 1)",
            "piko_filter_story_types_to_hide", "Story types to hide",
            "piko_filter_story_user_types_to_hide", "User types to hide",
            "piko_follow_back_indicator", "Enable friendship status indicator",
            "piko_follow_back_indicator_desc", "Adds a follows you back status label on the profile page and shows a detailed friendship status breakdown on click",
            "piko_friendship_status", "Friendship status",
            "piko_ghost_modes_default", "Ghost mode: DEFAULT",
            "piko_ghost_modes_on", "Ghost mode: ON",
            "piko_goto_piko_settings", "Goto Piko settings",
            "piko_hide_group_creation_button_on_sharesheet", "Hide group creation button on sharesheet",
            "piko_hide_navigation_create", "Hide Create button",
            "piko_hide_navigation_direct", "Hide Direct button",
            "piko_hide_navigation_feed", "Hide Feed button",
            "piko_hide_navigation_reels", "Hide Reels button",
            "piko_hide_navigation_search", "Hide Search button",
            "piko_hide_notes_tray", "Hide notes tray",
            "piko_hide_notes_tray_desc", "Hides notes tray in DM section",
            "piko_hide_reshare_button", "Hide reshare button",
            "piko_hide_stories_tray", "Hide stories tray",
            "piko_hide_stories_tray_desc", "Hide stories tray from main feed",
            "piko_hide_suggested_content", "Hide suggested content",
            "piko_hide_suggested_content_desc", "Hides suggested stories, reels, threads (Suggested posts will still be shown).",
            "piko_image_variants", "Image variants",
            "piko_import_dev_overrides", "Import overrides",
            "piko_import_fail", "Import failed",
            "piko_import_id_mapping", "Import mapping files",
            "piko_import_pref", "Import Piko preferences",
            "piko_import_success", "Imported successfully",
            "piko_improve_image_viewing", "Improve image viewing",
            "piko_improve_image_viewing_desc", "Fetches max resolution images from server. May reduce performance, increase app data size, or cause the app to switch to an older layout",
            "piko_limit_following_feed", "Limit feed to following profiles",
            "piko_limit_following_feed_desc", "Filters the home feed to display only content from profiles you follow.",
            "piko_loop_story", "Loop story",
            "piko_loop_story_desc", "Replay the current story when it ends",
            "piko_material_you_title", "Material You",
            "piko_media_activity", "activity",
            "piko_media_deleted", "[%s deleted]",
            "piko_media_deleted_generic", "[deleted]",
            "piko_media_disappearing_photo", "disappearing photo",
            "piko_media_exists", "Media exists",
            "piko_media_gif", "GIF",
            "piko_media_like", "like",
            "piko_media_link", "link",
            "piko_media_not_available", "media not available",
            "piko_media_photo", "photo",
            "piko_media_post", "post",
            "piko_media_reel", "reel",
            "piko_media_story", "story",
            "piko_media_unknown", "media",
            "piko_media_video", "video",
            "piko_media_voice", "voice message",
            "piko_missing_mapping_file", "Missing mapping file",
            "piko_missing_mapping_file_desc", "Without mapping file, developer options will not have proper names. Do you want to download it ?",
            "piko_more_options", "More options",
            "piko_more_profile_options", "More profile options",
            "piko_no_deleted_messages", "No deleted messages captured yet.\\nEnable the feature and messages will be saved as they arrive.",
            "piko_no_internet", "Please connect to internet",
            "piko_no_links_in_bio", "No links in this bio",
            "piko_ok", "OK",
            "piko_open_image_externally", "Open image externally",
            "piko_open_image_with", "Open image with",
            "piko_open_links_externally", "Open links externally",
            "piko_open_links_externally_desc", "Open links in external browser instead of in-app browser",
            "piko_open_share_in_instagram", "Open in Instagram",
            "piko_open_video_externally", "Open video externally",
            "piko_open_video_with", "Open video with",
            "piko_open_voice_with_player", "Open with music player",
            "piko_patch_disabled", "Disabled",
            "piko_patch_enabled", "Enabled",
            "piko_patch_info_title", "Patch information",
            "piko_patch_version", "Patch version: %s",
            "piko_post_options", "Post options",
            "piko_rec_flags_last_modified_at", "Last modified: %s",
            "piko_rec_flags_no_file", "Recommended flags file not found",
            "piko_rec_flags_read_error", "Failed to read cached flags file",
            "piko_rec_flags_refresh_file", "Refresh flags",
            "piko_remove_build_expire_popup", "Remove build expire popup",
            "piko_remove_build_expire_popup_desc", "Removes the popup that appears after a while, when the app version ages",
            "piko_remove_empty_bottom_space", "Remove empty bottom space",
            "piko_reset_pref", "Reset Piko settings",
            "piko_reset_pref_confirm", "Reset Piko settings?",
            "piko_reset_pref_failed", "Failed to reset Piko settings",
            "piko_reset_pref_success", "Piko settings reset",
            "piko_restart_app", "The app needs to be restarted for the changes to reflect",
            "piko_sanitize_share_links", "Sanitize share links",
            "piko_save_deleted_messages", "Save deleted messages",
            "piko_save_deleted_messages_desc", "Captures incoming DMs locally as they arrive from the server. Marks messages as deleted when unsent, so you can view them even after the sender deletes them.",
            "piko_save_media_comment", "Save media comment",
            "piko_save_media_comment_desc", "Adds a button to save media comments on posts and reels",
            "piko_share_this_profile", "Share this profile",
            "piko_someone", "Someone",
            "piko_stories_audio_autoplay", "Stories audio autoplay",
            "piko_tap_here", "Tap here !!",
            "piko_title_settings", "Piko settings",
            "piko_turn_on_all_ghost_modes", "Turn on all ghost modes",
            "piko_unknown", "Unknown",
            "piko_unlimited_replays", "Make ephemeral media permanent",
            "piko_unlimited_replays_desc", "Changes unexpired view once, view twice media to permanent view",
            "piko_unlock_plus_benefits", "Unlock Plus benefits",
            "piko_unlock_plus_benefits_desc", "Unlock 'Plus' subscription benefits that are checked locally. USE IT AT YOUR OWN RISK",
            "piko_video_variants", "Video variants",
            "piko_view_deleted_messages", "View deleted messages",
            "piko_view_dm_anonymously", "View direct messages anonymously",
            "piko_view_live_anonymously", "View live anonymously",
            "piko_view_profile_picture", "View profile picture",
            "piko_view_stories_anonymously", "View stories anonymously",
            "piko_view_story_mentions", "View story mentions",
            "piko_welcome_message", "To improve your experience with Piko, please vist Piko settings and adjust your preference",
            "piko_welcome_title", "Welcome to Piko",
    };

    static final Map<String, String> BY_NAME = build();

    private static Map<String, String> build() {
        Map<String, String> map = new HashMap<>(ENTRIES.length);
        for (int i = 0; i < ENTRIES.length; i += 2) {
            map.put(ENTRIES[i], ENTRIES[i + 1]);
        }
        return map;
    }
}
