package e.e.a;
import android.app.*;import android.content.*;import android.os.*;import android.view.*;import android.widget.*;import android.net.Uri;import org.json.*;import java.util.*;import java.util.concurrent.*;
/** Authenticated account mylist chooser with inline folder creation. */
public final class AccountLists {
 private static final ExecutorService WORK=Executors.newSingleThreadExecutor();private static final Handler MAIN=new Handler(Looper.getMainLooper());
 static String tr(Context c,String j,String e,String z){return PanelUi.tr(c,j,e,z);}
 public static void load(Object owner,String video){try{Activity a=(Activity)Review181.field(owner,"b");if(owner.getClass().getField("f").getBoolean(owner))return;owner.getClass().getField("f").setBoolean(owner,true);VideoDetails.initializeCookies(a);WORK.execute(()->{ArrayList<Map<String,Object>> folders=new ArrayList<>();boolean ok=false;try{JSONObject data=VideoDetails.request("https://nvapi.nicovideo.jp/v1/users/me/mylists?sampleItemCount=3","GET",true,new NetworkTask()).getJSONObject("data");JSONArray rows=data.getJSONArray("mylists");for(int n=0;n<rows.length();n++){JSONObject row=rows.getJSONObject(n);Map<String,Object> f=new HashMap<>();f.put("id",row.optString("id"));f.put("title",row.optString("name"));folders.add(f);}ok=true;}catch(Exception e){android.util.Log.w("nicoid-mylist","Unable to load mylists: "+e.getClass().getSimpleName());}boolean success=ok;MAIN.post(()->{try{owner.getClass().getField("f").setBoolean(owner,false);}catch(Exception ignored){}if(a.isFinishing())return;if(success)show(owner,folders,video);else Toast.makeText(a,tr(a,"マイリストを取得できませんでした","Unable to load mylists","無法載入播放清單"),1).show();});});}catch(Exception e){android.util.Log.w("nicoid-mylist","Unable to prepare mylists",e);}}
 public static void show(Object owner,ArrayList<?> original,String video){try{Activity a=(Activity)Review181.field(owner,"b");VideoDetails.initializeCookies(a);Context c=PlaybackSession.dialogContext(a);ArrayList<Map<String,Object>> folders=new ArrayList<>();for(Object row:original){Map<?,?> map=(Map<?,?>)row;Map<String,Object> f=new HashMap<>();f.put("id",map.get("id"));f.put("title",map.get("title"));folders.add(f);}LinearLayout box=PanelUi.column(c);box.setPadding(PanelUi.dp(c,24),PanelUi.dp(c,8),PanelUi.dp(c,24),0);Spinner spinner=new Spinner(c);ArrayAdapter<String> choices=new ArrayAdapter<>(c,android.R.layout.simple_spinner_dropdown_item);for(Map<String,Object> f:folders)choices.add(String.valueOf(f.get("title")));spinner.setAdapter(choices);box.addView(spinner);Button create=PanelUi.button(c,tr(c,"フォルダーを作成","Create folder","建立資料夾"));box.addView(create);EditText note=new EditText(c);note.setHint(tr(c,"メモ","Note","備註"));box.addView(note);AlertDialog dialog=new AlertDialog.Builder(c).setTitle(UiStrings.translate("マイリスト登録")).setView(box).setPositiveButton(tr(c,"登録","Add","新增"),null).setNegativeButton(tr(c,"キャンセル","Cancel","取消"),null).create();PlaybackSession.showForm(dialog);create.setOnClickListener(v->create(a,(id,name)->{Map<String,Object> f=new HashMap<>();f.put("id",id);f.put("title",name);folders.add(f);choices.add(name);spinner.setSelection(folders.size()-1);}));dialog.getButton(-1).setOnClickListener(v->{int n=spinner.getSelectedItemPosition();if(n<0||n>=folders.size())return;String id=String.valueOf(folders.get(n).get("id")),description=note.getText().toString();dialog.getButton(-1).setEnabled(false);WORK.execute(()->{boolean ok=false;try{String path="https://nvapi.nicovideo.jp/v1/users/me/mylists/"+Uri.encode(id)+"/items?itemId="+Uri.encode(HistoryRules.id(video))+"&description="+Uri.encode(description);VideoDetails.request(path,"POST",true,new NetworkTask());ok=true;}catch(Exception e){android.util.Log.w("nicoid-mylist","Unable to add mylist video: "+e.getClass().getSimpleName());}boolean success=ok;MAIN.post(()->{if(a.isFinishing())return;if(success)dialog.dismiss();else dialog.getButton(-1).setEnabled(true);Toast.makeText(a,tr(a,success?"登録しました":"登録できませんでした",success?"Added":"Unable to add",success?"已新增":"無法新增"),1).show();});});});}catch(Exception e){android.util.Log.w("nicoid-mylist","Unable to display chooser",e);}}
 interface Created {void done(String id,String name);}
 static void create(Activity a,Created result){Context c=PlaybackSession.dialogContext(a);LinearLayout form=PanelUi.column(c);EditText name=new EditText(c);name.setSingleLine(true);name.setHint(tr(c,"フォルダー名","Folder name","資料夾名稱"));form.addView(name);CheckBox publicList=new CheckBox(c);publicList.setText(tr(c,"公開する","Public","公開"));form.addView(publicList);AlertDialog d=new AlertDialog.Builder(c).setTitle(tr(c,"フォルダーを作成","Create folder","建立資料夾")).setView(form).setPositiveButton(tr(c,"作成","Create","建立"),null).setNegativeButton(tr(c,"キャンセル","Cancel","取消"),null).create();PlaybackSession.showForm(d);d.getButton(-1).setOnClickListener(v->{String title=name.getText().toString().trim();if(title.isEmpty()){name.setError(tr(c,"名前を入力してください","Enter a name","請輸入名稱"));return;}boolean isPublic=publicList.isChecked();d.getButton(-1).setEnabled(false);WORK.execute(()->{String id="";try{JSONObject data=VideoDetails.request("https://nvapi.nicovideo.jp/v1/users/me/mylists?name="+Uri.encode(title)+"&description=&isPublic="+isPublic+"&defaultSortKey=addedAt&defaultSortOrder=desc","POST",true,new NetworkTask()).getJSONObject("data");id=data.optString("mylistId");if(!id.matches("[0-9]+"))throw new java.io.IOException();}catch(Exception e){android.util.Log.w("nicoid-mylist","Unable to create folder: "+e.getClass().getSimpleName());id="";}String created=id;MAIN.post(()->{if(a.isFinishing())return;if(!created.isEmpty()){d.dismiss();result.done(created,title);}else{d.getButton(-1).setEnabled(true);name.setError(tr(c,"作成に失敗しました","Unable to create","建立失敗"));}});});});}
}
