package e.e.a;
import android.app.*;import android.content.*;import android.net.Uri;import android.os.*;import android.graphics.*;import android.view.*;import android.widget.*;import org.json.*;import java.util.*;import java.util.concurrent.*;import java.util.regex.*;
public final class AccountPage {
 private static final Handler MAIN=new Handler(Looper.getMainLooper());private static final ExecutorService WORK=Executors.newFixedThreadPool(2);
 private static String tr(Context c,String j,String e,String z){return PanelUi.tr(c,j,e,z);}
 @SuppressWarnings({"unchecked","rawtypes"}) public static void addMenu(Context c,ArrayList list){String account=c.getString(0x7f0f01b1);for(int i=0;i<list.size();i++){Object o=list.get(i);if(!(o instanceof Map))continue;Object title=((Map)o).get("title");if(account.equals(title)||UiStrings.translate(account).equals(title)){Map row=new HashMap();row.put("title",tr(c,"マイページ","My page","我的頁面"));row.put("subtitle",tr(c,"プロフィール・投稿動画・マイリスト","Profile, uploads and my lists","個人資料、投稿影片與播放清單"));row.put("islabel",false);row.put("type",0);row.put("intent",nativeIntent(c,"NicoidNicorepoActivity").putExtra("nicoid_my_page",true));list.add(i+1,row);return;}}}
 private static Intent nativeIntent(Context c,String cls){return new Intent(Intent.ACTION_VIEW).setClassName(c,"com.sauzask.nicoid."+cls);}
 private static void open(Activity a,Intent i){try{a.startActivity(i);}catch(Exception e){Toast.makeText(a,tr(a,"ページを開けませんでした","Unable to open page","無法開啟頁面"),0).show();}}
 private static void link(Activity a,LinearLayout box,String title,int icon,Intent target){LinearLayout row=new LinearLayout(a);row.setGravity(Gravity.CENTER_VERTICAL);row.setPadding(PanelUi.dp(a,16),PanelUi.dp(a,4),PanelUi.dp(a,16),PanelUi.dp(a,4));row.addView(new MenuIcon(a,icon),new LinearLayout.LayoutParams(PanelUi.dp(a,24),PanelUi.dp(a,24)));TextView t=PanelUi.text(a,title,15);t.setPadding(PanelUi.dp(a,12),PanelUi.dp(a,4),PanelUi.dp(a,8),PanelUi.dp(a,4));row.addView(t,new LinearLayout.LayoutParams(0,-2,1));row.setMinimumHeight(PanelUi.dp(a,44));row.setContentDescription(title);row.setOnClickListener(v->open(a,target));box.addView(row);}
 public static void load(Activity a){VideoDetails.initializeCookies(a);ScrollView scroll=new ScrollView(a);scroll.setTag("nicoid_my_page");ThemeChoice.background(scroll);LinearLayout box=PanelUi.column(a);scroll.addView(box);boolean visible=false;try{Object old=a.getClass().getField("y").get(a);visible=old instanceof View&&"nicoid_my_page".equals(((View)old).getTag());a.getClass().getField("y").set(a,scroll);a.getClass().getField("H").setBoolean(a,false);a.getClass().getField("I").setBoolean(a,true);Object bar=a.getClass().getField("O").get(a);bar.getClass().getMethod("b",CharSequence.class).invoke(bar,tr(a,"マイページ","My page","我的頁面"));bar.getClass().getMethod("c",CharSequence.class).invoke(bar,"");}catch(Exception ignored){}if(visible)a.setContentView(scroll);
 LinearLayout profile=PanelUi.column(a);profile.setPadding(PanelUi.dp(a,16),PanelUi.dp(a,20),PanelUi.dp(a,16),PanelUi.dp(a,12));box.addView(profile);TextView loading=PanelUi.text(a,tr(a,"読み込み中…","Loading…","載入中…"),14);profile.addView(loading);Matcher match=Pattern.compile("(?:^|;\\s*)user_session=user_session_(\\d+)_").matcher(VideoDetails.cookie());String user=match.find()?match.group(1):"";NetworkTask task=new NetworkTask();scroll.addOnAttachStateChangeListener(new View.OnAttachStateChangeListener(){public void onViewAttachedToWindow(View v){}public void onViewDetachedFromWindow(View v){task.cancel();}});
 if(!user.isEmpty())task.start(WORK,()->{try{JSONObject d=VideoDetails.request("https://nvapi.nicovideo.jp/v1/users/"+user,"GET",true,task).optJSONObject("data");JSONObject u=d==null?null:d.optJSONObject("user");if(u==null)throw new java.io.IOException();MAIN.post(()->{if(!task.cancelled())profile(a,profile,u,user);});}catch(Exception e){MAIN.post(()->{if(!task.cancelled())loading.setText(tr(a,"プロフィールを取得できませんでした","Unable to load profile","無法載入個人資料"));});}});else loading.setText(tr(a,"ログインが必要です","Sign in required","請先登入"));
 PanelUi.divider(box);link(a,box,tr(a,"視聴履歴","Watch history","觀看紀錄"),0,nativeIntent(a,"NicoidVideoListActivity").putExtra("type",4));link(a,box,tr(a,"あとで見る","Watch later","稍後觀看"),0,nativeIntent(a,"NicoidVideoListActivity").putExtra("type",9).putExtra("name",tr(a,"あとで見る","Watch later","稍後觀看")).setData(Uri.parse("deflist")));link(a,box,tr(a,"マイリスト","My lists","播放清單"),1,nativeIntent(a,"NicoidMylistGroupActivity"));link(a,box,tr(a,"キャッシュ管理","Cache manager","快取管理"),2,nativeIntent(a,"NicoidCacheManagerActivity"));PanelUi.divider(box);
 if(!user.isEmpty()){link(a,box,tr(a,"投稿動画","Uploaded videos","投稿影片"),3,nativeIntent(a,"NicoidUserVideoListActivity").setData(Uri.parse("https://www.nicovideo.jp/user/"+user+"/video")));link(a,box,tr(a,"シリーズ","Series","系列"),3,new Intent(Intent.ACTION_VIEW,Uri.parse("https://www.nicovideo.jp/user/"+user+"/series")));}PanelUi.divider(box);link(a,box,tr(a,"フォロー中","Following","追蹤中"),4,nativeIntent(a,"NicoidFavUserActivity"));link(a,box,tr(a,"ニコレポ","Nico Reports","Nico 動態"),3,nativeIntent(a,"NicoidNicorepoActivity"));if(!user.isEmpty())link(a,box,tr(a,"フォロワー","Followers","追蹤者"),4,new Intent(Intent.ACTION_VIEW,Uri.parse("https://www.nicovideo.jp/user/"+user+"/follower")));}
 private static void profile(Activity a,LinearLayout root,JSONObject u,String id){root.removeAllViews();LinearLayout head=new LinearLayout(a);head.setGravity(Gravity.CENTER_VERTICAL);FrameLayout avatar=new FrameLayout(a);ImageView image=new ImageView(a);image.setScaleType(ImageView.ScaleType.CENTER_CROP);image.setBackground(PanelUi.round(a,ThemeChoice.isNight(a)?0xff252831:0xffeeeeee,100));image.setClipToOutline(true);TextView placeholder=PanelUi.text(a,"",14);avatar.addView(placeholder);avatar.addView(image,new FrameLayout.LayoutParams(-1,-1));head.addView(avatar,new LinearLayout.LayoutParams(PanelUi.dp(a,56),PanelUi.dp(a,56)));LinearLayout names=PanelUi.column(a);names.addView(PanelUi.text(a,u.optString("nickname",u.optString("name",id)),18));names.addView(PanelUi.text(a,"ID: "+id,13));head.addView(names,new LinearLayout.LayoutParams(0,-2,1));Button edit=PanelUi.button(a,tr(a,"編集","Edit","編輯"));edit.setOnClickListener(v->open(a,new Intent(Intent.ACTION_VIEW,Uri.parse("https://account.nicovideo.jp/my/profile"))));head.addView(edit);root.addView(head);JSONObject icons=u.optJSONObject("icons");if(icons!=null)ShortImages.load(icons.optString("small",icons.optString("large","")),image,placeholder);LinearLayout stats=new LinearLayout(a);JSONObject level=u.optJSONObject("userLevel");if(level!=null){TextView lv=PanelUi.text(a,"LV "+level.optInt("currentLevel"),13);lv.setGravity(Gravity.CENTER);stats.addView(lv,new LinearLayout.LayoutParams(0,-2,1));}for(String k:new String[]{"followeeCount","followerCount"})if(u.has(k)){TextView t=PanelUi.text(a,u.optString(k)+"\n"+(k.equals("followeeCount")?tr(a,"フォロー中","Following","追蹤中"):tr(a,"フォロワー","Followers","追蹤者")),13);t.setGravity(Gravity.CENTER);stats.addView(t,new LinearLayout.LayoutParams(0,-2,1));}root.addView(stats);String desc=u.optString("description","");if(!desc.isEmpty())root.addView(PanelUi.text(a,android.text.Html.fromHtml(desc).toString(),14));}
 static final class MenuIcon extends View {final int kind;final Paint p=new Paint(3);MenuIcon(Context c,int k){super(c);kind=k;}protected void onDraw(Canvas c){p.setColor(PanelUi.ink(getContext()));p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(1.8f);p.setStrokeCap(Paint.Cap.ROUND);c.save();float s=Math.min(getWidth(),getHeight())/28f;c.scale(s,s);if(kind==0){c.drawCircle(14,14,10,p);c.drawLine(14,7,14,14,p);c.drawLine(14,14,19,17,p);}else if(kind==1){Path x=new Path();x.moveTo(3,8);x.lineTo(10,8);x.lineTo(12,11);x.lineTo(25,11);x.lineTo(25,23);x.lineTo(3,23);x.close();c.drawPath(x,p);}else if(kind==2){c.drawLine(14,3,14,18,p);c.drawLine(9,13,14,18,p);c.drawLine(14,18,19,13,p);c.drawLine(4,20,4,24,p);c.drawLine(4,24,24,24,p);c.drawLine(24,24,24,20,p);}else if(kind==3){c.drawRoundRect(3,7,25,23,2,2,p);Path x=new Path();x.moveTo(11,11);x.lineTo(19,15);x.lineTo(11,19);x.close();c.drawPath(x,p);}else if(kind==4){c.drawCircle(14,8,5,p);c.drawArc(4,15,24,30,180,180,false,p);}else{c.drawCircle(14,14,5,p);c.drawCircle(14,14,9,p);for(int n=0;n<8;n++){double angle=n*Math.PI/4;c.drawLine(14+(float)Math.cos(angle)*9,14+(float)Math.sin(angle)*9,14+(float)Math.cos(angle)*13,14+(float)Math.sin(angle)*13,p);}}c.restore();}}
}
