package e.e.a;
import android.app.*;import android.content.*;import android.net.Uri;import android.os.*;import android.view.*;import android.widget.*;import android.text.SpannableString;import org.json.*;import java.net.*;import java.io.*;import java.util.*;import java.util.concurrent.*;
public final class ChannelPage {
 private static final ExecutorService WORK=Executors.newFixedThreadPool(2);private static final Handler MAIN=new Handler(Looper.getMainLooper());
 static String tr(Context c,String j,String e,String z){return PanelUi.tr(c,j,e,z);}
 static void set(Object o,String field,Object value)throws Exception{o.getClass().getField(field).set(o,value);}
 static void record(String message){try{Class.forName("e.e.a.ModernDebug").getMethod("record",String.class).invoke(null,"Channel list: "+message);}catch(Exception ignored){}}
 static SpannableString duration(String value){SpannableString text=new SpannableString(value);text.setSpan(new android.text.style.StyleSpan(android.graphics.Typeface.BOLD),0,text.length(),android.text.Spanned.SPAN_EXCLUSIVE_EXCLUSIVE);return text;}
 public static String channelId(String url){return ChannelFeed.channelId(url);}
 public static boolean redirect(Activity a){String id=channelId(a.getIntent().getDataString());if(id.isEmpty())return false;try{VideoDetails.initializeCookies(a);JSONObject channel=new JSONObject().put("id",id).put("name",id);JSONObject latest=Review181.latest(),cached=latest==null?null:latest.optJSONObject("channel");if(cached!=null&&id.equals(cached.optString("id")))channel=cached;launch(a,channel);a.finish();return true;}catch(Exception e){android.util.Log.w("nicoid-channel","Unable to redirect channel listing",e);return false;}}
 public static void launch(Context c,JSONObject channel){String id=channel.optString("id");if(!id.matches("ch[0-9]+"))return;c.startActivity(new Intent().setClassName(c,"com.sauzask.nicoid.NicoidNicorepoActivity").putExtra("nicoid_channel_page",channel.toString()));}
 public static boolean open(Activity a){String encoded=a.getIntent().getStringExtra("nicoid_channel_page");if(encoded==null)return false;try{JSONObject channel=new JSONObject(encoded);String id=channel.optString("id");if(!id.matches("ch[0-9]+"))throw new IOException("Invalid channel ID");LinearLayout page=PanelUi.column(a);ThemeChoice.background(page);set(a,"y",page);set(a,"H",false);set(a,"I",true);Object toolbar=Review181.field(a,"O");toolbar.getClass().getMethod("b",CharSequence.class).invoke(toolbar,channel.optString("name",id));toolbar.getClass().getMethod("c",CharSequence.class).invoke(toolbar,"");
  ListView list=new ListView(a);Button more=PanelUi.button(a,tr(a,"読み込み中…","Loading…","載入中…"));more.setEnabled(false);list.addFooterView(more,null,false);ArrayList<Object> rows=new ArrayList<>();Class<?> imageClass=Class.forName("e.e.a.y0");Object images=imageClass.getConstructor(Context.class).newInstance(a);set(images,"d",0);set(a,"G",images);BaseAdapter adapter=(BaseAdapter)Class.forName("e.e.a.b0").getConstructor(Context.class,ArrayList.class,int.class,imageClass).newInstance(a,rows,0,images);set(adapter,"l",Class.forName("e.e.a.b1").getConstructor(Activity.class).newInstance(a));BaseAdapter display=new BaseAdapter(){public int getCount(){return adapter.getCount();}public Object getItem(int position){return adapter.getItem(position);}public long getItemId(int position){return adapter.getItemId(position);}public View getView(int position,View recycled,ViewGroup parent){View row=adapter.getView(position,recycled,parent);View owner=row.findViewById(0x7f0801e2);if(owner!=null)owner.setVisibility(View.GONE);View info=row.findViewById(0x7f0801d3);if(info instanceof TextView){info.setVisibility(View.VISIBLE);VideoCounts.setText((TextView)info,ListActions.value(rows.get(position),"videoinfo"));}ListActions.bind(row,adapter,position);return row;}};list.setAdapter(display);page.addView(list,new LinearLayout.LayoutParams(-1,0,1));list.setOnItemClickListener((parent,v,position,rowId)->{if(position>=rows.size())return;String url=ListActions.value(rows.get(position),"videourl");a.startActivity(new Intent(Intent.ACTION_VIEW,Uri.parse(url)).setClassName(a,"com.sauzask.nicoid.NicoidVideoActivity"));});
  Listing state=new Listing(a,page,more,rows,display,id,channel.optString("name"));more.setOnClickListener(v->state.load());page.addOnAttachStateChangeListener(new View.OnAttachStateChangeListener(){public void onViewAttachedToWindow(View v){}public void onViewDetachedFromWindow(View v){state.stop();}});page.post(state::load);return true;
 }catch(Exception e){android.util.Log.w("nicoid-channel","Unable to prepare channel page",e);Toast.makeText(a,tr(a,"チャンネルを表示できませんでした","Unable to open channel","無法開啟頻道"),1).show();return false;}}
 static final class Listing {final Activity a;final View root;final Button more;final ArrayList<Object> rows;final BaseAdapter adapter;final String id,name;final Set<String> seen=new HashSet<>();int page=1;boolean busy;NetworkTask task;final ArrayList<NetworkTask> metadata=new ArrayList<>();
  Listing(Activity a,View root,Button more,ArrayList<Object> rows,BaseAdapter adapter,String id,String name){this.a=a;this.root=root;this.more=more;this.rows=rows;this.adapter=adapter;this.id=id;this.name=name;}
  void stop(){if(task!=null)task.cancel();for(NetworkTask item:metadata)item.cancel();metadata.clear();}
  void hydrate(ChannelFeed.Video video,Object row){NetworkTask active=new NetworkTask();metadata.add(active);active.start(WORK,()->{try{ChannelVideoMetadata.Result result=ChannelVideoMetadata.fetch(video,active);JSONObject watch=DetailData.watchData(result.response),data=watch.optJSONObject("video"),client=watch.optJSONObject("client");record("metadata "+video.id+" resolved="+(data==null?"missing":data.optString("id"))+" client="+(client==null?"missing":client.optString("watchId"))+" count="+(data!=null&&data.optJSONObject("count")!=null));if(!ChannelVideoMetadata.applyFetched(video,result)){record("metadata rejected "+video.id);return;}record("counts "+video.id+" "+(video.counts.isEmpty()?"missing":video.counts));MAIN.post(()->{if(active.cancelled()||a.isFinishing()||!rows.contains(row))return;try{java.lang.reflect.Method put=row.getClass().getMethod("a",String.class,Object.class);put.invoke(row,"thumbnail",video.image);put.invoke(row,"videoinfo",new SpannableString(video.counts));adapter.notifyDataSetChanged();record("row updated "+video.id);}catch(Exception e){record("row update failed "+video.id+" "+e.getClass().getSimpleName());android.util.Log.w("nicoid-channel","Unable to update video metadata",e);}});}catch(Exception e){if(!active.cancelled())record("metadata failed "+video.id+" "+e.getClass().getSimpleName()+" "+(e.getMessage()!=null&&e.getMessage().startsWith("HTTP ")?e.getMessage():""));android.util.Log.w("nicoid-channel","Unable to load video metadata",e);}finally{MAIN.post(()->metadata.remove(active));}});}
  void reload(){if(busy)return;stop();page=1;rows.clear();seen.clear();adapter.notifyDataSetChanged();more.setVisibility(View.VISIBLE);load();}
  void load(){if(busy)return;busy=true;more.setEnabled(false);more.setText(tr(a,"読み込み中…","Loading…","載入中…"));NetworkTask active=new NetworkTask();task=active;int requested=page;active.start(WORK,()->{try{List<ChannelFeed.Video> videos=ChannelFeed.parse(read("https://ch.nicovideo.jp/"+id+"/video?rss=2.0&page="+requested,active));MAIN.post(()->{if(active.cancelled()||a.isFinishing())return;busy=false;int added=0;try{for(ChannelFeed.Video v:videos){if(!seen.add(v.id))continue;added++;if(ContentFilter.blocked(a,v.title,name))continue;Object row=Class.forName("e.e.a.x1").getConstructor().newInstance();java.lang.reflect.Method put=row.getClass().getMethod("a",String.class,Object.class);put.invoke(row,"videourl",v.url);put.invoke(row,"title",v.title);put.invoke(row,"thumbnail",v.image);put.invoke(row,"videoinfo",new SpannableString(v.counts));put.invoke(row,"posttime",new SpannableString(v.date));put.invoke(row,"length",duration(v.length));set(row,"b",v.id);set(row,"y",name);rows.add(row);hydrate(v,row);}page++;adapter.notifyDataSetChanged();more.setEnabled(true);more.setText(rows.isEmpty()?tr(a,"動画はありません","No videos","影片不存在"):tr(a,"もっと見る","View more","查看更多"));if(!rows.isEmpty()&&(added==0||videos.size()<10))more.setVisibility(View.GONE);}catch(Exception e){more.setText(tr(a,"再試行","Retry","重試"));more.setEnabled(true);}});}catch(Exception e){MAIN.post(()->{if(!active.cancelled()&&!a.isFinishing()){busy=false;more.setEnabled(true);more.setText(tr(a,"読み込みに失敗しました。再試行","Unable to load. Retry","載入失敗，重試"));}});}});}
 }
 static String read(String url,NetworkTask task)throws Exception{for(int redirects=0;redirects<4;redirects++){HttpURLConnection c=(HttpURLConnection)new URL(url).openConnection();if(!task.bind(c))throw new InterruptedIOException();try{c.setConnectTimeout(10000);c.setReadTimeout(10000);c.setInstanceFollowRedirects(false);c.setRequestProperty("User-Agent","Mozilla/5.0");c.setRequestProperty("Cookie",VideoDetails.cookie());int status=c.getResponseCode();if(status>=300&&status<400){String next=new URL(new URL(url),c.getHeaderField("Location")).toString();if(!next.startsWith("https://ch.nicovideo.jp/"))throw new IOException("Invalid channel redirect");url=next;continue;}if(status!=200)throw new IOException("HTTP "+status);ByteArrayOutputStream out=new ByteArrayOutputStream();try(InputStream in=c.getInputStream()){byte[] buffer=new byte[8192];int count;while((count=in.read(buffer))>=0){if(task.cancelled()||out.size()+count>2*1024*1024)throw new IOException("Cancelled or oversized");out.write(buffer,0,count);}}return out.toString("UTF-8");}finally{task.release(c);c.disconnect();}}throw new IOException("Too many redirects");}
}
