package e.e.a;
import android.view.*;import android.widget.*;import android.content.res.Configuration;import android.util.TypedValue;
public final class FullscreenControls {
 private static class State{ViewGroup original;ViewGroup.LayoutParams controlsLayout,textLayout;float textSize;int orientation,gravity,barHeight;int[] padding;java.util.Map<View,int[]> heights=new java.util.HashMap<>();}
 private static void thin(View v,int h,State s){if(!s.heights.containsKey(v))s.heights.put(v,new int[]{v.getLayoutParams().height,v.getMinimumHeight(),v instanceof TextView?((TextView)v).getMinHeight():0,v.getPaddingTop(),v.getPaddingBottom()});v.setPadding(v.getPaddingLeft(),0,v.getPaddingRight(),0);v.setMinimumHeight(0);if(v instanceof TextView)((TextView)v).setMinHeight(0);v.getLayoutParams().height=h;if(v instanceof ViewGroup){ViewGroup g=(ViewGroup)v;for(int i=0;i<g.getChildCount();i++)thin(g.getChildAt(i),h,s);}}
 private static void row(View view,int slot){if(!(view instanceof LinearLayout))return;LinearLayout group=(LinearLayout)view;group.setPadding(0,0,0,0);group.setGravity(Gravity.RIGHT|Gravity.CENTER_VERTICAL);for(int i=0;i<group.getChildCount();i++){View child=group.getChildAt(i);ViewGroup.LayoutParams p=child.getLayoutParams();p.width=OverlayRules.slot(slot);p.height=slot;if(p instanceof LinearLayout.LayoutParams){LinearLayout.LayoutParams lp=(LinearLayout.LayoutParams)p;lp.weight=0;lp.setMargins(0,0,0,0);}child.setLayoutParams(p);child.setPadding(0,0,0,0);child.setMinimumWidth(0);child.setMinimumHeight(0);if(child instanceof TextView){TextView t=(TextView)child;t.setMinWidth(0);t.setMinHeight(0);t.setGravity(Gravity.CENTER);t.setIncludeFontPadding(false);t.setShadowLayer(0,0,0,0);t.setTextSize(TypedValue.COMPLEX_UNIT_PX,slot*.34f);}}view.getLayoutParams().height=slot;view.requestLayout();}
 public static void update(Object fragment){try{
  View root=(View)fragment.getClass().getField("x1").get(fragment);if(root==null)return;android.content.Context c=root.getContext();String pkg=c.getPackageName();
  LinearLayout bar=(LinearLayout)root.findViewById(c.getResources().getIdentifier("titlebar","id",pkg));View controls=root.findViewById(c.getResources().getIdentifier("topmenulay","id",pkg));TextView text=(TextView)root.findViewById(c.getResources().getIdentifier("titlebartext","id",pkg));View video=root.findViewById(c.getResources().getIdentifier("videoLayout","id",pkg));if(bar==null||controls==null||text==null)return;PlayerIcons.attach(root);
  boolean full=c.getResources().getConfiguration().orientation==Configuration.ORIENTATION_LANDSCAPE||(video!=null&&video.getLayoutParams().height==ViewGroup.LayoutParams.MATCH_PARENT);
  controls.setBackgroundColor(full?android.graphics.Color.TRANSPARENT:0x77000000);
  State state=bar.getTag() instanceof State?(State)bar.getTag():null;
  if(full){if(state==null){state=new State();state.original=(ViewGroup)controls.getParent();state.controlsLayout=controls.getLayoutParams();state.textLayout=text.getLayoutParams();state.textSize=text.getTextSize();state.orientation=bar.getOrientation();state.gravity=bar.getGravity();state.barHeight=bar.getLayoutParams().height;state.padding=new int[]{bar.getPaddingLeft(),bar.getPaddingTop(),bar.getPaddingRight(),bar.getPaddingBottom()};bar.setTag(state);}
   if(controls.getParent()!=bar){((ViewGroup)controls.getParent()).removeView(controls);bar.addView(controls,new LinearLayout.LayoutParams(-2,-2));}
   bar.setOrientation(LinearLayout.HORIZONTAL);bar.setGravity(Gravity.CENTER_VERTICAL);int h=(int)(36*c.getResources().getDisplayMetrics().density);bar.setPadding((int)(8*c.getResources().getDisplayMetrics().density),0,0,0);bar.setTranslationY(0);if(bar.getLayoutParams() instanceof RelativeLayout.LayoutParams){RelativeLayout.LayoutParams lp=(RelativeLayout.LayoutParams)bar.getLayoutParams();lp.addRule(RelativeLayout.ALIGN_PARENT_TOP);lp.topMargin=0;}bar.getLayoutParams().height=h;thin(controls,h,state);bar.requestLayout();text.setTextSize(TypedValue.COMPLEX_UNIT_PX,state.textSize*.8f);text.setGravity(Gravity.CENTER_VERTICAL);text.setIncludeFontPadding(false);text.setSingleLine(true);text.setEllipsize(android.text.TextUtils.TruncateAt.END);text.setLayoutParams(new LinearLayout.LayoutParams(0,h,1));
  }else if(state!=null){bar.removeView(controls);state.original.addView(controls,state.controlsLayout);text.setLayoutParams(state.textLayout);text.setTextSize(TypedValue.COMPLEX_UNIT_PX,state.textSize);bar.setOrientation(state.orientation);bar.setGravity(state.gravity);bar.getLayoutParams().height=state.barHeight;bar.setPadding(state.padding[0],state.padding[1],state.padding[2],state.padding[3]);int[] padding;for(java.util.Map.Entry<View,int[]> e:state.heights.entrySet()){View v=e.getKey();int[] a=e.getValue();v.getLayoutParams().height=a[0];v.setMinimumHeight(a[1]);v.setPadding(v.getPaddingLeft(),a[3],v.getPaddingRight(),a[4]);if(v instanceof TextView)((TextView)v).setMinHeight(a[2]);v.requestLayout();}bar.requestLayout();bar.setTag(null);}
  int slot=Math.round((full?36:32)*c.getResources().getDisplayMetrics().density);row(controls,slot);row(root.findViewById(c.getResources().getIdentifier("bottommenulay","id",pkg)),slot);
 }catch(Exception e){android.util.Log.w("nicoid-controls","Fullscreen layout failed",e);}}
}
