package e.e.a;
import android.app.*;import android.content.*;import android.net.Uri;import android.preference.PreferenceManager;import android.view.*;import android.widget.*;import android.text.SpannableString;import org.json.*;import java.util.*;
/** Device lists reuse the app's video rows and list selection layout. */
public final class LocalPlaylists {
 private static final String KEY="nicoid_local_playlists_v1";
 private static final Map<Activity,Page> PAGES=new WeakHashMap<>();
 private static final Map<Object,Page> ADAPTER_PAGES=new WeakHashMap<>();
 static String tr(Context c,String j,String e,String z){return PanelUi.tr(c,j,e,z);}
 static LocalPlaylistData read(Context c){try{return new LocalPlaylistData(PreferenceManager.getDefaultSharedPreferences(c).getString(KEY,"{}"));}catch(JSONException e){throw new IllegalStateException("Invalid local playlist store",e);}}
 static boolean save(Context c,LocalPlaylistData d){boolean ok=PreferenceManager.getDefaultSharedPreferences(c).edit().putString(KEY,d.toString()).commit();if(!ok)Toast.makeText(c,tr(c,"保存に失敗しました","Unable to save","儲存失敗"),1).show();return ok;}
 static void choose(Context host,String current,java.util.function.Consumer<String> chosen){Context c=PlaybackSession.dialogContext(host);LocalPlaylistData d=read(host);ArrayList<String> ids=new ArrayList<>(),names=new ArrayList<>();if(!"".equals(current)){ids.add("");names.add(tr(c,"プレイリスト","Playlists","播放清單"));}for(int n=0;n<d.folders.length();n++){JSONObject f=d.folders.optJSONObject(n);if(!f.optString("id").equals(current)){ids.add(f.optString("id"));names.add(f.optString("name"));}}names.add(tr(c,"フォルダーを作成","Create folder","建立資料夾"));UiDialogs.show(new AlertDialog.Builder(c).setTitle(tr(c,"フォルダーを選択","Select folder","選擇資料夾")).setItems(names.toArray(new String[0]),(x,w)->{if(w<ids.size())chosen.accept(ids.get(w));else create(host,chosen);}).setNegativeButton(tr(c,"キャンセル","Cancel","取消"),null).create());}
 static void confirmFolderDelete(Activity host,String id,String name,Runnable done){if(id==null||id.isEmpty())return;Context c=PlaybackSession.dialogContext(host);UiDialogs.show(new AlertDialog.Builder(c).setTitle(tr(c,"フォルダーを削除しますか？","Delete folder?","刪除資料夾？")).setMessage(name+"\n"+tr(c,"フォルダー内の動画は未分類に移動します。","Videos in this folder will move to Unfiled.","資料夾中的影片會移至未分類。" )).setPositiveButton(tr(c,"削除","Delete","刪除"),(d,w)->{try{LocalPlaylistData data=read(host);data.removeFolder(id);if(save(host,data))done.run();}catch(Exception e){Toast.makeText(host,tr(host,"削除に失敗しました","Unable to delete folder","刪除失敗"),1).show();}}).setNegativeButton(tr(c,"キャンセル","Cancel","取消"),null).create());}
 static void create(Context host,java.util.function.Consumer<String> done){Context c=PlaybackSession.dialogContext(host);EditText input=new EditText(c);input.setSingleLine(true);input.setHint(tr(c,"フォルダー名","Folder name","資料夾名稱"));AlertDialog d=new AlertDialog.Builder(c).setTitle(tr(c,"フォルダーを作成","Create folder","建立資料夾")).setView(input).setPositiveButton(tr(c,"作成","Create","建立"),null).setNegativeButton(tr(c,"キャンセル","Cancel","取消"),null).create();PlaybackSession.showForm(d);d.getButton(-1).setOnClickListener(v->{String name=input.getText().toString().trim();if(name.isEmpty()){input.setError(tr(c,"名前を入力してください","Enter a name","請輸入名稱"));return;}try{LocalPlaylistData data=read(host);String id=data.folder(name);if(save(host,data)){d.dismiss();done.accept(id);}}catch(Exception e){input.setError(tr(c,"保存に失敗しました","Unable to save","儲存失敗"));}});}
 public static void add(Context host,String url,String title,String owner,String image){add(host,url,title,owner,image,null);}
 public static void addRow(Context host,Object row){String owner="";try{owner=String.valueOf(ListActions.get(row,"y"));}catch(Exception ignored){}add(host,ListActions.value(row,"videourl"),ListActions.value(row,"title"),owner,ListActions.value(row,"thumbnail"),row);}
 private static void add(Context host,String url,String title,String owner,String image,Object row){choose(host,null,folder->{try{LocalPlaylistData d=read(host);d.add(folder,url,title,owner,image);String videoId=HistoryRules.id(url);if(row!=null)for(int n=0;n<d.videos.length();n++){JSONObject v=d.videos.getJSONObject(n);if(folder.equals(v.optString("folder"))&&videoId.equals(v.optString("videoId")))for(String key:new String[]{"length","videoinfo","posttime"})v.put(key,ListActions.value(row,key));}if(save(host,d))Toast.makeText(host,tr(host,"プレイリストに追加しました","Added to playlist","已加入播放清單"),0).show();}catch(Exception e){Toast.makeText(host,tr(host,"追加に失敗しました","Unable to add video","新增失敗"),1).show();}});}
 public static void show(Context host){if(host instanceof Activity){Page page=PAGES.get((Activity)host);if(page!=null)page.render();}}
 public static boolean open(Activity a){if(!a.getIntent().getBooleanExtra("nicoid_local_playlists",false))return false;Page page=PAGES.get(a);if(page==null){page=new Page(a);PAGES.put(a,page);}try{a.getClass().getField("y").set(a,page.root);a.getClass().getField("H").setBoolean(a,false);a.getClass().getField("I").setBoolean(a,true);}catch(Exception e){android.util.Log.w("nicoid-playlist","Unable to prepare playlist page",e);}page.render();return true;}
 public static void destroy(Activity a){PAGES.remove(a);ADAPTER_PAGES.entrySet().removeIf(e->e.getValue().a==a);}
 static void registerAdapter(Object adapter,Page page){ADAPTER_PAGES.put(adapter,page);}
 static boolean hasAdapter(Object adapter){return ADAPTER_PAGES.containsKey(adapter);}
 static boolean superLong(Object adapter,Object row){Page page=ADAPTER_PAGES.get(adapter);if(page==null||page.selecting)return page!=null;String url=ListActions.value(row,"videourl");for(JSONObject video:page.visible)if(url.equals(video.optString("url"))){page.selecting=true;page.toggle(video.optString("id"));return true;}return false;}
 static void withAdapterMode(Activity host,Object adapter,Runnable action){Page page=ADAPTER_PAGES.get(adapter);if(page==null||(!page.continuous&&!page.shuffle)){action.run();return;}Class<?> list;java.lang.reflect.Field enabled,mode;boolean oldEnabled;int oldMode;try{list=Class.forName("com.sauzask.nicoid.NicoidVideoListActivity");enabled=list.getField("I");mode=list.getField("J");oldEnabled=enabled.getBoolean(null);oldMode=mode.getInt(null);enabled.setBoolean(null,true);}catch(Exception e){android.util.Log.w("nicoid-playlist","Unable to apply folder playback mode",e);action.run();return;}try{PlaylistPlayback.withMode(page.shuffle,action);}finally{try{enabled.setBoolean(null,oldEnabled);mode.setInt(null,oldMode);}catch(Exception e){android.util.Log.w("nicoid-playlist","Unable to restore folder playback mode",e);}}}
 public static boolean home(Activity a,MenuItem item){return item.getItemId()==android.R.id.home&&back(a);}
 public static boolean back(Activity a){Page p=PAGES.get(a);if(p==null)return false;if(p.selecting){p.selecting=false;p.selected.clear();p.render();return true;}if(p.folder!=null){p.folder=null;p.render();return true;}return false;}
 public static boolean options(Activity a,Menu menu){Page p=PAGES.get(a);if(p==null)return false;menu.add(tr(a,"プレイリスト作成","Create playlist","建立播放清單")).setShowAsAction(MenuItem.SHOW_AS_ACTION_NEVER);menu.getItem(menu.size()-1).setOnMenuItemClickListener(i->{create(a,id->p.render());return true;});if(p.folder!=null){menu.add(tr(a,"フォルダーを削除","Delete folder","刪除資料夾")).setOnMenuItemClickListener(i->{p.deleteFolder();return true;});menu.add(tr(a,"複数選択","Select multiple","選取多個")).setOnMenuItemClickListener(i->{p.selecting=true;p.render();return true;});}return true;}
 public static boolean menuOrFeed(Activity a,Menu menu){if(options(a,menu))return true;try{return (Boolean)Class.forName("e.e.a.FollowFeed").getMethod("menu",Activity.class,Menu.class).invoke(null,a,menu);}catch(Exception e){return false;}}
 public static void loadOrFeed(Activity a){if(open(a)||ChannelPage.open(a))return;try{Class.forName("e.e.a.FollowFeed").getMethod("load",Activity.class).invoke(null,a);}catch(Exception e){android.util.Log.w("nicoid-page","Unable to open page",e);}}
 @SuppressWarnings({"rawtypes","unchecked"})public static void menu(Context c,ArrayList rows){for(int n=0;n<rows.size();n++){Object row=rows.get(n);if(!(row instanceof Map))continue;Object intent=((Map)row).get("intent");if(intent instanceof Intent){String target=((Intent)intent).getComponent()==null?"":((Intent)intent).getComponent().getClassName();if(target.endsWith("NicoidVideoListActivity")&&((Intent)intent).getIntExtra("type",-1)==8){Map entry=new HashMap();entry.put("title",tr(c,"プレイリスト","Playlists","播放清單"));entry.put("subtitle",tr(c,"本体に保存した動画のリスト","Video lists saved on this device","儲存在此裝置的影片清單"));entry.put("islabel",false);entry.put("type",0);entry.put("intent",new Intent().setClassName(c,"com.sauzask.nicoid.NicoidNicorepoActivity").putExtra("nicoid_local_playlists",true));rows.add(n+1,entry);return;}}}}
 static final class Page {
  final Activity a;final LinearLayout root;final Set<String> selected=new HashSet<>();String folder=null;boolean selecting,continuous,shuffle;int sort;Object images;List<JSONObject> visible=new ArrayList<>();
  Page(Activity a){this.a=a;folder=a.getIntent().hasExtra("nicoid_playlist_folder")?a.getIntent().getStringExtra("nicoid_playlist_folder"):null;root=PanelUi.column(a);ThemeChoice.background(root);}
  void toolbar(String title){try{Object bar=Review181.field(a,"O");bar.getClass().getMethod("b",CharSequence.class).invoke(bar,title);bar.getClass().getMethod("c",CharSequence.class).invoke(bar,tr(a,"プレイリスト","Playlists","播放清單"));}catch(Exception ignored){}a.invalidateOptionsMenu();}
  void render(){if(folder==null)a.getIntent().removeExtra("nicoid_playlist_folder");else a.getIntent().putExtra("nicoid_playlist_folder",folder);root.removeAllViews();LocalPlaylistData data=read(a);if(folder!=null&&!data.hasFolder(folder))folder=null;if(folder==null){toolbar(tr(a,"プレイリスト一覧","Playlists","播放清單"));ListView list=new ListView(a);List<String> ids=new ArrayList<>(),names=new ArrayList<>();ids.add("");names.add(tr(a,"フォルダー未分類","Unfiled videos","未分類影片"));for(int n=0;n<data.folders.length();n++){JSONObject f=data.folders.optJSONObject(n);ids.add(f.optString("id"));names.add(f.optString("name"));}list.setAdapter(new ArrayAdapter<String>(a,android.R.layout.simple_list_item_1,names));list.setOnItemClickListener((p,v,n,id)->{folder=ids.get(n);selecting=false;selected.clear();render();});list.setOnItemLongClickListener((p,v,n,id)->{if(n<=0)return false;String target=ids.get(n),label=names.get(n);confirmFolderDelete(a,target,label,this::render);return true;});root.addView(list,new LinearLayout.LayoutParams(-1,0,1));return;}
   String name=tr(a,"フォルダー未分類","Unfiled videos","未分類影片");for(int n=0;n<data.folders.length();n++)if(folder.equals(data.folders.optJSONObject(n).optString("id")))name=data.folders.optJSONObject(n).optString("name");toolbar(name);
   LinearLayout playback=new LinearLayout(a);playback.setGravity(Gravity.CENTER_VERTICAL);playback.setPadding(PanelUi.dp(a,8),0,PanelUi.dp(a,8),0);CheckBox sequential=new CheckBox(a),random=new CheckBox(a);sequential.setText(tr(a,"連続再生","Continuous play","連續播放"));random.setText(tr(a,"シャッフル再生","Shuffle play","隨機播放"));PanelUi.tint(sequential);PanelUi.tint(random);sequential.setChecked(continuous);random.setChecked(shuffle);playback.addView(sequential,new LinearLayout.LayoutParams(0,PanelUi.dp(a,48),1));playback.addView(random,new LinearLayout.LayoutParams(0,PanelUi.dp(a,48),1));root.addView(playback);boolean[] syncing={false};sequential.setOnCheckedChangeListener((b,checked)->{if(syncing[0])return;continuous=checked;if(checked&&shuffle){syncing[0]=true;shuffle=false;random.setChecked(false);syncing[0]=false;}});random.setOnCheckedChangeListener((b,checked)->{if(syncing[0])return;shuffle=checked;if(checked&&continuous){syncing[0]=true;continuous=false;sequential.setChecked(false);syncing[0]=false;}});
   Spinner order=new Spinner(a);order.setAdapter(new ArrayAdapter<String>(a,android.R.layout.simple_spinner_dropdown_item,new String[]{tr(a,"新しい順","Newest first","由新到舊"),tr(a,"古い順","Oldest first","由舊到新"),tr(a,"タイトル順","Title","標題順")}));order.setSelection(sort);order.setPadding(PanelUi.dp(a,8),0,PanelUi.dp(a,8),0);root.addView(order,new LinearLayout.LayoutParams(-1,PanelUi.dp(a,40)));order.setOnItemSelectedListener(new AdapterView.OnItemSelectedListener(){public void onNothingSelected(AdapterView<?> p){}public void onItemSelected(AdapterView<?> p,View v,int n,long id){if(sort!=n){sort=n;render();}}});
   visible=new ArrayList<>();for(int n=0;n<data.videos.length();n++){JSONObject v=data.videos.optJSONObject(n);if(folder.equals(v.optString("folder"))&&!ContentFilter.blocked(a,v.optString("title"),v.optString("owner")))visible.add(v);}Collections.sort(visible,(l,r)->sort==2?l.optString("title").compareToIgnoreCase(r.optString("title")):sort==1?Long.compare(l.optLong("date"),r.optLong("date")):Long.compare(r.optLong("date"),l.optLong("date")));
   ListView list=new ListView(a);ArrayList<Object> rows=new ArrayList<>();Map<Object,JSONObject> identities=new IdentityHashMap<>();try{Class<?> x=Class.forName("e.e.a.x1"),ic=Class.forName("e.e.a.y0");if(images==null){images=ic.getConstructor(Context.class).newInstance(a);a.getClass().getField("G").set(a,images);}for(JSONObject video:visible){Object row=x.getConstructor().newInstance();java.lang.reflect.Method put=x.getMethod("a",String.class,Object.class);put.invoke(row,"title",video.optString("title"));put.invoke(row,"videourl",video.optString("url"));put.invoke(row,"thumbnail",video.optString("thumbnail"));for(String key:new String[]{"length","videoinfo","posttime"})put.invoke(row,key,new SpannableString(video.optString(key,key.equals("posttime")?android.text.format.DateFormat.format("yyyy/MM/dd HH:mm",video.optLong("date")).toString():"")));x.getField("b").set(row,video.optString("videoId"));x.getField("y").set(row,video.optString("owner"));rows.add(row);identities.put(row,video);}BaseAdapter nativeRows=(BaseAdapter)Class.forName("e.e.a.b0").getConstructor(Context.class,ArrayList.class,int.class,ic).newInstance(a,rows,0,images);nativeRows.getClass().getField("l").set(nativeRows,Class.forName("e.e.a.b1").getConstructor(Activity.class).newInstance(a));list.setAdapter(new BaseAdapter(){public int getCount(){return nativeRows.getCount();}public Object getItem(int n){return nativeRows.getItem(n);}public long getItemId(int n){return n;}public View getView(int n,View old,ViewGroup parent){View row=nativeRows.getView(n,null,parent);if(!selecting)ListActions.bind(row,nativeRows,n);if(selecting){JSONObject v=identities.get(rows.get(n));boolean checked=selected.contains(v.optString("id"));disable(row);FrameLayout frame=new FrameLayout(a);frame.addView(row);TextView mark=PanelUi.text(a,checked?"✓":"□",22);mark.setTextColor(UiDialogs.accent(a));frame.addView(mark,new FrameLayout.LayoutParams(PanelUi.dp(a,40),-2,Gravity.END|Gravity.TOP));frame.setOnClickListener(w->toggle(v.optString("id")));frame.setBackgroundColor(checked?(UiDialogs.accent(a)&0xffffff)|0x33000000:android.graphics.Color.TRANSPARENT);return frame;}return row;}});registerAdapter(nativeRows,this);list.setOnItemClickListener((p,v,n,id)->{if(n>=rows.size())return;JSONObject video=identities.get(rows.get(n));if(selecting)toggle(video.optString("id"));else PlaylistPlayback.launchTap(a,video.optString("url"),video.optString("title"),rows,n,continuous||shuffle,shuffle);});}catch(Exception e){android.util.Log.w("nicoid-playlist","Unable to build video list",e);}
   root.addView(list,new LinearLayout.LayoutParams(-1,0,1));if(visible.isEmpty()){TextView empty=PanelUi.text(a,tr(a,"動画はありません","No videos","沒有影片"),14);empty.setGravity(Gravity.CENTER);root.addView(empty);}if(selecting){LinearLayout footer=PanelUi.column(a);footer.addView(BulkSelection.countLabel(a,selected.size()));LinearLayout all=new LinearLayout(a);button(all,tr(a,"全選択","Select all","全選"),()->{for(JSONObject v:visible)selected.add(v.optString("id"));render();});button(all,tr(a,"全解除","Clear all","取消全選"),()->{selected.clear();render();});footer.addView(all);LinearLayout actions=new LinearLayout(a);button(actions,tr(a,"削除","Delete","刪除"),this::delete);button(actions,tr(a,"移動","Move","移動"),()->choose(a,folder,to->{try{LocalPlaylistData d=read(a);d.move(selected,to);if(save(a,d)){selected.clear();selecting=false;render();}}catch(Exception e){Toast.makeText(a,tr(a,"移動に失敗しました","Unable to move","移動失敗"),1).show();}}));button(actions,tr(a,"完了","Done","完成"),()->{selecting=false;selected.clear();render();});footer.addView(actions);root.addView(footer);}
  }
  void deleteFolder(){if(folder==null||folder.isEmpty())return;String target=folder,name=tr(a,"プレイリスト","Playlist","播放清單");LocalPlaylistData d=read(a);for(int n=0;n<d.folders.length();n++){JSONObject f=d.folders.optJSONObject(n);if(target.equals(f.optString("id"))){name=f.optString("name");break;}}confirmFolderDelete(a,target,name,()->{folder=null;render();});}
  void toggle(String id){if(!selected.add(id))selected.remove(id);render();}
  void delete(){if(selected.isEmpty())return;UiDialogs.show(new AlertDialog.Builder(PlaybackSession.dialogContext(a)).setTitle(tr(a,"選択した動画を削除しますか？","Remove selected videos?","刪除所選影片？")).setMessage(Integer.toString(selected.size())).setPositiveButton(tr(a,"削除","Delete","刪除"),(d,w)->{LocalPlaylistData data=read(a);data.delete(selected);if(save(a,data)){selected.clear();selecting=false;render();}}).setNegativeButton(tr(a,"キャンセル","Cancel","取消"),null).create());}
  void button(LinearLayout row,String text,Runnable click){BulkSelection.button(row,text,click);}
  void disable(View v){v.setClickable(false);v.setLongClickable(false);if(v instanceof ViewGroup){ViewGroup g=(ViewGroup)v;for(int n=0;n<g.getChildCount();n++)disable(g.getChildAt(n));}}
 }
}
