package e.e.a;
import android.app.*;import android.content.*;import android.os.*;import android.view.*;import android.widget.*;import org.json.*;import java.net.*;import java.io.*;import java.util.*;import java.util.concurrent.*;
/** Modern authenticated writes; never retry a POST with an unknown result. */
public final class ModernPosting {
 private static final Handler MAIN=new Handler(Looper.getMainLooper());private static final ExecutorService WORK=Executors.newFixedThreadPool(2);private static final Set<Object> BUSY=Collections.newSetFromMap(new WeakHashMap<Object,Boolean>());
 static Object get(Object o,String k)throws Exception{return o.getClass().getField(k).get(o);}static String tr(Context c,String j,String e,String z){return PanelUi.tr(c,j,e,z);}
 static void message(Activity a,String s){if(!a.isFinishing())Toast.makeText(a,s,1).show();}
 static JSONObject watch(String id,NetworkTask t)throws Exception{return DetailData.watchData(VideoDetails.request("https://www.nicovideo.jp/watch/"+id+"?responseType=json","GET",true,t));}
 public static void comment(Object fragment,String text,String commands){try{Activity a=(Activity)get(fragment,"A1");VideoDetails.initializeCookies(a);if(text==null||text.trim().isEmpty())return;if(!VideoDetails.cookie().contains("user_session=")){message(a,tr(a,"ログインが必要です","Sign in required","請先登入"));return;}synchronized(BUSY){if(!BUSY.add(fragment))return;}String id=HistoryRules.id((String)get(fragment,"b0"));Object player=get(fragment,"a0");long position=(Long)player.getClass().getMethod("getCurrentPosition").invoke(player);NetworkTask task=new NetworkTask();WORK.execute(()->{boolean ok=false;try{JSONObject data=watch(id,task),comment=data.optJSONObject("comment"),nv=comment==null?null:comment.optJSONObject("nvComment");if(nv==null)throw new IOException("No comment metadata");JSONObject params=nv.getJSONObject("params");JSONArray targets=params.getJSONArray("targets");String thread="";for(int n=0;n<targets.length();n++){JSONObject target=targets.getJSONObject(n);if("main".equals(target.optString("fork"))){thread=target.optString("id");break;}}if(thread.isEmpty())throw new IOException("No main thread");String key=VideoDetails.request("https://nvapi.nicovideo.jp/v1/comment/keys/post?threadId="+UriEncode(thread),"GET",true,task).getJSONObject("data").getString("postKey");JSONArray cmd=new JSONArray();for(String token:(commands==null?"":commands).trim().split("\\s+"))if(!token.isEmpty())cmd.put(token);JSONObject body=new JSONObject().put("videoId",data.getJSONObject("video").optString("id",id)).put("commands",cmd).put("body",text).put("vposMs",Math.max(0,position)).put("postKey",key);String server=nv.optString("server","https://nvcomment.nicovideo.jp");if(!server.matches("https://(?:public\\.)?nv-?comment\\.nicovideo\\.jp/?"))throw new IOException("Unsupported comment server");jsonPost(server.replaceAll("/$","")+"/v1/threads/"+UriEncode(thread)+"/comments",body,task);ok=true;}catch(Exception e){android.util.Log.w("nicoid-comment","Comment submission failed: "+e.getClass().getSimpleName());}finally{synchronized(BUSY){BUSY.remove(fragment);}}boolean success=ok;MAIN.post(()->message(a,tr(a,success?"コメントを投稿しました":"コメントを投稿できませんでした",success?"Comment posted":"Unable to post comment",success?"已發送留言":"無法發送留言")));});}catch(Exception e){android.util.Log.w("nicoid-comment","Unable to prepare comment",e);synchronized(BUSY){BUSY.remove(fragment);}}}
 private static String UriEncode(String s){return android.net.Uri.encode(s);}
 static JSONObject jsonPost(String url,JSONObject body,NetworkTask task)throws Exception{HttpURLConnection c=(HttpURLConnection)new URL(url).openConnection();if(!task.bind(c))throw new InterruptedIOException();try{c.setRequestMethod("POST");c.setConnectTimeout(10000);c.setReadTimeout(10000);c.setInstanceFollowRedirects(false);c.setRequestProperty("Content-Type","application/json");c.setRequestProperty("X-Frontend-Id","6");c.setRequestProperty("X-Frontend-Version","0");c.setRequestProperty("X-Request-With","https://www.nicovideo.jp");c.setRequestProperty("X-Requested-With","https://www.nicovideo.jp");c.setRequestProperty("Origin","https://www.nicovideo.jp");c.setRequestProperty("Cookie",VideoDetails.cookie());byte[] b=body.toString().getBytes("UTF-8");c.setDoOutput(true);c.setFixedLengthStreamingMode(b.length);try(OutputStream out=c.getOutputStream()){out.write(b);}int status=c.getResponseCode();if(status<200||status>=300)throw new IOException("HTTP "+status);ByteArrayOutputStream out=new ByteArrayOutputStream();try(InputStream in=c.getInputStream()){byte[] buffer=new byte[4096];int n;while((n=in.read(buffer))!=-1){if(out.size()+n>2*1024*1024)throw new IOException("Response too large");out.write(buffer,0,n);}}JSONObject result=out.size()==0?new JSONObject():new JSONObject(out.toString("UTF-8"));JSONObject meta=result.optJSONObject("meta");if(meta!=null&&meta.optInt("status",200)>=300)throw new IOException("Request rejected");return result;}finally{task.release(c);c.disconnect();}}
 public static void later(Object owner,String video){try{Activity a=(Activity)get(owner,"b");VideoDetails.initializeCookies(a);String id=HistoryRules.id(video);AlertDialog d=new AlertDialog.Builder(PlaybackSession.dialogContext(a)).setTitle(UiStrings.translate("とりあえずマイリスト登録")).setMessage(id).setPositiveButton(tr(a,"登録","Add","新增"),(x,w)->{if(!VideoDetails.cookie().contains("user_session=")){message(a,tr(a,"ログインが必要です","Sign in required","請先登入"));return;}synchronized(BUSY){if(!BUSY.add(owner))return;}WORK.execute(()->{boolean ok=false;try{VideoDetails.request("https://nvapi.nicovideo.jp/v1/users/me/watch-later?watchId="+UriEncode(id),"POST",true,new NetworkTask());ok=true;}catch(Exception e){android.util.Log.w("nicoid-list","Watch-later submission failed: "+e.getClass().getSimpleName());}finally{synchronized(BUSY){BUSY.remove(owner);}}boolean success=ok;MAIN.post(()->message(a,tr(a,success?"登録しました":"登録できませんでした",success?"Added":"Unable to add",success?"已新增":"無法新增")));});}).setNegativeButton(tr(a,"キャンセル","Cancel","取消"),null).create();PlaybackSession.showDialog(d);}catch(Exception e){android.util.Log.w("nicoid-list","Unable to prepare watch-later dialog",e);}}
}
