package e.e.a;
import android.app.*;import android.content.*;import android.preference.*;import android.os.*;import android.view.*;import android.widget.*;import org.json.*;import java.util.*;import java.util.concurrent.*;
public final class NgCommentSettings {
 private static final String URL="https://nvapi.nicovideo.jp/v1/users/me/ng-comments/client";
 private static final ExecutorService WORK=Executors.newSingleThreadExecutor();private static final Handler MAIN=new Handler(Looper.getMainLooper());
 static String tr(Context c,String j,String e,String z){return PanelUi.tr(c,j,e,z);}
 static void install(PreferenceActivity a,PreferenceGroup group){if(a.findPreference("nicoid_ng_comments")!=null)return;Preference p=new Preference(a);p.setKey("nicoid_ng_comments");p.setTitle(tr(a,"NGコメントリスト","NG comment list","NG 留言清單"));p.setSummary(tr(a,"NGワード・NGユーザー・NGコマンドを管理","Manage blocked words, users and commands","管理封鎖文字、使用者與指令"));p.setOnPreferenceClickListener(v->{show(a);return true;});group.addPreference(p);}
 static JSONArray items(String raw){return NgCommentData.items(raw);}
 static String typeLabel(Context c,String type){return type.equals("word")?tr(c,"NGワード","Blocked word","封鎖文字"):type.equals("id")?tr(c,"NGユーザー","Blocked user","封鎖使用者"):type.equals("command")?tr(c,"NGコマンド","Blocked command","封鎖指令"):type;}
 static void show(PreferenceActivity a){new ListDialog(a).show();}
 private static final class ListDialog {
  final PreferenceActivity activity;final Context context;final SharedPreferences prefs;final LinearLayout body,rows,actions;final TextView status;final Button add,delete,clear;final Set<String> selected=new HashSet<>();final AlertDialog dialog;final boolean online;JSONArray data;boolean busy,choosing;NetworkTask active;
  ListDialog(PreferenceActivity a){activity=a;context=PlaybackSession.dialogContext(a);prefs=PreferenceManager.getDefaultSharedPreferences(a);VideoDetails.initializeCookies(a);online=!prefs.getBoolean("nologin",false)&&VideoDetails.cookie().contains("user_session=");data=items(prefs.getString("saveNGList","{}"));body=PanelUi.column(context);status=PanelUi.text(context,"",13);body.addView(status);ScrollView scroll=new ScrollView(context);rows=PanelUi.column(context);scroll.addView(rows);body.addView(scroll,new LinearLayout.LayoutParams(-1,Math.min(PanelUi.dp(context,400),context.getResources().getDisplayMetrics().heightPixels/2)));actions=new LinearLayout(context);add=PanelUi.button(context,tr(context,"追加","Add","新增"));delete=PanelUi.button(context,tr(context,"選択した項目を削除","Delete selected","刪除所選項目"));clear=PanelUi.button(context,tr(context,"選択解除","Clear selection","取消選取"));for(Button b:new Button[]{add,delete,clear})actions.addView(b,new LinearLayout.LayoutParams(0,-2,1));body.addView(actions);dialog=new AlertDialog.Builder(context).setTitle(tr(context,"NGコメントリスト","NG comment list","NG 留言清單")).setView(body).setNegativeButton(tr(context,"閉じる","Close","關閉"),null).create();dialog.setOnDismissListener(v->{if(active!=null)active.cancel();});add.setOnClickListener(v->add());delete.setOnClickListener(v->confirm(new HashSet<>(selected)));clear.setOnClickListener(v->{selected.clear();choosing=false;render();});}
  void show(){PlaybackSession.showDialog(dialog);render();if(online)refresh();}
  void state(boolean value,boolean mutation){busy=value;add.setEnabled(!busy);clear.setEnabled(!busy);delete.setEnabled(!busy&&!selected.isEmpty());dialog.setCancelable(!value||!mutation);dialog.getButton(-2).setEnabled(!value||!mutation);}
  void save(){try{prefs.edit().putString("saveNGList",NgCommentData.stored(data)).commit();}catch(Exception ignored){}}
  void applyPlayer(){try{Class<?> type=Class.forName("e.e.a.g0");Object store=type.getConstructor(Context.class,Boolean.class).newInstance(activity,Boolean.FALSE);type.getMethod("a").invoke(store);}catch(Exception ignored){}}
  void render(){rows.removeAllViews();add.setVisibility(choosing?View.GONE:View.VISIBLE);delete.setVisibility(choosing?View.VISIBLE:View.GONE);clear.setVisibility(choosing?View.VISIBLE:View.GONE);delete.setEnabled(!busy&&!selected.isEmpty());if(data.length()==0)rows.addView(PanelUi.text(context,tr(context,"登録されたNG設定はありません","No NG rules","尚無 NG 規則"),14));for(int i=0;i<data.length();i++){JSONObject o=data.optJSONObject(i);if(o==null)continue;String key=NgCommentData.key(o);LinearLayout row=PanelUi.column(context);row.addView(PanelUi.text(context,(choosing?(selected.contains(key)?"✓ ":"□ "):"")+o.optString("source"),16));row.addView(PanelUi.text(context,typeLabel(context,o.optString("type")),12));row.setOnClickListener(v->{if(busy)return;if(choosing){if(!selected.add(key))selected.remove(key);render();}else confirm(Collections.singleton(key));});row.setOnLongClickListener(v->{if(busy)return true;choosing=true;if(!selected.add(key))selected.remove(key);render();return true;});rows.addView(row);PanelUi.divider(rows);}}
  void refresh(){state(true,false);status.setVisibility(View.VISIBLE);status.setText(tr(context,"更新中…","Refreshing…","更新中…"));NetworkTask task=new NetworkTask();active=task;task.start(WORK,()->{try{JSONObject response=VideoDetails.request(URL,"GET",true,task);JSONObject d=response.optJSONObject("data");if(d==null||d.optJSONArray("items")==null)throw new java.io.IOException();JSONArray updated=d.getJSONArray("items");MAIN.post(()->{if(task.cancelled())return;data=updated;save();state(false,false);status.setVisibility(View.GONE);render();});}catch(Exception e){MAIN.post(()->{if(task.cancelled())return;state(false,false);status.setText(tr(context,"更新できませんでした。保存済みのリストを表示しています","Unable to refresh. Showing the saved list","無法更新，顯示已儲存清單"));});}});}
  void add(){LinearLayout form=PanelUi.column(context);RadioGroup types=new RadioGroup(context);String[] values={"word","id","command"};for(int i=0;i<values.length;i++){RadioButton b=new RadioButton(context);b.setId(200+i);b.setText(typeLabel(context,values[i]));PanelUi.tint(b);types.addView(b);}types.check(200);form.addView(types);EditText value=new EditText(context);value.setHint(tr(context,"NGにする文字・ユーザーID・コマンド","Word, user ID or command to block","封鎖文字、使用者 ID 或指令"));form.addView(value);AlertDialog editor=new AlertDialog.Builder(context).setTitle(tr(context,"NGコメントを追加","Add NG rule","新增 NG 規則")).setView(form).setPositiveButton(tr(context,"追加","Add","新增"),null).setNegativeButton(tr(context,"キャンセル","Cancel","取消"),null).create();PlaybackSession.showForm(editor);value.setTextColor(PanelUi.ink(context));value.setHintTextColor(ThemeChoice.isNight(context)?0xffb7bac3:0xff666a73);value.setBackgroundTintList(android.content.res.ColorStateList.valueOf(ThemeChoice.accent(activity)));editor.getButton(-1).setOnClickListener(v->{String source=value.getText().toString();if(source.trim().isEmpty()){value.setError(tr(context,"文字を入力してください","Enter a value","請輸入文字"));return;}try{JSONObject item=new JSONObject().put("type",values[types.getCheckedRadioButtonId()-200]).put("source",source);if(NgCommentData.contains(data,item)){value.setError(tr(context,"すでに登録されています","Already registered","已經登錄"));return;}editor.dismiss();mutate(item,null);}catch(Exception ignored){}});}
  void confirm(Set<String> keys){if(keys.isEmpty())return;String message=keys.size()==1?source(keys.iterator().next()):keys.size()+tr(context,"件"," rules","項");AlertDialog d=new AlertDialog.Builder(context).setTitle(tr(context,"NG設定を削除しますか？","Delete NG rules?","刪除 NG 規則？")).setMessage(message).setPositiveButton(tr(context,"削除","Delete","刪除"),(v,w)->mutate(null,keys)).setNegativeButton(tr(context,"キャンセル","Cancel","取消"),null).create();PlaybackSession.showDialog(d);}
  String source(String key){for(int i=0;i<data.length();i++){JSONObject o=data.optJSONObject(i);if(o!=null&&NgCommentData.key(o).equals(key))return o.optString("source");}return "";}
  void mutate(JSONObject addition,Set<String> deletion){if(busy)return;state(true,true);status.setVisibility(View.VISIBLE);status.setText(tr(context,"保存中…","Saving…","儲存中…"));NetworkTask task=new NetworkTask();active=task;task.start(WORK,()->{boolean failed=false;try{if(addition!=null){if(online)VideoDetails.request(URL,"POST",true,task,NgCommentData.form(addition.getString("type"),addition.getString("source")));data=NgCommentData.add(data,addition);save();}else{ArrayList<JSONObject> targets=new ArrayList<>();for(int i=0;i<data.length();i++){JSONObject o=data.optJSONObject(i);if(o!=null&&deletion.contains(NgCommentData.key(o)))targets.add(o);}for(JSONObject o:targets){if(task.cancelled())throw new java.io.InterruptedIOException();if(online)VideoDetails.request(URL,"DELETE",true,task,NgCommentData.form(o.getString("type"),o.getString("source")));data=NgCommentData.remove(data,Collections.singleton(NgCommentData.key(o)));save();}}}catch(Exception e){failed=true;}final boolean error=failed;MAIN.post(()->{if(task.cancelled())return;applyPlayer();state(false,false);selected.clear();choosing=false;render();if(error)status.setText(tr(context,"一部の変更を保存できませんでした。保存に成功した変更のみ反映しました","Some changes could not be saved. Only successful changes were applied","部分變更無法儲存，僅套用成功的變更"));else status.setVisibility(View.GONE);});});}
 }
}
