package e.e.a;

import java.util.HashMap;
import java.util.Locale;
import java.util.Map;

/** Runtime UI translations use the locale selected by nicoid's app language setting. */
public final class UiStrings {
    private static final Map<String, String[]> TEXT = new java.util.LinkedHashMap<>();
    private static final Map<String,String> JAPANESE_ALIASES = new HashMap<>();
    private static final Map<String,String> JAPANESE_LOOKUP = new HashMap<>();
    // 0 = Japanese, 1 = English, 2 = Traditional Chinese; -1 follows the device locale.
    private static volatile int selectedLanguage = -1;
    static {
        TEXT.put("起動時の画面", new String[]{"Startup screen", "啟動畫面"});
        TEXT.put("ニコレポ", new String[]{"Nico Reports", "Nico 動態"});
        TEXT.put("投稿者のフォローボタンを表示", new String[]{"Show creator follow button", "顯示投稿者追蹤按鈕"});
        TEXT.put("動画情報にフォローボタンを表示します", new String[]{"Show a follow button in video details", "在影片資訊顯示追蹤按鈕"});
        TEXT.put("コメントを太字にする", new String[]{"Bold comments", "粗體留言"});
        TEXT.put("次の再生から反映されます", new String[]{"Applies on the next playback", "下次播放時生效"});
        JAPANESE_ALIASES.put("I will change the language of the entire application.", "アプリ全体の言語を変更します。");
        JAPANESE_ALIASES.put("External memory (SD card)", "外部メモリ（SDカード）");
        JAPANESE_ALIASES.put("None (view all)", "指定なし（すべて表示）");
        JAPANESE_ALIASES.put("Are you sure you want to delete all the cache?", "キャッシュをすべて削除しますか？");
        JAPANESE_ALIASES.put("I set the comment drawing frame rate limit.", "コメント描画フレームレートの上限を設定します。");
        JAPANESE_ALIASES.put("I will change the display method suitable for each tablet, smartphone", "タブレットやスマートフォンに適した表示方法を設定します。");
        JAPANESE_ALIASES.put("I will change the method of playing videos (streaming / cache)", "動画の再生方法（ストリーミング／キャッシュ）を設定します。");
        JAPANESE_ALIASES.put("I will change the language of the comment and video information. (The default is subject to the language of the entire application.)", "コメント・動画情報の言語を変更できます（デフォルトはアプリ全体の言語に従います）。");
        JAPANESE_ALIASES.put("And what to do when you tap the video list. (Item other than that you set will be displayed by tapping the triangle in the bottom right-hand corner.)", "動画リストをタップしたときの動作を設定します（設定以外の項目は右下の三角をタップすると表示されます）。");
        JAPANESE_ALIASES.put("Video List of cached (Viewable offline)", "キャッシュ取得済みの動画（オフライン視聴可能）");
        JAPANESE_ALIASES.put("Keywords video, tag search", "動画のキーワード、タグ検索");
        JAPANESE_ALIASES.put("Language", "言語");
        JAPANESE_ALIASES.put("Pop-up playback", "ポップアップ再生");

        TEXT.put("件。", new String[]{" comments. ", " 則留言。"});
        TEXT.put("設定", new String[]{"Settings", "設定"});
        TEXT.put("標準", new String[]{"Standard", "標準"});
        TEXT.put("自動", new String[]{"Automatic", "自動"});
        TEXT.put("速度", new String[]{"Speed", "速度"});
        TEXT.put("倍", new String[]{"×", "倍"});
        TEXT.put("最小", new String[]{"Minimum", "最小"});
        TEXT.put("小", new String[]{"Small", "小"});
        TEXT.put("大", new String[]{"Large", "大"});
        TEXT.put("最大", new String[]{"Maximum", "最大"});
        TEXT.put("料理", new String[]{"Cooking", "料理"});
        TEXT.put("自然", new String[]{"Nature", "自然"});
        TEXT.put("動物", new String[]{"Animals", "動物"});
        TEXT.put("不登入使用", new String[]{"Use without signing in", "不登入使用"});
        TEXT.put("播放模式", new String[]{"Playback mode", "播放模式"});
        TEXT.put("已儲存設定", new String[]{"Settings saved", "已儲存設定"});
        TEXT.put("Language", new String[]{"Language", "語言"});
        TEXT.put("Pop-up playback", new String[]{"Pop-up playback", "懸浮視窗播放"});
        TEXT.put("登入成功", new String[]{"Signed in successfully", "登入成功"});

        TEXT.put("デフォルトに戻す", new String[]{"Reset to default", "還原預設值"});
        TEXT.put("キャッシュのみを使用し再生", new String[]{"Play using cached files only", "僅使用快取播放"});
        TEXT.put("常に使用", new String[]{"Always", "一律使用"});
        TEXT.put("モバイル通信時のみ", new String[]{"On mobile data only", "僅使用行動網路時"});
        TEXT.put("使用しない", new String[]{"Never", "不使用"});
        TEXT.put("モバイル通信時の画質", new String[]{"Quality on mobile data", "行動網路畫質"});
        TEXT.put("品質", new String[]{"Quality", "畫質"});
        TEXT.put("コメント取得数", new String[]{"Comments to load", "留言載入數量"});
        TEXT.put("取得数：", new String[]{"Target: ", "目標："});
        TEXT.put("次回の再生から反映されます。追加取得数は動画やログイン状態により異なります。", new String[]{"Applies on the next playback. The number of additional comments depends on the video and sign-in status.", "下次播放時生效。可額外載入的留言數量依影片及登入狀態而異。"});
        TEXT.put("デバッグログの保存", new String[]{"Save debug log", "儲存偵錯紀錄"});
        TEXT.put("再生状況と通信結果をDownloadフォルダに保存", new String[]{"Save playback and network diagnostics to Downloads", "將播放與網路診斷記錄儲存至 Downloads"});
        TEXT.put("再生状況や通信エラーなどの診断ログを Download フォルダに保存します。不具合報告時に利用できます。", new String[]{"Save diagnostic logs, including playback status and network errors, to the Downloads folder for troubleshooting.", "將播放狀態與網路錯誤等診斷記錄儲存至 Downloads 資料夾，以便排查問題。"});

        TEXT.put("ニコる数順", new String[]{"Nicoru count", "Nico 讚數量順序"});
        TEXT.put("コメント取得数", new String[]{"Comments to load", "留言載入數量"});
        TEXT.put("標準（追加取得なし）", new String[]{"Standard (no additional loading)", "標準（不額外載入）"});
        TEXT.put("次の再生から反映。追加取得できる件数は動画やログイン状態によって異なります", new String[]{"Applies on the next playback. Additional comments depend on the video and sign-in status.", "下次播放時生效。可額外載入的留言數量依影片及登入狀態而異。"});
        TEXT.put("再生位置に自動追従", new String[]{"Follow playback position", "自動跟隨播放位置"});
        TEXT.put("再生時間順", new String[]{"Playback time", "播放時間順序"});
        TEXT.put("投稿時間順", new String[]{"Posting time", "發佈時間順序"});
        TEXT.put("コメントの影の種類", new String[]{"Comment shadow style", "彈幕陰影樣式"});
        TEXT.put("コメントの影の大きさ", new String[]{"Comment shadow size", "彈幕陰影大小"});
        TEXT.put("コメントの最大行数", new String[]{"Maximum comment rows", "彈幕最大行數"});
        TEXT.put("コメントの表示時間", new String[]{"Comment display duration", "彈幕顯示時間"});
        TEXT.put("通常の画質設定に従う", new String[]{"Use the default quality setting", "使用預設畫質設定"});
        TEXT.put("ランキング", new String[]{"Rankings", "排行榜"});

        TEXT.put("旧コメント経路の取得上限", new String[]{"Legacy comment path limit", "舊留言路徑載入上限"});
        TEXT.put("旧コメント経路にのみ適用。次の再生から反映", new String[]{"Legacy comment path only; applies on the next playback", "僅適用於舊留言路徑，下次播放時生效"});
        TEXT.put("自動（動画の長さに応じて変更）", new String[]{"Automatic (based on video length)", "自動（依影片長度調整）"});
        TEXT.put("件", new String[]{" comments", " 則"});
        TEXT.put("デバッグログをDownloadフォルダに保存しますか？", new String[]{"Save the debug log to Downloads?", "要將偵錯紀錄儲存至 Downloads 嗎？"});
        TEXT.put("保存", new String[]{"Save", "儲存"});
        TEXT.put("\u691c\u7d22\u30b5\u30b8\u30a7\u30b9\u30c8", new String[]{"Search suggestions", "\u641c\u5c0b\u5efa\u8b70"});
        TEXT.put("\u691c\u7d22\u5165\u529b\u6642\u306b\u5019\u88dc\u3092\u8868\u793a\u3057\u307e\u3059", new String[]{"Show suggestions while entering a search", "\u8f38\u5165\u641c\u5c0b\u6642\u986f\u793a\u5efa\u8b70"});
        TEXT.put("\u52d5\u4f5c\u3092\u5b89\u5b9a\u3055\u305b\u308b\u305f\u3081\u8868\u793a\u3059\u308b\u30b3\u30e1\u30f3\u30c8\u91cf\u3092\u5c11\u306a\u304f\u3057\u30d5\u30ec\u30fc\u30e0\u30ec\u30fc\u30c8\u3092\u4f4e\u304f\u5236\u9650\u3057\u307e\u3059\u3002", new String[]{"Reduce displayed comments and frame rate for stable casting.", "\u6e1b\u5c11\u986f\u793a\u7684\u5f48\u5e55\u6578\u91cf\u4e26\u9650\u5236\u5f71\u683c\u7387\uff0c\u4ee5\u7a69\u5b9a\u6295\u653e\u3002"});
        TEXT.put("\u30c7\u30d0\u30c3\u30b0\u30ed\u30b0\u306e\u4fdd\u5b58", new String[]{"Save debug log", "\u5132\u5b58\u5075\u932f\u8a18\u9304"});
        TEXT.put("\u518d\u751f\u72b6\u6cc1\u3068\u901a\u4fe1\u7d50\u679c\u3092Download\u30d5\u30a9\u30eb\u30c0\u306b\u4fdd\u5b58", new String[]{"Save playback and network logs to Downloads", "\u5c07\u64ad\u653e\u8207\u7db2\u8def\u8a18\u9304\u5132\u5b58\u81f3 Downloads"});
        TEXT.put("Download\u306b\u4fdd\u5b58\u3057\u307e\u3057\u305f", new String[]{"Saved to Downloads", "\u5df2\u5132\u5b58\u81f3 Downloads"});
        TEXT.put("\u30ed\u30b0\u3092\u4fdd\u5b58\u3067\u304d\u307e\u305b\u3093\u3067\u3057\u305f", new String[]{"Could not save the log", "\u7121\u6cd5\u5132\u5b58\u8a18\u9304"});

        TEXT.put("テーマ", new String[]{"Theme", "主題"});
        TEXT.put("ライトモード", new String[]{"Light mode", "淺色模式"});
        TEXT.put("ダークモード", new String[]{"Dark mode", "深色模式"});
        TEXT.put("再生速度変更", new String[]{"Change playback speed", "變更播放速度"});
        TEXT.put("スワイプで音量調整", new String[]{"Swipe to adjust volume", "滑動調整音量"});
        TEXT.put("上下スワイプで音量を調整します。輝度調整もONの場合は動画の右側で操作します", new String[]{"Swipe vertically to adjust volume. When brightness gestures are also enabled, use the right side of the video.", "上下滑動調整音量。若同時啟用亮度調整，請在影片右側操作。"});
        TEXT.put("スワイプで輝度調整", new String[]{"Swipe to adjust brightness", "滑動調整亮度"});
        TEXT.put("上下スワイプで再生画面の輝度を調整します。音量調整もONの場合は動画の左側で操作します", new String[]{"Swipe vertically to adjust video brightness. When volume gestures are also enabled, use the left side of the video.", "上下滑動調整播放畫面的亮度。若同時啟用音量調整，請在影片左側操作。"});
        TEXT.put("キャッシュのコピーが完了しました", new String[]{"Cache copy completed", "快取複製完成"});
        TEXT.put("キャッシュをコピー中", new String[]{"Copying cached videos…", "正在複製快取影片…"});
        TEXT.put("コピー", new String[]{"Copy", "複製"});
        TEXT.put("コピーに失敗しました。元のファイルは保持されています", new String[]{"Could not copy the cache. The original files have been kept.", "無法複製快取。原始檔案已保留。"});
        TEXT.put("フォルダー選択画面を開けませんでした", new String[]{"Could not open the folder picker", "無法開啟資料夾選擇畫面"});
        TEXT.put("以前の保存先からコピーします。元のファイルは削除しません", new String[]{"Copy cached videos from the previous folder. The original files will not be deleted.", "從先前的儲存位置複製快取影片。原始檔案不會被刪除。"});
        TEXT.put("保存先を使用できません。別のフォルダーを選択してください", new String[]{"Cannot use this folder. Please choose another one.", "無法使用此儲存位置。請選擇其他資料夾。"});
        TEXT.put("後で", new String[]{"Later", "稍後"});
        TEXT.put("既存キャッシュをコピー", new String[]{"Copy existing cache", "複製現有快取"});
        TEXT.put("設定でキャッシュ保存先を選択してください", new String[]{"Choose a cache folder in Settings", "請在設定中選擇快取儲存位置"});
        TEXT.put("キャスト再生中です", new String[]{"Casting video", "正在投放影片"});
        TEXT.put("ポップアップ再生を利用するには他のアプリの上に表示を許可してください", new String[]{"Allow display over other apps to use pop-up playback", "若要使用懸浮視窗播放，請允許顯示在其他應用程式上層"});
        TEXT.put("パーミッションの取得", new String[]{"Permissions", "權限"});
        TEXT.put("この動画はRTMPを使用している為再生できません", new String[]{"This video uses RTMP and cannot be played", "此影片使用 RTMP，無法播放"});
        TEXT.put("再生する", new String[]{"Play", "播放"});
        TEXT.put("再生リスト", new String[]{"Playlist", "播放清單"});
        TEXT.put("実況プレイ動画", new String[]{"Gameplay videos", "遊戲實況影片"});
        TEXT.put("バーチャル", new String[]{"Virtual", "虛擬"});
        TEXT.put("ランダム", new String[]{"Random", "隨機"});
        TEXT.put("人気が低い順", new String[]{"Least popular first", "人氣由低到高"});
        TEXT.put("人気が高い順", new String[]{"Most popular first", "人氣由高到低"});
        TEXT.put("並び順指定なし", new String[]{"Default order", "不指定排序"});
        TEXT.put("あなたにオススメの動画", new String[]{"Recommended for you", "為你推薦的影片"});
        TEXT.put("過去の視聴情報などからのオススメ動画", new String[]{"Videos recommended based on your viewing history", "根據觀看紀錄推薦的影片"});
        TEXT.put("端末との接続を解除", new String[]{"Disconnect from the device", "中斷與裝置的連線"});
        TEXT.put("既に登録済みです", new String[]{"Already added", "已加入"});
        TEXT.put("%s をお気に入りから解除しますか？", new String[]{"Remove %s from favorites?", "要將 %s 從我的最愛移除嗎？"});
        TEXT.put("フォローに失敗しました", new String[]{"Could not follow", "無法追蹤"});
        TEXT.put("フォローしました", new String[]{"Followed", "已追蹤"});
        TEXT.put("%s をフォローしますか？", new String[]{"Follow %s?", "要追蹤 %s 嗎？"});
        TEXT.put("フォロー", new String[]{"Follow", "追蹤"});
        TEXT.put("フォロー済み", new String[]{"Following", "已追蹤"});
        TEXT.put("昇順(上から下)", new String[]{"Ascending (top to bottom)", "遞增（由上到下）"});
        TEXT.put("降順(下から上)", new String[]{"Descending (bottom to top)", "遞減（由下到上）"});
        TEXT.put("再生:<b>%s</b> コメ:<b>%s</b> マイ:<b>%s</b> いいね:<b>%s</b>", new String[]{"Views:<b>%s</b> Comments:<b>%s</b> Mylists:<b>%s</b> Likes:<b>%s</b>", "觀看:<b>%s</b> 留言:<b>%s</b> 播放清單:<b>%s</b> 按讚:<b>%s</b>"});
        TEXT.put("ジャンル:<font color='#000000'><b>%s</b></font><br>過去最高:<font color='#000000'><b>%s</b></font>", new String[]{"Genre:<font color='#000000'><b>%s</b></font><br>Best rank:<font color='#000000'><b>%s</b></font>", "類別:<font color='#000000'><b>%s</b></font><br>最高排名:<font color='#000000'><b>%s</b></font>"});
        TEXT.put("カテゴリ:<font color='#000000'><b>%s</b></font><br>前日順位:<font color='#000000'><b>%s</b></font>(過去最高:<font color='#000000'><b>%s</b></font>)", new String[]{"Category:<font color='#000000'><b>%s</b></font><br>Yesterday:<font color='#000000'><b>%s</b></font> (Best:<font color='#000000'><b>%s</b></font>)", "分類:<font color='#000000'><b>%s</b></font><br>昨日排名:<font color='#000000'><b>%s</b></font>（最高排名:<font color='#000000'><b>%s</b></font>）"});
        TEXT.put("再生履歴の保存やキャッシュなどを取得する為にメディア、ファイルへのアクセス許可が必要です。\nアプリを再起動し再度許可ダイアログを表示させるか、端末の設定画面からアプリ→nicoidを選択し、ストレージのアクセス権限を付与してください。", new String[]{"Access to media and files is required to save watch history and download cached videos.\nRestart the app to show the permission dialog again, or grant storage access under Apps → nicoid in your device settings.", "儲存觀看紀錄及下載快取影片需要媒體與檔案存取權限。\n請重新啟動應用程式以再次顯示權限對話框，或在裝置設定的「應用程式 → nicoid」中授予儲存空間存取權限。"});
        TEXT.put("有料", new String[]{"Paid", "付費"});
        TEXT.put("本体ストレージ（アプリ専用フォルダー）", new String[]{"Device storage (app-specific folder)", "裝置儲存空間（應用程式專用資料夾）"});
        TEXT.put("SDカード（アプリ専用フォルダー）", new String[]{"SD card (app-specific folder)", "SD 卡（應用程式專用資料夾）"});
        TEXT.put("内部ストレージ（アプリ非公開領域）", new String[]{"Internal storage (private app data)", "內部儲存空間（應用程式私人資料）"});
        TEXT.put("ショート", new String[]{"Shorts", "短片"});
        TEXT.put("ショート動画の視聴", new String[]{"Watch short videos", "觀看短片"});
        TEXT.put("アプリを再起動", new String[]{"Restart app", "重新啟動應用程式"});
        TEXT.put("デバッグログを共有", new String[]{"Share debug log", "分享偵錯紀錄"});
        TEXT.put("その他", new String[]{"Other", "其他"});
        TEXT.put("設定を反映して最初から開く", new String[]{"Restart to apply settings", "重新啟動以套用設定"});
        TEXT.put("設定", new String[]{"Settings", "設定"});
        TEXT.put("アプリ設定", new String[]{"App settings", "應用程式設定"});
        TEXT.put("一般設定・再生設定", new String[]{"General and playback settings", "一般與播放設定"});
        TEXT.put("サイドバーにショートを表示", new String[]{"Show Shorts in the sidebar", "在側邊選單顯示短片"});
        TEXT.put("ランキングの下にショート動画の入口を表示します", new String[]{"Show the Shorts entry below Rankings", "在排行榜下方顯示短片入口"});
        TEXT.put("デバッグ", new String[]{"Debug", "偵錯"});
        TEXT.put("言語", new String[]{"Language", "語言"});
        TEXT.put("再生エラーや通信先、応答コードなどの診断ログを共有します。不具合の報告時に利用できます。共有前にログの内容と送信先を確認してください。", new String[]{"Share diagnostic logs, including playback errors, request destinations and response codes, when reporting a problem. Review the log and recipient before sharing.", "回報問題時可分享診斷紀錄，內容包含播放錯誤、連線目標與回應代碼。分享前請確認紀錄內容及接收對象。"});
        TEXT.put("気になる動画を選んで再生", new String[]{"Choose a video to watch", "選擇想看的影片"});
        TEXT.put("ショート動画を検索", new String[]{"Search short videos", "搜尋短片"});
        TEXT.put("検索", new String[]{"Search", "搜尋"});
        TEXT.put("ショート動画を読み込んでいます…", new String[]{"Loading short videos…", "正在載入短片…"});
        TEXT.put("再試行", new String[]{"Retry", "重試"});
        TEXT.put("ニコニコ動画のホームに戻る", new String[]{"Return to NicoNico home", "返回 Niconico 首頁"});
        TEXT.put("ニコニコ動画に戻る", new String[]{"Return to NicoNico", "返回 Niconico"});
        TEXT.put("ショート一覧を更新", new String[]{"Refresh short videos", "重新整理短片清單"});
        TEXT.put("ショート動画を取得できませんでした。通信状態を確認して再試行してください。", new String[]{"Could not load short videos. Check your connection and try again.", "無法載入短片。請確認網路連線後重試。"});
        TEXT.put(" 本の動画", new String[]{" videos", " 部影片"});
        TEXT.put("ニコニコ動画  •  ", new String[]{"NicoNico  •  ", "Niconico  •  "});
        TEXT.put("ショート動画を検索しています…", new String[]{"Searching short videos…", "正在搜尋短片…"});
        TEXT.put("検索結果を取得できませんでした。通信状態を確認して再試行してください。", new String[]{"Could not load search results. Check your connection and try again.", "無法載入搜尋結果。請確認網路連線後重試。"});
        TEXT.put("ショート動画が見つかりませんでした。キーワードを変えてお試しください。", new String[]{"No short videos found. Try another keyword.", "找不到短片。請嘗試其他關鍵字。"});
        TEXT.put("現在のショート", new String[]{"Current short", "目前的短片"});
        TEXT.put("前のショート", new String[]{"Previous short", "上一部短片"});
        TEXT.put("ショート動画一覧", new String[]{"Short video list", "短片清單"});
        TEXT.put("ショートのホーム", new String[]{"Shorts home", "短片首頁"});
        TEXT.put("動画情報", new String[]{"Video details", "影片資訊"});
        TEXT.put("次のショート", new String[]{"Next short", "下一部短片"});
        TEXT.put("上にスワイプで次、下にスワイプで前の動画", new String[]{"Swipe up for the next video or down for the previous one", "向上滑動切換下一部，向下滑動切換上一部"});
        TEXT.put("ショート動画", new String[]{"Short videos", "短片"});
        TEXT.put("更新", new String[]{"Refresh", "重新整理"});
        TEXT.put("閉じる", new String[]{"Close", "關閉"});
        TEXT.put("最初の動画です", new String[]{"This is the first video", "這是第一部影片"});
        TEXT.put("一覧を取得できませんでした。もう一度お試しください", new String[]{"Could not load the list. Please try again.", "無法載入清單。請再試一次。"});
        TEXT.put("新しいショート動画が見つかりませんでした", new String[]{"No more short videos found", "沒有找到更多短片"});
        TEXT.put("更新が完了しませんでした。もう一度お試しください。", new String[]{"Refresh did not complete. Please try again.", "重新整理未完成。請再試一次。"});
        TEXT.put("最大画質（最大解像度・動画により変動）", new String[]{"Maximum quality (highest available resolution; varies by video)", "最高畫質（最高可用解析度，依影片而異）"});
        TEXT.put("高画質（最大解像度・動画により変動）", new String[]{"High quality (highest available resolution; varies by video)", "高畫質（最高可用解析度，依影片而異）"});
        TEXT.put("標準画質（2番目の解像度・動画により変動）", new String[]{"Standard quality (second-highest resolution; varies by video)", "標準畫質（第二高解析度，依影片而異）"});
        TEXT.put("低画質（3番目の解像度・動画により変動）", new String[]{"Low quality (third-highest resolution; varies by video)", "低畫質（第三高解析度，依影片而異）"});
        TEXT.put("最大画質", new String[]{"Maximum quality", "最高畫質"});
        TEXT.put("高画質", new String[]{"High quality", "高畫質"});
        TEXT.put("標準画質", new String[]{"Standard quality", "標準畫質"});
        TEXT.put("低画質", new String[]{"Low quality", "低畫質"});
        TEXT.put("標準", new String[]{"Standard", "標準"});
        TEXT.put("自動", new String[]{"Auto", "自動"});
        TEXT.put("速度", new String[]{"Speed", "速度"});
        TEXT.put("画質", new String[]{"Quality", "畫質"});
        TEXT.put("ループ", new String[]{"Loop", "循環"});
        TEXT.put("再生速度", new String[]{"Playback speed", "播放速度"});
        TEXT.put("キャンセル", new String[]{"Cancel", "取消"});
        TEXT.put("画質を取得できませんでした", new String[]{"Could not retrieve video quality", "無法取得影片畫質"});
        TEXT.put("画質: ", new String[]{"Quality: ", "畫質： "});
        TEXT.put("再生速度: ", new String[]{"Playback speed: ", "播放速度： "});
        TEXT.put("倍", new String[]{"×", "倍"});
        TEXT.put("ループ再生: ", new String[]{"Loop playback: ", "循環播放： "});
        TEXT.put("操作に失敗しました。ログを確認してください", new String[]{"Action failed. Please check the log.", "操作失敗。請查看紀錄。"});
        TEXT.put("デフォルトの再生速度", new String[]{"Default playback speed", "預設播放速度"});
        TEXT.put("何もしない（従来の動作）", new String[]{"No change (original behavior)", "維持原本的行為"});
        TEXT.put("バックグラウンド再生", new String[]{"Background playback", "背景播放"});
        TEXT.put("ポップアップ再生", new String[]{"Pop-up playback", "懸浮視窗播放"});
        TEXT.put("アプリ切替時の動作", new String[]{"When switching apps", "切換應用程式時的行為"});
        TEXT.put("再生中に戻る場合の動作", new String[]{"When pressing Back during playback", "播放時按下返回的行為"});
        TEXT.put("再生位置の保存", new String[]{"Save playback position", "儲存播放進度"});
        TEXT.put("動画ごとに再生位置を保存し、次回の再生時に再開します", new String[]{"Save each video's playback position and resume from it next time", "儲存每部影片的播放進度，下次播放時從該位置繼續"});
        TEXT.put("ポップアップ再生には他のアプリの上に表示する権限が必要です", new String[]{"Allow display over other apps to use pop-up playback", "使用懸浮視窗播放需要允許顯示在其他應用程式上層"});
        TEXT.put("パッチバージョン", new String[]{"Patch version", "修補程式版本"});
        TEXT.put("Android 12以降の壁紙の色をアプリに適用します", new String[]{"Use wallpaper colors on Android 12 and later", "在 Android 12 以上版本套用桌布色彩"});
        TEXT.put("コメント取得数の上限を拡張", new String[]{"Increase the comment limit", "提高留言載入上限"});
        TEXT.put("従来形式の動画で取得するコメント数を増やします。通信量と描画負荷が増えます", new String[]{"Load more comments for videos using the legacy format. This increases data usage and rendering load.", "載入更多舊格式影片的留言。這會增加網路流量與繪製負擔。"});
        TEXT.put("コメントの大きさ", new String[]{"Comment size", "留言大小"});
        TEXT.put("最小・小・標準・大・最大（次の再生から反映）", new String[]{"Smallest, small, standard, large or largest (applies on the next playback)", "最小、小、標準、大、最大（下次播放時生效）"});
        TEXT.put("最小", new String[]{"Smallest", "最小"});
        TEXT.put("小", new String[]{"Small", "小"});
        TEXT.put("大", new String[]{"Large", "大"});
        TEXT.put("最大", new String[]{"Largest", "最大"});
        TEXT.put("接続", new String[]{"Connect", "連線"});
        TEXT.put("接続する端末を選択", new String[]{"Choose a device to connect to", "選擇要連線的裝置"});
        TEXT.put("接続解除", new String[]{"Disconnect", "中斷連線"});
        TEXT.put("Google Cast の接続を解除", new String[]{"Disconnect Google Cast", "中斷 Google Cast 連線"});
        TEXT.put("共有ストレージ（アプリ専用領域）", new String[]{"Shared storage (app-specific folder)", "共用儲存空間（應用程式專用資料夾）"});
        TEXT.put("本体ストレージ（アプリ内部領域）", new String[]{"Internal storage (private app folder)", "內部儲存空間（應用程式私人資料夾）"});
        TEXT.put("共有ストレージ、SDカード、本体内部領域から保存先を選択できます。変更前のキャッシュは移動されません", new String[]{"Choose shared storage, an SD card or internal storage. Existing cached files will not be moved.", "可選擇共用儲存空間、SD 卡或內部儲存空間。現有快取檔案不會移動。"});
        TEXT.put("フォロー新着", new String[]{"New from followed users", "追蹤對象的新影片"});
        TEXT.put("フォロー中の新着動画", new String[]{"New videos from followed users", "追蹤對象的最新影片"});
        TEXT.put("選択中: ", new String[]{"Selected: ", "已選取： "});
        TEXT.put("件の履歴を削除しますか？", new String[]{" history entries. Delete them?", " 筆紀錄，要刪除嗎？"});
        TEXT.put("削除", new String[]{"Delete", "刪除"});
        TEXT.put("動画", new String[]{"Video", "影片"});
        TEXT.put("削除する履歴を選択", new String[]{"Select history entries to delete", "選取要刪除的觀看紀錄"});
        TEXT.put("選択した履歴を削除", new String[]{"Delete selected history", "刪除選取的觀看紀錄"});
        TEXT.put("件", new String[]{" items", " 筆"});
        TEXT.put("ログイン画面の表示が停止しました。アプリを再起動して再試行してください。", new String[]{"The sign-in screen stopped responding. Restart the app and try again.", "登入畫面沒有回應。請重新啟動應用程式後重試。"});
        TEXT.put("ログイン画面を開けませんでした。\n", new String[]{"Could not open the sign-in screen.\n", "無法開啟登入畫面。\n"});
        TEXT.put("保存", new String[]{"Save", "儲存"});
        TEXT.put("ログイン方法", new String[]{"Sign-in method", "登入方式"});
        TEXT.put("通常ログイン", new String[]{"Standard sign-in", "一般登入"});
        TEXT.put("Cookie手動入力", new String[]{"Enter session cookie", "手動輸入 Cookie"});
        TEXT.put("別の端末・PCでニコニコにログインし、ブラウザのCookieからuser_sessionの値を貼り付けてください。user_session=… の形式でも入力できます。Cookieは他の人に渡さないでください。", new String[]{"Sign in to Niconico on another device or PC and paste the user_session cookie value from your browser. You can also enter user_session=… . Do not share your cookie with others.", "請在其他裝置或電腦登入 Niconico，再貼上瀏覽器 Cookie 中的 user_session 值。也可輸入 user_session=… 。請勿將 Cookie 提供給他人。"});
        TEXT.put("user_sessionの値、またはuser_session=… の形式で入力してください。", new String[]{"Enter the user_session value or use the user_session=… format.", "請輸入 user_session 值，或使用 user_session=… 格式。"});
        TEXT.put("Cookieを保存しました。認証が通らない場合は、ログインし直してCookieを再取得してください。", new String[]{"Cookie saved. If authentication fails, sign in again and obtain a new cookie.", "已儲存 Cookie。若驗證失敗，請重新登入並取得新的 Cookie。"});
        TEXT.put("Cookieを保存できませんでした。再試行してください。", new String[]{"Could not save the cookie. Please try again.", "無法儲存 Cookie，請重試。"});
        TEXT.put("ログインしました", new String[]{"Signed in", "已登入"});
        TEXT.put("ニコレポはサービスが終了しました。フォロー新着はニコニコ公式サイトで確認できます。", new String[]{"Nico Reports has been discontinued. Visit the official NicoNico website for new videos from followed users.", "Nico Reports 已停止服務。請前往 Niconico 官方網站查看追蹤對象的新影片。"});
        TEXT.put("アプリ専用フォルダー（デフォルト）", new String[]{"App-private folder (default)", "應用程式專用資料夾（預設）"});
        TEXT.put("共有ストレージ・SDカードのフォルダーを選択", new String[]{"Choose a folder in shared storage or on an SD card", "選擇共用儲存空間或 SD 卡上的資料夾"});
        TEXT.put("保存先: ", new String[]{"Save location: ", "儲存位置： "});
        TEXT.put("ログイン情報を保存済み", new String[]{"Sign-in details saved", "已儲存登入資料"});
        TEXT.put("ログアウト", new String[]{"Sign out", "登出"});
        TEXT.put("履歴を削除できませんでした。再試行してください。", new String[]{"Could not delete history. Please try again.", "無法刪除紀錄，請重試。"});
        TEXT.put("ログイン情報を削除してログアウトしますか？", new String[]{"Remove saved sign-in details and sign out?", "要刪除已儲存的登入資料並登出嗎？"});
        TEXT.put("ログアウトしました", new String[]{"Signed out", "已登出"});
        TEXT.put("ログアウトできませんでした。再試行してください。", new String[]{"Could not sign out. Please try again.", "無法登出，請重試。"});
        TEXT.put("コンテンツフィルタ", new String[]{"Content filter", "內容篩選器"});
        TEXT.put("キーワードフィルタ", new String[]{"Keyword filter", "關鍵字篩選器"});
        TEXT.put("チャンネルフィルタ", new String[]{"Channel filter", "頻道篩選器"});
        TEXT.put("非表示にする投稿者・チャンネル名をカンマまたは改行で区切って入力してください。名前の部分一致で判定します。次の一覧読み込みから反映されます。", new String[]{"Enter uploader or channel names to hide, separated by commas or new lines. Names are matched by substring. Applies the next time a list is loaded.", "輸入要隱藏的投稿者或頻道名稱，以逗號或換行分隔。以名稱部分相符判定，下次載入清單時套用。"});
        TEXT.put("動画タイトルに含まれるキーワードをカンマまたは改行で区切って入力してください。次の一覧読み込みから非表示になります。", new String[]{"Enter keywords found in video titles, separated by commas or new lines. Matching videos will be hidden the next time a list is loaded.", "輸入影片標題中的關鍵字，以逗號或換行分隔。下次載入清單時會隱藏符合的影片。"});
        TEXT.put("<b>%s</b> <font color='red'>%s回視聴</font>", new String[]{"<b>%s</b> <font color='red'>Watched %s times</font>", "<b>%s</b> <font color='red'>觀看 %s 次</font>"});
        TEXT.put("未ログイン・ログイン情報なし", new String[]{"Not signed in; no saved sign-in details", "未登入，沒有已儲存的登入資料"});
        TEXT.put("再生状況と通信結果を送る", new String[]{"Share playback and connection diagnostics", "分享播放與連線診斷資訊"});
        TEXT.put("動画の読み込みが進みません。再生をやり直してください", new String[]{"Video loading has stalled. Start playback again.", "影片載入停滯。請重新開始播放。"});
        TEXT.put("動画情報を取得できません: ", new String[]{"Could not retrieve video details: ", "無法取得影片資訊： "});
        TEXT.put("動画情報を取得できません。通信状態を確認してください", new String[]{"Could not retrieve video details. Check your connection.", "無法取得影片資訊。請確認網路連線。"});
        TEXT.put("この動画に対応する再生形式がありません", new String[]{"No supported playback format is available for this video", "這部影片沒有可支援的播放格式"});
        TEXT.put("再生情報の取得に失敗しました。通信状態や視聴権限を確認してください", new String[]{"Could not retrieve playback information. Check your connection and viewing permissions.", "無法取得播放資訊。請確認網路連線與觀看權限。"});
        TEXT.put("再生:%,d  コメント:%,d  マイリス:%,d  いいね:%,d", new String[]{"Views: %,d  Comments: %,d  Mylists: %,d  Likes: %,d", "觀看：%,d  留言：%,d  播放清單：%,d  按讚：%,d"});
        TEXT.put("再生数", new String[]{"Views", "觀看"});
        TEXT.put("いいね", new String[]{"Likes", "按讚"});
        TEXT.put("マイリス", new String[]{"Mylists", "播放清單"});
        TEXT.put("動画再生", new String[]{"Play video", "播放影片"});
        TEXT.put("キャッシュ取得", new String[]{"Download cache", "下載快取"});
        TEXT.put("キャッシュの取得", new String[]{"Download cache", "下載快取"});
        TEXT.put("ミニゲームを閉じる", new String[]{"Close mini-game", "關閉小遊戲"});
        TEXT.put("自転車ラン。タップで2段ジャンプ。障害物と穴を避けます。終了後はタップで再挑戦。", new String[]{"Bicycle Run. Tap to jump, then tap again in midair for a double jump. Avoid obstacles and gaps. Tap after game over to try again.", "自行車跑酷。輕觸跳躍，在空中再次輕觸可二段跳。避開障礙與缺口。遊戲結束後輕觸重試。"});
        TEXT.put("自転車ラン", new String[]{"Bicycle Run", "自行車跑酷"});
        TEXT.put("距離 ", new String[]{"Distance: ", "距離： "});
        TEXT.put(" m   ベスト ", new String[]{" m   Best: ", " m   最佳： "});
        TEXT.put("タップで2段ジャンプ", new String[]{"Tap to jump; tap again in midair", "輕觸跳躍，在空中再點一次可二段跳"});
        TEXT.put("ゲームオーバー", new String[]{"Game over", "遊戲結束"});
        TEXT.put("障害物と穴をジャンプで避けよう", new String[]{"Jump over obstacles and gaps", "跳過障礙與缺口"});
        TEXT.put("タップで再挑戦", new String[]{"Tap to try again", "輕觸重試"});
        TEXT.put("タップしてスタート", new String[]{"Tap to start", "輕觸開始"});
        TEXT.put("総合", new String[]{"All categories", "綜合"});
        TEXT.put("ゲーム", new String[]{"Gaming", "遊戲"});
        TEXT.put("アニメ", new String[]{"Anime", "動畫"});
        TEXT.put("ボカロ", new String[]{"Vocaloid", "VOCALOID"});
        TEXT.put("音声合成実況・解説・劇場", new String[]{"Synthesized voice commentary, explanations and skits", "語音合成實況、解說與劇場"});
        TEXT.put("エンタメ", new String[]{"Entertainment", "娛樂"});
        TEXT.put("音楽", new String[]{"Music", "音樂"});
        TEXT.put("歌ってみた", new String[]{"Singing covers", "翻唱"});
        TEXT.put("踊ってみた", new String[]{"Dance covers", "翻跳"});
        TEXT.put("演奏してみた", new String[]{"Instrumental covers", "演奏"});
        TEXT.put("解説・講座", new String[]{"Explanations and tutorials", "解說與教學"});
        TEXT.put("料理", new String[]{"Cooking", "料理"});
        TEXT.put("旅行・アウトドア", new String[]{"Travel and outdoors", "旅遊與戶外"});
        TEXT.put("自然", new String[]{"Nature", "自然"});
        TEXT.put("乗り物", new String[]{"Vehicles", "交通工具"});
        TEXT.put("技術・工作", new String[]{"Technology and crafts", "技術與手作"});
        TEXT.put("社会・政治・時事", new String[]{"Society, politics and current affairs", "社會、政治與時事"});
        TEXT.put("ラジオ", new String[]{"Radio", "廣播"});
        TEXT.put("スポーツ", new String[]{"Sports", "運動"});
        TEXT.put("動物", new String[]{"Animals", "動物"});
        TEXT.put("Setting", new String[]{"Settings", "設定"});
        TEXT.put("nicoidについて", new String[]{"About nicoid Re", "關於 nicoid Re"});
        TEXT.put("About nicoid", new String[]{"About nicoid Re", "關於 nicoid Re"});
        TEXT.put("關於nicoid", new String[]{"About nicoid Re", "關於 nicoid Re"});
        TEXT.put("アプリ全体の言語", new String[]{"App language", "應用程式語言"});
        TEXT.put("Language of the entire application", new String[]{"App language", "應用程式語言"});
        TEXT.put("語言的整個應用程序的", new String[]{"App language", "應用程式語言"});
        TEXT.put("アプリ全体の言語を変更できます", new String[]{"Choose the language used throughout the app", "選擇整個應用程式使用的語言"});
        TEXT.put("I will change the language of the entire application.", new String[]{"Choose the language used throughout the app", "選擇整個應用程式使用的語言"});
        TEXT.put("我將改變整個應用程序的語言", new String[]{"Choose the language used throughout the app", "選擇整個應用程式使用的語言"});
        TEXT.put("外部メモリ（SDカード）", new String[]{"External storage (SD card)", "外部儲存空間（SD 卡）"});
        TEXT.put("External memory (SD card)", new String[]{"External storage (SD card)", "外部儲存空間（SD 卡）"});
        TEXT.put("外部存儲器（SD卡）", new String[]{"External storage (SD card)", "外部儲存空間（SD 卡）"});
        TEXT.put("本体メモリ", new String[]{"Internal storage", "內部儲存空間"});
        TEXT.put("Internal memory", new String[]{"Internal storage", "內部儲存空間"});
        TEXT.put("機身內存", new String[]{"Internal storage", "內部儲存空間"});
        TEXT.put("無制限", new String[]{"Unlimited", "無限制"});
        TEXT.put("Limitless", new String[]{"Unlimited", "無限制"});
        TEXT.put("タブレット", new String[]{"Tablet", "平板電腦"});
        TEXT.put("Tablets", new String[]{"Tablet", "平板電腦"});
        TEXT.put("平板電腦", new String[]{"Tablet", "平板電腦"});
        TEXT.put("毎回選択する", new String[]{"Ask every time", "每次詢問"});
        TEXT.put("I choose every time", new String[]{"Ask every time", "每次詢問"});
        TEXT.put("每次選擇", new String[]{"Ask every time", "每次詢問"});
        TEXT.put("Video Info", new String[]{"Video details", "影片資訊"});
        TEXT.put("動畫情報", new String[]{"Video details", "影片資訊"});
        TEXT.put("Video playback", new String[]{"Play video", "播放影片"});
        TEXT.put("播放動畫", new String[]{"Play video", "播放影片"});
        TEXT.put("Pop-up playback", new String[]{"Pop-up playback", "懸浮視窗播放"});
        TEXT.put("Popup播放", new String[]{"Pop-up playback", "懸浮視窗播放"});
        TEXT.put("強", new String[]{"High", "高"});
        TEXT.put("Strength", new String[]{"High", "高"});
        TEXT.put("弱", new String[]{"Low", "低"});
        TEXT.put("Weak", new String[]{"Low", "低"});
        TEXT.put("無(全て表示)", new String[]{"None (show all)", "無（顯示全部）"});
        TEXT.put("None (view all)", new String[]{"None (show all)", "無（顯示全部）"});
        TEXT.put("無(全部顯示)", new String[]{"None (show all)", "無（顯示全部）"});
        TEXT.put("Economy image quality", new String[]{"Standard quality", "標準畫質"});
        TEXT.put("經濟畫質", new String[]{"Standard quality", "標準畫質"});
        TEXT.put("オリジナル画質", new String[]{"Original quality", "原始畫質"});
        TEXT.put("Original image quality", new String[]{"Original quality", "原始畫質"});
        TEXT.put("原始畫質", new String[]{"Original quality", "原始畫質"});
        TEXT.put("端末の設定に従う", new String[]{"Follow device settings", "依照裝置設定"});
        TEXT.put("Follow the configuration of the terminal", new String[]{"Follow device settings", "依照裝置設定"});
        TEXT.put("依照客戶端設定", new String[]{"Follow device settings", "依照裝置設定"});
        TEXT.put("横画面固定", new String[]{"Lock to landscape", "固定橫向"});
        TEXT.put("Horizontal screen fixed", new String[]{"Lock to landscape", "固定橫向"});
        TEXT.put("固定橫向畫面", new String[]{"Lock to landscape", "固定橫向"});
        TEXT.put("縦画面固定", new String[]{"Lock to portrait", "固定直向"});
        TEXT.put("Vertical screen fixed", new String[]{"Lock to portrait", "固定直向"});
        TEXT.put("固定縱向畫面", new String[]{"Lock to portrait", "固定直向"});
        TEXT.put("センサーに従う", new String[]{"Auto-rotate using sensors", "依感應器自動旋轉"});
        TEXT.put("I follow the sensor", new String[]{"Auto-rotate using sensors", "依感應器自動旋轉"});
        TEXT.put("依照感應器", new String[]{"Auto-rotate using sensors", "依感應器自動旋轉"});
        TEXT.put("常に使用", new String[]{"Always", "一律使用"});
        TEXT.put("モバイル通信時のみ", new String[]{"On mobile data only", "僅使用行動網路時"});
        TEXT.put("使用しない", new String[]{"Never", "不使用"});
        TEXT.put("ぼかし", new String[]{"Soft shadow", "柔和陰影"});
        TEXT.put("縁取り", new String[]{"Outline", "描邊"});
        TEXT.put("キャッシュを全て削除する", new String[]{"Clear all cache", "清除所有快取"});
        TEXT.put("I delete all the cache", new String[]{"Clear all cache", "清除所有快取"});
        TEXT.put("清除快取", new String[]{"Clear all cache", "清除所有快取"});
        TEXT.put("キャッシュを全て削除しますか？", new String[]{"Clear all cached files?", "要清除所有快取檔案嗎？"});
        TEXT.put("Are you sure you want to delete all the cache?", new String[]{"Clear all cached files?", "要清除所有快取檔案嗎？"});
        TEXT.put("要清除全部快取嗎？", new String[]{"Clear all cached files?", "要清除所有快取檔案嗎？"});
        TEXT.put("キャッシュ保存先", new String[]{"Cache location", "快取儲存位置"});
        TEXT.put("Cache destination", new String[]{"Cache location", "快取儲存位置"});
        TEXT.put("緩存目的地", new String[]{"Cache location", "快取儲存位置"});
        TEXT.put("キャッシュフォルダ非表示", new String[]{"Hide cached videos from galleries", "在相簿中隱藏快取影片"});
        TEXT.put("アルバムなどからキャッシュした動画ファイルを閲覧できないように変更できます", new String[]{"Prevent gallery apps from displaying cached video files", "避免相簿應用程式顯示快取的影片檔案"});
        TEXT.put("キャッシュは通常再生のみ実行されます（ポップアップ、nicoidcastでは実行されません）\nシークバーの白のゲージがキャッシュの進行度になります", new String[]{"Caching is available during normal playback only. The white seek-bar segment shows caching progress.", "快取僅適用於一般播放。進度列的白色部分表示快取進度。"});
        TEXT.put("Normal playback is executed only for the cache. (Pop-up, it does not run on nicoidcast)\nGauge of white seek bar is the progress of the cache", new String[]{"Caching is available during normal playback only. The white seek-bar segment shows caching progress.", "快取僅適用於一般播放。進度列的白色部分表示快取進度。"});
        TEXT.put("快取只使用於一般播放（Popup、nicoidcast不使用）\n在時間軸以白色長條顯示快取進行度", new String[]{"Caching is available during normal playback only. The white seek-bar segment shows caching progress.", "快取僅適用於一般播放。進度列的白色部分表示快取進度。"});
        TEXT.put("キャッシュ容量", new String[]{"Cache size limit", "快取容量上限"});
        TEXT.put("Cache capacity", new String[]{"Cache size limit", "快取容量上限"});
        TEXT.put("快取容量", new String[]{"Cache size limit", "快取容量上限"});
        TEXT.put("キャッシュに使用する最大容量を変更できます", new String[]{"Set the maximum storage space used by cached files", "設定快取檔案可使用的最大儲存空間"});
        TEXT.put("You can set the maximum capacity to be used for cache", new String[]{"Set the maximum storage space used by cached files", "設定快取檔案可使用的最大儲存空間"});
        TEXT.put("設定快取使用的最大容量", new String[]{"Set the maximum storage space used by cached files", "設定快取檔案可使用的最大儲存空間"});
        TEXT.put("キャッシュのみを使用し再生", new String[]{"Use cached files for offline playback", "使用快取檔案離線播放"});
        TEXT.put("キャッシュ取得済み(100％)の動画を再生するとき、動画だけでなく動画情報やコメントもキャッシュを使用しデータ通信を行わずに再生します", new String[]{"For fully cached videos, also use cached video details and comments to play without network access", "播放已完整快取的影片時，也使用快取的影片資訊與留言，不連線至網路"});
        TEXT.put("キャッシュ高速取得モード(非推奨)", new String[]{"Fast cache download (not recommended)", "快速下載快取（不建議）"});
        TEXT.put("すべて高速取得モード(非推奨)", new String[]{"Use fast download for all playback (not recommended)", "所有播放方式皆使用快速下載（不建議）"});
        TEXT.put("オリジナル画質より劣化しますが高速に取得可能なオプションです。キャッシュのみに適応され画質設定は無視されます。今後の仕様変更で動作しなくなる可能性があります。", new String[]{"Download faster at reduced quality. Applies only to caching and overrides the quality setting. Future service changes may make this option unavailable.", "降低畫質以加快下載。僅適用於快取，並忽略畫質設定。未來服務變更可能導致此選項失效。"});
        TEXT.put("キャッシュだけではなくすべての再生方法で高速取得の方法を使用します。再生開始までの時間やシーク後の読み込みが短くなるわけではありません。", new String[]{"Use the fast download method for all playback modes. This does not reduce startup or seek-loading time.", "在所有播放模式使用快速下載方式。這不會縮短開始播放或拖曳進度後的載入時間。"});
        TEXT.put("コメント", new String[]{"Comments", "留言"});
        TEXT.put("Comment", new String[]{"Comments", "留言"});
        TEXT.put("評論", new String[]{"Comments", "留言"});
        TEXT.put("コメントの不透明度", new String[]{"Comment opacity", "留言不透明度"});
        TEXT.put("コメントの表示を透過することができます", new String[]{"Adjust how transparent comments appear", "調整留言顯示的透明程度"});
        TEXT.put("キャスト再生時コメントを減らす", new String[]{"Reduce comments while casting", "投放時減少留言"});
        TEXT.put("動作を安定させるため表示するコメント量を少なくしフレームレートを低く制限します。再生側のスペックに余裕がある場合、無効にすると通常のコメント量・フレームレートで表示することができます", new String[]{"Reduce comments and frame rate for smoother casting. Turn this off if the receiving device can handle normal comment rendering.", "減少留言與幀率以改善投放穩定性。接收裝置效能足夠時可關閉，以正常數量與幀率顯示留言。"});
        TEXT.put("描画フレームレート", new String[]{"Comment frame rate", "留言繪製幀率"});
        TEXT.put("Drawing frame rate", new String[]{"Comment frame rate", "留言繪製幀率"});
        TEXT.put("繪製幀率", new String[]{"Comment frame rate", "留言繪製幀率"});
        TEXT.put("コメント描画フレームレート上限を変更できます", new String[]{"Set the maximum frame rate for comment rendering", "設定留言繪製的最高幀率"});
        TEXT.put("I set the comment drawing frame rate limit.", new String[]{"Set the maximum frame rate for comment rendering", "設定留言繪製的最高幀率"});
        TEXT.put("我設置的註釋繪圖幀速率限制。", new String[]{"Set the maximum frame rate for comment rendering", "設定留言繪製的最高幀率"});
        TEXT.put("コメントを表示しない", new String[]{"Hide comments by default", "預設隱藏留言"});
        TEXT.put("Do not show comment", new String[]{"Hide comments by default", "預設隱藏留言"});
        TEXT.put("不顯示評論", new String[]{"Hide comments by default", "預設隱藏留言"});
        TEXT.put("コメントをデフォルトで非表示します", new String[]{"Start playback with comments hidden", "開始播放時隱藏留言"});
        TEXT.put("I can hide by default comment", new String[]{"Start playback with comments hidden", "開始播放時隱藏留言"});
        TEXT.put("評論預設為不顯示", new String[]{"Start playback with comments hidden", "開始播放時隱藏留言"});
        TEXT.put("コメントのドロップシャドウ", new String[]{"Comment shadow", "留言陰影"});
        TEXT.put("コメントのドロップシャドウを変更できます", new String[]{"Choose the shadow style for comments", "選擇留言的陰影樣式"});
        TEXT.put("タブレット・スマートフォンそれぞれに適した表示方法に変更できます", new String[]{"Choose a layout suited to a phone or tablet", "選擇適合手機或平板電腦的版面配置"});
        TEXT.put("I will change the display method suitable for each tablet, smartphone", new String[]{"Choose a layout suited to a phone or tablet", "選擇適合手機或平板電腦的版面配置"});
        TEXT.put("變更適應平板電腦・智慧型手機等表示方法", new String[]{"Choose a layout suited to a phone or tablet", "選擇適合手機或平板電腦的版面配置"});
        TEXT.put("タブレット端末のみ変更可能です", new String[]{"Available on tablets only", "僅適用於平板電腦"});
        TEXT.put("Can be changed only tablets", new String[]{"Available on tablets only", "僅適用於平板電腦"});
        TEXT.put("僅平板電腦適用變更", new String[]{"Available on tablets only", "僅適用於平板電腦"});
        TEXT.put("リンク時の動作", new String[]{"Action when opening a video link", "開啟影片連結時的行為"});
        TEXT.put("Operation of the link-time", new String[]{"Action when opening a video link", "開啟影片連結時的行為"});
        TEXT.put("連結時的動作", new String[]{"Action when opening a video link", "開啟影片連結時的行為"});
        TEXT.put("外部アプリからの呼び出し時の動作を選択できます", new String[]{"Choose what happens when another app opens a video link", "選擇從其他應用程式開啟影片連結時的行為"});
        TEXT.put("I want the behavior of the call from the external application", new String[]{"Choose what happens when another app opens a video link", "選擇從其他應用程式開啟影片連結時的行為"});
        TEXT.put("選擇從外部應用程式叫出時的動作", new String[]{"Choose what happens when another app opens a video link", "選擇從其他應用程式開啟影片連結時的行為"});
        TEXT.put("実験的機能", new String[]{"Experimental features", "實驗性功能"});
        TEXT.put("実験的機能について", new String[]{"About experimental features", "關於實驗性功能"});
        TEXT.put("通常は設定しないでください。こちらのオプションは正しく動作しなかったり予告なく廃止する可能性があります。", new String[]{"Leave these options off for normal use. They may not work correctly and may be removed without notice.", "一般使用時請保持關閉。這些選項可能無法正常運作，且可能不另行通知就移除。"});
        TEXT.put("Language", new String[]{"Language", "語言"});
        TEXT.put("語", new String[]{"Language", "語言"});
        TEXT.put("ログイン中", new String[]{"Signing in…", "正在登入…"});
        TEXT.put("Log in", new String[]{"Signing in…", "正在登入…"});
        TEXT.put("登入中", new String[]{"Signing in…", "正在登入…"});
        TEXT.put("ニコニコ動画のメールアドレス・パスワードを設定", new String[]{"Sign in with your NicoNico account", "使用 Niconico 帳號登入"});
        TEXT.put("Set the e-mail address password of Nico Nico Douga", new String[]{"Sign in with your NicoNico account", "使用 Niconico 帳號登入"});
        TEXT.put("設定NICONICO動畫的電郵地址・密碼", new String[]{"Sign in with your NicoNico account", "使用 Niconico 帳號登入"});
        TEXT.put("ログインに成功しました", new String[]{"Signed in successfully", "登入成功"});
        TEXT.put("I have successfully logged", new String[]{"Signed in successfully", "登入成功"});
        TEXT.put("登入成功", new String[]{"Signed in successfully", "登入成功"});
        TEXT.put("ログインに失敗しました\nメールアドレスとパスワードをお確かめください", new String[]{"Sign-in failed. Check your email address and password.", "登入失敗。請確認電子郵件地址與密碼。"});
        TEXT.put("I failed to login", new String[]{"Sign-in failed. Check your email address and password.", "登入失敗。請確認電子郵件地址與密碼。"});
        TEXT.put("登入失敗", new String[]{"Sign-in failed. Check your email address and password.", "登入失敗。請確認電子郵件地址與密碼。"});
        TEXT.put("ログインに失敗しました\n確認コードが間違っています", new String[]{"Sign-in failed. Check your verification code.", "登入失敗。請確認驗證碼。"});
        TEXT.put("通常画面の向き", new String[]{"App screen orientation", "一般畫面方向"});
        TEXT.put("The orientation of the screen", new String[]{"App screen orientation", "一般畫面方向"});
        TEXT.put("畫面方向", new String[]{"App screen orientation", "一般畫面方向"});
        TEXT.put("通常画面の向きの固定・変更方法を設定できます", new String[]{"Choose how the app screen rotates", "選擇一般畫面的旋轉方式"});
        TEXT.put("I set the fixed and how to change the orientation of the normal screen", new String[]{"Choose how the app screen rotates", "選擇一般畫面的旋轉方式"});
        TEXT.put("設定一般畫面方向的固定・變更方法", new String[]{"Choose how the app screen rotates", "選擇一般畫面的旋轉方式"});
        TEXT.put("モバイル通信時低画質再生", new String[]{"Low quality on mobile data", "使用行動網路時降低畫質"});
        TEXT.put("モバイル通信時、画質設定にかかわらず低画質で取得します", new String[]{"Use low quality on mobile data, regardless of the quality setting", "使用行動網路時一律使用低畫質，不受畫質設定影響"});
        TEXT.put("ログインせずに使用", new String[]{"Use without signing in", "不登入使用"});
        TEXT.put("The use without logging", new String[]{"Use without signing in", "不登入使用"});
        TEXT.put("不登入使用", new String[]{"Use without signing in", "不登入使用"});
        TEXT.put("ログインせずにnicoidを使用できます", new String[]{"Use nicoid without a NicoNico account", "不登入 Niconico 帳號即可使用 nicoid"});
        TEXT.put("Use nicoid without logging", new String[]{"Use nicoid without a NicoNico account", "不登入 Niconico 帳號即可使用 nicoid"});
        TEXT.put("不登入使用nicoid", new String[]{"Use nicoid without a NicoNico account", "不登入 Niconico 帳號即可使用 nicoid"});
        TEXT.put("再生モード", new String[]{"Playback mode", "播放模式"});
        TEXT.put("Play mode", new String[]{"Playback mode", "播放模式"});
        TEXT.put("播放模式", new String[]{"Playback mode", "播放模式"});
        TEXT.put("動画の再生方法（ストリーミング・キャッシュ）を変更できます", new String[]{"Choose streaming or cached playback", "選擇串流或快取播放"});
        TEXT.put("I will change the method of playing videos (streaming / cache)", new String[]{"Choose streaming or cached playback", "選擇串流或快取播放"});
        TEXT.put("動畫播放方法（串流・快取）變更", new String[]{"Choose streaming or cached playback", "選擇串流或快取播放"});
        TEXT.put("コメント・動画情報の言語", new String[]{"Comment and video details language", "留言與影片資訊的語言"});
        TEXT.put("Language of the comment and video information", new String[]{"Comment and video details language", "留言與影片資訊的語言"});
        TEXT.put("語言", new String[]{"Comment and video details language", "留言與影片資訊的語言"});
        TEXT.put("コメント・動画情報の言語を変更できます（デフォルトはアプリ全体の言語に従います）", new String[]{"Choose the language for comments and video details. By default, this follows the app language.", "選擇留言與影片資訊的語言。預設使用應用程式的語言。"});
        TEXT.put("I will change the language of the comment and video information. (The default is subject to the language of the entire application.)", new String[]{"Choose the language for comments and video details. By default, this follows the app language.", "選擇留言與影片資訊的語言。預設使用應用程式的語言。"});
        TEXT.put("變更評論・動畫情報的語言", new String[]{"Choose the language for comments and video details. By default, this follows the app language.", "選擇留言與影片資訊的語言。預設使用應用程式的語言。"});
        TEXT.put("再生画面の向き", new String[]{"Player screen orientation", "播放畫面方向"});
        TEXT.put("再生画面（プレイヤー）の向きの固定・変更方法を設定できます", new String[]{"Choose how the player screen rotates", "選擇播放畫面的旋轉方式"});
        TEXT.put("I set the fixed and how to change the screen orientation in player", new String[]{"Choose how the player screen rotates", "選擇播放畫面的旋轉方式"});
        TEXT.put("設定播放器畫面方向的固定・變更方法", new String[]{"Choose how the player screen rotates", "選擇播放畫面的旋轉方式"});
        TEXT.put("先行再生", new String[]{"Start before comments finish loading", "留言載入完成前開始播放"});
        TEXT.put("Preceding Play", new String[]{"Start before comments finish loading", "留言載入完成前開始播放"});
        TEXT.put("先行播放", new String[]{"Start before comments finish loading", "留言載入完成前開始播放"});
        TEXT.put("動画の取得が完了した時点でコメントの取得が完了していなくても動画の再生を開始します", new String[]{"Start playback as soon as the video is ready, even if comments are still loading", "影片準備好後立即播放，即使留言仍在載入"});
        TEXT.put("I will start playing the video acquisition of comment even if not completed at the time of acquisition of the video was completed", new String[]{"Start playback as soon as the video is ready, even if comments are still loading", "影片準備好後立即播放，即使留言仍在載入"});
        TEXT.put("動畫取得後尚未取得評論時直接播放", new String[]{"Start playback as soon as the video is ready, even if comments are still loading", "影片準備好後立即播放，即使留言仍在載入"});
        TEXT.put("キャッシュ安定再生（暫定対応）", new String[]{"Stable cached playback (temporary workaround)", "穩定快取播放（暫時解決方案）"});
        TEXT.put("一部環境下で外部メモリにキャッシュされた動画を再生時にプツプツ途切れる現象を解消出来ます（再生に問題がない場合設定しないで下さい。暫定対応のため削除される可能性があります）", new String[]{"Reduce stuttering when playing cached videos from external storage. Leave this off if playback works normally. This temporary workaround may be removed.", "減少播放外部儲存空間快取影片時的卡頓。播放正常時請保持關閉，此暫時解決方案未來可能移除。"});
        TEXT.put("Image quality", new String[]{"Video quality", "影片畫質"});
        TEXT.put("畫質", new String[]{"Video quality", "影片畫質"});
        TEXT.put("取得する動画の画質を変更できます", new String[]{"Choose the video quality to download or stream", "選擇下載或串流的影片畫質"});
        TEXT.put("I can change the quality of the video to get", new String[]{"Choose the video quality to download or stream", "選擇下載或串流的影片畫質"});
        TEXT.put("能變更取得動畫的畫質", new String[]{"Choose the video quality to download or stream", "選擇下載或串流的影片畫質"});
        TEXT.put("設定を保存しました", new String[]{"Settings saved", "已儲存設定"});
        TEXT.put("I have to save the settings", new String[]{"Settings saved", "已儲存設定"});
        TEXT.put("已儲存設定", new String[]{"Settings saved", "已儲存設定"});
        TEXT.put("共有NGレベル", new String[]{"Shared comment filter strength", "共用留言過濾強度"});
        TEXT.put("NG share level", new String[]{"Shared comment filter strength", "共用留言過濾強度"});
        TEXT.put("分享NG等級", new String[]{"Shared comment filter strength", "共用留言過濾強度"});
        TEXT.put("共有NGレベルを変更できます", new String[]{"Adjust the strength of the shared comment filter", "調整共用留言過濾器的強度"});
        TEXT.put("I will modify the share NG level", new String[]{"Adjust the strength of the shared comment filter", "調整共用留言過濾器的強度"});
        TEXT.put("變更分享NG等級", new String[]{"Adjust the strength of the shared comment filter", "調整共用留言過濾器的強度"});
        TEXT.put("スリープ再生", new String[]{"Keep playing with the screen off", "螢幕關閉時繼續播放"});
        TEXT.put("通常再生状態でスリープ（画面オフ）にしても再生を続けます", new String[]{"Continue normal playback when the screen turns off", "螢幕關閉後仍繼續一般播放"});
        TEXT.put("ステータスバー非表示", new String[]{"Hide status bar", "隱藏狀態列"});
        TEXT.put("フルスクリーン時ステータスバーを非表示にします", new String[]{"Hide the status bar in full screen", "全螢幕時隱藏狀態列"});
        TEXT.put("タップ時の動作", new String[]{"Action when tapping a video", "輕觸影片時的行為"});
        TEXT.put("Operation of the tap when", new String[]{"Action when tapping a video", "輕觸影片時的行為"});
        TEXT.put("輕觸時動作", new String[]{"Action when tapping a video", "輕觸影片時的行為"});
        TEXT.put("動画をタップした時の動作を選択できます（設定した項目以外は右下の三角形をタップすることで表示されます）", new String[]{"Choose what happens when tapping a video. Use the triangle at the bottom right for other actions.", "選擇輕觸影片時的行為。其他操作可由右下角的三角形開啟。"});
        TEXT.put("And what to do when you tap the video list. (Item other than that you set will be displayed by tapping the triangle in the bottom right-hand corner.)", new String[]{"Choose what happens when tapping a video. Use the triangle at the bottom right for other actions.", "選擇輕觸影片時的行為。其他操作可由右下角的三角形開啟。"});
        TEXT.put("選擇輕觸時的動作（已設定項目以外請輕觸右下角的三角形）", new String[]{"Choose what happens when tapping a video. Use the triangle at the bottom right for other actions.", "選擇輕觸影片時的行為。其他操作可由右下角的三角形開啟。"});
        TEXT.put("全般", new String[]{"General", "一般"});
        TEXT.put("Whole", new String[]{"General", "一般"});
        TEXT.put("全體", new String[]{"General", "一般"});
        TEXT.put("フォロー中のユーザー", new String[]{"Followed users", "追蹤的使用者"});
        TEXT.put("User favorite", new String[]{"Followed users", "追蹤的使用者"});
        TEXT.put("用戶喜愛", new String[]{"Followed users", "追蹤的使用者"});
        TEXT.put("User list of favorite", new String[]{"Users you follow", "你追蹤的使用者"});
        TEXT.put("喜歡的用戶列表", new String[]{"Users you follow", "你追蹤的使用者"});
        TEXT.put("アカウントのマイリスト", new String[]{"Your account's playlists", "帳號的播放清單"});
        TEXT.put("My List list of accounts", new String[]{"Your account's playlists", "帳號的播放清單"});
        TEXT.put("帳戶的我的清單一覽", new String[]{"Your account's playlists", "帳號的播放清單"});
        TEXT.put("とりあえずマイリスト", new String[]{"Watch later", "稍後觀看"});
        TEXT.put("My List for the time being", new String[]{"Watch later", "稍後觀看"});
        TEXT.put("一秒清單", new String[]{"Watch later", "稍後觀看"});
        TEXT.put("アカウントのとりあえずマイリスト", new String[]{"Your Watch later playlist", "稍後觀看清單"});
        TEXT.put("My List list for the time being of the account", new String[]{"Your Watch later playlist", "稍後觀看清單"});
        TEXT.put("帳戶的一秒清單一覽", new String[]{"Your Watch later playlist", "稍後觀看清單"});
        TEXT.put("本体に登録したブックマーク", new String[]{"Bookmarks saved on this device", "儲存在此裝置的書籤"});
        TEXT.put("A list of bookmarks that it has registered with the body", new String[]{"Bookmarks saved on this device", "儲存在此裝置的書籤"});
        TEXT.put("裝置本體上的書籤一覽", new String[]{"Bookmarks saved on this device", "儲存在此裝置的書籤"});
        TEXT.put("キャッシュリスト", new String[]{"Cached videos", "快取影片"});
        TEXT.put("Cache list", new String[]{"Cached videos", "快取影片"});
        TEXT.put("緩存列表", new String[]{"Cached videos", "快取影片"});
        TEXT.put("キャッシュ取得済みの動画（オフライン視聴可能）", new String[]{"Cached videos available offline", "可離線觀看的快取影片"});
        TEXT.put("Video List of cached (Viewable offline)", new String[]{"Cached videos available offline", "可離線觀看的快取影片"});
        TEXT.put("緩存的視頻列表（離線瀏覽）", new String[]{"Cached videos available offline", "可離線觀看的快取影片"});
        TEXT.put("本体", new String[]{"On this device", "此裝置"});
        TEXT.put("Body", new String[]{"On this device", "此裝置"});
        TEXT.put("裝置本體", new String[]{"On this device", "此裝置"});
        TEXT.put("キャッシュ取得を開始しました", new String[]{"Cache download started", "已開始下載快取"});
        TEXT.put("本体の視聴履歴", new String[]{"Watch history on this device", "此裝置的觀看紀錄"});
        TEXT.put("Viewing history of the body", new String[]{"Watch history on this device", "此裝置的觀看紀錄"});
        TEXT.put("裝置本體的視聽紀錄", new String[]{"Watch history on this device", "此裝置的觀看紀錄"});
        TEXT.put("動画ID入力", new String[]{"Enter video ID", "輸入影片 ID"});
        TEXT.put("Video ID input", new String[]{"Enter video ID", "輸入影片 ID"});
        TEXT.put("輸入動畫ID", new String[]{"Enter video ID", "輸入影片 ID"});
        TEXT.put("動画IDを直接指定しアクセス", new String[]{"Open a video by its ID", "以影片 ID 開啟影片"});
        TEXT.put("Accessed directly specify the video ID", new String[]{"Open a video by its ID", "以影片 ID 開啟影片"});
        TEXT.put("經由直接指定動畫ID進入", new String[]{"Open a video by its ID", "以影片 ID 開啟影片"});
        TEXT.put("IDが入力されていません", new String[]{"Enter a video ID", "請輸入影片 ID"});
        TEXT.put("ID has not been entered", new String[]{"Enter a video ID", "請輸入影片 ID"});
        TEXT.put("未輸入ID", new String[]{"Enter a video ID", "請輸入影片 ID"});
        TEXT.put("nicoidの設定", new String[]{"nicoid settings", "nicoid 設定"});
        TEXT.put("Setting nicoid", new String[]{"nicoid settings", "nicoid 設定"});
        TEXT.put("動画のキーワード、タグ検索", new String[]{"Search by keyword or tag", "以關鍵字或標籤搜尋"});
        TEXT.put("Keywords video, tag search", new String[]{"Search by keyword or tag", "以關鍵字或標籤搜尋"});
        TEXT.put("動畫的關鍵字、標籤搜尋", new String[]{"Search by keyword or tag", "以關鍵字或標籤搜尋"});
        TEXT.put("Pop up播放", new String[]{"Pop-up playback", "懸浮視窗播放"});
        TEXT.put("バックグラウンドでキャッシュを取得しますか？", new String[]{"Download the video cache in the background?", "要在背景下載影片快取嗎？"});
        TEXT.put("連続再生", new String[]{"Play continuously", "連續播放"});
        TEXT.put("シャッフル再生", new String[]{"Shuffle play", "隨機播放"});
        TEXT.put("フォルダーを削除", new String[]{"Delete folder", "刪除資料夾"});
        TEXT.put("フォルダーを削除しますか？", new String[]{"Delete this folder?", "要刪除此資料夾嗎？"});
        TEXT.put("フォルダー内の動画は未分類に移動します。", new String[]{"Videos in this folder will move to Unfiled.", "資料夾中的影片會移至未分類。"});
        buildJapaneseLookup();
    }
    private static String[] lookup(String source) {
        String[] exact = TEXT.get(source);
        if (exact != null) return exact;
        if (source.matches("[0-9]+行")) { String n=source.substring(0,source.length()-1); return new String[]{n+" rows",n+" 行"}; }
        if (source.matches("[0-9]+秒")) { String n=source.substring(0,source.length()-1); return new String[]{n+" seconds",n+" 秒"}; }
        return null;
    }
    private static void buildJapaneseLookup() {
        java.util.regex.Pattern englishKey = java.util.regex.Pattern.compile("[A-Za-z][A-Za-z0-9 ’'/-]*");
        Map<String,String> canonicalKeys = new HashMap<>();
        for (Map.Entry<String,String[]> entry : TEXT.entrySet()) {
            String key=entry.getKey();String[] values=entry.getValue();
            if (!englishKey.matcher(key).matches() && values!=null && values.length>0 && !canonicalKeys.containsKey(values[0])) canonicalKeys.put(values[0],key);
        }
        JAPANESE_LOOKUP.putAll(canonicalKeys);
        for (Map.Entry<String,String[]> entry : TEXT.entrySet()) {
            String key=entry.getKey();String[] values=entry.getValue();
            if (!JAPANESE_LOOKUP.containsKey(key) && englishKey.matcher(key).matches() && values!=null && values.length>0 && !key.equals(values[0])) {
                String canonical=canonicalKeys.get(values[0]);
                if (canonical!=null) JAPANESE_LOOKUP.put(key,canonical);
            }
        }
        JAPANESE_LOOKUP.putAll(JAPANESE_ALIASES);
    }
    private static String toJapanese(String source) {
        if (source == null) return null;
        String translated=JAPANESE_LOOKUP.get(source);
        return translated == null ? source : translated;
    }
    private UiStrings() { }
    public static void selectLanguage(String preferenceValue) {
        if (preferenceValue == null) { selectedLanguage = -1; return; }
        String value = preferenceValue.trim().toLowerCase(Locale.ROOT);
        if ("0".equals(value) || "ja".equals(value) || value.startsWith("ja-") || "japanese".equals(value)) selectedLanguage = 0;
        else if ("1".equals(value) || "en".equals(value) || value.startsWith("en-") || "english".equals(value)) selectedLanguage = 1;
        else if ("2".equals(value) || "zh".equals(value) || value.startsWith("zh-") || "chinese".equals(value)) selectedLanguage = 2;
        else selectedLanguage = -1;
    }
    public static String translate(String source) {
        if ("デバッグログを共有".equals(source)) source = "デバッグログの保存";
        if ("再生状況と通信結果を送る".equals(source)) source = "再生状況と通信結果をDownloadフォルダに保存";
        int language = selectedLanguage;
        if (language < 0) return translate(source, Locale.getDefault());
        if (source == null) return null;
        if (language == 0) return toJapanese(source);
        String[] translated = lookup(source);
        return translated == null ? source : translated[language - 1];
    }
    public static String translate(String source, Locale locale) {
        if ("デバッグログを共有".equals(source)) source = "デバッグログの保存";
        if ("再生状況と通信結果を送る".equals(source)) source = "再生状況と通信結果をDownloadフォルダに保存";
        if (source == null) return null;
        String lang = locale.getLanguage();
        if (!"en".equals(lang) && !"zh".equals(lang)) return toJapanese(source);
        String[] translated = lookup(source);
        return translated == null ? source : translated["en".equals(lang) ? 0 : 1];
    }
}
