package e.e.a;
import android.content.*;import android.net.Uri;import android.os.*;import android.preference.PreferenceManager;import android.view.*;import android.widget.*;import android.graphics.*;import org.json.*;import java.io.*;import java.net.*;import java.util.concurrent.*;
public final class VideoDetails {
 private static final Handler MAIN=new Handler(Looper.getMainLooper());private static final ExecutorService WORK=Executors.newFixedThreadPool(2);
 private static String tr(String j,String e,String z){String l=UiStrings.translate("ニコレポ");return l.equals("Nico Reports")?e:l.equals("Nico 動態")?z:j;}
 private static int dp(Context c,int n){return PanelUi.dp(c,n);}private static TextView text(Context c,String s,int size){return PanelUi.text(c,s,size);}private static Button button(Context c,String s){return PanelUi.button(c,s);}
 static void initializeCookies(Context c){try{Class<?> v=Class.forName("e.e.a.v0");if(v.getField("b").get(null)!=null)return;android.content.SharedPreferences p=PreferenceManager.getDefaultSharedPreferences(c);if(p.getBoolean("nologin",false))return;String saved=p.getString("save_cookie","");if(!saved.isEmpty())v.getField("b").set(null,v.getMethod("b",String.class).invoke(null,saved));}catch(Exception ignored){}}
 public static void capture(JSONObject d,Bundle b){if(d==null||b==null)return;for(String k:new String[]{"series","owner"}){JSONObject o=d.optJSONObject(k);if(o!=null)b.putString("details_"+k,o.toString());}}
 private static JSONObject json(Bundle b,String k){try{return new JSONObject(b.getString(k,"{}"));}catch(Exception e){return new JSONObject();}}
 private static void open(Context c,String url){Intent i=new Intent(Intent.ACTION_VIEW,Uri.parse(url));if(url.matches("https://(?:www\\.)?nicovideo\\.jp/watch/(?:sm|nm|so)?[0-9]+.*"))i.setClassName(c,"com.sauzask.nicoid.NicoidVideoActivity");try{c.startActivity(i);}catch(Exception e){Toast.makeText(c,tr("ページを開けませんでした","Unable to open page","無法開啟頁面"),0).show();}}
 public static void bind(Object f,View root){if(root==null)return;try{initializeCookies(root.getContext());Bundle data=(Bundle)f.getClass().getField("i0").get(f);if(data==null)return;String id=data.getString("videoId","");if(!id.matches("(?:sm|nm|so)?[0-9]+"))return;try{JSONObject w=(JSONObject)Class.forName("e.e.a.ModernPlayback").getField("latestWatch").get(null);if(w!=null&&w.optJSONObject("video")!=null&&id.equals(w.optJSONObject("video").optString("id")))capture(w,data);}catch(Exception ignored){}View description=root.findViewById(0x7f08007a);if(description==null||!(description.getParent() instanceof LinearLayout))return;View nativeFollow=root.findViewById(0x7f0801c7);if(nativeFollow!=null){nativeFollow.setVisibility(8);if(nativeFollow.getLayoutParams()!=null)nativeFollow.getLayoutParams().width=0;}View bar=root.findViewById(0x7f0801c8);if(bar instanceof LinearLayout){LinearLayout holder=(LinearLayout)bar;View previous=holder.findViewWithTag("nicoid_follow");if(previous==null){JSONObject owner=json(data,"details_owner");String user=owner.optString("id",data.getString("videoUserId",""));if(user.matches("[0-9]+")){FollowIcon b=new FollowIcon(root.getContext());b.setTag("nicoid_follow");LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(dp(root.getContext(),48),dp(root.getContext(),48));lp.gravity=Gravity.CENTER_VERTICAL;lp.setMargins(dp(root.getContext(),8),0,dp(root.getContext(),8),0);holder.addView(b,lp);b.setVisibility(PreferenceManager.getDefaultSharedPreferences(root.getContext()).getBoolean(DetailSettings.FOLLOW,true)?0:8);if(b.getVisibility()==0)followButton(b,user,owner);}}else previous.setVisibility(PreferenceManager.getDefaultSharedPreferences(root.getContext()).getBoolean(DetailSettings.FOLLOW,true)?0:8);}LinearLayout parent=(LinearLayout)description.getParent();if(parent.findViewWithTag("nicoid_details")!=null)return;LinearLayout box=PanelUi.column(root.getContext());box.setTag("nicoid_details");parent.addView(box);box.addView(text(root.getContext(),tr("シリーズ","Series","系列"),18));LinearLayout series=PanelUi.column(root.getContext());box.addView(series);JSONObject cached=json(data,"details_series");if(cached.optString("id").matches("[0-9]+"))renderSeries(series,cached);else loadSeries(series,id);box.addView(text(root.getContext(),tr("親作品・子作品","Parent and child works","父作品與子作品"),18));for(String k:new String[]{"parents","children"}){LinearLayout group=PanelUi.column(root.getContext());box.addView(group);new TreePage(group,id,k).load();}}catch(Exception ignored){}}
 static JSONObject watchData(JSONObject response){return DetailData.watchData(response);}
 private static void loadSeries(LinearLayout box,String id){box.removeAllViews();TextView loading=text(box.getContext(),tr("読み込み中…","Loading…","載入中…"),14);box.addView(loading);NetworkTask task=new NetworkTask();scope(box,task);box.addOnAttachStateChangeListener(new View.OnAttachStateChangeListener(){public void onViewDetachedFromWindow(View v){}public void onViewAttachedToWindow(View v){if(task.cancelled()&&loading.getParent()!=null){box.removeOnAttachStateChangeListener(this);loadSeries(box,id);}}});task.start(WORK,()->{try{JSONObject d=watchData(request("https://www.nicovideo.jp/watch/"+id+"?responseType=json","GET",true,task));JSONObject s=d.optJSONObject("series");if(!d.has("video"))throw new IOException();MAIN.post(()->{if(task.cancelled())return;box.removeAllViews();if(s==null||!s.optString("id").matches("[0-9]+"))box.addView(text(box.getContext(),tr("シリーズに登録されていません","Not part of a series","未加入系列"),14));else renderSeries(box,s);});}catch(Exception e){android.util.Log.w("NicoidDetails","Series metadata request failed: "+e.getClass().getSimpleName()+" "+(e instanceof IOException?e.getMessage():"invalid response"));MAIN.post(()->{if(task.cancelled())return;loading.setText(tr("シリーズ情報を取得できませんでした","Unable to load series","無法載入系列資訊"));Button retry=button(box.getContext(),tr("再試行","Retry","重試"));retry.setOnClickListener(v->loadSeries(box,id));box.addView(retry);});}});}
 private static void renderSeries(LinearLayout box,JSONObject s){box.addView(text(box.getContext(),s.optString("title"),16));JSONObject videos=s.optJSONObject("video");if(videos!=null)for(String k:new String[]{"prev","next"}){JSONObject row=videos.optJSONObject(k);if(row!=null)videoRow(box,row,k.equals("prev")?tr("前の動画","Previous video","上一部影片"):tr("次の動画","Next video","下一部影片"));}new SeriesPage(box,s.optString("id"));}
 static String target(JSONObject item){return DetailData.target(item);}
 static String thumbnail(JSONObject item){return DetailData.thumbnail(item);}
 private static void videoRow(LinearLayout box,JSONObject item,String prefix){Context c=box.getContext();LinearLayout row=new LinearLayout(c);row.setGravity(Gravity.CENTER_VERTICAL);row.setPadding(dp(c,4),dp(c,6),dp(c,4),dp(c,6));FrameLayout image=new FrameLayout(c);ImageView thumb=new ImageView(c);thumb.setScaleType(ImageView.ScaleType.CENTER_CROP);TextView placeholder=text(c,"▶",14);image.addView(placeholder,new FrameLayout.LayoutParams(-1,-1));image.addView(thumb,new FrameLayout.LayoutParams(-1,-1));row.addView(image,new LinearLayout.LayoutParams(dp(c,96),dp(c,54)));TextView name=text(c,(prefix.isEmpty()?"":prefix+"\n")+item.optString("title",item.optString("globalId","")),14);row.addView(name,new LinearLayout.LayoutParams(0,-2,1));row.setContentDescription(name.getText());row.setOnClickListener(v->open(c,target(item)));box.addView(row);PanelUi.divider(box);ShortImages.load(thumbnail(item),thumb,placeholder);}
 private static final class TreePage {
 final LinearLayout box,rows;final String id,key;final TextView title;final Button more,collapse;int offset,initialRows,total;boolean busy,collapsed;NetworkTask active;
 TreePage(LinearLayout b,String i,String k){box=b;id=i;key=k;title=text(b.getContext(),k.equals("parents")?tr("親作品","Parent works","父作品"):tr("子作品","Child works","子作品"),14);box.addView(title);rows=PanelUi.column(b.getContext());box.addView(rows);more=button(b.getContext(),tr("読み込み中…","Loading…","載入中…"));more.setOnClickListener(v->{if(collapsed){collapsed=false;for(int n=initialRows;n<rows.getChildCount();n++)rows.getChildAt(n).setVisibility(View.VISIBLE);buttons();}else load();});box.addView(more);collapse=button(b.getContext(),tr("折りたたむ","Show less","收合"));collapse.setVisibility(View.GONE);collapse.setOnClickListener(v->{collapsed=true;for(int n=initialRows;n<rows.getChildCount();n++)rows.getChildAt(n).setVisibility(View.GONE);buttons();});box.addView(collapse);box.addOnAttachStateChangeListener(new View.OnAttachStateChangeListener(){public void onViewDetachedFromWindow(View v){if(active!=null)active.cancel();}public void onViewAttachedToWindow(View v){if(active!=null&&active.cancelled()&&busy){busy=false;load();}}});}
 void buttons(){more.setVisibility(collapsed||offset<total?View.VISIBLE:View.GONE);more.setEnabled(!busy);more.setText(tr("もっと見る","View more","查看更多"));collapse.setVisibility(!collapsed&&rows.getChildCount()>initialRows?View.VISIBLE:View.GONE);collapse.setEnabled(!busy);}
 void load(){if(busy)return;busy=true;more.setEnabled(false);collapse.setEnabled(false);NetworkTask task=new NetworkTask();active=task;int limit=offset==0?3:20;task.start(WORK,()->{try{JSONObject d=request("https://public-api.commons.nicovideo.jp/v1/tree/"+id+"/relatives/"+key+"?_limit="+limit+"&_offset="+offset+"&with_meta=1","GET",false,task).optJSONObject("data");JSONObject group=d==null?null:d.optJSONObject(key);if(group==null)throw new IOException();JSONArray a=group.optJSONArray("contents");int foundTotal=group.optInt("total");MAIN.post(()->{if(task.cancelled())return;busy=false;total=foundTotal;title.setText((key.equals("parents")?tr("親作品","Parent works","父作品"):tr("子作品","Child works","子作品"))+" ("+total+")");int count=a==null?0:a.length();for(int n=0;n<count;n++){JSONObject o=a.optJSONObject(n);if(o!=null&&o.optString("visibleStatus","visible").equals("visible"))videoRow(rows,o,"");}if(offset==0)initialRows=rows.getChildCount();offset+=count;if(count==0)total=offset;buttons();});}catch(Exception e){MAIN.post(()->{if(task.cancelled())return;busy=false;more.setEnabled(true);collapse.setEnabled(true);more.setText(tr("再試行","Retry","重試"));});}});}}
 private static final class SeriesPage {
 final LinearLayout box,rows;final String id;final Button more,collapse;int page=1,loaded,total=Integer.MAX_VALUE;boolean busy,collapsed;NetworkTask active;
 SeriesPage(LinearLayout b,String i){box=b;id=i;rows=PanelUi.column(b.getContext());box.addView(rows);more=button(b.getContext(),tr("もっと見る","View more","查看更多"));box.addView(more);collapse=button(b.getContext(),tr("折りたたむ","Show less","收合"));collapse.setVisibility(View.GONE);box.addView(collapse);more.setOnClickListener(v->{if(collapsed){collapsed=false;rows.setVisibility(View.VISIBLE);buttons();}else load();});collapse.setOnClickListener(v->{collapsed=true;rows.setVisibility(View.GONE);buttons();});box.addOnAttachStateChangeListener(new View.OnAttachStateChangeListener(){public void onViewDetachedFromWindow(View v){if(active!=null)active.cancel();}public void onViewAttachedToWindow(View v){if(active!=null&&active.cancelled()&&busy){busy=false;load();}}});}
 void buttons(){more.setVisibility(collapsed||loaded<total?View.VISIBLE:View.GONE);more.setEnabled(!busy);more.setText(tr("もっと見る","View more","查看更多"));collapse.setVisibility(!collapsed&&rows.getChildCount()>0?View.VISIBLE:View.GONE);collapse.setEnabled(!busy);}
 void load(){if(busy)return;busy=true;more.setEnabled(false);collapse.setEnabled(false);NetworkTask task=new NetworkTask();active=task;task.start(WORK,()->{try{JSONObject d=request("https://nvapi.nicovideo.jp/v1/playlist/series/"+id+"?page="+page+"&pageSize=20","GET",false,task).optJSONObject("data");if(d==null)throw new IOException();JSONArray items=d.optJSONArray("items");int foundTotal=d.optInt("totalCount");MAIN.post(()->{if(task.cancelled())return;busy=false;total=foundTotal;int count=items==null?0:items.length();for(int i=0;i<count;i++){JSONObject row=items.optJSONObject(i);JSONObject item=row==null?null:row.optJSONObject("content");if(item!=null)videoRow(rows,item,"");}loaded+=count;page++;if(count==0)total=loaded;buttons();});}catch(Exception e){MAIN.post(()->{if(task.cancelled())return;busy=false;more.setEnabled(true);collapse.setEnabled(true);more.setText(tr("再試行","Retry","重試"));});}});}}
 static void label(Button b,String text,boolean followed){b.setText(text);b.setContentDescription(text);if(b instanceof FollowIcon)((FollowIcon)b).state(followed);}
 static final class FollowIcon extends Button {boolean followed;final Paint ink=new Paint(3);FollowIcon(Context c){super(c);setPadding(0,0,0,0);setMinWidth(0);setMinimumWidth(0);setMinHeight(0);setMinimumHeight(0);setElevation(0);state(false);}void state(boolean s){followed=s;setBackgroundTintList(null);int color=s?ThemeChoice.accent(getContext()):ThemeChoice.isNight(getContext())?0xff22252b:0xffe5e8eb;setBackground(new android.graphics.drawable.InsetDrawable(PanelUi.round(getContext(),color,100),dp(getContext(),6)));invalidate();}protected void onDraw(Canvas c){float w=getWidth(),h=getHeight(),unit=Math.min(w,h)/64f;int color=followed?(ThemeChoice.isNight(getContext())?0xff19202a:0xffffffff):ThemeChoice.accent(getContext());ink.setColor(color);ink.setAlpha(isEnabled()?255:130);ink.setStrokeWidth(2*unit);ink.setStyle(Paint.Style.STROKE);ink.setStrokeCap(Paint.Cap.ROUND);c.save();c.translate((w-48*unit)/2,(h-48*unit)/2);c.scale(unit,unit);ink.setStrokeWidth(2);c.drawCircle(20,15,5,ink);c.drawArc(10,23,30,39,180,180,false,ink);if(followed){c.drawLine(32,27,35,30,ink);c.drawLine(35,30,41,23,ink);}else{c.drawLine(32,26,40,26,ink);c.drawLine(36,22,36,30,ink);}c.restore();}}
 static String cookie(){try{Class<?> c=Class.forName("e.e.a.v0");Object store=c.getField("b").get(null);return store==null?"":(String)c.getMethod("a",Class.forName("org.apache.http.client.CookieStore")).invoke(null,store);}catch(Exception e){return "";}}
 static JSONObject request(String url,String method,boolean authenticated,NetworkTask task)throws Exception{return request(url,method,authenticated,task,null);}
 static JSONObject request(String url,String method,boolean authenticated,NetworkTask task,String body)throws Exception{
  HttpURLConnection c=(HttpURLConnection)new URL(url).openConnection();if(!task.bind(c))throw new InterruptedIOException();try{c.setRequestMethod(method);c.setConnectTimeout(10000);c.setReadTimeout(10000);c.setInstanceFollowRedirects(false);c.setRequestProperty("Accept",url.startsWith("https://www.nicovideo.jp/watch/")?"*/*":"application/json");if(url.startsWith("https://www.nicovideo.jp/watch/"))c.setRequestProperty("User-Agent","Mozilla/5.0");c.setRequestProperty("X-Frontend-Id","6");c.setRequestProperty("X-Frontend-Version","0");c.setRequestProperty("X-Request-With","https://www.nicovideo.jp");c.setRequestProperty("Origin","https://www.nicovideo.jp");if(authenticated)c.setRequestProperty("Cookie",cookie());if(body!=null){byte[] payload=body.getBytes("UTF-8");c.setDoOutput(true);c.setRequestProperty("Content-Type","application/x-www-form-urlencoded; charset=UTF-8");c.setFixedLengthStreamingMode(payload.length);try(OutputStream output=c.getOutputStream()){output.write(payload);}}int status=c.getResponseCode();if(status<200||status>=300)throw new IOException("HTTP "+status);ByteArrayOutputStream out=new ByteArrayOutputStream();try(InputStream in=c.getInputStream()){byte[] bytes=new byte[8192];int n;while((n=in.read(bytes))!=-1){if(task.cancelled()||out.size()+n>2*1024*1024)throw new IOException("Request cancelled or oversized");out.write(bytes,0,n);}}JSONObject result=out.size()==0?new JSONObject():new JSONObject(out.toString("UTF-8"));JSONObject meta=result.optJSONObject("meta");if(meta!=null&&meta.optInt("status",200)>=300)throw new IOException("Request rejected");return result;}finally{task.release(c);c.disconnect();}}
 private static void scope(View view,NetworkTask task){view.addOnAttachStateChangeListener(new View.OnAttachStateChangeListener(){public void onViewAttachedToWindow(View v){if(task.cancelled()&&v instanceof Button){((Button)v).setText(tr("再試行","Retry","重試"));v.setEnabled(true);v.removeOnAttachStateChangeListener(this);}}public void onViewDetachedFromWindow(View v){task.cancel();}});}
 private static void followButton(Button button,String user,JSONObject owner){final boolean[] following={owner.optBoolean("isFollowing",false)};final String url="https://user-follow-api.nicovideo.jp/v1/user/followees/niconico-users/"+user+".json";
  Runnable label=()->label(button,following[0]?tr("フォロー中","Following","追蹤中"):tr("フォロー","Follow","追蹤"),following[0]);label.run();button.setEnabled(false);NetworkTask status=new NetworkTask();scope(button,status);status.start(WORK,()->{try{JSONObject data=request(url,"GET",true,status).optJSONObject("data");if(data==null||!data.has("following"))throw new IOException();boolean value=data.optBoolean("following");MAIN.post(()->{if(!status.cancelled()){following[0]=value;label.run();button.setEnabled(true);}});}catch(Exception e){MAIN.post(()->{if(!status.cancelled()){button.setText(tr("再試行","Retry","重試"));button.setEnabled(true);}});}});
  button.setOnClickListener(v->{if(button.getText().equals(tr("再試行","Retry","重試"))){followButton(button,user,owner);return;}if(!cookie().contains("user_session=")){Toast.makeText(button.getContext(),tr("ログインが必要です","Sign in required","請先登入"),Toast.LENGTH_SHORT).show();return;}button.setEnabled(false);NetworkTask task=new NetworkTask();scope(button,task);task.start(WORK,()->{try{request(url,following[0]?"DELETE":"POST",true,task);MAIN.post(()->{if(!task.cancelled()){following[0]=!following[0];label.run();button.setEnabled(true);}});}catch(Exception e){MAIN.post(()->{if(!task.cancelled()){button.setEnabled(true);Toast.makeText(button.getContext(),tr("フォローの変更に失敗しました","Unable to change follow status","無法變更追蹤狀態"),Toast.LENGTH_SHORT).show();}});}});});
 }

}
