package dev.jkcarino.adobo.patches.imdb.ad

internal const val AD_HOSTS = """
    ad.doubleclick.net
    admob-gmats.uc.r.appspot.com
    advertising.a2z.com
    amazon-adsystem.com
    api.branch.io
    api.imdb.eu-west-1.prod.paets.advertising.amazon.dev
    api2.branch.io
    api3-eu.branch.io
    cdn.branch.io
    cdn.prod.metrics.imdb.a2z.com
    cdn.prod.metrics.imdb.com
    census-app.scorecardresearch.com
    googleads.g.doubleclick.net
    logs.af-south-1.amazonaws.com
    logs.ap-northeast-1.amazonaws.com
    logs.ap-northeast-2.amazonaws.com
    logs.ap-south-1.amazonaws.com
    logs.ap-southeast-1.amazonaws.com
    logs.ap-southeast-2.amazonaws.com
    logs.ca-central-1.amazonaws.com
    logs.eu-central-1.amazonaws.com
    logs.eu-north-1.amazonaws.com
    logs.eu-south-1.amazonaws.com
    logs.eu-west-2.amazonaws.com
    logs.eu-west-3.amazonaws.com
    logs.me-south-1.amazonaws.com
    logs.sa-east-1.amazonaws.com
    logs.us-east-2.amazonaws.com
    logs.us-gov-east-1.amazonaws.com
    logs.us-gov-west-1.amazonaws.com
    logs.us-west-1.amazonaws.com
    logs.us-west-2.amazonaws.com
    mobileanalytics.us-east-1.amazonaws.com
    pagead2.googlesyndication.com
    sb.scorecardresearch.com
    sdk.iad-01.braze.com
    sondheim.braze.com
    www.googleadservices.com
"""
