name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - dev

jobs:
  release:
    name: Release
    permissions:
      contents: write
      packages: write
      id-token: write
      attestations: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache Gradle
        uses: burrunan/gradle-cache-action@v3

      - name: Download Stockfish Binaries
        run: ./.github/scripts/download_stockfish.sh

      - name: Build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew :patches:buildAndroid generatePatchesList clean

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 'lts/*'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Release
        uses: cycjimmy/semantic-release-action@v5
        id: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Attest
        if: steps.release.outputs.new_release_published == 'true'
        uses: actions/attest-build-provenance@v4
        with:
          subject-name: 'Morphe Patches ${{ steps.release.outputs.new_release_git_tag }}'
          subject-path: patches/build/libs/patches-*.mpp

      - name: Install database dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y zstd

      - name: Run database extraction script
        run: |
          python3 .github/scripts/extract_puzzles.py

      - name: Upload databases to Database Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release view database || gh release create database --title "Lichess Offline Database" --notes "Pre-built Lichess offline puzzle database files."
          gh release upload database lichess_offline_puzzles_all.csv.gz --clobber
          gh release upload database lichess_offline_puzzles_500k.csv.gz --clobber
          gh release upload database lichess_offline_puzzles_100k.csv.gz --clobber
          gh release upload database lichess_offline_puzzles_50k.csv.gz --clobber
          gh release upload database lichess_offline_puzzles_20k.csv.gz --clobber
