package app.intothedead2.patches.il2cpp

import app.morphe.patcher.patch.rawResourcePatch
import app.intothedead2.patches.shared.Constants.COMPATIBILITY_INTO_THE_DEAD_2

/**
 * Embeds the compiled IAP-grant engine into the APK as a native library.
 *
 * The engine (built from analysis/into-the-dead-2/ndk/ via nix + NDK r27,
 * bytes generated by ndk/lib/gen_so_bytes.py) is a small ARM64 companion
 * library that, once loaded by the trigger patch:
 *   1. waits for libil2cpp.so to be mapped + unpacked (probe, not blind sleep),
 *   2. forces the <VerifyReceipt>d__1.MoveNext verdict branch to Success
 *      (tbz -> nop, so the PCubed server rejection can never fail the flow),
 *   3. forces PurchaseManager.get_Busy to false (re-taps are never dropped),
 *   4. backstops stuck purchases by invoking RewardsManager.ProcessReward
 *      with the tapped product id directly (same tail GiveReward uses).
 *
 * Ships alongside the T1+T2 Java patches (FreeIap): Java delivers the
 * fabricated purchase to C#, native forces the grant. Either layer alone
 * cannot grant (see notes/verify-receipt-trace.md).
 */
@Suppress("unused")
val nativeIapGrantEnginePatch = rawResourcePatch(
    name = "IAP Grant Engine",
    description = "Helper that makes the game approve every purchase on your own device, including subscriptions like VIP membership, so bought items land in your account without paying anything.",
    default = true
) {
    compatibleWith(COMPATIBILITY_INTO_THE_DEAD_2)

    execute {
        val soFile = get("lib/arm64-v8a/libDr2IapGrant.so", true)
        soFile.writeBytes(Dr2IapGrantSoBytes.bytes())
    }
}
