[versions]
morphe-patcher = "1.11.0"
#noinspection GradleDependency
smali = "d92701d947"
gson = "2.14.0"
kotlin-test = "2.1.20"

[libraries]
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin-test" }
