package com.drew.metadata.exif;

import androidx.core.widget.nRCC.nGxjfIr;
import com.drew.metadata.Directory;
import defpackage.lv8;
import java.util.HashMap;
import sprig.b.VPIE.dpBiLjNeNsiASg;
import sprig.g.Hq.fiHTiFJ;

/* JADX INFO: compiled from: r8-map-id-b2309a5993a3f14549aeb617bc4a78ecbec51e99a3efca387f8965087335ae2d */
/* JADX INFO: loaded from: classes2.dex */
public abstract class ExifDirectoryBase extends Directory {
    public static final int TAG_35MM_FILM_EQUIV_FOCAL_LENGTH = 41989;
    public static final int TAG_ACCELERATION = 37892;
    public static final int TAG_APERTURE = 37378;
    public static final int TAG_APPLICATION_NOTES = 700;
    public static final int TAG_ARTIST = 315;
    public static final int TAG_BATTERY_LEVEL = 33423;
    public static final int TAG_BITS_PER_SAMPLE = 258;
    public static final int TAG_BODY_SERIAL_NUMBER = 42033;
    public static final int TAG_BRIGHTNESS_VALUE = 37379;
    public static final int TAG_CAMERA_ELEVATION_ANGLE = 37893;
    public static final int TAG_CAMERA_OWNER_NAME = 42032;
    public static final int TAG_CFA_PATTERN = 41730;
    public static final int TAG_CFA_PATTERN_2 = 33422;
    public static final int TAG_CFA_REPEAT_PATTERN_DIM = 33421;
    public static final int TAG_COLOR_SPACE = 40961;
    public static final int TAG_COMPONENTS_CONFIGURATION = 37121;
    public static final int TAG_COMPRESSED_AVERAGE_BITS_PER_PIXEL = 37122;
    public static final int TAG_COMPRESSION = 259;
    public static final int TAG_CONTRAST = 41992;
    public static final int TAG_COPYRIGHT = 33432;
    public static final int TAG_CUSTOM_RENDERED = 41985;
    public static final int TAG_DATETIME = 306;
    public static final int TAG_DATETIME_DIGITIZED = 36868;
    public static final int TAG_DATETIME_ORIGINAL = 36867;
    public static final int TAG_DEVICE_SETTING_DESCRIPTION = 41995;
    public static final int TAG_DIGITAL_ZOOM_RATIO = 41988;
    public static final int TAG_DOCUMENT_NAME = 269;
    public static final int TAG_EXIF_IMAGE_HEIGHT = 40963;
    public static final int TAG_EXIF_IMAGE_WIDTH = 40962;
    public static final int TAG_EXIF_VERSION = 36864;
    public static final int TAG_EXPOSURE_BIAS = 37380;
    public static final int TAG_EXPOSURE_INDEX = 41493;
    public static final int TAG_EXPOSURE_INDEX_TIFF_EP = 37397;
    public static final int TAG_EXPOSURE_MODE = 41986;
    public static final int TAG_EXPOSURE_PROGRAM = 34850;
    public static final int TAG_EXPOSURE_TIME = 33434;
    public static final int TAG_EXTRA_SAMPLES = 338;
    public static final int TAG_FILE_SOURCE = 41728;
    public static final int TAG_FILL_ORDER = 266;
    public static final int TAG_FLASH = 37385;
    public static final int TAG_FLASHPIX_VERSION = 40960;
    public static final int TAG_FLASH_ENERGY = 41483;
    public static final int TAG_FLASH_ENERGY_TIFF_EP = 37387;
    public static final int TAG_FNUMBER = 33437;
    public static final int TAG_FOCAL_LENGTH = 37386;
    public static final int TAG_FOCAL_PLANE_RESOLUTION_UNIT = 41488;
    public static final int TAG_FOCAL_PLANE_X_RESOLUTION = 41486;
    public static final int TAG_FOCAL_PLANE_X_RESOLUTION_TIFF_EP = 37390;
    public static final int TAG_FOCAL_PLANE_Y_RESOLUTION = 41487;
    public static final int TAG_FOCAL_PLANE_Y_RESOLUTION_TIFF_EP = 37391;
    public static final int TAG_GAIN_CONTROL = 41991;
    public static final int TAG_GAMMA = 42240;
    public static final int TAG_HOST_COMPUTER = 316;
    public static final int TAG_HUMIDITY = 37889;
    public static final int TAG_IMAGE_DESCRIPTION = 270;
    public static final int TAG_IMAGE_HEIGHT = 257;
    public static final int TAG_IMAGE_HISTORY = 37395;
    public static final int TAG_IMAGE_NUMBER = 37393;
    public static final int TAG_IMAGE_UNIQUE_ID = 42016;
    public static final int TAG_IMAGE_WIDTH = 256;
    public static final int TAG_INTERLACE = 34857;
    public static final int TAG_INTEROP_INDEX = 1;
    public static final int TAG_INTEROP_VERSION = 2;
    public static final int TAG_INTER_COLOR_PROFILE = 34675;
    public static final int TAG_IPTC_NAA = 33723;
    public static final int TAG_ISO_EQUIVALENT = 34855;
    public static final int TAG_ISO_SPEED = 34867;
    public static final int TAG_ISO_SPEED_LATITUDE_YYY = 34868;
    public static final int TAG_ISO_SPEED_LATITUDE_ZZZ = 34869;
    public static final int TAG_JPEG_AC_TABLES = 521;
    public static final int TAG_JPEG_DC_TABLES = 520;
    public static final int TAG_JPEG_LOSSLESS_PREDICTORS = 517;
    public static final int TAG_JPEG_POINT_TRANSFORMS = 518;
    public static final int TAG_JPEG_PROC = 512;
    public static final int TAG_JPEG_Q_TABLES = 519;
    public static final int TAG_JPEG_RESTART_INTERVAL = 515;
    public static final int TAG_JPEG_TABLES = 347;
    public static final int TAG_LENS = 65002;
    public static final int TAG_LENS_MAKE = 42035;
    public static final int TAG_LENS_MODEL = 42036;
    public static final int TAG_LENS_SERIAL_NUMBER = 42037;
    public static final int TAG_LENS_SPECIFICATION = 42034;

    @Deprecated
    public static final int TAG_LIGHT_SOURCE = 37384;
    public static final int TAG_MAKE = 271;
    public static final int TAG_MAKERNOTE = 37500;
    public static final int TAG_MAX_APERTURE = 37381;
    public static final int TAG_MAX_SAMPLE_VALUE = 281;
    public static final int TAG_METERING_MODE = 37383;
    public static final int TAG_MIN_SAMPLE_VALUE = 280;
    public static final int TAG_MODEL = 272;
    public static final int TAG_NEW_SUBFILE_TYPE = 254;
    public static final int TAG_NOISE = 37389;
    public static final int TAG_OPTO_ELECTRIC_CONVERSION_FUNCTION = 34856;
    public static final int TAG_ORIENTATION = 274;
    public static final int TAG_PADDING = 59932;
    public static final int TAG_PAGE_NAME = 285;
    public static final int TAG_PAGE_NUMBER = 297;
    public static final int TAG_PANASONIC_TITLE = 50898;
    public static final int TAG_PANASONIC_TITLE_2 = 50899;
    public static final int TAG_PHOTOMETRIC_INTERPRETATION = 262;
    public static final int TAG_PHOTOSHOP_SETTINGS = 34377;
    public static final int TAG_PLANAR_CONFIGURATION = 284;
    public static final int TAG_PREDICTOR = 317;
    public static final int TAG_PRESSURE = 37890;
    public static final int TAG_PRIMARY_CHROMATICITIES = 319;
    public static final int TAG_PRINT_IMAGE_MATCHING_INFO = 50341;
    public static final int TAG_RATING = 18246;
    public static final int TAG_RATING_PERCENT = 18249;
    public static final int TAG_RECOMMENDED_EXPOSURE_INDEX = 34866;
    public static final int TAG_REFERENCE_BLACK_WHITE = 532;
    public static final int TAG_RELATED_IMAGE_FILE_FORMAT = 4096;
    public static final int TAG_RELATED_IMAGE_HEIGHT = 4098;
    public static final int TAG_RELATED_IMAGE_WIDTH = 4097;
    public static final int TAG_RELATED_SOUND_FILE = 40964;
    public static final int TAG_RESOLUTION_UNIT = 296;
    public static final int TAG_ROWS_PER_STRIP = 278;
    public static final int TAG_SAMPLES_PER_PIXEL = 277;
    public static final int TAG_SAMPLE_FORMAT = 339;
    public static final int TAG_SATURATION = 41993;
    public static final int TAG_SCENE_CAPTURE_TYPE = 41990;
    public static final int TAG_SCENE_TYPE = 41729;
    public static final int TAG_SECURITY_CLASSIFICATION = 37394;
    public static final int TAG_SELF_TIMER_MODE_TIFF_EP = 34859;
    public static final int TAG_SENSING_METHOD = 41495;
    public static final int TAG_SENSITIVITY_TYPE = 34864;
    public static final int TAG_SHARPNESS = 41994;
    public static final int TAG_SHUTTER_SPEED = 37377;
    public static final int TAG_SOFTWARE = 305;
    public static final int TAG_SPATIAL_FREQ_RESPONSE = 41484;
    public static final int TAG_SPATIAL_FREQ_RESPONSE_TIFF_EP = 37388;
    public static final int TAG_SPECTRAL_SENSITIVITY = 34852;
    public static final int TAG_STANDARD_ID_TIFF_EP = 37398;
    public static final int TAG_STANDARD_OUTPUT_SENSITIVITY = 34865;
    public static final int TAG_STRIP_BYTE_COUNTS = 279;
    public static final int TAG_STRIP_OFFSETS = 273;
    public static final int TAG_STRIP_ROW_COUNTS = 559;
    public static final int TAG_SUBFILE_TYPE = 255;
    public static final int TAG_SUBJECT_DISTANCE = 37382;
    public static final int TAG_SUBJECT_DISTANCE_RANGE = 41996;
    public static final int TAG_SUBJECT_LOCATION = 41492;
    public static final int TAG_SUBJECT_LOCATION_TIFF_EP = 37396;
    public static final int TAG_SUBSECOND_TIME = 37520;
    public static final int TAG_SUBSECOND_TIME_DIGITIZED = 37522;
    public static final int TAG_SUBSECOND_TIME_ORIGINAL = 37521;
    public static final int TAG_SUB_IFD_OFFSET = 330;
    public static final int TAG_TEMPERATURE = 37888;
    public static final int TAG_THRESHOLDING = 263;
    public static final int TAG_TILE_BYTE_COUNTS = 325;
    public static final int TAG_TILE_LENGTH = 323;
    public static final int TAG_TILE_OFFSETS = 324;
    public static final int TAG_TILE_WIDTH = 322;
    public static final int TAG_TIME_ZONE = 36880;
    public static final int TAG_TIME_ZONE_DIGITIZED = 36882;
    public static final int TAG_TIME_ZONE_OFFSET_TIFF_EP = 34858;
    public static final int TAG_TIME_ZONE_ORIGINAL = 36881;
    public static final int TAG_TRANSFER_FUNCTION = 301;
    public static final int TAG_TRANSFER_RANGE = 342;
    public static final int TAG_USER_COMMENT = 37510;
    public static final int TAG_WATER_DEPTH = 37891;
    public static final int TAG_WHITE_BALANCE = 37384;
    public static final int TAG_WHITE_BALANCE_MODE = 41987;
    public static final int TAG_WHITE_POINT = 318;
    public static final int TAG_WIN_AUTHOR = 40093;
    public static final int TAG_WIN_COMMENT = 40092;
    public static final int TAG_WIN_KEYWORDS = 40094;
    public static final int TAG_WIN_SUBJECT = 40095;
    public static final int TAG_WIN_TITLE = 40091;
    public static final int TAG_X_RESOLUTION = 282;
    public static final int TAG_YCBCR_COEFFICIENTS = 529;
    public static final int TAG_YCBCR_POSITIONING = 531;
    public static final int TAG_YCBCR_SUBSAMPLING = 530;
    public static final int TAG_Y_RESOLUTION = 283;

    public static void addExifTagNames(HashMap<Integer, String> map) {
        lv8.x(1, map, "Interoperability Index", 2, "Interoperability Version");
        lv8.x(TAG_NEW_SUBFILE_TYPE, map, "New Subfile Type", 255, "Subfile Type");
        lv8.x(256, map, "Image Width", 257, "Image Height");
        lv8.x(258, map, "Bits Per Sample", 259, "Compression");
        lv8.x(262, map, "Photometric Interpretation", 263, "Thresholding");
        lv8.x(266, map, "Fill Order", 269, "Document Name");
        lv8.x(270, map, "Image Description", 271, "Make");
        lv8.x(272, map, "Model", 273, "Strip Offsets");
        lv8.x(274, map, "Orientation", 277, "Samples Per Pixel");
        lv8.x(278, map, "Rows Per Strip", 279, "Strip Byte Counts");
        lv8.x(280, map, "Minimum Sample Value", 281, "Maximum Sample Value");
        lv8.x(282, map, "X Resolution", 283, "Y Resolution");
        lv8.x(284, map, "Planar Configuration", 285, "Page Name");
        lv8.x(296, map, "Resolution Unit", TAG_PAGE_NUMBER, "Page Number");
        lv8.x(301, map, "Transfer Function", 305, "Software");
        lv8.x(306, map, "Date/Time", TAG_ARTIST, "Artist");
        lv8.x(TAG_PREDICTOR, map, "Predictor", 316, "Host Computer");
        lv8.x(TAG_WHITE_POINT, map, "White Point", TAG_PRIMARY_CHROMATICITIES, "Primary Chromaticities");
        lv8.x(TAG_TILE_WIDTH, map, "Tile Width", TAG_TILE_LENGTH, "Tile Length");
        lv8.x(TAG_TILE_OFFSETS, map, "Tile Offsets", TAG_TILE_BYTE_COUNTS, "Tile Byte Counts");
        lv8.x(TAG_SUB_IFD_OFFSET, map, "Sub IFD Pointer(s)", TAG_EXTRA_SAMPLES, "Extra Samples");
        lv8.x(TAG_SAMPLE_FORMAT, map, "Sample Format", TAG_TRANSFER_RANGE, "Transfer Range");
        lv8.x(TAG_JPEG_TABLES, map, "JPEG Tables", 512, "JPEG Proc");
        lv8.x(515, map, "JPEG Restart Interval", 517, "JPEG Lossless Predictors");
        lv8.x(518, map, "JPEG Point Transforms", 519, "JPEGQ Tables");
        lv8.x(520, map, "JPEGDC Tables", 521, "JPEGAC Tables");
        lv8.x(529, map, "YCbCr Coefficients", 530, "YCbCr Sub-Sampling");
        lv8.x(531, map, "YCbCr Positioning", 532, "Reference Black/White");
        lv8.x(559, map, "Strip Row Counts", 700, "Application Notes");
        lv8.x(4096, map, "Related Image File Format", 4097, "Related Image Width");
        lv8.x(4098, map, "Related Image Height", TAG_RATING, "Rating");
        lv8.x(TAG_RATING_PERCENT, map, "Rating Percent", TAG_CFA_REPEAT_PATTERN_DIM, "CFA Repeat Pattern Dim");
        String str = fiHTiFJ.CQkVGkBTFYx;
        lv8.x(TAG_CFA_PATTERN_2, map, str, TAG_BATTERY_LEVEL, "Battery Level");
        lv8.x(TAG_COPYRIGHT, map, "Copyright", TAG_EXPOSURE_TIME, "Exposure Time");
        lv8.x(TAG_FNUMBER, map, "F-Number", TAG_IPTC_NAA, "IPTC/NAA");
        lv8.x(TAG_PHOTOSHOP_SETTINGS, map, "Photoshop Settings", TAG_INTER_COLOR_PROFILE, "Inter Color Profile");
        lv8.x(TAG_EXPOSURE_PROGRAM, map, "Exposure Program", TAG_SPECTRAL_SENSITIVITY, dpBiLjNeNsiASg.wyHD);
        lv8.x(TAG_ISO_EQUIVALENT, map, "ISO Speed Ratings", TAG_OPTO_ELECTRIC_CONVERSION_FUNCTION, "Opto-electric Conversion Function (OECF)");
        lv8.x(TAG_INTERLACE, map, "Interlace", TAG_TIME_ZONE_OFFSET_TIFF_EP, "Time Zone Offset");
        lv8.x(TAG_SELF_TIMER_MODE_TIFF_EP, map, "Self Timer Mode", TAG_SENSITIVITY_TYPE, "Sensitivity Type");
        lv8.x(TAG_STANDARD_OUTPUT_SENSITIVITY, map, "Standard Output Sensitivity", TAG_RECOMMENDED_EXPOSURE_INDEX, "Recommended Exposure Index");
        lv8.x(TAG_ISO_SPEED, map, "ISO Speed", TAG_ISO_SPEED_LATITUDE_YYY, "ISO Speed Latitude yyy");
        lv8.x(TAG_ISO_SPEED_LATITUDE_ZZZ, map, "ISO Speed Latitude zzz", TAG_EXIF_VERSION, "Exif Version");
        lv8.x(TAG_DATETIME_ORIGINAL, map, "Date/Time Original", TAG_DATETIME_DIGITIZED, "Date/Time Digitized");
        lv8.x(TAG_TIME_ZONE, map, "Time Zone", TAG_TIME_ZONE_ORIGINAL, "Time Zone Original");
        lv8.x(TAG_TIME_ZONE_DIGITIZED, map, "Time Zone Digitized", TAG_COMPONENTS_CONFIGURATION, "Components Configuration");
        lv8.x(TAG_COMPRESSED_AVERAGE_BITS_PER_PIXEL, map, "Compressed Bits Per Pixel", TAG_SHUTTER_SPEED, "Shutter Speed Value");
        lv8.x(TAG_APERTURE, map, "Aperture Value", TAG_BRIGHTNESS_VALUE, "Brightness Value");
        lv8.x(TAG_EXPOSURE_BIAS, map, nGxjfIr.kyPxEgxMXykDUr, TAG_MAX_APERTURE, "Max Aperture Value");
        lv8.x(TAG_SUBJECT_DISTANCE, map, "Subject Distance", TAG_METERING_MODE, "Metering Mode");
        lv8.x(37384, map, "White Balance", TAG_FLASH, "Flash");
        lv8.x(TAG_FOCAL_LENGTH, map, "Focal Length", TAG_FLASH_ENERGY_TIFF_EP, "Flash Energy");
        lv8.x(TAG_SPATIAL_FREQ_RESPONSE_TIFF_EP, map, "Spatial Frequency Response", TAG_NOISE, "Noise");
        lv8.x(TAG_FOCAL_PLANE_X_RESOLUTION_TIFF_EP, map, "Focal Plane X Resolution", TAG_FOCAL_PLANE_Y_RESOLUTION_TIFF_EP, "Focal Plane Y Resolution");
        lv8.x(TAG_IMAGE_NUMBER, map, "Image Number", TAG_SECURITY_CLASSIFICATION, "Security Classification");
        lv8.x(TAG_IMAGE_HISTORY, map, "Image History", TAG_SUBJECT_LOCATION_TIFF_EP, "Subject Location");
        lv8.x(TAG_EXPOSURE_INDEX_TIFF_EP, map, "Exposure Index", TAG_STANDARD_ID_TIFF_EP, "TIFF/EP Standard ID");
        lv8.x(TAG_MAKERNOTE, map, "Makernote", TAG_USER_COMMENT, "User Comment");
        lv8.x(TAG_SUBSECOND_TIME, map, "Sub-Sec Time", TAG_SUBSECOND_TIME_ORIGINAL, "Sub-Sec Time Original");
        lv8.x(TAG_SUBSECOND_TIME_DIGITIZED, map, "Sub-Sec Time Digitized", TAG_TEMPERATURE, "Temperature");
        lv8.x(TAG_HUMIDITY, map, "Humidity", TAG_PRESSURE, "Pressure");
        lv8.x(TAG_WATER_DEPTH, map, "Water Depth", TAG_ACCELERATION, "Acceleration");
        lv8.x(TAG_CAMERA_ELEVATION_ANGLE, map, "Camera Elevation Angle", TAG_WIN_TITLE, "Windows XP Title");
        lv8.x(TAG_WIN_COMMENT, map, "Windows XP Comment", TAG_WIN_AUTHOR, "Windows XP Author");
        lv8.x(TAG_WIN_KEYWORDS, map, "Windows XP Keywords", TAG_WIN_SUBJECT, "Windows XP Subject");
        lv8.x(TAG_FLASHPIX_VERSION, map, "FlashPix Version", 40961, "Color Space");
        lv8.x(40962, map, "Exif Image Width", 40963, "Exif Image Height");
        lv8.x(40964, map, "Related Sound File", TAG_FLASH_ENERGY, "Flash Energy");
        lv8.x(TAG_SPATIAL_FREQ_RESPONSE, map, "Spatial Frequency Response", TAG_FOCAL_PLANE_X_RESOLUTION, "Focal Plane X Resolution");
        lv8.x(TAG_FOCAL_PLANE_Y_RESOLUTION, map, "Focal Plane Y Resolution", TAG_FOCAL_PLANE_RESOLUTION_UNIT, "Focal Plane Resolution Unit");
        lv8.x(TAG_SUBJECT_LOCATION, map, "Subject Location", TAG_EXPOSURE_INDEX, "Exposure Index");
        lv8.x(TAG_SENSING_METHOD, map, "Sensing Method", TAG_FILE_SOURCE, "File Source");
        lv8.x(TAG_SCENE_TYPE, map, "Scene Type", TAG_CFA_PATTERN, str);
        lv8.x(TAG_CUSTOM_RENDERED, map, "Custom Rendered", TAG_EXPOSURE_MODE, "Exposure Mode");
        lv8.x(TAG_WHITE_BALANCE_MODE, map, "White Balance Mode", TAG_DIGITAL_ZOOM_RATIO, "Digital Zoom Ratio");
        lv8.x(TAG_35MM_FILM_EQUIV_FOCAL_LENGTH, map, "Focal Length 35", TAG_SCENE_CAPTURE_TYPE, "Scene Capture Type");
        lv8.x(TAG_GAIN_CONTROL, map, "Gain Control", TAG_CONTRAST, "Contrast");
        lv8.x(TAG_SATURATION, map, "Saturation", TAG_SHARPNESS, "Sharpness");
        lv8.x(TAG_DEVICE_SETTING_DESCRIPTION, map, "Device Setting Description", TAG_SUBJECT_DISTANCE_RANGE, "Subject Distance Range");
        lv8.x(TAG_IMAGE_UNIQUE_ID, map, "Unique Image ID", TAG_CAMERA_OWNER_NAME, "Camera Owner Name");
        lv8.x(TAG_BODY_SERIAL_NUMBER, map, "Body Serial Number", TAG_LENS_SPECIFICATION, "Lens Specification");
        lv8.x(TAG_LENS_MAKE, map, "Lens Make", TAG_LENS_MODEL, "Lens Model");
        lv8.x(TAG_LENS_SERIAL_NUMBER, map, "Lens Serial Number", TAG_GAMMA, "Gamma");
        lv8.x(TAG_PRINT_IMAGE_MATCHING_INFO, map, "Print Image Matching (PIM) Info", TAG_PANASONIC_TITLE, "Panasonic Title");
        lv8.x(TAG_PANASONIC_TITLE_2, map, "Panasonic Title (2)", TAG_PADDING, "Padding");
        map.put(Integer.valueOf(TAG_LENS), "Lens");
    }
}
