#!/usr/bin/env python3
"""Render Android locale resources from a reviewed language catalog."""

from __future__ import annotations

import argparse
import csv
import re
import xml.etree.ElementTree as ET
from collections import OrderedDict
from pathlib import Path


BOLD_FRAGMENT = re.compile(r"^(.*?)<b>(.*?)</b>(.*?)$", re.DOTALL)


def android_string_text(value: str) -> str:
    escaped = re.sub(r"(?<!\\)'", r"\\'", value)
    escaped = re.sub(r'(?<!\\)"', r'\\"', escaped)
    if escaped.startswith(("@", "?")):
        escaped = "\\" + escaped
    return escaped


def set_android_text(element: ET.Element, plain: str, markup: str) -> None:
    if not markup:
        element.text = android_string_text(plain)
        return
    match = BOLD_FRAGMENT.fullmatch(markup)
    if match is None or markup.count("<b>") != 1 or markup.count("</b>") != 1:
        raise ValueError("unsupported localized markup; expected one <b> span")
    before, bold, after = match.groups()
    if before + bold + after != plain:
        raise ValueError("localized markup differs from plain text")
    element.text = android_string_text(before)
    bold_element = ET.SubElement(element, "b")
    bold_element.text = android_string_text(bold)
    bold_element.tail = android_string_text(after)


def serialize(root: ET.Element, language: str, source_name: str) -> str:
    mixed_content = [
        (element, element.text, [(child, child.tail) for child in element])
        for element in root.iter()
        if element.tag in {"string", "item"} and len(element) > 0
    ]
    ET.indent(root, space="    ")
    for element, text, child_tails in mixed_content:
        element.text = text
        for child, tail in child_tails:
            child.tail = tail
    body = ET.tostring(root, encoding="unicode", short_empty_elements=False)
    return (
        '<?xml version="1.0" encoding="utf-8"?>\n'
        f'<!-- Generated by tools/render_android_catalog.py from {source_name} ({language}). -->\n'
        f"{body}\n"
    )


def render_resources(
    rows: list[dict[str, str]],
    language: str,
    source_name: str = "catalog.csv",
) -> dict[str, str]:
    value_column = language
    markup_column = f"{language}_markup"
    seen: set[tuple[str, str, str]] = set()
    strings_root = ET.Element("resources")
    plural_groups: OrderedDict[str, list[dict[str, str]]] = OrderedDict()
    array_groups: OrderedDict[str, list[dict[str, str]]] = OrderedDict()

    for row in rows:
        resource_type = row["resource_type"]
        key = row["key"]
        qualifier = row.get("item_qualifier", "")
        identity = (resource_type, key, qualifier)
        if identity in seen:
            raise ValueError(f"duplicate resource identity: {identity}")
        seen.add(identity)
        if key == "app_name":
            continue
        if value_column not in row:
            raise ValueError(f"missing language column: {value_column}")
        value = row[value_column]
        if not value.strip():
            raise ValueError(f"blank localized value: {identity}")
        formatted = row.get("formatted", "")
        if formatted not in {"", "true", "false"}:
            raise ValueError(f"invalid formatted attribute: {identity}")
        if formatted and resource_type != "string":
            raise ValueError(f"formatted attribute is only supported for strings: {identity}")
        if resource_type == "string":
            attributes = {"name": key}
            if formatted:
                attributes["formatted"] = formatted
            element = ET.SubElement(strings_root, "string", attributes)
            set_android_text(element, value, row.get(markup_column, ""))
        elif resource_type == "plurals":
            plural_groups.setdefault(key, []).append(row)
        elif resource_type == "string-array":
            array_groups.setdefault(key, []).append(row)
        else:
            raise ValueError(f"unsupported resource type: {resource_type}")

    plurals_root = ET.Element("resources")
    for key, group in plural_groups.items():
        element = ET.SubElement(plurals_root, "plurals", {"name": key})
        for row in group:
            item = ET.SubElement(element, "item", {"quantity": row["item_qualifier"]})
            set_android_text(item, row[value_column], row.get(markup_column, ""))

    arrays_root = ET.Element("resources")
    for key, group in array_groups.items():
        try:
            ordered = sorted(group, key=lambda row: int(row["item_qualifier"]))
        except ValueError as error:
            raise ValueError(f"non-numeric array qualifier for {key}") from error
        element = ET.SubElement(arrays_root, "string-array", {"name": key})
        for row in ordered:
            item = ET.SubElement(element, "item")
            set_android_text(item, row[value_column], row.get(markup_column, ""))

    return {
        "strings.xml": serialize(strings_root, language, source_name),
        "plurals.xml": serialize(plurals_root, language, source_name),
        "arrays.xml": serialize(arrays_root, language, source_name),
    }


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--catalog", type=Path, required=True)
    parser.add_argument("--language", required=True)
    parser.add_argument("--output-dir", type=Path, required=True)
    args = parser.parse_args()

    with args.catalog.open(encoding="utf-8", newline="") as handle:
        rows = list(csv.DictReader(handle))
    rendered = render_resources(rows, args.language, args.catalog.name)
    args.output_dir.mkdir(parents=True, exist_ok=True)
    for file_name, content in rendered.items():
        (args.output_dir / file_name).write_text(content, encoding="utf-8")
        print(args.output_dir / file_name)


if __name__ == "__main__":
    main()
