"""Stage Flutter natives for blutter and explain where to look in its output.

    python tools/blutter_stage.py --package com.hamropatro
    python tools/blutter_stage.py --package com.hamropatro --check

Stages libapp.so / libflutter.so (if not already present) and writes a handoff note with
the facts that are easy to get wrong:

  * blutter's per-function `addr` IS the libapp.so file offset. No vaddr translation.
    Confirm once per snapshot by checking a function prologue.
  * function bodies live in `asm/**/<file>.dart`, one `// ** addr:` header each.
    `objs.txt` does NOT contain Dart function names. `pp.txt` holds strings.

That last point costs an hour if you do not know it: grepping objs.txt for
`setAdsRemovalType` returns nothing and looks like the function does not exist.
"""

from __future__ import annotations

import argparse
import shutil
import sys
import zipfile
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from common import (
    APKS_DIR,
    EXTRACTED_DIR,
    ToolError,
    aot_magic_offset,
    fail,
    head,
    human,
    info,
    ok,
    rel,
    zip_entries,
)

NATIVES = ("libapp.so", "libflutter.so")

HANDOFF = """# blutter handoff - {app}

Generated by `tools/blutter_stage.py`. Do not edit by hand.

## Inputs

| file | bytes |
|---|---|
{input_rows}

- AOT snapshot magic `0xdcdcf5f5` at file offset `{magic}`
- Dart / Flutter version: see `blutter-output/pp.txt`, or let blutter report it
- abi: arm64-v8a (blutter only supports arm64 here)

## Run blutter

    blutter <path-to-blutter.py> <dir-containing-libapp-and-libflutter> <output-dir>

Point it at THIS directory so it sees both `libapp.so` and `libflutter.so`.
Output goes to `blutter-output/` next to them.

## Where to look in the output

- `asm/<package>/<path>/<file>.dart` - **function bodies**, one header per function:
      _ setAdsRemovalType(/* No info */) async {{
        // ** addr: 0x8fa4b4, size: 0x68
- `pp.txt` - strings (app log messages, URLs). Line ~33092 carried the ads markers.
- `objs.txt` - object metadata. **Does not contain Dart function names** - grepping it for a
  function name returns nothing and looks like the function is absent. It is not.

## The one fact that makes byte-patching practical

**blutter's per-function `addr` is the `libapp.so` file offset.** No vaddr arithmetic.

Confirm it once per snapshot before trusting any offset: take a function's `addr`, read four
bytes at that offset, and check they decode to the AArch64 prologue

    fd 79 bf a9   stp x29, x30, [sp, #-0x10]!
    fd 03 0f aa   mov x29, sp

If that does not line up, the mapping is different and every offset below is wrong.

## Patching notes

- `rawResourcePatch` on `lib/arm64-v8a/libapp.so` is the morphe-native way to do this.
- Keep every edit **length preserving** (e.g. `b.ne #imm` -> `b #imm`, 4 bytes in, 4 out).
  There is no re-layout pass, so nothing can grow.
- **Assert the exact bytes at the offset before writing.** A stale offset on a new snapshot
  should throw with the observed bytes, not overwrite an unrelated instruction. There is no
  fingerprint to fall back on for native code.
- Prefer **retargeting an existing branch** over NOPing one. A conditional's fall-through often
  rejoins the path you meant to skip, so a NOP silently does nothing while looking applied.
- Reuse the app's own early-return where one exists, so no new return convention is invented and
  frame teardown stays correct.
"""


def stage(key: str, apk_dir: Path, analysis: Path) -> None:
    analysis.mkdir(parents=True, exist_ok=True)
    for name in NATIVES:
        dest = analysis / name
        if dest.exists() and dest.stat().st_size:
            ok(f"{name:<16} already staged ({human(dest.stat().st_size)} bytes)")
            continue
        found = False
        for apk in sorted(apk_dir.glob("*.apk")):
            try:
                names = zip_entries(apk)
            except zipfile.BadZipFile:
                continue
            member = next((n for n in names if n.endswith(f"/{name}")), None)
            if not member:
                continue
            with zipfile.ZipFile(apk) as z:
                dest.write_bytes(z.read(member))
            ok(f"{name:<16} {human(dest.stat().st_size)} bytes  (from {apk.name})")
            found = True
            break
        if not found:
            fail(f"{name} not found in {rel(apk_dir)} - is this a Flutter app?")


def write_handoff(analysis: Path, key: str) -> Path:
    rows = []
    magic = "n/a"
    for name in NATIVES:
        p = analysis / name
        if p.exists():
            rows.append(f"| `{name}` | {p.stat().st_size:,} |")
            if name == "libapp.so":
                off = aot_magic_offset(p.read_bytes())
                magic = hex(off) if off is not None else "NOT FOUND"
    note = analysis / "BLUTTER.md"
    note.write_text(
        HANDOFF.format(app=key, input_rows="\n".join(rows), magic=magic),
        encoding="utf-8",
    )
    ok(f"wrote {rel(note)}")
    return note


def check_output(analysis: Path) -> bool:
    out = analysis / "blutter-output"
    head("blutter output check")
    if not out.exists():
        info("no blutter-output/ yet - run blutter (see BLUTTER.md)")
        return True
    files = list(out.rglob("*.dart"))
    total = sum(1 for _ in out.rglob("*") if _.is_file())
    ok(f"{human(len(files))} .dart files, {human(total)} files total under {rel(out)}")
    asm = out / "asm"
    if asm.is_dir():
        n = sum(1 for _ in asm.rglob("*") if _.is_file())
        ok(f"asm/ has {human(n)} files - this is where function bodies are")
    else:
        warn("no asm/ directory; blutter may have failed or output a different layout")
    return True


def main(argv: list[str]) -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--package", required=True)
    ap.add_argument("--key")
    ap.add_argument(
        "--check",
        action="store_true",
        help="only inspect existing blutter output; do not stage or write a handoff",
    )
    args = ap.parse_args(argv[1:])

    from intake import resolve_key

    key = resolve_key(args.package, args.key)
    apk_dir = APKS_DIR / key
    analysis = EXTRACTED_DIR / f"{key}-analysis"

    if args.check:
        if not analysis.exists():
            raise ToolError(f"nothing staged at {rel(analysis)}")
        check_output(analysis)
        print()
        ok("check complete")
        return 0

    if not apk_dir.exists():
        raise ToolError(
            f"no apks at {apk_dir} - run: python tools/intake.py --package {args.package}"
        )

    head(f"staging natives for {key}")
    stage(key, apk_dir, analysis)
    write_handoff(analysis, key)
    check_output(analysis)
    print()
    ok("ready for blutter")
    return 0


if __name__ == "__main__":
    try:
        sys.exit(main(sys.argv))
    except ToolError as exc:
        fail(str(exc))
        sys.exit(2)
