package io.github.liongalahad.nuviotv.extension.playback.localdownloads;

import io.github.liongalahad.nuviotv.extension.settings.MorpheTranslations;

/** Owned translation catalogue. Columns: en, es, it, de, fr, pt, ja, ko, zh-Hans, zh-Hant. */
final class PatchTranslations {
    private PatchTranslations() {}
    static void register() { MorpheTranslations.register(ENTRIES); }
    static final String[][] ENTRIES = {
        {"Playback", "Reproducción", "Riproduzione", "Wiedergabe", "Lecture", "Reprodução", "再生", "재생", "播放", "播放"},
        {"Configure playback patch settings", "Configura los parches de reproducción", "Configura le patch di riproduzione", "Wiedergabe-Patches konfigurieren", "Configurer les patchs de lecture", "Configurar patches de reprodução", "再生パッチを設定", "재생 패치 설정", "配置播放补丁设置", "設定播放修補程式"},
        {"Local Downloads", "Descargas locales", "Download locali", "Lokale Downloads", "Téléchargements locaux", "Transferências locais", "ローカルダウンロード", "로컬 다운로드", "本地下载", "本機下載"},
        {"Download selected movie and episode sources to local storage", "Descarga las fuentes seleccionadas de películas y episodios al almacenamiento local", "Scarica in locale le sorgenti selezionate di film ed episodi", "Ausgewählte Film- und Episodenquellen lokal herunterladen", "Télécharger les sources sélectionnées des films et épisodes en local", "Transferir fontes selecionadas de filmes e episódios para o armazenamento local", "選択した映画やエピソードのソースをローカルにダウンロード", "선택한 영화 및 에피소드 소스를 로컬 저장소에 다운로드", "将选定的电影和单集资源下载到本地存储", "將選取的電影與單集來源下載至本機儲存空間"},
        {"Allow local downloads", "Permitir descargas locales", "Consenti i download locali", "Lokale Downloads zulassen", "Autoriser les téléchargements locaux", "Permitir transferências locais", "ローカルダウンロードを許可", "로컬 다운로드 허용", "允许本地下载", "允許本機下載"},
        {"Add Download to storage to title playback options", "Añade Descargar al almacenamiento a las opciones de reproducción", "Aggiunge Scarica in memoria alle opzioni di riproduzione", "Fügt In den Speicher herunterladen zu den Wiedergabeoptionen hinzu", "Ajoute Télécharger dans le stockage aux options de lecture", "Adicionar Transferir para armazenamento às opções de reprodução", "作品の再生オプションに「ストレージにダウンロード」を追加", "작품 재생 옵션에 저장소에 다운로드 추가", "在作品播放选项中添加下载到存储", "在作品播放選項中新增下載至儲存空間"},
        {"Autoplay local storage when available", "Reproducir la copia local cuando esté disponible", "Riproduci la copia locale quando disponibile", "Lokale Kopie abspielen, wenn verfügbar", "Lire la copie locale lorsqu’elle est disponible", "Reproduzir a cópia local quando disponível", "ローカルコピーがある場合は自動再生", "로컬 사본이 있으면 자동 재생", "有本地副本时自动播放", "有本機副本時自動播放"},
        {"Use an exact downloaded copy when Play is pressed", "Usa la copia descargada del mismo título y episodio al pulsar Reproducir", "Usa la copia scaricata dello stesso titolo ed episodio premendo Riproduci", "Verwendet beim Abspielen die heruntergeladene Kopie desselben Titels und derselben Episode", "Utilise la copie téléchargée du même titre et du même épisode en appuyant sur Lire", "Usar a cópia transferida do mesmo título e episódio ao premir Reproduzir", "再生を押すと、同じ作品・エピソードのダウンロード済みコピーを使用", "재생을 누르면 같은 작품과 에피소드의 다운로드 사본 사용", "按下播放时，使用同一作品和单集的下载副本", "按下播放時，使用同一作品與單集的下載副本"},
        {"Downloads", "Descargas", "Download", "Downloads", "Téléchargements", "Transferências", "ダウンロード", "다운로드", "下载", "下載"},
        {"%d item", "%d elemento", "%d elemento", "%d Eintrag", "%d élément", "%d item", "%d 件", "%d개 항목", "%d 项", "%d 個項目"},
        {"%d items", "%d elementos", "%d elementi", "%d Einträge", "%d éléments", "%d itens", "%d 件", "%d개 항목", "%d 项", "%d 個項目"},
        {"Maximum usable selected storage", "Uso máximo del almacenamiento seleccionado", "Utilizzo massimo della memoria selezionata", "Maximal nutzbarer Anteil des gewählten Speichers", "Utilisation maximale du stockage sélectionné", "Utilização máxima do armazenamento selecionado", "選択したストレージの使用上限", "선택한 저장소의 최대 사용량", "所选存储的最大使用量", "所選儲存空間的使用上限"},
        {"Selected storage usage unavailable", "Uso del almacenamiento seleccionado no disponible", "Utilizzo della memoria selezionata non disponibile", "Belegung des gewählten Speichers nicht verfügbar", "Utilisation du stockage sélectionné indisponible", "Utilização do armazenamento selecionado indisponível", "選択したストレージの使用量を取得できません", "선택한 저장소의 사용량을 확인할 수 없음", "无法获取所选存储的使用情况", "無法取得所選儲存空間的使用情況"},
        {"%.1f GB used / %.1f GB total (%.0f%% full)", "%.1f GB usados / %.1f GB en total (%.0f%% ocupado)", "%.1f GB usati / %.1f GB totali (%.0f%% occupato)", "%.1f GB belegt / %.1f GB gesamt (%.0f%% voll)", "%.1f Go utilisés / %.1f Go au total (%.0f%% occupé)", "%.1f GB usados / %.1f GB no total (%.0f%% ocupado)", "使用済み %.1f GB / 合計 %.1f GB（%.0f%% 使用）", "사용 %.1f GB / 전체 %.1f GB (%.0f%% 사용)", "已用 %.1f GB / 共 %.1f GB（已用 %.0f%%）", "已用 %.1f GB / 共 %.1f GB（已用 %.0f%%）"},
        {"Delete all downloads", "Eliminar todas las descargas", "Elimina tutti i download", "Alle Downloads löschen", "Supprimer tous les téléchargements", "Eliminar todas as transferências", "すべてのダウンロードを削除", "모든 다운로드 삭제", "删除所有下载", "刪除所有下載"},
        {"Press an item to play it. Hold for playback or deletion options.", "Pulsa un elemento para reproducirlo. Mantén pulsado para ver las opciones de reproducción o eliminación.", "Premi un elemento per riprodurlo. Tieni premuto per le opzioni di riproduzione o eliminazione.", "Eintrag zum Abspielen drücken. Gedrückt halten, um Wiedergabe- oder Löschoptionen zu öffnen.", "Appuyez sur un élément pour le lire. Maintenez pour les options de lecture ou de suppression.", "Prima um item para o reproduzir. Mantenha premido para opções de reprodução ou eliminação.", "項目を押すと再生します。長押しで再生・削除オプションを開きます。", "항목을 누르면 재생됩니다. 길게 누르면 재생 또는 삭제 옵션이 열립니다.", "按下项目进行播放。长按可查看播放或删除选项。", "按下項目即可播放。長按可查看播放或刪除選項。"},
        {"No local downloads", "No hay descargas locales", "Nessun download locale", "Keine lokalen Downloads", "Aucun téléchargement local", "Sem transferências locais", "ローカルダウンロードはありません", "로컬 다운로드 없음", "没有本地下载", "沒有本機下載"},
    };
}
