include:
  - .gitlab/ci/release.yml
  - .gitlab/ci/open-merge-request.yml
  - .gitlab/ci/renovate.yml

workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'
    - if: '$CI_PIPELINE_SOURCE == "web"'
    - if: '$CI_PIPELINE_SOURCE == "api"'
    - if: '$CI_PIPELINE_SOURCE == "trigger"'
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
    - when: never

stages:
  - automate
