package dev.local.mixplorer

import app.morphe.patcher.patch.loadPatchesFromJar
import com.google.gson.GsonBuilder
import java.io.File
import java.util.jar.JarFile

@Suppress("DEPRECATION")
fun main(arguments: Array<String>) {
    require(arguments.size == 2) { "Expected the bundle path and catalogue output path." }
    val bundle = File(arguments[0])
    val output = File(arguments[1])
    val version = JarFile(bundle).use { archive ->
        requireNotNull(archive.manifest?.mainAttributes?.getValue("Version")) {
            "Patch bundle has no Version manifest attribute."
        }
    }
    val patches = loadPatchesFromJar(setOf(bundle)).filter { it.name != null }.sortedBy { it.name }
    check(patches.isNotEmpty()) { "Patch bundle contains no named patches." }
    val catalogue = linkedMapOf(
        "NOTE" to "Generated by ./gradlew :patches:generatePatchesList. Do not edit manually.",
        "version" to version,
        "patches" to patches.map { patch ->
            linkedMapOf(
                "name" to patch.name,
                "description" to patch.description,
                "default" to patch.default,
                "category" to patch.category,
                "dependencies" to patch.dependencies.map { it.javaClass.simpleName },
                "compatiblePackages" to patch.compatibility?.map { compatibility ->
                    linkedMapOf(
                        "packageName" to compatibility.packageName,
                        "name" to compatibility.name,
                        "description" to compatibility.description,
                        "apkFileType" to compatibility.apkFileType?.name,
                        "appIconColor" to compatibility.appIconColor?.let { "#%06X".format(it) },
                        "signatures" to compatibility.signatures,
                        "targets" to compatibility.targets.map { target ->
                            linkedMapOf(
                                "version" to target.version,
                                "versionCodes" to target.versionCodes?.mapKeys { it.key.name },
                                "isExperimental" to target.isExperimental,
                                "minSdk" to target.minSdk,
                                "description" to target.description,
                            )
                        },
                    )
                },
                "options" to patch.options.values.map { option ->
                    linkedMapOf(
                        "key" to option.key,
                        "title" to option.title,
                        "description" to option.description,
                        "required" to option.required,
                        "type" to option.type.toString(),
                        "default" to option.default,
                        "values" to option.values,
                    )
                },
            )
        },
    )
    val gson = GsonBuilder().serializeNulls().disableHtmlEscaping().setPrettyPrinting().create()
    output.writeText(gson.toJson(catalogue) + "\n")
}