name: Verify

on:
  workflow_call:
  pull_request:
    branches:
      - dev
      - main
  workflow_dispatch:

permissions:
  contents: read
  packages: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup Java
        uses: actions/setup-java@v5.7.0
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Validate config
        run: jq empty .releaserc package.json patches-bundle.json patches-list.json

      - name: Build patches
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew clean :patches:buildAndroid --no-daemon