package com.gdjztech.ringconn.ui;

public class DashboardHtml {
    public static String getHtml() {
        StringBuilder sb = new StringBuilder(32000);
        sb.append("<!DOCTYPE html>\n");
        sb.append("<html lang=\"en\">\n");
        sb.append("<head>\n");
        sb.append("    <meta charset=\"UTF-8\">\n");
        sb.append("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, user-scalable=no, viewport-fit=cover\">\n");
        sb.append("    <title>Intervals.icu Sync</title>\n");
        sb.append("    <style>\n");
        sb.append("        :root {\n");
        sb.append("            --bg: #070A11;\n");
        sb.append("            --card-bg: rgba(22, 31, 48, 0.88);\n");
        sb.append("            --card-border: #1E293B;\n");
        sb.append("            --card-border-glow: rgba(56, 189, 248, 0.25);\n");
        sb.append("            --text-primary: #F8FAFC;\n");
        sb.append("            --text-secondary: #94A3B8;\n");
        sb.append("            --text-muted: #64748B;\n");
        sb.append("            --accent: #38BDF8;\n");
        sb.append("            --accent-gradient: linear-gradient(135deg, #0284C7, #38BDF8);\n");
        sb.append("            --success: #10B981;\n");
        sb.append("            --warning: #F59E0B;\n");
        sb.append("            --danger: #EF4444;\n");
        sb.append("            --deep: #6366F1;\n");
        sb.append("            --rem: #06B6D4;\n");
        sb.append("            --light: #3B82F6;\n");
        sb.append("            --awake: #64748B;\n");
        sb.append("        }\n");
        sb.append("        * { box-sizing: border-box; margin: 0; padding: 0; font-family: -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, Helvetica, Arial, sans-serif; -webkit-tap-highlight-color: transparent; }\n");
        sb.append("        body { background-color: var(--bg); color: var(--text-primary); padding: 16px; padding-top: max(16px, env(safe-area-inset-top)); padding-bottom: max(38px, env(safe-area-inset-bottom)); min-height: 100vh; }\n");
        sb.append("        .header { display: flex; justify-content: space-between; align-items: center; margin-bottom: 18px; padding-top: 6px; }\n");
        sb.append("        .brand { display: flex; align-items: center; gap: 12px; }\n");
        sb.append("        .brand-icon { width: 38px; height: 38px; border-radius: 12px; background: var(--accent-gradient); display: flex; align-items: center; justify-content: center; font-size: 20px; color: #fff; box-shadow: 0 4px 16px rgba(56,189,248,0.35); }\n");
        sb.append("        .brand h1 { font-size: 19px; font-weight: 800; letter-spacing: -0.4px; background: linear-gradient(180deg, #FFFFFF, #CBD5E1); -webkit-background-clip: text; -webkit-text-fill-color: transparent; }\n");
        sb.append("        .brand p { font-size: 11px; color: var(--text-secondary); margin-top: 1px; }\n");
        sb.append("        .close-btn { background: #111827; border: 1px solid var(--card-border); color: var(--text-secondary); width: 36px; height: 36px; border-radius: 50%; display: flex; align-items: center; justify-content: center; font-size: 18px; cursor: pointer; transition: all 0.2s; }\n");
        sb.append("        .close-btn:active { background: #1E293B; color: #fff; transform: scale(0.95); }\n");
        sb.append("        .nav-tabs { display: flex; background: #0F172A; border-radius: 14px; padding: 4px; margin-bottom: 18px; border: 1px solid var(--card-border); }\n");
        sb.append("        .nav-btn { flex: 1; padding: 10px 0; background: transparent; border: none; color: var(--text-secondary); font-size: 13px; font-weight: 600; border-radius: 10px; cursor: pointer; transition: all 0.2s; white-space: nowrap; text-align: center; }\n");
        sb.append("        .nav-btn.active { background: var(--accent); color: #070A11; font-weight: 700; box-shadow: 0 2px 10px rgba(56,189,248,0.3); }\n");
        sb.append("        .tab-content { display: none; }\n");
        sb.append("        .tab-content.active { display: block; }\n");
        sb.append("        .card { background: var(--card-bg); border: 1px solid var(--card-border); border-radius: 18px; padding: 16px; margin-bottom: 14px; box-shadow: 0 8px 24px rgba(0,0,0,0.35); backdrop-filter: blur(8px); }\n");
        sb.append("        .card-header { display: flex; justify-content: space-between; align-items: center; margin-bottom: 12px; }\n");
        sb.append("        .card-title { font-size: 12px; font-weight: 700; color: var(--text-secondary); text-transform: uppercase; letter-spacing: 0.8px; }\n");
        sb.append("        .badge { padding: 4px 10px; border-radius: 8px; font-size: 12px; font-weight: 800; display: inline-flex; align-items: center; }\n");
        sb.append("        .badge-score { background: rgba(56,189,248,0.15); color: var(--accent); border: 1px solid rgba(56,189,248,0.3); }\n");
        sb.append("        .badge-type { background: rgba(255,255,255,0.06); color: var(--text-secondary); font-size: 10px; font-weight: 600; border: 1px solid var(--card-border); padding: 2px 6px; border-radius: 6px; text-transform: uppercase; }\n");
        sb.append("        .metrics-grid { display: grid; grid-template-columns: repeat(2, 1fr); gap: 10px; margin-bottom: 14px; }\n");
        sb.append("        .metric-box { background: rgba(11,15,25,0.7); border: 1px solid var(--card-border); border-radius: 14px; padding: 12px; }\n");
        sb.append("        .metric-label { font-size: 10px; font-weight: 600; color: var(--text-muted); text-transform: uppercase; letter-spacing: 0.5px; margin-bottom: 4px; }\n");
        sb.append("        .metric-val { font-size: 20px; font-weight: 800; color: var(--text-primary); letter-spacing: -0.5px; }\n");
        sb.append("        .metric-unit { font-size: 12px; font-weight: 400; color: var(--text-secondary); margin-left: 3px; }\n");
        sb.append("        .stage-bar { display: flex; height: 14px; border-radius: 7px; overflow: hidden; margin: 8px 0 12px 0; background: #0B0F19; border: 1px solid var(--card-border); }\n");
        sb.append("        .stage-deep { background: var(--deep); }\n");
        sb.append("        .stage-rem { background: var(--rem); }\n");
        sb.append("        .stage-light { background: var(--light); }\n");
        sb.append("        .stage-awake { background: var(--awake); }\n");
        sb.append("        .stage-legend { display: grid; grid-template-columns: repeat(2, 1fr); gap: 8px; font-size: 12px; color: var(--text-secondary); margin-top: 8px; }\n");
        sb.append("        .stage-item { display: flex; align-items: center; justify-content: space-between; background: rgba(11,15,25,0.5); padding: 6px 10px; border-radius: 8px; border: 1px solid var(--card-border); }\n");
        sb.append("        .stage-dot { display: inline-block; width: 8px; height: 8px; border-radius: 50%; margin-right: 6px; }\n");
        sb.append("        .stage-time { font-weight: 700; color: var(--text-primary); }\n");
        sb.append("        .stage-pct { font-size: 10px; color: var(--text-muted); margin-left: 4px; }\n");
        sb.append("        .btn-sync { width: 100%; padding: 14px; background: var(--accent-gradient); border: none; border-radius: 14px; color: #fff; font-size: 14px; font-weight: 700; cursor: pointer; display: flex; align-items: center; justify-content: center; gap: 10px; box-shadow: 0 4px 20px rgba(56,189,248,0.35); transition: transform 0.15s, opacity 0.15s; margin-top: 10px; }\n");
        sb.append("        .btn-sync:active { transform: scale(0.98); opacity: 0.9; }\n");
        sb.append("        .btn-sync:disabled { opacity: 0.6; cursor: not-allowed; }\n");
        sb.append("        .form-group { margin-bottom: 16px; }\n");
        sb.append("        .form-label { display: block; font-size: 11px; font-weight: 700; color: var(--text-secondary); margin-bottom: 6px; text-transform: uppercase; letter-spacing: 0.5px; }\n");
        sb.append("        .form-input { width: 100%; padding: 12px; background: #0B0F19; border: 1px solid var(--card-border); border-radius: 12px; color: var(--text-primary); font-size: 14px; outline: none; transition: border-color 0.2s; }\n");
        sb.append("        .form-input:focus { border-color: var(--accent); }\n");
        sb.append("        .segmented-control { display: flex; background: #0B0F19; border: 1px solid var(--card-border); border-radius: 12px; padding: 3px; gap: 4px; }\n");
        sb.append("        .segmented-option { flex: 1; text-align: center; padding: 9px 6px; font-size: 12px; font-weight: 600; color: var(--text-secondary); border-radius: 9px; cursor: pointer; transition: all 0.2s; }\n");
        sb.append("        .segmented-option.selected { background: #1E293B; color: var(--accent); font-weight: 700; border: 1px solid rgba(56,189,248,0.3); }\n");
        sb.append("        .form-hint { font-size: 11px; color: var(--text-muted); margin-top: 6px; line-height: 1.4; }\n");
        sb.append("        .switch-row { display: flex; justify-content: space-between; align-items: center; padding: 12px 0; border-top: 1px solid var(--card-border); }\n");
        sb.append("        .toast { position: fixed; bottom: 24px; left: 16px; right: 16px; padding: 14px 20px; border-radius: 14px; font-size: 13px; font-weight: 600; text-align: center; z-index: 1000; display: none; box-shadow: 0 8px 24px rgba(0,0,0,0.6); }\n");
        sb.append("        .toast-success { background: #064E3B; color: #D1FAE5; border: 1px solid var(--success); }\n");
        sb.append("        .toast-error { background: #7F1D1D; color: #FEE2E2; border: 1px solid var(--danger); }\n");
        sb.append("        .history-item { background: rgba(11,15,25,0.7); border: 1px solid var(--card-border); border-radius: 14px; padding: 12px; margin-bottom: 10px; display: flex; justify-content: space-between; align-items: center; }\n");
        sb.append("        .history-date { font-weight: 700; font-size: 14px; color: var(--text-primary); margin-bottom: 3px; }\n");
        sb.append("        .history-meta { font-size: 12px; color: var(--text-secondary); }\n");
        sb.append("        .history-right { text-align: right; display: flex; flex-direction: column; align-items: flex-end; gap: 4px; }\n");
        sb.append("        .history-score { font-size: 20px; font-weight: 800; color: var(--accent); }\n");
        sb.append("        .history-sync-btn { background: #0284C7; border: none; color: #fff; font-size: 11px; font-weight: 700; padding: 6px 12px; border-radius: 7px; cursor: pointer; transition: background 0.15s; }\n");
        sb.append("        .history-sync-btn:active { background: #0369A1; }\n");
        sb.append("        .log-item { padding: 10px 12px; border-bottom: 1px solid var(--card-border); font-size: 12px; font-family: ui-monospace, SFMono-Regular, monospace; }\n");
        sb.append("        .log-time { color: var(--text-muted); font-size: 11px; margin-bottom: 2px; }\n");
        sb.append("        .log-msg { color: var(--text-primary); line-height: 1.3; }\n");
        sb.append("    </style>\n");
        sb.append("</head>\n");
        sb.append("<body>\n");
        sb.append("    <div class=\"header\">\n");
        sb.append("        <div class=\"brand\">\n");
        sb.append("            <div class=\"brand-icon\">&#9889;</div>\n");
        sb.append("            <div>\n");
        sb.append("                <h1>Intervals.icu Sync</h1>\n");
        sb.append("                <p id=\"status-line\">RingConn &rarr; Intervals.icu Cloud</p>\n");
        sb.append("            </div>\n");
        sb.append("        </div>\n");
        sb.append("        <button class=\"close-btn\" onclick=\"closeApp()\" title=\"Close\">&#10005;</button>\n");
        sb.append("    </div>\n");
        sb.append("\n");
        sb.append("    <div class=\"nav-tabs\">\n");
        sb.append("        <button class=\"nav-btn active\" onclick=\"setTab(0)\">Sync</button>\n");
        sb.append("        <button class=\"nav-btn\" onclick=\"setTab(1)\">History</button>\n");
        sb.append("        <button class=\"nav-btn\" onclick=\"setTab(2)\">Settings</button>\n");
        sb.append("        <button class=\"nav-btn\" onclick=\"setTab(3)\">Logs</button>\n");
        sb.append("    </div>\n");
        sb.append("\n");
        sb.append("    <!-- SYNC TAB -->\n");
        sb.append("    <div id=\"tab-0\" class=\"tab-content active\">\n");
        sb.append("        <div class=\"card\">\n");
        sb.append("            <div class=\"card-header\">\n");
        sb.append("                <span class=\"card-title\" id=\"dashboard-date\">Last Night</span>\n");
        sb.append("                <div class=\"score-pill-group\">\n");
        sb.append("                    <span class=\"badge badge-score\" id=\"sleep-score-badge\">Score: --</span>\n");
        sb.append("                    <span class=\"badge-type\" id=\"score-mode-badge\">Athletic</span>\n");
        sb.append("                </div>\n");
        sb.append("            </div>\n");
        sb.append("            <div class=\"metrics-grid\">\n");
        sb.append("                <div class=\"metric-box\">\n");
        sb.append("                    <div class=\"metric-label\">Sleep Duration</div>\n");
        sb.append("                    <div class=\"metric-val\" id=\"val-duration\">--<span class=\"metric-unit\"></span></div>\n");
        sb.append("                </div>\n");
        sb.append("                <div class=\"metric-box\">\n");
        sb.append("                    <div class=\"metric-label\">Resting HR</div>\n");
        sb.append("                    <div class=\"metric-val\" id=\"val-rhr\">--<span class=\"metric-unit\">bpm</span></div>\n");
        sb.append("                </div>\n");
        sb.append("                <div class=\"metric-box\">\n");
        sb.append("                    <div class=\"metric-label\">HRV (rMSSD)</div>\n");
        sb.append("                    <div class=\"metric-val\" id=\"val-hrv\">--<span class=\"metric-unit\">ms</span></div>\n");
        sb.append("                </div>\n");
        sb.append("                <div class=\"metric-box\">\n");
        sb.append("                    <div class=\"metric-label\">Skin Temp</div>\n");
        sb.append("                    <div class=\"metric-val\" id=\"val-temp\">--<span class=\"metric-unit\">&deg;C</span></div>\n");
        sb.append("                </div>\n");
        sb.append("            </div>\n");
        sb.append("            <div class=\"stage-card\">\n");
        sb.append("                <div class=\"stage-title-row\" style=\"display:flex; justify-content:space-between; font-size:12px; font-weight:600; color:var(--text-secondary); margin-bottom:6px;\">\n");
        sb.append("                    <span>Sleep Stages</span>\n");
        sb.append("                    <span id=\"lbl-efficiency\">-- Efficiency</span>\n");
        sb.append("                </div>\n");
        sb.append("                <div class=\"stage-bar\">\n");
        sb.append("                    <div id=\"bar-deep\" class=\"stage-deep\" style=\"width: 25%\"></div>\n");
        sb.append("                    <div id=\"bar-rem\" class=\"stage-rem\" style=\"width: 20%\"></div>\n");
        sb.append("                    <div id=\"bar-light\" class=\"stage-light\" style=\"width: 45%\"></div>\n");
        sb.append("                    <div id=\"bar-awake\" class=\"stage-awake\" style=\"width: 10%\"></div>\n");
        sb.append("                </div>\n");
        sb.append("                <div class=\"stage-legend\">\n");
        sb.append("                    <div class=\"stage-item\">\n");
        sb.append("                        <span><span class=\"stage-dot\" style=\"background: var(--deep)\"></span>Deep Sleep</span>\n");
        sb.append("                        <span><span class=\"stage-time\" id=\"lbl-deep\">--</span><span class=\"stage-pct\" id=\"pct-deep\"></span></span>\n");
        sb.append("                    </div>\n");
        sb.append("                    <div class=\"stage-item\">\n");
        sb.append("                        <span><span class=\"stage-dot\" style=\"background: var(--rem)\"></span>REM Sleep</span>\n");
        sb.append("                        <span><span class=\"stage-time\" id=\"lbl-rem\">--</span><span class=\"stage-pct\" id=\"pct-rem\"></span></span>\n");
        sb.append("                    </div>\n");
        sb.append("                    <div class=\"stage-item\">\n");
        sb.append("                        <span><span class=\"stage-dot\" style=\"background: var(--light)\"></span>Light Sleep</span>\n");
        sb.append("                        <span><span class=\"stage-time\" id=\"lbl-light\">--</span><span class=\"stage-pct\" id=\"pct-light\"></span></span>\n");
        sb.append("                    </div>\n");
        sb.append("                    <div class=\"stage-item\">\n");
        sb.append("                        <span><span class=\"stage-dot\" style=\"background: var(--awake)\"></span>Awake</span>\n");
        sb.append("                        <span><span class=\"stage-time\" id=\"lbl-awake\">--</span><span class=\"stage-pct\" id=\"pct-awake\"></span></span>\n");
        sb.append("                    </div>\n");
        sb.append("                </div>\n");
        sb.append("            </div>\n");
        sb.append("        </div>\n");
        sb.append("        <button class=\"btn-sync\" id=\"main-sync-btn\" onclick=\"syncCurrentDay()\">\n");
        sb.append("            <span>&#8644;</span> &#9889; Transfer to Intervals.icu Now\n");
        sb.append("        </button>\n");
        sb.append("    </div>\n");
        sb.append("\n");
        sb.append("    <!-- HISTORY TAB -->\n");
        sb.append("    <div id=\"tab-1\" class=\"tab-content\">\n");
        sb.append("        <div class=\"card\">\n");
        sb.append("            <div class=\"card-header\">\n");
        sb.append("                <span class=\"card-title\">History (Last 30 Days)</span>\n");
        sb.append("            </div>\n");
        sb.append("            <div id=\"history-list\">Loading records from ring_conn.db...</div>\n");
        sb.append("        </div>\n");
        sb.append("    </div>\n");
        sb.append("\n");
        sb.append("    <!-- SETTINGS TAB -->\n");
        sb.append("    <div id=\"tab-2\" class=\"tab-content\">\n");
        sb.append("        <div class=\"card\">\n");
        sb.append("            <div class=\"card-header\">\n");
        sb.append("                <span class=\"card-title\">Intervals.icu Configuration</span>\n");
        sb.append("            </div>\n");
        sb.append("            <div class=\"form-group\">\n");
        sb.append("                <label class=\"form-label\">Athlete ID</label>\n");
        sb.append("                <input class=\"form-input\" id=\"cfg-athlete-id\" placeholder=\"e.g. i12345\">\n");
        sb.append("                <div class=\"form-hint\">Your Intervals.icu Athlete ID (e.g. i12345 or 0 for main account)</div>\n");
        sb.append("            </div>\n");
        sb.append("            <div class=\"form-group\">\n");
        sb.append("                <label class=\"form-label\">API Key</label>\n");
        sb.append("                <input class=\"form-input\" id=\"cfg-api-key\" type=\"password\" placeholder=\"Intervals API Key\">\n");
        sb.append("                <div class=\"form-hint\">Generated under Intervals.icu &gt; Settings &gt; Developer API.</div>\n");
        sb.append("            </div>\n");
        sb.append("            <div class=\"form-group\">\n");
        sb.append("                <label class=\"form-label\">Sleep Score Engine</label>\n");
        sb.append("                <div class=\"segmented-control\">\n");
        sb.append("                    <div class=\"segmented-option selected\" id=\"opt-score-athletic\" onclick=\"selectScoreSource('athletic')\">Athletic (Recommended)</div>\n");
        sb.append("                    <div class=\"segmented-option\" id=\"opt-score-ringconn\" onclick=\"selectScoreSource('ringconn')\">RingConn Official</div>\n");
        sb.append("                </div>\n");
        sb.append("                <div class=\"form-hint\" id=\"score-source-hint\">Athletic formula: Non-linear sleep duration evaluation, high deep & REM sleep weighting, calibrated for endurance athletes.</div>\n");
        sb.append("            </div>\n");
        sb.append("            <div class=\"switch-row\">\n");
        sb.append("                <span class=\"form-label\" style=\"margin-bottom:0\">Automatic Background Sync</span>\n");
        sb.append("                <input type=\"checkbox\" id=\"cfg-auto-sync\" checked style=\"transform: scale(1.3);\">\n");
        sb.append("            </div>\n");
        sb.append("            <button class=\"btn-sync\" onclick=\"saveConfig()\">Save Settings</button>\n");
        sb.append("            <div class=\"form-group\" style=\"margin-top: 20px; padding-top: 14px; border-top: 1px solid var(--card-border);\">\n");
        sb.append("                <label class=\"form-label\">Local Data Export (Backup / Google Drive)</label>\n");
        sb.append("                <button class=\"btn-sync\" type=\"button\" onclick=\"triggerLocalBackup()\" style=\"background: #1E293B; border: 1px solid rgba(56,189,248,0.5); color: #38BDF8; box-shadow: none;\">Save to Download/IntervalsDirect</button>\n");
        sb.append("                <div class=\"form-hint\" id=\"backup-status-hint\">Exports RingConn_Wellness_Master.json and .csv to device storage.</div>\n");
        sb.append("            </div>\n");
        sb.append("        </div>\n");
        sb.append("    </div>\n");
        sb.append("\n");
        sb.append("    <!-- LOGS TAB -->\n");
        sb.append("    <div id=\"tab-3\" class=\"tab-content\">\n");
        sb.append("        <div class=\"card\">\n");
        sb.append("            <div class=\"card-header\">\n");
        sb.append("                <span class=\"card-title\">Sync Logs</span>\n");
        sb.append("            </div>\n");
        sb.append("            <div id=\"logs-list\" style=\"max-height: 420px; overflow-y: auto;\">No logs recorded yet.</div>\n");
        sb.append("        </div>\n");
        sb.append("    </div>\n");
        sb.append("\n");
        sb.append("    <div id=\"toast\" class=\"toast\"></div>\n");
        sb.append("\n");
        sb.append("    <script>\n");
        sb.append("        let currentHistory = [];\n");
        sb.append("        let latestDate = \"\";\n");
        sb.append("        let currentScoreSource = \"athletic\";\n");
        sb.append("\n");
        sb.append("        function showToast(msg, isError) {\n");
        sb.append("            const t = document.getElementById(\"toast\");\n");
        sb.append("            if (!t) return;\n");
        sb.append("            t.innerText = msg;\n");
        sb.append("            t.className = \"toast \" + (isError ? \"toast-error\" : \"toast-success\");\n");
        sb.append("            t.style.display = \"block\";\n");
        sb.append("            setTimeout(function() { t.style.display = \"none\"; }, 3500);\n");
        sb.append("        }\n");
        sb.append("\n");
        sb.append("        function triggerLocalBackup() {\n");
        sb.append("            if (!window.IntervalsBridge) {\n");
        sb.append("                showToast(\"Bridge not available\", true);\n");
        sb.append("                return;\n");
        sb.append("            }\n");
        sb.append("            const hint = document.getElementById(\"backup-status-hint\");\n");
        sb.append("            if (hint) hint.innerText = \"Exporting records...\";\n");
        sb.append("            try {\n");
        sb.append("                const res = window.IntervalsBridge.exportLocalBackup();\n");
        sb.append("                if (hint) hint.innerText = res;\n");
        sb.append("                showToast(res, false);\n");
        sb.append("            } catch (e) {\n");
        sb.append("                if (hint) hint.innerText = \"Error: \" + e.message;\n");
        sb.append("                showToast(\"Error: \" + e.message, true);\n");
        sb.append("            }\n");
        sb.append("        }\n");
        sb.append("\n");
        sb.append("        function setTab(idx) {\n");
        sb.append("            document.querySelectorAll(\".nav-btn\").forEach(function(b, i) { b.classList.toggle(\"active\", i === idx); });\n");
        sb.append("            document.querySelectorAll(\".tab-content\").forEach(function(c, i) { c.classList.toggle(\"active\", i === idx); });\n");
        sb.append("            if (idx === 1) renderHistory();\n");
        sb.append("            if (idx === 3) loadLogs();\n");
        sb.append("        }\n");
        sb.append("\n");
        sb.append("        function selectScoreSource(src) {\n");
        sb.append("            currentScoreSource = src;\n");
        sb.append("            const btnAthletic = document.getElementById(\"opt-score-athletic\");\n");
        sb.append("            const btnRingConn = document.getElementById(\"opt-score-ringconn\");\n");
        sb.append("            if (btnAthletic) btnAthletic.classList.toggle(\"selected\", src === \"athletic\");\n");
        sb.append("            if (btnRingConn) btnRingConn.classList.toggle(\"selected\", src === \"ringconn\");\n");
        sb.append("            const hint = document.getElementById(\"score-source-hint\");\n");
        sb.append("            if (hint) {\n");
        sb.append("                if (src === \"athletic\") {\n");
        sb.append("                    hint.innerText = \"Athletic formula: Non-linear sleep duration evaluation, high deep & REM sleep weighting, calibrated for endurance athletes.\";\n");
        sb.append("                } else {\n");
        sb.append("                    hint.innerText = \"RingConn Official: Uses the unmodified sleep score directly from RingConn's algorithm.\";\n");
        sb.append("                }\n");
        sb.append("            }\n");
        sb.append("            if (currentHistory && currentHistory.length > 0) {\n");
        sb.append("                displayDashboard(currentHistory[0]);\n");
        sb.append("            }\n");
        sb.append("        }\n");
        sb.append("\n");
        sb.append("        function closeApp() {\n");
        sb.append("            if (window.IntervalsBridge) {\n");
        sb.append("                window.IntervalsBridge.close();\n");
        sb.append("            }\n");
        sb.append("        }\n");
        sb.append("\n");
        sb.append("        function loadInitialData() {\n");
        sb.append("            if (!window.IntervalsBridge) {\n");
        sb.append("                console.log(\"IntervalsBridge not found\");\n");
        sb.append("                return;\n");
        sb.append("            }\n");
        sb.append("            try {\n");
        sb.append("                const rawSettings = window.IntervalsBridge.getSettings();\n");
        sb.append("                const settings = rawSettings ? JSON.parse(rawSettings) : {};\n");
        sb.append("                const elAth = document.getElementById(\"cfg-athlete-id\");\n");
        sb.append("                const elKey = document.getElementById(\"cfg-api-key\");\n");
        sb.append("                const elAuto = document.getElementById(\"cfg-auto-sync\");\n");
        sb.append("\n");
        sb.append("                if (elAth) elAth.value = settings.athleteId || \"\";\n");
        sb.append("                if (elKey) elKey.value = settings.apiKey || \"\";\n");
        sb.append("                if (elAuto) elAuto.checked = settings.autoSync !== false;\n");
        sb.append("\n");
        sb.append("                selectScoreSource(settings.scoreSource || \"athletic\");\n");
        sb.append("                if (settings.lastSyncStatus) {\n");
        sb.append("                    const statusLine = document.getElementById(\"status-line\");\n");
        sb.append("                    if (statusLine) statusLine.innerText = settings.lastSyncStatus;\n");
        sb.append("                }\n");
        sb.append("\n");
        sb.append("                const rawHistory = window.IntervalsBridge.getSleepHistory(30);\n");
        sb.append("                currentHistory = rawHistory ? JSON.parse(rawHistory) : [];\n");
        sb.append("                if (currentHistory && currentHistory.length > 0) {\n");
        sb.append("                    displayDashboard(currentHistory[0]);\n");
        sb.append("                }\n");
        sb.append("            } catch (e) {\n");
        sb.append("                console.error(\"loadInitialData error:\", e);\n");
        sb.append("            }\n");
        sb.append("        }\n");
        sb.append("\n");
        sb.append("        function displayDashboard(d) {\n");
        sb.append("            if (!d) return;\n");
        sb.append("            latestDate = d.date || \"\";\n");
        sb.append("            const elDate = document.getElementById(\"dashboard-date\");\n");
        sb.append("            if (elDate) elDate.innerText = d.date || \"Last Night\";\n");
        sb.append("\n");
        sb.append("            const displayScore = currentScoreSource === \"ringconn\" ? (d.ringconnScore || d.score) : (d.athleticScore || d.score);\n");
        sb.append("            const elBadge = document.getElementById(\"sleep-score-badge\");\n");
        sb.append("            if (elBadge) elBadge.innerText = \"Score: \" + (displayScore || \"--\");\n");
        sb.append("\n");
        sb.append("            const elMode = document.getElementById(\"score-mode-badge\");\n");
        sb.append("            if (elMode) elMode.innerText = currentScoreSource === \"ringconn\" ? \"RingConn\" : \"Athletic\";\n");
        sb.append("\n");
        sb.append("            const totalMins = d.sleepDurationMinutes || 0;\n");
        sb.append("            const h = Math.floor(totalMins / 60);\n");
        sb.append("            const m = totalMins % 60;\n");
        sb.append("            const durationEl = document.getElementById(\"val-duration\");\n");
        sb.append("            if (durationEl) {\n");
        sb.append("                durationEl.innerHTML = (h > 0 ? h + \"h \" : \"\") + m + \"<span class='metric-unit'>m</span>\";\n");
        sb.append("            }\n");
        sb.append("\n");
        sb.append("            const rhrEl = document.getElementById(\"val-rhr\");\n");
        sb.append("            if (rhrEl) {\n");
        sb.append("                rhrEl.innerHTML = (d.restingHr || \"--\") + \"<span class='metric-unit'>bpm</span>\";\n");
        sb.append("            }\n");
        sb.append("\n");
        sb.append("            const hrvEl = document.getElementById(\"val-hrv\");\n");
        sb.append("            if (hrvEl) {\n");
        sb.append("                hrvEl.innerHTML = (d.hrv || \"--\") + \"<span class='metric-unit'>ms</span>\";\n");
        sb.append("            }\n");
        sb.append("\n");
        sb.append("            const temp = d.tempOffset !== undefined ? ((d.tempOffset > 0 ? \"+\" : \"\") + d.tempOffset) : \"--\";\n");
        sb.append("            const tempEl = document.getElementById(\"val-temp\");\n");
        sb.append("            if (tempEl) {\n");
        sb.append("                tempEl.innerHTML = temp + \"<span class='metric-unit'>&deg;C</span>\";\n");
        sb.append("            }\n");
        sb.append("\n");
        sb.append("            const deep = d.deepMinutes || 0;\n");
        sb.append("            const rem = d.remMinutes || 0;\n");
        sb.append("            const light = d.lightMinutes || 0;\n");
        sb.append("            const awake = d.awakeMinutes || 0;\n");
        sb.append("            const sum = (deep + rem + light + awake) || 1;\n");
        sb.append("\n");
        sb.append("            const deepPct = Math.round(deep / sum * 100);\n");
        sb.append("            const remPct = Math.round(rem / sum * 100);\n");
        sb.append("            const lightPct = Math.round(light / sum * 100);\n");
        sb.append("            const awakePct = Math.round(awake / sum * 100);\n");
        sb.append("\n");
        sb.append("            const bDeep = document.getElementById(\"bar-deep\");\n");
        sb.append("            const bRem = document.getElementById(\"bar-rem\");\n");
        sb.append("            const bLight = document.getElementById(\"bar-light\");\n");
        sb.append("            const bAwake = document.getElementById(\"bar-awake\");\n");
        sb.append("            if (bDeep) bDeep.style.width = deepPct + \"%\";\n");
        sb.append("            if (bRem) bRem.style.width = remPct + \"%\";\n");
        sb.append("            if (bLight) bLight.style.width = lightPct + \"%\";\n");
        sb.append("            if (bAwake) bAwake.style.width = awakePct + \"%\";\n");
        sb.append("\n");
        sb.append("            const lDeep = document.getElementById(\"lbl-deep\");\n");
        sb.append("            const pDeep = document.getElementById(\"pct-deep\");\n");
        sb.append("            if (lDeep) lDeep.innerText = deep + \"m\";\n");
        sb.append("            if (pDeep) pDeep.innerText = \" (\" + deepPct + \"%)\";\n");
        sb.append("\n");
        sb.append("            const lRem = document.getElementById(\"lbl-rem\");\n");
        sb.append("            const pRem = document.getElementById(\"pct-rem\");\n");
        sb.append("            if (lRem) lRem.innerText = rem + \"m\";\n");
        sb.append("            if (pRem) pRem.innerText = \" (\" + remPct + \"%)\";\n");
        sb.append("\n");
        sb.append("            const lLight = document.getElementById(\"lbl-light\");\n");
        sb.append("            const pLight = document.getElementById(\"pct-light\");\n");
        sb.append("            if (lLight) lLight.innerText = light + \"m\";\n");
        sb.append("            if (pLight) pLight.innerText = \" (\" + lightPct + \"%)\";\n");
        sb.append("\n");
        sb.append("            const lAwake = document.getElementById(\"lbl-awake\");\n");
        sb.append("            const pAwake = document.getElementById(\"pct-awake\");\n");
        sb.append("            if (lAwake) lAwake.innerText = awake + \"m\";\n");
        sb.append("            if (pAwake) pAwake.innerText = \" (\" + awakePct + \"%)\";\n");
        sb.append("\n");
        sb.append("            const eff = sum > 0 ? Math.round(totalMins / sum * 100) : 0;\n");
        sb.append("            const lEff = document.getElementById(\"lbl-efficiency\");\n");
        sb.append("            if (lEff) lEff.innerText = eff + \"% Efficiency\";\n");
        sb.append("        }\n");
        sb.append("\n");
        sb.append("        function renderHistory() {\n");
        sb.append("            const container = document.getElementById(\"history-list\");\n");
        sb.append("            if (!container) return;\n");
        sb.append("            if (!currentHistory || currentHistory.length === 0) {\n");
        sb.append("                container.innerHTML = \"<p style='color:var(--text-muted);text-align:center;padding:20px;'>No sleep records found in ring_conn.db</p>\";\n");
        sb.append("                return;\n");
        sb.append("            }\n");
        sb.append("            let html = \"\";\n");
        sb.append("            currentHistory.forEach(function(item) {\n");
        sb.append("                const totalMins = item.sleepDurationMinutes || 0;\n");
        sb.append("                const h = Math.floor(totalMins / 60);\n");
        sb.append("                const m = totalMins % 60;\n");
        sb.append("                const itemScore = currentScoreSource === \"ringconn\" ? (item.ringconnScore || item.score) : (item.athleticScore || item.score);\n");
        sb.append("                html += \"<div class='history-item'>\" +\n");
        sb.append("                    \"<div>\" +\n");
        sb.append("                        \"<div class='history-date'>\" + item.date + \"</div>\" +\n");
        sb.append("                        \"<div class='history-meta'>\" + h + \"h \" + m + \"m &bull; Resting HR: \" + (item.restingHr || \"--\") + \" bpm &bull; HRV: \" + (item.hrv || \"--\") + \" ms</div>\" +\n");
        sb.append("                    \"</div>\" +\n");
        sb.append("                    \"<div class='history-right'>\" +\n");
        sb.append("                        \"<div class='history-score'>\" + (itemScore || \"--\") + \"</div>\" +\n");
        sb.append("                        \"<button class='history-sync-btn' data-date='\" + item.date + \"'>Sync</button>\" +\n");
        sb.append("                    \"</div>\" +\n");
        sb.append("                \"</div>\";\n");
        sb.append("            });\n");
        sb.append("            container.innerHTML = html;\n");
        sb.append("            container.onclick = function(e) {\n");
        sb.append("                const btn = e.target.closest(\".history-sync-btn\");\n");
        sb.append("                if (btn && btn.getAttribute(\"data-date\")) {\n");
        sb.append("                    syncSingle(btn.getAttribute(\"data-date\"));\n");
        sb.append("                }\n");
        sb.append("            };\n");
        sb.append("        }\n");
        sb.append("\n");
        sb.append("        function loadLogs() {\n");
        sb.append("            if (!window.IntervalsBridge) return;\n");
        sb.append("            const container = document.getElementById(\"logs-list\");\n");
        sb.append("            if (!container) return;\n");
        sb.append("            try {\n");
        sb.append("                const logs = JSON.parse(window.IntervalsBridge.getLogs());\n");
        sb.append("                if (!logs || logs.length === 0) {\n");
        sb.append("                    container.innerHTML = \"<p style='color:var(--text-muted);padding:14px;'>No logs recorded yet.</p>\";\n");
        sb.append("                    return;\n");
        sb.append("                }\n");
        sb.append("                let html = \"\";\n");
        sb.append("                logs.forEach(function(l) {\n");
        sb.append("                    html += \"<div class='log-item'><div class='log-time'>\" + l.time + \"</div><div class='log-msg'>\" + l.message + \"</div></div>\";\n");
        sb.append("                });\n");
        sb.append("                container.innerHTML = html;\n");
        sb.append("            } catch (e) { console.error(e); }\n");
        sb.append("        }\n");
        sb.append("\n");
        sb.append("        function saveConfig() {\n");
        sb.append("            if (!window.IntervalsBridge) return;\n");
        sb.append("            const elAth = document.getElementById(\"cfg-athlete-id\");\n");
        sb.append("            const elKey = document.getElementById(\"cfg-api-key\");\n");
        sb.append("            const elAuto = document.getElementById(\"cfg-auto-sync\");\n");
        sb.append("            const athleteId = elAth ? elAth.value.trim() : \"\";\n");
        sb.append("            const apiKey = elKey ? elKey.value.trim() : \"\";\n");
        sb.append("            const autoSync = elAuto ? elAuto.checked : true;\n");
        sb.append("\n");
        sb.append("            window.IntervalsBridge.saveSettings(athleteId, apiKey, autoSync, currentScoreSource);\n");
        sb.append("            showToast(\"Settings saved successfully!\", false);\n");
        sb.append("            if (currentHistory && currentHistory.length > 0) {\n");
        sb.append("                displayDashboard(currentHistory[0]);\n");
        sb.append("            }\n");
        sb.append("        }\n");
        sb.append("\n");
        sb.append("        function syncCurrentDay() {\n");
        sb.append("            if (!latestDate) {\n");
        sb.append("                showToast(\"No record found to transfer.\", true);\n");
        sb.append("                return;\n");
        sb.append("            }\n");
        sb.append("            syncSingle(latestDate);\n");
        sb.append("        }\n");
        sb.append("\n");
        sb.append("        function syncSingle(d) {\n");
        sb.append("            if (!window.IntervalsBridge) return;\n");
        sb.append("            const btn = document.getElementById(\"main-sync-btn\");\n");
        sb.append("            if (btn) btn.disabled = true;\n");
        sb.append("            showToast(\"Transferring \" + d + \" to Intervals.icu...\", false);\n");
        sb.append("            setTimeout(function() {\n");
        sb.append("                try {\n");
        sb.append("                    const res = JSON.parse(window.IntervalsBridge.syncDate(d));\n");
        sb.append("                    if (res.success) {\n");
        sb.append("                        showToast(\"Successfully transferred: \" + d, false);\n");
        sb.append("                        const statusLine = document.getElementById(\"status-line\");\n");
        sb.append("                        if (statusLine) statusLine.innerText = \"Last sync: \" + d + \" OK\";\n");
        sb.append("                    } else {\n");
        sb.append("                        showToast(\"Sync error: \" + res.message, true);\n");
        sb.append("                    }\n");
        sb.append("                } catch (e) {\n");
        sb.append("                    showToast(\"Transfer error: \" + e, true);\n");
        sb.append("                } finally {\n");
        sb.append("                    if (btn) btn.disabled = false;\n");
        sb.append("                }\n");
        sb.append("            }, 100);\n");
        sb.append("        }\n");
        sb.append("\n");
        sb.append("        window.onload = loadInitialData;\n");
        sb.append("    </script>\n");
        sb.append("</body>\n");
        sb.append("</html>\n");
        return sb.toString();
    }
}
