package io.github.liongalahad.nuviotv.extension.subtitles.sdh;

import io.github.liongalahad.nuviotv.extension.settings.MorpheTranslations;

/** Owned translation catalogue. Columns: en, es, it, de, fr, pt, ja, ko, zh-Hans, zh-Hant. */
final class PatchTranslations {
    private PatchTranslations() {}
    static void register() { MorpheTranslations.register(ENTRIES); }
    static final String[][] ENTRIES = {
        {"Subtitles", "Subtítulos", "Sottotitoli", "Untertitel", "Sous-titres", "Legendas", "字幕", "자막", "字幕", "字幕"},
        {"Configure subtitle patch settings", "Configura los parches de subtítulos", "Configura le patch dei sottotitoli", "Untertitel-Patches konfigurieren", "Configurer les patchs de sous-titres", "Configurar patches de legendas", "字幕パッチを設定", "자막 패치 설정", "配置字幕补丁设置", "設定字幕修補程式"},
        {"SDH subtitle processing", "Procesamiento de subtítulos SDH", "Elaborazione dei sottotitoli SDH", "Verarbeitung von SDH-Untertiteln", "Traitement des sous-titres SDH", "Processamento de legendas SDH", "SDH 字幕の処理", "SDH 자막 처리", "SDH 字幕处理", "SDH 字幕處理"},
        {"Off", "Desactivado", "Disattivato", "Aus", "Désactivé", "Desativado", "オフ", "끄기", "关闭", "關閉"},
        {"Normalize music symbols only", "Normalizar solo los símbolos musicales", "Normalizza solo i simboli musicali", "Nur Musiksymbole normalisieren", "Normaliser uniquement les symboles musicaux", "Normalizar apenas símbolos musicais", "音楽記号のみ正規化", "음악 기호만 정규화", "仅规范音乐符号", "僅統一音樂符號"},
        {"Remove SDH, keep lyrics", "Eliminar SDH y conservar las letras", "Rimuovi le annotazioni SDH, mantieni i testi delle canzoni", "SDH entfernen, Liedtexte beibehalten", "Supprimer les annotations SDH, conserver les paroles", "Remover SDH, manter letras", "SDH 注釈を削除し歌詞を保持", "SDH 제거, 가사 유지", "移除 SDH 注释，保留歌词", "移除 SDH 註解，保留歌詞"},
        {"Full cleanup", "Limpieza completa", "Pulizia completa", "Vollständige Bereinigung", "Nettoyage complet", "Limpeza completa", "すべてクリーンアップ", "전체 정리", "全面清理", "完整清理"},
        {"Do not alter subtitle text.", "No modifica el texto de los subtítulos.", "Non modifica il testo dei sottotitoli.", "Untertiteltext unverändert lassen.", "Ne modifie pas le texte des sous-titres.", "Não alterar o texto das legendas.", "字幕テキストを変更しません。", "자막 텍스트를 변경하지 않습니다.", "不更改字幕文本。", "不變更字幕文字。"},
        {"Replace repeated or misdecoded lyric markers with music-note symbols without removing text.", "Sustituye los marcadores de letras repetidos o mal decodificados por notas musicales sin eliminar texto.", "Sostituisce i marcatori dei testi ripetuti o decodificati male con note musicali, senza rimuovere testo.", "Ersetzt wiederholte oder falsch dekodierte Liedtextmarkierungen durch Musiknoten, ohne Text zu entfernen.", "Remplace les marqueurs de paroles répétés ou mal décodés par des notes de musique sans supprimer de texte.", "Substituir marcadores de letras repetidos ou mal descodificados por notas musicais, sem remover texto.", "重複した歌詞マーカーや文字化けした歌詞マーカーを音符に置き換えます。テキストは削除しません。", "텍스트를 제거하지 않고 반복되거나 잘못 디코딩된 가사 표시를 음표로 바꿉니다.", "将重复或解码错误的歌词标记替换为音符，不删除文本。", "將重複或解碼錯誤的歌詞標記替換為音符，不刪除文字。"},
        {"Remove annotations, sound descriptions and speaker labels while preserving and normalizing likely song lyrics.", "Elimina anotaciones, descripciones de sonidos e identificadores de hablantes, conservando y normalizando los posibles textos de canciones.", "Rimuove annotazioni, descrizioni dei suoni e nomi di chi parla, mantenendo e normalizzando i probabili testi delle canzoni.", "Entfernt Anmerkungen, Geräuschbeschreibungen und Sprecherbezeichnungen. Erkannte Liedtexte bleiben erhalten und werden normalisiert.", "Supprime les annotations, descriptions sonores et noms des locuteurs tout en conservant et normalisant les paroles probables.", "Remover anotações, descrições de sons e nomes dos falantes, preservando e normalizando prováveis letras de músicas.", "注釈、効果音の説明、話者名を削除し、歌詞と思われるテキストは保持して正規化します。", "주석, 소리 설명 및 화자 표시를 제거하고 가사로 추정되는 텍스트는 유지하고 정규화합니다.", "移除注释、声音描述和说话人标签，同时保留并规范可能的歌词。", "移除註解、聲音描述與說話者標籤，同時保留並統一可能的歌詞格式。"},
        {"Also remove all text enclosed by normal, inferred or misdecoded music-note markers.", "Elimina también todo el texto entre marcadores musicales normales, deducidos o mal decodificados.", "Rimuove anche tutto il testo racchiuso tra marcatori musicali normali, dedotti o decodificati male.", "Entfernt auch sämtlichen Text zwischen normalen, erkannten oder falsch dekodierten Musiknotenmarkierungen.", "Supprime aussi tout le texte entre les marqueurs musicaux normaux, déduits ou mal décodés.", "Remover também todo o texto entre marcadores musicais normais, inferidos ou mal descodificados.", "通常の音符、推定された音符、文字化けした音符で囲まれたテキストもすべて削除します。", "일반 음표, 추정된 음표 또는 잘못 디코딩된 음표로 둘러싸인 텍스트도 모두 제거합니다.", "还会移除正常、推断或解码错误的音符标记之间的所有文本。", "也會移除正常、推斷或解碼錯誤的音符標記之間的所有文字。"},
    };
}
