package app.yydarlinker.deepseekcaptions;
/** One process/app-launch choice. No default language, no cross-video URL or track object retention. */
final class CaptionChoice {
    private static String language="";
    private static boolean translation,on,chosen,asr;
    static synchronized void select(String code,boolean translate) {
        if(code==null || code.trim().isEmpty() || code.endsWith("_OPTION")) return;
        language=code;translation=translate;on=true;chosen=true;asr=false;
    }
    static synchronized void select(String code,boolean translate,boolean autoGenerated) { select(code,translate);asr=autoGenerated; }
    static synchronized boolean asr() { return asr; }
    static synchronized void toggle(boolean enabled) { on=enabled; if(!enabled) chosen=true; }
    static synchronized boolean isOn() { return chosen && on && !language.isEmpty(); }
    static synchronized boolean known() { return chosen; }
    static synchronized boolean translates() { return translation; }
    static synchronized String language() { return language; }
    static synchronized void reset() { language="";translation=false;on=false;chosen=false;asr=false; }
}
