package app.yydarlinker.deepseekcaptions;

import android.content.Context;
import android.net.Uri;

import java.io.InputStream;
import java.net.HttpURLConnection;
import java.net.URL;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import java.util.Set;

/**
 * Loads YouTube's source-caption text while keeping timing provenance explicit.
 *
 * <p>The selected provider track remains the semantic/text source. For every source language,
 * YouTube's auto-generated track is fetched only as a clock reference. Whether calibration
 * is needed is decided from real provider-vs-ASR text anchors, never from a broadcast/roll-up
 * heuristic. Provider words and the semantic translation path stay untouched.</p>
 */
final class RawCaptionSource {
    private static final int MAX_SOURCE_BYTES = 16 * 1024 * 1024;
    private static final int ENGLISH_TEXT_THRESHOLD = 78;
    private static final int TIMING_PROBE_BUDGET_MS = 2_000;
    private static final int PRIMARY_BUDGET_MS = 12_000;

    private RawCaptionSource() {}

    static Source load(Context context, String translatedUrl) throws Exception {
        return load(context, translatedUrl, true);
    }

    static Source load(
            Context context,
            String translatedUrl,
            boolean publishSharedTimeline
    ) throws Exception {
        return load(context,translatedUrl,publishSharedTimeline,true);
    }
    static Source load(Context context,String translatedUrl,boolean publishSharedTimeline,boolean calibrate) throws Exception {
        return load(context,translatedUrl,publishSharedTimeline,calibrate,null);
    }
    static Source load(Context context,String translatedUrl,boolean publishSharedTimeline,boolean calibrate,
                       DeepSeekApiClient.RequestControl control) throws Exception {
        checkActive(control);
        String sourceUrl = CaptionEngine.sourceCaptionUrl(translatedUrl);
        long primaryDeadline=System.nanoTime()+java.util.concurrent.TimeUnit.MILLISECONDS.toNanos(PRIMARY_BUDGET_MS);
        LoadedTrack provider;
        String timedUrl=calibrate ? SourceFormatPolicy.json3(sourceUrl) : sourceUrl;
        try {
            provider=loadTrack(context,timedUrl,"SOURCE",true,remaining(primaryDeadline),control);
            sourceUrl=timedUrl;
        } catch(Exception unavailable) {
            if(timedUrl.equals(sourceUrl) || !SourceRecoveryPolicy.formatFallback(unavailable)) throw unavailable;
            checkActive(control);
            CaptionDiagnostics.mark(context,"SOURCE_FORMAT_FALLBACK","JSON3 不可用；单次回退原格式，时间精度会明确报告");
            provider=loadTrack(context,sourceUrl,"SOURCE",true,remaining(primaryDeadline),control);
        }

        byte[] body = provider.body;
        String contentType = provider.contentType;
        CaptionDocument.Parsed document = provider.document;
        TrackIdentity identity = classifyTrack(sourceUrl, document);
        SourceAtomTimeline.Result alignedAtoms = null;
        SourceAtomTimeline.Result providerAtoms = calibrate ? SourceAtomTimeline.build(body,document) : null;

        CaptionDiagnostics.mark(
                context,
                "SOURCE_TRACK_CLASSIFIED",
                identity.diagnostic()
        );

        if(calibrate && identity.autoGenerated && providerAtoms.preciseRatio()<0.8){
            try{
                TimingAnchor precise=loadAsrAnchor(context,sourceUrl,document,providerAtoms,control);
                if(precise!=null){
                    SourceAtomTimeline.Result original=providerAtoms,reference=precise.atoms;
                    if(WordTimingReference.sameWords(document,precise.document) && reference.preciseRatio()>=original.preciseRatio()){
                        body=precise.body;contentType=precise.contentType;document=precise.document;providerAtoms=reference;
                        CaptionDiagnostics.mark(context,reference.nativeTimedAtoms>0?"ASR_NATIVE_WORD_TIMING_SELECTED":"ASR_CUE_TIMING_BASE","same_source_words=true;native="+reference.nativeTimedAtoms+";estimated="+reference.estimatedAtoms);
                    }else{
                        SourceAtomTimeline.Result matched=AsrLocalTiming.align(original,reference);
                        if(matched!=original){alignedAtoms=matched;CaptionDiagnostics.mark(context,"ASR_NATIVE_WORD_TIMING_ALIGNED","provider_text_preserved;native="+matched.nativeTimedAtoms);}
                        else CaptionDiagnostics.mark(context,"ASR_WORD_TIMING_UNAVAILABLE","reason=unmatched_reference;keeping_estimated_cue_times");
                    }
                }else CaptionDiagnostics.mark(context,"ASR_WORD_TIMING_UNAVAILABLE","reason=no_native_reference;keeping_estimated_cue_times");
            }catch(Exception failure){checkActive(control);CaptionDiagnostics.mark(context,"ASR_WORD_TIMING_UNAVAILABLE","reason="+timingFailureReason(failure)+";keeping_asr_cue_bounds");}
        }
        if (identity.autoGenerated) {
            if(providerAtoms==null)providerAtoms=SourceAtomTimeline.build(body,document);
            CaptionDiagnostics.mark(
                    context,
                    providerAtoms.nativeTimedAtoms>0?"SOURCE_TIMING_BASE":"ASR_CUE_TIMING_BASE",
                    "当前底层轨为自动生成字幕；句段边界保留，内部非原生词时刻为估计；native="+providerAtoms.nativeTimedAtoms+";estimated="+providerAtoms.estimatedAtoms
            );
        } else if (calibrate && identity.providerTrack) {
            CaptionDiagnostics.mark(
                    context,
                    "ASR_TIMING_PROBE",
                    "源轨不经过语种或广播类型预筛选；优先尝试自动生成字幕时间参照"
            );
            try {
                TimingAnchor anchor = loadAsrAnchor(context, sourceUrl,document,providerAtoms,control);
                if (anchor == null) {
                    CaptionDiagnostics.mark(
                            context,
                            "SOURCE_TIMING_FALLBACK",
                            "未取得可用的自动生成字幕时间锚，保持原轨时间"
                    );
                } else {
                    SourceAtomTimeline.Result originalAtoms = providerAtoms;
                    SourceAtomTimeline.Result referenceAtoms = anchor.atoms;
                    alignedAtoms = anchor.alignment != null ? anchor.alignment : AsrLocalTiming.alignWithCueTiming(originalAtoms, referenceAtoms);
                    if(alignedAtoms == originalAtoms){
                        alignedAtoms=null;
                        CaptionDiagnostics.mark(context,"ASR_LOCAL_TIMING_REJECTED","sourceAtoms="+originalAtoms.atoms.size()+";asrNative="+referenceAtoms.nativeTimedAtoms+";reason=insufficient_unique_monotonic_anchors");
                    }
                    CaptionTimingCalibrator.Calibration calibration =
                            anchor.calibration != null ? anchor.calibration : CaptionTimingCalibrator.compare(document, anchor.document);
                    CaptionDiagnostics.mark(
                            context,
                            "ASR_TIMING_MATCH",
                            calibration.diagnostic()
                    );
                    if (alignedAtoms != null) {
                        CaptionDiagnostics.mark(context,alignedAtoms.asrMatchedAtoms>alignedAtoms.nativeTimedAtoms?"ASR_CUE_TIMING_APPLIED":"ASR_LOCAL_TIMING_APPLIED",
                            "保留原轨文本；ASR 匹配="+alignedAtoms.asrMatchedAtoms+"；原生逐词="+alignedAtoms.nativeTimedAtoms+"；句内估计="+alignedAtoms.estimatedAtoms);
                    } else if (calibration.apply) {
                        byte[] shiftedJson3 = CaptionTimingCalibrator.shiftJson3(body, calibration.offsetMs);
                        if (shiftedJson3 != null) {
                            body = shiftedJson3;
                            document = CaptionDocument.parse(body, contentType);
                        } else {
                            document = CaptionTimingCalibrator.shiftDocument(document, calibration.offsetMs);
                        }
                        providerAtoms = SourceAtomTimeline.build(body,document);
                        CaptionDiagnostics.mark(
                                context,
                                "SOURCE_TIMING_CALIBRATED",
                                "保留原轨文本，仅以自动生成字幕校时：原轨减去校准偏移 " +
                                        calibration.offsetMs + " ms；" + calibration.anchors +
                                        " 个文本锚，MAD " + calibration.madMs + " ms"
                        );
                    } else if (calibration.alreadySynced) {
                        CaptionDiagnostics.mark(
                                context,
                                "SOURCE_TIMING_CONFIRMED",
                                "原轨与自动生成字幕时间已基本一致：中位差 " +
                                        calibration.offsetMs + " ms；无需修正"
                        );
                    } else {
                        CaptionDiagnostics.mark(
                                context,
                                "SOURCE_TIMING_FALLBACK",
                                "未对原轨改时：" + calibration.reason
                        );
                    }
                }
            } catch (Exception failure) {
                checkActive(control);
                CaptionDiagnostics.mark(
                        context,
                        "SOURCE_TIMING_FALLBACK",
                        "自动生成字幕时间锚不可用，保持原轨时间：" +
                                timingFailureReason(failure)
                );
            }
        } else {
            CaptionDiagnostics.mark(
                    context,
                    "SOURCE_TIMING_NOT_PROBED",
                    "本次未启用校时；保留原字幕时间轴"
            );
        }

        checkActive(control);
        if (publishSharedTimeline) {
            String videoId = PageCaptionController.videoIdFromUrl(translatedUrl);
            if (videoId.isEmpty()) videoId = SemanticCaptionTimeline.currentVideoId();
            publishSharedTimeline(videoId, document.cues());
        }
        CaptionDiagnostics.mark(
                context,
                "RAW_TIMELINE_READY",
                "保留 YouTube 原轨 " + document.cues().size() + " 个时间原子；分句译文由模型单次生成，本地保留原词时间锚"
        );
        return new Source(body, contentType, sourceUrl, document, alignedAtoms!=null ? alignedAtoms : providerAtoms);
    }

    static boolean publishSharedTimeline(
            String videoId,
            List<CaptionDocument.Cue> values
    ) {
        String owner = videoId == null ? "" : videoId.trim();
        if (owner.isEmpty()) return false;
        return SemanticCaptionTimeline.replace(owner, values);
    }

    private static LoadedTrack loadTrack(Context context,String url,String diagnosticPrefix,
                                          boolean cacheAsPrimary,int budgetMs,
                                          DeepSeekApiClient.RequestControl control) throws Exception {
        checkActive(control);
        String cacheKey = cacheAsPrimary ? SourceCaptionCache.key(url) : SourceCaptionCache.referenceKey(url);
        SourceCaptionCache.Entry cached = SourceCaptionCache.get(context, cacheKey);
        if (cached != null) {
            try {
                LoadedTrack valid=new LoadedTrack(cached.body,cached.contentType,url);
                CaptionDiagnostics.mark(context,diagnosticPrefix+"_CACHE_HIT",
                        (cacheAsPrimary?"复用原始字幕缓存 ":"复用时间锚缓存 ")+cached.body.length+" bytes");
                return valid;
            } catch(Exception invalid) {
                // Older releases cached 200/HTML and malformed tracks before parsing them.
                SourceCaptionCache.remove(context,cacheKey);
                CaptionDiagnostics.mark(context,"SOURCE_CACHE_REJECTED","unreadable_cached_track");
            }
        }
        CaptionDiagnostics.mark(context,diagnosticPrefix+"_FETCH",
                cacheAsPrimary?"正在获取原始字幕":"正在获取自动生成字幕时间锚");
        Fetch fetched=fetch(url,false,System.nanoTime()+java.util.concurrent.TimeUnit.MILLISECONDS.toNanos(budgetMs),control);
        LoadedTrack valid=new LoadedTrack(fetched.body,fetched.contentType,url);
        checkActive(control);
        SourceCaptionCache.put(context,cacheKey,fetched.body,fetched.contentType);
        CaptionDiagnostics.mark(context,diagnosticPrefix+"_OK",
                (cacheAsPrimary?"原始字幕 ":"时间锚 ")+fetched.body.length+" bytes");
        return valid;
    }

    private static final java.util.Map<String,TimingAnchor> WORD_ANCHORS=new java.util.LinkedHashMap<>();
    private static TimingAnchor loadPublicWordAnchor(Context context,String sourceUrl,CaptionDocument.Parsed source,SourceAtomTimeline.Result sourceAtoms,int budgetMs,DeepSeekApiClient.RequestControl control)throws Exception{
        String video=PageCaptionController.videoIdFromUrl(sourceUrl);if(!video.matches("[A-Za-z0-9_-]{11}"))return null;
        String cacheKey=video+"|"+sourceLanguage(sourceUrl,source);
        synchronized(WORD_ANCHORS){TimingAnchor cached=WORD_ANCHORS.get(cacheKey);if(cached!=null){TimingAnchor checked=matched(cached,source,sourceAtoms);if(checked!=null)return checked;}}
        long deadline=android.os.SystemClock.elapsedRealtime()+Math.max(1,budgetMs);
        java.net.URL url=new java.net.URL("https://www.youtube.com/watch?v="+video+"&hl=en");
        java.net.HttpURLConnection connection=DeepSeekCaptionHook.openWithYouTubeCronet(url);if(connection==null)connection=(java.net.HttpURLConnection)url.openConnection();
        byte[] page;
        try(NetworkDeadline guard=new NetworkDeadline(connection,System.nanoTime()+java.util.concurrent.TimeUnit.MILLISECONDS.toNanos(budgetMs))){
            if(control!=null)control.onConnection(connection);checkActive(control);
            connection.setConnectTimeout(Math.max(1,Math.min(2000,budgetMs/2)));connection.setReadTimeout(Math.max(1,Math.min(3000,budgetMs/2)));connection.setInstanceFollowRedirects(false);connection.setRequestProperty("User-Agent","Mozilla/5.0");connection.setRequestProperty("Accept-Encoding","identity");
            int status=connection.getResponseCode();if(status!=200){CaptionDiagnostics.mark(context,"ASR_REFERENCE_FETCH_FAILED","http_"+status);return null;}
            java.io.ByteArrayOutputStream bytes=new java.io.ByteArrayOutputStream();try(InputStream in=connection.getInputStream()){
                byte[] buffer=new byte[8192];while(true){checkActive(control);long remaining=deadline-android.os.SystemClock.elapsedRealtime();if(remaining<=0)throw new java.net.SocketTimeoutException("public ASR lookup budget");connection.setReadTimeout((int)remaining);int n=in.read(buffer);if(n<0)break;if(bytes.size()+n>8*1024*1024)throw new java.io.IOException("public ASR metadata size");bytes.write(buffer,0,n);}
            }page=bytes.toByteArray();
        }finally{connection.disconnect();if(control!=null)control.onConnection(null);}
        checkActive(control);
        List<String> tracks=WordTimingReference.findAll(new String(page,java.nio.charset.StandardCharsets.UTF_8),video,sourceLanguage(sourceUrl,source));
        TimingAnchor found=loadMatchingAnchor(context,tracks,source,sourceAtoms,deadline,"ASR_WORD_REFERENCE",control);
        if(found!=null)synchronized(WORD_ANCHORS){if(WORD_ANCHORS.size()>=4)WORD_ANCHORS.remove(WORD_ANCHORS.keySet().iterator().next());WORD_ANCHORS.put(cacheKey,new TimingAnchor(found,null,null));}
        return found;
    }
    private static TimingAnchor matched(TimingAnchor anchor,CaptionDocument.Parsed source,SourceAtomTimeline.Result sourceAtoms){
        // Cached references may outlive the selected provider track. Never reuse a prior
        // provider's derived alignment, only immutable reference text/atoms.
        if(anchor.alignment!=null || anchor.calibration!=null)anchor=new TimingAnchor(anchor,null,null);
        if(WordTimingReference.sameWords(source,anchor.document))return anchor;
        // Evaluate the exact same original atoms once. Retain the result for installation below.
        SourceAtomTimeline.Result alignment=AsrLocalTiming.alignWithCueTiming(sourceAtoms,anchor.atoms);
        CaptionTimingCalibrator.Calibration calibration=CaptionTimingCalibrator.compare(source,anchor.document);
        if(alignment==sourceAtoms && calibration.anchors<6)return null;
        return new TimingAnchor(anchor,alignment,calibration);
    }
    private static TimingAnchor loadMatchingAnchor(Context context,List<String> urls,CaptionDocument.Parsed source,
            SourceAtomTimeline.Result sourceAtoms,long deadline,String diagnostic,DeepSeekApiClient.RequestControl control)throws Exception{
        for(String url:urls){
            checkActive(control);
            int remaining=(int)(deadline-android.os.SystemClock.elapsedRealtime());if(remaining<=0)break;
            try{
                LoadedTrack data=loadTrack(context,SourceFormatPolicy.json3(url),diagnostic,false,Math.min(3000,remaining),control);
                TimingAnchor anchor=new TimingAnchor(data.body,data.contentType,url,data.document);
                TimingAnchor checked=matched(anchor,source,sourceAtoms);
                if(checked!=null)return checked;
                CaptionDiagnostics.mark(context,"ASR_REFERENCE_REJECTED","reason=source_text_mismatch;lang="+query(url,"lang"));
            }catch(Exception failure){checkActive(control);CaptionDiagnostics.mark(context,"ASR_REFERENCE_FETCH_FAILED",diagnostic+";reason="+timingFailureReason(failure));}
        }
        return null;
    }
    private static TimingAnchor loadAsrAnchor(Context context,String sourceUrl,CaptionDocument.Parsed source,
            SourceAtomTimeline.Result sourceAtoms,DeepSeekApiClient.RequestControl control)throws Exception{
        long deadline=android.os.SystemClock.elapsedRealtime()+TIMING_PROBE_BUDGET_MS;
        String video=PageCaptionController.videoIdFromUrl(sourceUrl);
        TimingAnchor best=loadMatchingAnchor(context,NativeAsrTrackReference.candidates(video,sourceLanguage(sourceUrl,source)),source,sourceAtoms,deadline,"ASR_NATIVE_TRACK",control);
        if(best!=null)return best;
        int remaining=(int)(deadline-android.os.SystemClock.elapsedRealtime());
        if(remaining>0)try{
            best=loadPublicWordAnchor(context,sourceUrl,source,sourceAtoms,remaining,control);
        }catch(Exception failure){checkActive(control);CaptionDiagnostics.mark(context,"ASR_REFERENCE_FETCH_FAILED","player_metadata;reason="+timingFailureReason(failure));}
        if(best!=null)return best;
        return loadMatchingAnchor(context,autoGeneratedCandidates(sourceUrl,sourceLanguage(sourceUrl,source)),source,sourceAtoms,deadline,"ASR_TIMING",control);
    }
    static String sourceLanguage(String url,CaptionDocument.Parsed source){
        String language=query(url,"lang");if(!language.isEmpty())return language;
        String vss=query(url,"vss_id");if(vss.isEmpty())vss=query(url,"vssId");
        if(vss.startsWith("a."))return vss.substring(2);
        if(vss.startsWith("."))return vss.substring(1);
        return englishTextConfidence(source)>=ENGLISH_TEXT_THRESHOLD?"en":"";
    }

    static String timingFailureReason(Throwable failure) {
        if(failure==null)return "unavailable";
        if(failure instanceof SourceRecoveryPolicy.Failure)return ((SourceRecoveryPolicy.Failure)failure).category;
        if(failure instanceof java.net.SocketTimeoutException)return "timeout";
        String message=failure.getMessage();
        if(message!=null){
            java.util.regex.Matcher http=java.util.regex.Pattern.compile("HTTP ([0-9]{3})").matcher(message);
            if(http.find())return "http_"+http.group(1);
            if(message.contains("响应为空"))return "empty_response";
        }
        return failure.getClass().getSimpleName();
    }

    /**
     * Try several identity spellings because YouTube caption base URLs are not perfectly uniform
     * across app/server experiments. All candidates still point at the same video's source-language ASR
     * track; none is allowed to become a text source.
     */
    private static List<String> autoGeneratedCandidates(String sourceUrl,String language) {
        List<String> out = new ArrayList<>();
        String videoId = PageCaptionController.videoIdFromUrl(sourceUrl);
        if (videoId.isEmpty()||language.isEmpty()) return out;

        try {
            Uri original = Uri.parse(sourceUrl);
            Uri.Builder baseBuilder = original.buildUpon().clearQuery();
            Set<String> names = original.getQueryParameterNames();
            for (String name : names) {
                String lower = name == null ? "" : name.toLowerCase(Locale.ROOT);
                if (lower.equals("tlang") || lower.equals("lang") || lower.equals("kind") ||
                        lower.equals("name") || lower.equals("fmt") || lower.equals("xtags") ||
                        lower.equals("vss_id") || lower.equals("vssid") || lower.equals("caps")) {
                    continue;
                }
                for (String value : original.getQueryParameters(name)) {
                    baseBuilder.appendQueryParameter(name, value);
                }
            }
            String base = baseBuilder
                    .appendQueryParameter("lang", language)
                    .appendQueryParameter("kind", "asr")
                    .appendQueryParameter("caps", "asr")
                    .appendQueryParameter("fmt", "json3")
                    .build()
                    .toString();
            addCandidate(out, base);
            addCandidate(out, appendQuery(base, "vss_id", "a."+language));
            addCandidate(out, appendQuery(base, "vssId", "a."+language));
        } catch (Throwable ignored) {
        }

        String minimal = new Uri.Builder()
                .scheme("https")
                .authority("www.youtube.com")
                .path("/api/timedtext")
                .appendQueryParameter("v", videoId)
                .appendQueryParameter("lang", language)
                .appendQueryParameter("kind", "asr")
                .appendQueryParameter("caps", "asr")
                .appendQueryParameter("fmt", "json3")
                .build()
                .toString();
        addCandidate(out, minimal);
        return out;
    }

    private static void addCandidate(List<String> out, String value) {
        if (value == null || value.isEmpty()) return;
        if (!DeepSeekCaptionHook.isYouTubeTimedTextUrl(value)) return;
        if (!out.contains(value)) out.add(value);
    }

    private static String appendQuery(String url, String name, String value) {
        try {
            return Uri.parse(url).buildUpon().appendQueryParameter(name, value).build().toString();
        } catch (Throwable ignored) {
            return url;
        }
    }

    private static TrackIdentity classifyTrack(String url, CaptionDocument.Parsed document) {
        String lang = query(url, "lang");
        String kind = query(url, "kind");
        String vss = query(url, "vss_id");
        if (vss.isEmpty()) vss = query(url, "vssId");

        int confidence = englishTextConfidence(document);
        boolean asrHint = "asr".equalsIgnoreCase(kind.trim()) || vss.toLowerCase(Locale.ROOT).startsWith("a.");
        return new TrackIdentity(
                asrHint,
                !asrHint,
                lang,
                kind,
                vss,
                confidence
        );
    }

    /**
     * URL metadata is sometimes incomplete. Use the actual caption text as a second independent
     * signal so an English provider track cannot silently miss ASR calibration merely because a
     * YouTube experiment omitted lang=en from the request URL.
     */
    private static int englishTextConfidence(CaptionDocument.Parsed document) {
        if (document == null || document.cues().isEmpty()) return 0;
        int latinLetters = 0;
        int otherLetters = 0;
        int words = 0;
        int commonEnglish = 0;
        int budget = 24_000;
        StringBuilder word = new StringBuilder();

        int cueLimit = Math.min(document.cues().size(), 260);
        for (int i = 0; i < cueLimit && budget > 0; i++) {
            String text = document.cues().get(i).text;
            if (text == null) continue;
            int limit = Math.min(text.length(), budget);
            for (int j = 0; j < limit; j++) {
                char raw = text.charAt(j);
                if (Character.isLetter(raw)) {
                    Character.UnicodeScript script = Character.UnicodeScript.of(raw);
                    if (script == Character.UnicodeScript.LATIN) latinLetters++;
                    else otherLetters++;
                }

                char c = Character.toLowerCase(raw);
                if (c >= 'a' && c <= 'z') {
                    word.append(c);
                } else if ((c == '\'' || c == '’') && word.length() > 0) {
                    word.append(c);
                } else {
                    if (word.length() > 0) {
                        words++;
                        if (isCommonEnglishWord(word.toString())) commonEnglish++;
                        word.setLength(0);
                    }
                }
            }
            budget -= limit;
            if (word.length() > 0) {
                words++;
                if (isCommonEnglishWord(word.toString())) commonEnglish++;
                word.setLength(0);
            }
        }

        int letters = latinLetters + otherLetters;
        if (letters < 80 || words < 20) return 0;
        double latinRatio = latinLetters / (double) letters;
        double commonRatio = commonEnglish / (double) words;
        double lexicalEvidence = Math.min(1d, commonRatio / 0.12d);
        int score = (int) Math.round(60d * latinRatio + 40d * lexicalEvidence);
        return Math.max(0, Math.min(100, score));
    }

    private static boolean isCommonEnglishWord(String raw) {
        String value = raw == null ? "" : raw.replace("'", "").replace("’", "");
        switch (value) {
            case "the": case "and": case "of": case "to": case "in": case "a":
            case "is": case "that": case "for": case "it": case "on": case "with":
            case "as": case "was": case "at": case "by": case "this": case "from":
            case "be": case "are": case "or": case "have": case "an": case "not":
            case "but": case "we": case "you": case "they": case "he": case "she":
            case "his": case "her": case "their": case "our": case "your": case "will":
            case "would": case "can": case "could": case "should": case "has": case "had":
            case "were": case "been": case "do": case "does": case "did": case "what":
            case "who": case "when": case "where": case "why": case "how":
                return true;
            default:
                return false;
        }
    }

    private static String query(String url, String name) {
        try {
            String value = Uri.parse(url).getQueryParameter(name);
            return value == null ? "" : value.trim();
        } catch (Throwable ignored) {
            return "";
        }
    }

    static void checkActive(DeepSeekApiClient.RequestControl control)throws InterruptedException {
        if(Thread.currentThread().isInterrupted() || (control!=null&&control.isCancelled()))
            throw new InterruptedException("source_cancelled");
    }
    static int remaining(long deadline)throws java.net.SocketTimeoutException {
        long left=java.util.concurrent.TimeUnit.NANOSECONDS.toMillis(deadline-System.nanoTime());
        if(left<=0)throw new java.net.SocketTimeoutException("source_deadline");
        return (int)Math.min(Integer.MAX_VALUE,Math.max(1,left));
    }
    private static Fetch fetch(String sourceUrl,boolean refreshed,long deadline,DeepSeekApiClient.RequestControl control)throws Exception {
        checkActive(control);
        if(!DeepSeekCaptionHook.isYouTubeTimedTextUrl(sourceUrl))throw new IllegalArgumentException("invalid_source_url");
        String cookies=refreshed?FreshYouTubeCookies.refresh(deadline,control):FreshYouTubeCookies.cached();
        checkActive(control);remaining(deadline);
        URL url=new URL(sourceUrl);
        HttpURLConnection connection=DeepSeekCaptionHook.openWithYouTubeCronet(url);
        if(connection==null)connection=(HttpURLConnection)url.openConnection();
        boolean refresh=false;
        try(NetworkDeadline guard=new NetworkDeadline(connection,deadline)) {
            if(control!=null)control.onConnection(connection);checkActive(control);
            connection.setConnectTimeout(Math.min(5_000,remaining(deadline)));
            connection.setReadTimeout(remaining(deadline));
            connection.setInstanceFollowRedirects(true);connection.setUseCaches(false);
            connection.setRequestProperty("User-Agent",FreshYouTubeCookies.userAgent());
            connection.setRequestProperty("Accept","*/*");connection.setRequestProperty("Accept-Encoding","identity");
            connection.setRequestProperty("Referer","https://www.youtube.com/");
            if(!cookies.isEmpty()&&cookies.indexOf('\r')<0&&cookies.indexOf('\n')<0)connection.setRequestProperty("Cookie",cookies);
            checkActive(control);connection.setReadTimeout(remaining(deadline));
            int status=connection.getResponseCode();checkActive(control);remaining(deadline);
            if((status==401||status==403)&&!refreshed){refresh=true;}
            else if(status<200||status>=300)throw SourceRecoveryPolicy.http(status,connection.getHeaderField("Retry-After"));
            else {
                java.io.ByteArrayOutputStream bytes=new java.io.ByteArrayOutputStream();
                connection.setReadTimeout(remaining(deadline));
                try(InputStream input=connection.getInputStream()){
                    byte[] buffer=new byte[8192];
                    while(true){checkActive(control);connection.setReadTimeout(remaining(deadline));int n=input.read(buffer);if(n<0)break;
                        if(bytes.size()+n>MAX_SOURCE_BYTES)throw new SourceRecoveryPolicy.Failure("source_too_large",false,0,null);
                        bytes.write(buffer,0,n);
                    }
                }
                checkActive(control);remaining(deadline);
                if(bytes.size()==0)throw new SourceRecoveryPolicy.Failure("empty_response",true,0,null);
                String type=connection.getContentType();
                return new Fetch(bytes.toByteArray(),type==null?"application/octet-stream":type);
            }
        } finally {
            // Also disconnect failures in headers/open/read, not just a successful response body.
            connection.disconnect();if(control!=null)control.onConnection(null);
        }
        if(refresh){checkActive(control);remaining(deadline);return fetch(sourceUrl,true,deadline,control);}
        throw new IllegalStateException("source_unavailable");
    }

    static final class Source {
        final byte[] body;
        final String contentType;
        final String sourceUrl;
        final CaptionDocument.Parsed document;

        final SourceAtomTimeline.Result alignedAtoms;
        Source(byte[] body, String contentType, String sourceUrl, CaptionDocument.Parsed document) {
            this(body,contentType,sourceUrl,document,null);
        }
        Source(byte[] body, String contentType, String sourceUrl, CaptionDocument.Parsed document, SourceAtomTimeline.Result alignedAtoms) {
            this.alignedAtoms=alignedAtoms;
            this.body = body;
            this.contentType = contentType;
            this.sourceUrl = sourceUrl;
            this.document = document;
        }
    }

    private static final class TrackIdentity {
        final boolean autoGenerated;
        final boolean providerTrack;
        final String lang;
        final String kind;
        final String vss;
        final int englishConfidence;

        TrackIdentity(
                boolean autoGenerated,
                boolean providerTrack,
                String lang,
                String kind,
                String vss,
                int englishConfidence
        ) {
            this.autoGenerated = autoGenerated;
            this.providerTrack = providerTrack;
            this.lang = lang == null ? "" : lang;
            this.kind = kind == null ? "" : kind;
            this.vss = vss == null ? "" : vss;
            this.englishConfidence = englishConfidence;
        }

        String diagnostic() {
            String type = autoGenerated ? "自动生成字幕" : providerTrack ? "原生字幕轨" : "未确认";
            return type + "；lang=" + safe(lang) + "，kind=" + safe(kind) +
                    "，vss=" + safe(vss) + "，正文英文置信度 " + englishConfidence + "%";
        }

        private static String safe(String value) {
            if (value == null || value.trim().isEmpty()) return "-";
            String clean = value.replace('\n', ' ').replace('\r', ' ').trim();
            return clean.length() <= 48 ? clean : clean.substring(0, 48);
        }
    }

    private static final class LoadedTrack {
        final byte[] body;
        final String contentType;
        final String url;

        final CaptionDocument.Parsed document;
        LoadedTrack(byte[] body, String contentType, String url) throws Exception {
            this.document=CaptionDocument.parse(body,contentType);
            if(document.cues().isEmpty())throw new SourceRecoveryPolicy.Failure("source_empty",false,0,null);
            this.body = body;
            this.contentType = contentType;
            this.url = url;
        }
    }

    private static final class TimingAnchor {
        final SourceAtomTimeline.Result atoms;
        final SourceAtomTimeline.Result alignment;
        final CaptionTimingCalibrator.Calibration calibration;
        TimingAnchor(TimingAnchor original,SourceAtomTimeline.Result alignment,CaptionTimingCalibrator.Calibration calibration){
            this.body=original.body;this.contentType=original.contentType;this.url=original.url;this.document=original.document;
            this.atoms=original.atoms;this.alignment=alignment;this.calibration=calibration;
        }
        final byte[] body;
        final String contentType;
        final String url;
        final CaptionDocument.Parsed document;

        TimingAnchor(byte[] body, String contentType, String url, CaptionDocument.Parsed document) {
            this.body = body;
            this.contentType = contentType;
            this.url = url;
            this.document = document;
            this.atoms=SourceAtomTimeline.build(body,document);this.alignment=null;this.calibration=null;
        }
    }

    private static final class Fetch {
        final byte[] body;
        final String contentType;
        Fetch(byte[] body, String contentType) {
            this.body = body;
            this.contentType = contentType;
        }
    }
}
