#ifndef _DEFINITIONS_GLSL_
#define _DEFINITIONS_GLSL_

#ifndef MATERIAL_BLEND_MODE_OPAQUE
#define MATERIAL_BLEND_MODE_OPAQUE 0
#endif 

#ifndef MATERIAL_BLEND_MODE_MASKED
#define MATERIAL_BLEND_MODE_MASKED 0
#endif 

#ifndef MATERIAL_BLEND_MODE_TRANSLUCENT 
#define MATERIAL_BLEND_MODE_TRANSLUCENT 0
#endif 

#ifndef MATERIAL_BLEND_MODE_ADDITIVE
#define MATERIAL_BLEND_MODE_ADDITIVE 0
#endif 

#ifndef MATERIAL_SHADING_MODEL_UNLIT
#define MATERIAL_SHADING_MODEL_UNLIT 0
#endif 

#ifndef MATERIAL_SHADING_MODEL_DEFAULT_LIT
#define MATERIAL_SHADING_MODEL_DEFAULT_LIT 0
#endif

#ifndef MATERIAL_SHADING_MODEL_SUBSURFACE_PROFILE
#define MATERIAL_SHADING_MODEL_SUBSURFACE_PROFILE 0
#endif

#ifndef MATERIAL_SHADING_MODEL_SUBSURFACE
#define MATERIAL_SHADING_MODEL_SUBSURFACE 0
#endif

#ifndef MATERIAL_SHADING_MODEL_HAIR
#define MATERIAL_SHADING_MODEL_HAIR 0
#endif

#ifndef MATERIAL_SHADING_MODEL_EYE
#define MATERIAL_SHADING_MODEL_EYE 0
#endif

#ifndef MATERIAL_SHADING_MODEL_CLOTH
#define MATERIAL_SHADING_MODEL_CLOTH 0
#endif

#ifndef MATERIAL_AO_MODE_DEFAULT_AO 
#define MATERIAL_AO_MODE_DEFAULT_AO 0
#endif 

#ifndef MATERIAL_AO_MODE_NO_AO 
#define MATERIAL_AO_MODE_NO_AO 0
#endif 

#ifndef MATERIAL_AO_MODE_CUSTOM_AO 
#define MATERIAL_AO_MODE_CUSTOM_AO 0
#endif 

#ifndef MATERIAL_TWOSIDED
#define MATERIAL_TWOSIDED 0
#endif 

#ifndef MATERIAL_TANGENT_SPACE_NORMAL
#define MATERIAL_TANGENT_SPACE_NORMAL 0
#endif 

#ifndef GPU_SKIN_MAX_BONE_NUM
#define GPU_SKIN_MAX_BONE_NUM 0
#endif

#ifndef GPU_SKIN_USE_EXTRA_INFLUENCES
#define GPU_SKIN_USE_EXTRA_INFLUENCES 0
#endif

#ifndef GPU_MORPH_BLEND
#define GPU_MORPH_BLEND 0
#endif 

#ifndef FORWARD_SHADING_OPAQUE_LAYER
#define FORWARD_SHADING_OPAQUE_LAYER 0
#endif

#ifndef MASK_RENDER 
#define MASK_RENDER 0
#endif

#ifndef PHYSICAL_DIFFUSE
#define PHYSICAL_DIFFUSE 1
#endif 

#ifndef VERTEX_SHADER 
#define VERTEX_SHADER 0
#endif 

#ifndef PIXEL_SHADER
#define PIXEL_SHADER 0	
#endif

#ifndef SHADER_TONEMAPPING
#define SHADER_TONEMAPPING 0
#endif

#ifndef IBL_ENABLE
#define IBL_ENABLE 0
#endif

#define SHADING_MODEL_ID_UNLIT              0
#define SHADING_MODEL_ID_DEFAULT_LIT        1
#define SHADING_MODEL_ID_SUBSURFACE         2
#define SHADING_MODEL_ID_SUBSURFACE_PROFILE 3
#define SHADING_MODEL_ID_HAIR               4
#define SHADING_MODEL_ID_EYE                5
#define SHADING_MODEL_ID_CLOTH              6

#endif //_DEFINITIONS_GLSL_