name: Crowdin pull and merge

on:
  schedule:
    - cron: "0 */12 * * *" # every 12 hours
  workflow_dispatch:

jobs:
  pull:
    name: Pull translations from Crowdin
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout dev
        uses: actions/checkout@v7
        with:
          ref: dev
          fetch-depth: 0
          clean: true

      - name: Reset Crowdin branch
        run: git push origin dev:crowdin --force

      - name: Pull strings from Crowdin
        uses: crowdin/github-action@v3
        with:
          config: crowdin.yml
          upload_sources: false
          download_translations: true
          skip_ref_checkout: true
          localization_branch_name: crowdin
          create_pull_request: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}

      - name: Fix workspace ownership
        run: sudo chown -R "$(id -u):$(id -g)" "$GITHUB_WORKSPACE"

      - name: Checkout Crowdin branch
        uses: actions/checkout@v7
        with:
          ref: crowdin
          fetch-depth: 0

      - name: Unescape apostrophes in translations
        run: |
          if [ "$(git rev-parse HEAD)" != "$(git rev-parse origin/dev)" ]; then
            find src/main/composeResources -type f -name "*.xml" -exec sed -i "s/\\\\'/'/g" {} +
            if [ -n "$(git status --porcelain)" ]; then
              git config --local user.name "Crowdin Bot"
              git config --local user.email "support+bot@crowdin.com"
              git commit -a --amend --no-edit
              git push origin crowdin --force
            fi
          fi


  merge:
    name: Squash merge Crowdin into Dev
    if: github.event_name == 'workflow_dispatch'
    needs: pull
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout Crowdin branch to run checks on it
      - name: Checkout Crowdin branch
        uses: actions/checkout@v7
        with:
          ref: crowdin
          fetch-depth: 0
          clean: true

      - name: Cache Gradle
        uses: burrunan/gradle-cache-action@v3

      # Step 2: Compile app to check string resources
      - name: Compile app to check resources
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          _JAVA_OPTIONS: "-Djava.awt.headless=true"
        run: |
          chmod +x ./gradlew
          ./gradlew generateComposeResClass

      # Step 3: Checkout dev branch to prepare for merging
      - name: Checkout dev branch for merge
        uses: actions/checkout@v7
        with:
          ref: dev
          fetch-depth: 0
          clean: true

      # Step 4: Fetch the latest crowdin branch (already checked)
      - name: Fetch crowdin branch
        run: git fetch origin crowdin

      # Step 5: Squash merge crowdin into dev
      - name: Squash merge crowdin into dev
        run: |
          git config --local user.name "Crowdin Bot"
          git config --local user.email "support+bot@crowdin.com"
          git merge --squash origin/crowdin
          git commit --allow-empty -m "chore: Update translations from Crowdin"
          git push origin dev
