[versions]
morphe-patcher = "1.5.1"
#noinspection GradleDependency
smali = "b6365a84f4"
gson = "2.14.0"
guava = "33.5.0-jre"

[libraries]
morphe-patcher = { module = "app.morphe:morphe-patcher", version.ref = "morphe-patcher" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
guava = { module = "com.google.guava:guava", version.ref = "guava" }
